### ISSUE TITLE
'Index Sources & Publish Symbols' Task fails with 'Unable to connect to the remote server' for Azure DevOps with local VSTS Agent behind Proxy

### ISSUE THREAD

**Issue by joergbattermann** [microsoft/azure-pipelines-tasks#10154]
## Required Information

**Question, Bug, or Feature?**  
*Type*:  **Bug**

**Enter Task Name**: **Index Sources & Publish Symbols**

## Environment
- Server - Azure Pipelines or TFS on-premises? **Azure Pipelines**
- Agent - Hosted or Private: **Private** (v2.149.2, URL: https://dev.azure.com/ctplmtooling/Tooling/)

## Issue Description

Private Build Agent(s) are behind corporate proxy. All build tasks work as expected with proxy (corresponding VSTS environment variable afaik) except the "Index Sources & Publish Symbols" one failing with 'Unable to connect to the remote server'

### Task logs
(see attachment)
[log_10_405.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3093980/log_10_405.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
(see attachment above)

**Comment by pouliotf** [comment]
I have exactly the same problem, does a fix has been done. I can ByPass the problem with adding script to use the proxy in the task (PublishSymbols.ps1), but I think the problem must be fixed at the source.

**Comment by stephenmichaelf** [comment]
@arunkm @mihaif @fadnavistanmay @owenhuynMSFT

**Comment by Volkirith** [comment]
Having the same problem - Trying to index and publish symbols on private agent in corporate network with proxy. 
VSTS has been integrated with AAD. 
Attached the debug information from the VSTS build output (azure devops account name replaced with ####)

I've already tried some things on my end: 
It fails during Invoke-Webrequest to 'locationservice2" . I've copied the call and when testing it manually from Powershell ISE (running as the same user as the build agent service is configured) I get the html for the regular Azure Devops Security login page as response - not the JSON I was expecting - requesting my username and password as it would in a browser. According to documentation the parameter -UseDefaultCredentials that is actually used in the script should mitigate this, but it doesn't seem to work. 

When actually pasting the URL in a browser that passes on the windows credentials to Azure Devops, I get a json snippet with a result that points to the actual url for uploading symbols - so that seems like it works fine.  
[rawlog_indexsymbols_cannotconnect.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4107506/rawlog_indexsymbols_cannotconnect.txt)

**Comment by pouliotf** [comment]
I tried to use a simple PowerShell Task in the build. The script just run a simple Invoke-WebRequest and I get the same problem. It seems that the problem is the PowerShell is not using the proxy configuration of the agent. We tried to modify the default PowerShell profile ($PROFILE.AllUsersAllHosts) on the server where the script execute, but with no effect. Locally we do the same on the server, but it works. Does missing something for the PowerShell configuration on the server? Why cannot PowerShell accept using the agent configuration?
