### ISSUE TITLE
##vso[task.prependpath] in linux always results in an extra quote added wiht the prepended path

### ISSUE THREAD

**Issue by mjscosta** [microsoft/azure-pipelines-tasks#10165]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ##vso[task.prependpath]

## Environment
- Server - Azure Pipelines or TFS on-premises?
   Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: these are private data in private builds not to be tracked publicly.

- Agent - Hosted or Private:  Hosted
    
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

### Test 1
Using the following to set prepend the path results in an extra quote in the PATH
```
  - script: "echo '##vso[task.prependpath]$(Build.SourcesDirectory)/scripts1'"
  - script: 'echo "PATH: ${PATH}"'

  - script: "echo '##vso[task.prependpath]$(Build.SourcesDirectory)/scripts2'"
  - script: 'echo "PATH: ${PATH}"'
```
output1:
```
PATH: /home/vsts/work/1/s/scripts1:"/home/vsts/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
```

output2
```
PATH: /home/vsts/work/1/s/scripts2:/home/vsts/work/1/s/scripts1:"/home/vsts/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
```

Expected result:
```
PATH: /home/vsts/work/1/s/scripts2:/home/vsts/work/1/s/scripts1:/home/vsts/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

This seems to be causing some paths on added not be used in the search

**Comment by damccorm** [comment]
Hey @mjscosta - this looks like it might be the same issue as https://github.com/microsoft/azure-pipelines-tasks/issues/10331

Could you try running `set +x` at the start of your script? If that doesn't work, could you try queuing a build with system diagnostics turned on and sharing the output?

**Comment by HughDevlin** [comment]
Yesterday i lost a day cleaning up a spurious trailing single quote. Today I put together a minor variation on your "Set variables in scripts" YAML example on your "Variables" concept page. I hope this suggests some simple test cases.

```
trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none
- script: |
    FOO=BAR
    echo $FOO
    echo "##vso[task.setvariable variable=myvar]$FOO"
    set
  displayName: 'Reproduce vso trailing single quote bug; call vso'
- script: |
    echo my pipeline variable is $(myvar)
  displayName: 'Reproduce vso trailing single quote bug; echo variable'
```

Expected: BAR
Actual: BAR'

**Comment by damccorm** [comment]
Hey @HughDevlin per my comment above, I think this is all probably related to #10331 - we're working on a better long term fix, but in the short term adding `set +x` should fix the problem.

**Comment by HughDevlin** [comment]
No, adding `set -x` does not fix the problem, I'll test it if you won't:

```
trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none
- script: |
    set +x
    FOO=BAR
    echo $FOO
    echo "##vso[task.setvariable variable=myvar]$FOO"
    set
  displayName: 'Reproduce vso trailing single quote bug; call vso'
- script: |
    echo my pipeline variable is $(myvar)
  displayName: 'Reproduce vso trailing single quote bug; echo variable'
```
Expected: BAR
Actual: BAR'

Also, I note the potential duplicate you reference  #10331 is currently closed as no fault found which does not suggest a fix is in progress.

**Comment by HughDevlin** [comment]
Please add ##vso[task.setvariable] to the description.Thanks.

**Comment by damccorm** [comment]
> No, adding set +x does not fix the problem, I'll test it if you won't:

Oh, I see - this is the same type of root cause, but actually slightly different - sorry about that. Its actually the `set` command that is causing problems here which is why I didn't initially capture the issue.

Bash is setting the `$_` variable to the first arg of the previous command that was executed (see [here](https://unix.stackexchange.com/questions/280453/understand-the-meaning-of) for more info on this behavior). When you call `set`, that is getting written out to stdout. Since the previous command was a ## command, it writes out `_='##vso[task.setvariable variable=myvar]BAR'` - see [here](https://dev.azure.com/damccorm-repros/trailing-tick/_build/results?buildId=260&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=f8ed7bd8-2a7f-56f6-9385-7fc29a8b5b7b&l=222) for a repro with diagnostics turned on that shows this behavior.

So this is actually the correct behavior here - I'd recommend wiping `$_` before running `set`, which I've confirmed works [here](https://dev.azure.com/damccorm-repros/trailing-tick/_build/results?buildId=262&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9)

> Also, I note the potential duplicate you reference #10331 is currently closed as no fault found which does not suggest a fix is in progress.

Sure, probably should have been a little clearer here - right now, the system is working as designed. However, as you've seen here, this behavior is probably not desirable. Since its not a bug, we're not going to change behavior here, but we are looking at a feature to workaround this by making some variables read only (so they can't get overwritten). You can see the spec for that feature here - https://github.com/microsoft/azure-pipelines-yaml/pull/396/files

**Comment by damccorm** [comment]
> Please add ##vso[task.setvariable] to the description.Thanks.

I think its probably the same issue, I'd prefer to leave it to the issue author's discretion.

**Comment by HughDevlin** [comment]
We agree, this behavior is not desirable.
We disagree, it is bug.
After you implement a new category of read-only variables, and ask customers to flag variables as read-only with a new parameter at variable creation, you will maintain the undesirable behavior for non-read-only variables, because it is a design feature?

**Comment by damccorm** [comment]
_Updated the wording in my comment above for clarity_

To be clear, I think the behavior is undesirable for this use case, but in general it _is_ the behavior we want. The contract we have with the end user is essentially: any time you write something to stdout that matches our `##vso` commands, we'll process it. That includes when tools write something to stdout, or a command writes something to stdout. We have no way of differentiating between you trying to write something and the script accidentally writing something.

IMO the only potentially questionable behavior here is that we don't require the `##vso` command to be at the start of a line. I see pros and cons on that one, but that's somewhat moot at this point because we wouldn't be able to change that without risking breaking a significant portion of customers. Even with that, its not a bug as much as a design question that you _could_ disagree with.

Do you think that's fair?

**Comment by HughDevlin** [comment]
> Bash is setting the $_ variable to the first arg of the previous command that was executed (see here for more info on this behavior). When you call set, that is getting written out to stdout. Since the previous command was a ## command, it writes out _='##vso[task.setvariable variable=myvar]BAR'

Sorry, I do not think that's fair.

If as you say setting $_ to an arbitrary value prior to invoking ##vso is a circumvention, it is very clear to me that ##vso is making an unjustified assumption about its execution environment, and that needs to be fixed, even if it is not an easy fix. Is that not clear to you?

If I invoke ##vso in a script, it behaves differently (undesirably) if the immediately previous command happens to be a command with no parameters? and this is a design feature?

In other words, your demonstrated circumvention adding $_=blah before calling ##vso begs the question, well azure, maybe instead of asking customers to add this line maybe ##vso should always do something similar under the covers? 

Your proposed feature enhancement leaves existing customers with non-read-only variables vulnerable to this undesirable behavior, bottom line ##vso setvariable without the readOnly=true flag are so undesirable as to be useless.

Please add ##vso setvariable to the issue description so that other concerned parties, customer and MS, can more accurately recognize the scope of this issue and get more eyes on the proposed feature enhancement. Thank you.

**Comment by damccorm** [comment]
I think I maybe haven't made the problem here clear, there seems to be a little bit of misunderstanding.

>If as you say setting $_ to an arbitrary value prior to invoking ##vso is a circumvention, it is very clear to me that ##vso is making an unjustified assumption about its execution environment, and that needs to be fixed, even if it is not an easy fix. Is that not clear to you?
> If I invoke ##vso in a script, it behaves differently (undesirably) depending on the immediately previous command, and this is a design feature?

The issue is not that `##vso` commands are dependent on the previous line - its actually that in Bash, `set` gives you different output dependent on the previous line (since it is very intentionally dependent on the environment). Since you have an environment variable `$_` now set to `_='##vso[task.setvariable variable=myvar]BAR'`, set prints that line which invokes the `##` command a second time. So what is happening here is:

```
echo "##vso[task.setvariable variable=myvar]$FOO"
// The variable has been set to BAR
set
// The variable now gets set to BAR'
```

The `##` commands get masked from output which makes this a little challenging to see, but if you turn on diagnostics you can see that's what is happening. That's also why your case doesn't repro if you remove the `set` command.

> In other words, your demonstrated circumvention adding $_=blah before calling ##vso begs the question, well azure, maybe instead of asking customers to add this line to their scripts maybe ##vso should always do something similar under the covers?

This is mostly addressed by what I said previously in this comment, but to be clear, you'd actually want the `$_=blah` before `set` since that's the problematic command. So it would look like:

```
echo "##vso[task.setvariable variable=myvar]$FOO"
$_=abc
set
```

You wouldn't need this if you were running a different command which doesn't print the environment.

I would also kindly ask that we keep the conversation friendly and respectful. Please refer to our code of conduct: https://opensource.microsoft.com/codeofconduct/

**Comment by HughDevlin** [comment]
Dear friend,

May I respectfully advocate for intuitive behavior in our software, and may I respectfully suggest that if i need to turn on diagnostic tracing to understand how a bug is feature, perhaps it is a bug.

May i respectfully remind you and readers that the MS published idiom for ##vso usage is embedded in echo commands. Respectfully I do not agree that a fix is impossible. I think ##vso needs to be smarter.

I think this issue and the proposed solution needs more eyes.

**Comment by damccorm** [comment]
I'm going to ask again that we keep the conversation respectful going forward and work towards resolving the problem - otherwise I'll lock the thread to let the conversation cool off.

As far as the issue itself goes, I'd again reiterate that I think its working as intended, but we do have the read only feature coming to address use cases like yours. If you disagree, I'd appreciate clarification on how you believe the feature is working right now and how you believe it should work.

FWIW, the relevant design is as follows:

Any time a `##vso` command appears in stdout it is processed - regardless of where it appears in the output. If you set a variable twice, the second time you set it wins out. `##vso` commands are wiped from the output (though you can see that they were successfully processed in diagnostic mode).

**Comment by HughDevlin** [comment]
May I respectfully ask where is this documented?

**Comment by damccorm** [comment]
Our ## syntax is documented here - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-in-script

If you think we need further documentation please raise an issue in the docs repo - [this link](https://github.com/MicrosoftDocs/vsts-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a%0A*%20Version%20Independent%20ID%3A%20dae87abd-b73d-9120-bcdb-6097d4b40f2a%0A*%20Content%3A%20%5BVariables%20-%20Azure%20Pipelines%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdevops%2Fpipelines%2Fprocess%2Fvariables%3Fview%3Dazure-devops%26tabs%3Dyaml%252Cbatch%23feedback)%0A*%20Content%20Source%3A%20%5Bdocs%2Fpipelines%2Fprocess%2Fvariables.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fvsts-docs%2Fblob%2Fmaster%2Fdocs%2Fpipelines%2Fprocess%2Fvariables.md)%0A*%20Product%3A%20**devops**%0A*%20Technology%3A%20**devops-cicd**%0A*%20GitHub%20Login%3A%20%40juliakm%0A*%20Microsoft%20Alias%3A%20**jukullam**) should prepoluate it with the info needed to get it triaged/responded to fastest.

I'm going to lock this thread since I think it has ceased being productive and respectful.

**Comment by damccorm** [comment]
I'm also going to close since as it stands now this is still a no-op on our end.
