### ISSUE TITLE
Azure PowerShell Task v4 on Windows needs option to run on PowerShell core

### ISSUE THREAD

**Issue by bgelens** [microsoft/azure-pipelines-tasks#10328]
Azure PowerShell Task v4 which is currently in preview runs PowerShell core on any non Windows Image / Agent. On a Windows agent however, it decides on it's own to run Windows PowerShell with no way to overwrite it even though PowerShell Core is installed.

I'd like an option to set Core on Windows for this task (for me it would be the default).

**Comment by RoopeshNair** [comment]
We are looking into it. will check the feasibility of providing an option to switch to core. We can make PS Core as default in future versions.

**Comment by bgelens** [comment]
Nice, fyi, the PowerShell task already has [this capability](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PowerShellV2/task.json#L112).

**Comment by jfemobi** [comment]
I think this is a must because in the current state this task behaviors completely different on windows and non-windows agent.

**Comment by MisinformedDNA** [comment]
This issue just cost me hours of my life. I was trying to run `ConvertFrom-Json $appSettings -AsHashtable` and it kept complaining about `AsHashtable`. Turns out that `AsHashtable` only exists in Powershell Core. :( Switching to non-Windows isn't an option as we still use MSDEPLOY in a subsequent task. I can write my own version of `AsHashtable`, it's just annoying and confusing to run into a versioning issue.

**Comment by 20shivangi** [comment]
The support of PowerShell core in Windows for task AzurePowerShellV4 is recently added in this week. It will take at least 3-4 weeks to get deployed.

**Comment by bgelens** [comment]
Great news!

**Comment by 20shivangi** [comment]
Merged PR : https://github.com/microsoft/azure-pipelines-tasks/pull/11326

**Comment by 20shivangi** [comment]
Closing the issue.
