### ISSUE TITLE
Several tasks - remove BOM from [Console]::InputEncoding to prevent issues with Start-Job

### ISSUE THREAD

**Issue by bagstac** [microsoft/azure-pipelines-tasks#10332]
Environment

Server - Azure Pipelines

https://lubrizol.visualstudio.com/LTR/_releaseProgress?_a=release-environment-logs&releaseId=507&environmentId=623

 Agent - Private

 OS: Microsoft Windows Server 2012 R2 Datacenter (6.3.9600.0) [Win32NT] x64
Agent version: 2.150.3
Issue Description
Some tasks I use have this problem, if I use the parallel job check I got the error that seems fixed on this Bug

https://github.com/Microsoft/azure-pipelines-tasks/issues/9766, affected tasks (per now)
IIS Manage
Powershell on Target machines

 Error logs

##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: [localhost] The background process reported an error with the following message: Cannot process an element with node type "Text". Only Element and EndElement node types are supported.   at System.Management.Automation.Remoting.OutOfProcessUtils.ProcessData(String data, DataProcessingDelegates callbacks).

at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)

at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)

at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)

at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)

at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)

at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)

2019-05-07T16:51:04.4690448Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by ManuelGalindo** [comment]
@damccorm this is still failing and we are looking for a way not to disable the Pararel Job check

**Comment by arjgupta** [comment]
@bagstac what is the version of PowerShell on Target Machines task that is failing ?

**Comment by arjgupta** [comment]
The agent side changes made to handle this issue were applicable for only the PowerShell3 handler based tasks. The IIS extension tasks ( like IIS Web App Deploy and IIS Web App manage ) use the legacy PowerShell handler. And so that is why these tasks are failing. @damccorm if we take the changes that you made in the agent for powershell3 handler to handle this issue and apply them at the beginning of our tasks, will that work ?

**Comment by bagstac** [comment]
The primary target servers are at V4 of powershell.

**Comment by ManuelGalindo** [comment]
@arjgupta @damccorm be aware other tasks are affected like
Powershell on Target machines

**Comment by arjgupta** [comment]
@ManuelGalindo , are you using V1 of the PowerShell on Target Machines task ? Because that is the only version of the task that is still on the legacy handler. You can mitigate issues with PowerShell on Target Machines task by switching over to V2 or V3 of the task. As for the rest of the extension tasks ( IIS Web App Deploy using WinRM, IIS Web App Manage using WinRM, and Sql Dacpac Deploy using WinRM ), I have PR out to fix this issue.

**Comment by bagstac** [comment]
We will work on switching the version of the PS task.

**Comment by arjgupta** [comment]
@bagstac , @ManuelGalindo we have published a new version of the task with the appropriate fix. The version of the extension is 1.5.3. You should not face this issue for IIS Deploy or IIS Manage or Sql Deploy using WinRM.
