### ISSUE TITLE
user-agent header is fetched from environment variable with user information

### ISSUE THREAD

**Issue by Yiming-Jia** [microsoft/azure-pipelines-tasks#10348]
Hello,

We recently developed a custom task that integrated with our Azure App Configuration service. And we downloaded the lib `azure-arm-rest` into our repo as it's hasn't been public for npm to downloaded. 

Under the [webClient.ts](https://github.com/microsoft/azure-pipelines-tasks/blob/6877d2ef1cf73a21b7588b643f11876d2791e3eb/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/webClient.ts#L20), I'm seeing the `user-agent` is fetched from environment variable. And we noticed the pattern of that environment variable is `Vsts_{organization_guid}_{build/release}_{build/release_version}`. As we actively logging this data in Geneva and consuming it in kusto/PowerBI. Part of this data containing user information, so I think every team logging this header is facing same issue. Instead, it make sense for each task to come up a header at runtime.

**Comment by kmkumaran** [comment]
@Yiming-Jia  - As you rightly pointed out, the azure-arm-rest is written primarily as a shared lib fir the tasks within this task repo. It is not a generic library. Since you have a copy downloaded for your custom task, feel free to update the user agent in your copy to suit your need. 

@sachinma as well.

**Comment by Yiming-Jia** [comment]
@kmkumaran 
Thank you for information. Could you publish this task to internal feed, if you have any concerns to make the library publicly.

Also, as I mentioned `Part of this data containing user information, so I think every team logging this header is facing same issue. Instead, it make sense for each task to come up a header at runtime.` In the other word, any Azure services that integrated with custom task (like Azure Container Registry, Azure Fabric, etc) have already logged customer data without being aware of it.

**Comment by kmkumaran** [comment]
@Yiming-Jia, . The arm rest library here is customized to suit the needs of tasks in this tasks repo. 

If you are looking for generic node modules to be used in your custom task that needs to interact with ARM, I would suggest you to use the [Azure SDK modules](https://github.com/Azure/azure-sdk-for-node) instead.

**Comment by Yiming-Jia** [comment]
Hello @kmkumaran ,

Thank you for your explanation. Here are the two questions we were looking for:

1. Would that library `azure-arm-rest` be published? If you have concerns to make it as public, probably at least to internal feed. Because this library is served specifically to integrate between a custom task with any Azure services. So potentially, any incoming Azure service who wants to develop their own task needs the library.
2. Would you fix the `user-agent` to give user option to customize it, because current `user-agent` fetched environment variable which contains user's data. So any services that logged the `user-agent` header, might not be aware of it.

**Comment by kmkumaran** [comment]
For #1 - At this point we are not planning to publish azure-arm-rest as a library. 

For #2 - Since we haven't published this as library yet, at this point only the tasks in this repo will leverage this user-agent for logging. For now, if users are copying this code, they would have to [update ](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/azure-arm-rest/webClient.ts#L20) the user agent according to their need.

We will take this into account, whenever we decide to publish azure-arm-rest as a library.
