### ISSUE TITLE
Trigger a build in Azure DevOps using Services hooks 

### ISSUE THREAD

**Issue by Naidul** [microsoft/azure-pipelines-tasks#10360]
Hi Team,

I am trying to queue a build in azure devops (VSTS) using  Service Hooks.

I am able to trigger a Jenkins build using the service Hooks   
example
http://user:token@xx.xx.xx.xx:8080/job/job-name/build?token=token.

But I need to trigger a build in VSTS using Service hooks 
Please guide me

regards,
Naidu

**Comment by joshmgross** [comment]
@Naidul You can use our REST API to Queue a build, see here: https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/queue?view=azure-devops-rest-5.0

**Comment by Naidul** [comment]
Hi  Josh Gross
Thanks for your response,

I tried these approach but its not working for me .
Please find the below attachment what I followed
[VSTSBuildThroughServiceHooks.docx](https://github.com/microsoft/azure-pipelines-tasks/files/3180916/VSTSBuildThroughServiceHooks.docx)

Please suggest me

Kind Regards,
Naidu

**Comment by joshmgross** [comment]
@Naidul What is your use case? I'm not sure if Service Hooks is the correct method

**Comment by Naidul** [comment]
Hi Josh Gross

sorry for the delay ...
My use case is when ever a work item state(Active -->Resolved/Active --> Closed) updated the build need to be trigger automatically based on this work item state updated event. 

regards,
Naidu

**Comment by Naidul** [comment]
Hi Joshmgross,

Sorry for the delay...

My use case is when ever a work item state updated(Active --> Resolved/Active __> Closed/) then build needs to trigger automatically based on this work item state update event..

Could you please help on this

Regards,
Naidu

**Comment by joshmgross** [comment]
@Naidul 
Service Hooks are mostly used for external services, but it might work in this scenario with a WebHook (https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=azure-devops)

I see in your attached doc that the URL is incorrect, you'll want to fill in the fields for `{organization}` and `{project}` with the name of your Azure DevOps org and project

You'll also need to somehow specify the definition to queue the build, this goes in the request body but that won't be in the Service Hook event. See https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/queue?view=azure-devops-rest-5.0#request-body

You could also try setting up a server or function to receive these events and then queue a build from them. That way you'll be able to specify all the necessary information to queue the build.

**Comment by ziatahir** [comment]
> Hi Josh Gross
> Thanks for your response,
> 
> I tried these approach but its not working for me .
> Please find the below attachment what I followed
> [VSTSBuildThroughServiceHooks.docx](https://github.com/microsoft/azure-pipelines-tasks/files/3180916/VSTSBuildThroughServiceHooks.docx)
> 
> Please suggest me
> 
> Kind Regards,
> Naidu



> Hi Joshmgross,
> 
> Sorry for the delay...
> 
> My use case is when ever a work item state updated(Active --> Resolved/Active __> Closed/) then build needs to trigger automatically based on this work item state update event..
> 
> Could you please help on this
> 
> Regards,
> Naidu

Hi Naidul ,

Have you got the solution . I am stuck in same scenario .

regards
Zia

**Comment by pwalburn** [comment]
@Naidul 
Naidu, did you ever get this working, as I have a similar requirement

**Comment by cforce** [comment]
To sum it up: There is no real Webbhook support, because Webhook normally don't support POST data .. jut a simple get . The API should allow to pass the build definition id via http  query param

**Comment by marceloavf** [comment]
No way to trigger a build using any API from Azure DevOps ?

**Comment by picolino** [comment]
So... any info about this issue?

**Comment by cforce** [comment]
I'm able to start or canclel using this curl (reverse engineered from UI). Same hat works below for release pipelines will also work for build. You will find the url, but i think it's "Build/builds/" instead of "Release/releases"
"status":8 is cancel and so far i remember "status":1 (or 0?) was start. Juts try it out


`curl -u "username:${DEVOPS_TOKEN}" -X PATCH -H "Content-Type: application/json" -silent  --output /dev/null  --data '{"status":8,"scheduledDeploymentTime":null,"comment":"Skip Staging because '"${msg}"' "}' https://vsrm.dev.azure.com/daimler-mic/devdataproc/_apis/Release/releases/${RELEASE_RELEASEID}/environments/${RELEASE_ENVIRONMENTID}/?api-version=6.0-preview.6`

`curl -u "username:${DEVOPS_TOKEN}" -X PATCH -H "Content-Type: application/json" -silent  --output /dev/null  --data '{"status":1,"scheduledDeploymentTime":null,"comment":"Start Staging"}' https://vsrm.dev.azure.com/daimler-mic/devdataproc/_apis/Release/releases/${RELEASE_RELEASEID}/environments/${RELEASE_ENVIRONMENTID}/?api-version=6.0-preview.6`

**Comment by beauof** [comment]
I was trying to find a solution for a similar problem, where I wanted to monitor a docker base image update in the Azure Container Registry (ACR).

I found three options:

1. Trigger downstream builds from a [TriggerPipeline](https://marketplace.visualstudio.com/items?itemName=maikvandergaag.maikvandergaag-trigger-pipeline) task in your Azure DevOps pipeline's yaml file.
2. Create a [Service Hook](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=azure-devops) in the Azure DevOps project settings, then link it to an Azure Logic App that would _Queue a new build_.
3. Create a [webhook for the base image in ACR](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-webhook), then link it to an Azure Logic App that would _Queue a new build_.

I would recommend solution (3) because it is easy to set up, more universal and it keeps your build pipelines and project settings clean.

**Comment by rmaziarka** [comment]
Yes, I am curious as well about this problem, because I try to integrate with the GitHub repository webhooks, but using Personal Access Token. When you specify webhook there, you can only specify URL so it would be very valuable to run it with a build queue in the address:
![image](https://user-images.githubusercontent.com/5219374/79639181-5af99f00-818a-11ea-8d11-38d988e70467.png)

**Comment by ameetkonnur** [comment]
In addition to the REST API, one of the other ways could be to use a combination of LogicApp and DevOps Service. LogicApp has a great Azure DevOps task that will trigger a build / release and pass it parameters as well. The LogicApp can be exposed as either a simple webhook or HTTP POST API (if you want to pass parameters). We plan to use this to integrate GitLab (event based outbound webhook) with Azure DevOps in one of our scenarios. Not sure if this the best solution though.

**Comment by theBNT** [comment]
There is a relatively new feature described in the [Sprint 172 Release Notes](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-172-update#generic-webhook-based-triggers-for-yaml-pipelines) where one can trigger a YAML build via a Service Connection/Service Hook combination. I think this addresses this request.

**Comment by damccorm** [comment]
It looks like this request has been addressed so I'm going to close here. If this is still an issue I'd recommend opening a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html since this repo is mostly for tasks related issues

**Comment by cforce** [comment]
There is is still no webhook support which is simply based on HTTP GET and url param. Posts are just not supported in most of the tools working with WebHooks..

**Comment by mathstuf** [comment]
Hmm. Webhook delivery has always been via a POST verb in my experience (with GitHub and GitLab) with a JSON payload. How are you passing all of the relevant information in a GET request? A boatload of query parameters?
