### ISSUE TITLE
ValueTuple error occurs in Nuget Push build pipeline

### ISSUE THREAD

**Issue by jorismathijssen** [microsoft/azure-pipelines-tasks#10412]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGet  2.151.1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
        - Could not find it. Any idea how i can provide this information?

- Agent - Hosted:
    - Agent.OS| Windows_NT
    - Agent.Version | 2.146.0

## Issue Description

This problem started last friday 17-05-2019. Nuget push would not work anymore. We did not change any source code or the pipeline. After a few hours of try and error we saw a community page pop up with people having the same error. https://developercommunity.visualstudio.com/content/problem/572799/valuetuple-error-occurs-in-nuget-push-build-pipeli.html

it looks like its a problem with the 2.151.1 version of the nuget task.

### Task logs
[log_24_7097.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3195202/log_24_7097.zip)
### Error logs
https://gist.github.com/jorismathijssen/1565699d67dcc5df62563132a538bca2

There is a community page for this error:
https://developercommunity.visualstudio.com/content/problem/572799/valuetuple-error-occurs-in-nuget-push-build-pipeli.html

**Comment by ahaleiii** [comment]
The accepted solution on the community page linked above worked for me:
Install .NET Framework 4.7.2 on build server.

**Comment by shubham90** [comment]
The change which caused this is reverted and users should not see this issue now. Actual fix is currently been tested and will be deployed as part of regular deployment. Sorry for the disruption.

Cause: System.ValueTuple is not shipped with .NET Framework < 4.7.1. Any private agent with those versions will see this issue. Hosted agents are not affected because they have .NET > 4.7.2.
