### ISSUE TITLE
Support isDate function for task input validation

### ISSUE THREAD

**Issue by Yiming-Jia** [microsoft/azure-pipelines-tasks#10441]
Hello,

For Task [InputValidation](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/taskinputvalidation.md), could you support `isDate` function? Because there is no control for timestamp picker, custom task need to use textbox for timestamp input.

Thanks,
Yiming

**Comment by damccorm** [comment]
Hey, sorry this slipped through the cracks. Since this is a more general issue with the service and not a specific task, would you mind opening a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html? That's the best place for issues like this that aren't for a individual task since this repo's code base doesn't include input validation.

Again, sorry for the delayed response here
