### ISSUE TITLE
Task KubernetesManifest Deploy fails first time running.  Succeeds every time after.

### ISSUE THREAD

**Issue by Greenie0506** [microsoft/azure-pipelines-tasks#10575]
Setting up a pipeline for the first time with an existing YAML results in an error the first time the build runs.

The below task fails the first time saving the pipeline and running. Every time after the build will succeed.

- task: KubernetesManifest@0
            displayName: deploy
            name: deploy
            inputs:
              kubernetesServiceConnection: $(k8sServiceConnection)
              action: deploy
              namespace: $(k8sNamespace)
              manifests: $(bake.manifestsBundle)
              imagePullSecrets: $(imagePullSecret)

Results in this error: 
Deploy to Dev:Deploy job: "Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply"

**Comment by Greenie0506** [comment]
Just wondering what the outcome of this was? Was this an issue? Thanks

**Comment by ds-ms** [comment]
The `kubectl` tool throws this warning when the applied object on your cluster and the manifest which you're trying to apply don't match. 
The warning was thrown in your first run because of that, but on the later runs, it doesn't throw that warning because you have applied the same manifest file. 

Also, given that this is a warning, the task shouldn't have failed. 
@Greenie0506 is the task failing? If it is, I'll have to check where the warning logs are being piped to, i.e. stderr or stdout.

**Comment by Greenie0506** [comment]
Hi @ds-ms 

Yes the task is failing and the entire build is marked as failed

**Comment by ds-ms** [comment]
@Greenie0506 the issue was with how we were parsing the errors. I've raised a PR to fix it.

**Comment by Greenie0506** [comment]
@ds-ms Thank you!
