### ISSUE TITLE
Rerun tests which contain spaces in their names does not work

### ISSUE THREAD

**Issue by lukaskolafa** [microsoft/azure-pipelines-tasks#10709]
**Question, Bug, or Feature?**  
*Type*:  Question / Bug

**Enter Task Name**: VSTest@2

## Environment
- Server - Azure Pipelines
     - account name: ecom
     - project name: Courseware
     - build definition: Marketplace Test POC

- Agent - Hosted Windows 2019 with VS2019
      
## Issue Description

We are using SpecFlow xUnit for writing Tests and VSTest task to execute them. Typically, one will use spaces in Test Scenario names like this:

```
Scenario: Multi word scenario name
	Given Something given
	When Something happens
	Then Everything is fine
```

This will generate a test with following name:

```
        [Xunit.FactAttribute(DisplayName="Multi word scenario name")]
        [Xunit.TraitAttribute("FeatureTitle", "SomeFeature")]
        [Xunit.TraitAttribute("Description", "Multi word scenario name")]
        public virtual void MultiWordScenarioName()
        {
             ...
```

Execution of such test works, but if the test fails and we enable the option `Rerun failed tests`, the 2nd attempt does not execute the test again, because the rerun TestCaseFilter is generated incorrectly:

```
/TestCaseFilter:"FullyQualifiedName=FullyQualifiedName=TestProject.FailingFeature.Multi word scenario name"
```

the problem are the spaces in the test name. Without spaces or with underscore, rerun works correctly.

Do you have any idea how to fix that issue? SpecFlow does not support generation of test names without spaces and writing the Scenarios without spaces would be very sad workaround. 

What is even worse, the tests are not rerun again and the VSTest Tasks succeeds because no tests were executed for 2nd time, so the pipeline continues with potential code bugs.

Thanks
Lukas

**Comment by ShreyasRmsft** [comment]
@lukaskolafa we are looking into this.

**Comment by ShreyasRmsft** [comment]
@lukaskolafa the problem here is that XUnit is giving out the DisplayName as the Name of the test in the trx. But if you run vstest.console.exe with the args /ListFullyQualifiedTests /ListTestsTargetPath:"tempfile" it will tell you that the fullyqualifiednames are different. 

The problem with this is that only XUnit does this, the other frameworks don't. This will not be easy to fix as we prefer to filter on fqdns when rerunning and not on display names. But since XUnit omits the fqdn in the trx we have no way of knowing what the fqdn was.

There is a workaround for this and that is to enable test batching. (Preferably keep the batch size > total number of tests you have to minimize perf hit). Screenshot of reference

![image](https://user-images.githubusercontent.com/25194518/60656816-ced1f180-9e6d-11e9-8bfd-fff70303c29d.png)

This invokes vstest via the translation layer and avoid using the cmd line thus bypassing the whole filtering test cases by name and uses proper test cases objects to filter.

**Comment by lukaskolafa** [comment]
Hi Shreyas,
 
 thanks a lot for the good analysis!

This is indeed an xunit limitation. I didn't find any way how to specify fqtn with an attribute in xunit. I investigated as well the source code of the specflow xunit generator and there is no configuration option for generation of the xunit attributes so this behavior cannot be changed without adaptation of the nuget package. I will consider contacting the xunit team with this issue.

 Thank you for the workaround, this seems like being an option for us. 

best, L.

**Comment by ShreyasRmsft** [comment]
Closing this issue due to lower priority.
