### ISSUE TITLE
Can't install more than one p12 certificate to temporary keychain

### ISSUE THREAD

**Issue by anaisbetts** [microsoft/azure-pipelines-tasks#10792]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: InstallAppleCertificate@2  

## Environment
- Server - Azure Pipelines, all hosted

## Issue Description

Trying to install more than one certificate to the temporary keychain (i.e. having more than one instance of `InstallAppleCertificate` fails on the 2nd invocation. I'm not sure how you can install both the development and distribution certificates

### Task logs

```
[command]/usr/bin/security unlock-keychain -p *** /Users/vsts/agent/2.153.2/work/_temp/ios_signing_temp.keychain
[command]/usr/bin/security import /Users/vsts/agent/2.153.2/work/_temp/distribution.p12 -P *** -A -t cert -f pkcs12 -k /Users/vsts/agent/2.153.2/work/_temp/ios_signing_temp.keychain
1 identity imported.
[command]/usr/local/bin/openssl pkcs12 -in /Users/vsts/agent/2.153.2/work/_temp/distribution.p12 -nocerts -passin pass:*** -passout pass:*** | /usr/bin/grep friendlyName
MAC verified OK
    friendlyName: iOS Distribution: Ana�s Betts
[command]/usr/bin/security set-key-partition-list -S apple-tool:,apple: -s -l iOS Distribution: Ana�s Betts -k *** /Users/vsts/agent/2.153.2/work/_temp/ios_signing_temp.keychain
security: SecItemCopyMatching: The specified item could not be found in the keychain.
##[error]Error: The process '/usr/bin/security' failed with exit code 1
##[error]Error: Error setting the partition_id ACL for the private key. Verify that the `Keychain password` is correct, or use a `Temporary Keychain` instead.
```

**Comment by jessedc** [comment]
I am seeing the same failure from `/usr/bin/grep friendlyName` on the second call of `InstallAppleCertificate@2`. 

```
##[debug]/usr/bin/grep arg: ["friendlyName"] |  
-- | --
  | ##[debug]exec tool: /usr/local/bin/openssl |  
  | ##[debug]arguments: |  
  | ##[debug]   pkcs12 |  
  | ##[debug]   -in |  
  | ##[debug]   /Users/vsts/agent/2.153.2/work/_temp/Yxxx-entrprise-development.p12 |  
  | ##[debug]   -nocerts |  
  | ##[debug]   -passin |  
  | ##[debug]   pass:*** |  
  | ##[debug]   -passout |  
  | ##[debug]   pass:*** |  
  | sr/local/bin/openssl pkcs12 -in /Users/vsts/agent/2.153.2/work/_temp/Yxxx-entrprise-development.p12 -nocerts -passin pass:*** -passout pass:*** \| /usr/bin/grep friendlyName |  
  | MAC verified OK |  
  | ##[debug]success of first tool:true |  
  | ##[debug]rc:1 |  
  | ##[debug]success:false |  
  | ##[debug]task result: Failed |  
  | ##[error]Error: /usr/bin/grep failed with return code: 1
```

**Comment by anaisbetts** [comment]
@jessedc I don't believe that this is the same error, yours is failing because of `grep`, mine is failing because of a failing call to `security`

```
##[error]Error: Error setting the partition_id ACL for the private key. Verify that the `Keychain password` is correct, or use a `Temporary Keychain` instead.
```

**Comment by jessedc** [comment]
@anaisbetts Yes the errors are different - In my failure it's [failing to fetch the 'friendlyName' of the private key](https://github.com/microsoft/azure-pipelines-tasks/blob/b84aa58961d3b637f7d8036d06998b30480fa00c/Tasks/Common/ios-signing-common/ios-signing-common.ts#L627) in your case the grep for `friendlyName` is passing, but then [failing to find the primary key](https://github.com/microsoft/azure-pipelines-tasks/blob/b84aa58961d3b637f7d8036d06998b30480fa00c/Tasks/Common/ios-signing-common/ios-signing-common.ts#L699 in the keychain using this value. 

In both of our cases the Task is trying to update the permissions of this new certificate as it's added to an _existing_ keychain. The keychain is existing because this task is on its second run. This particular code path is not run the firs time this Task is run, since it's creating the keychain at that point.

I think the `grep` for `FriendlyName` might be the common brittle component here?

**Comment by anaisbetts** [comment]
@jessedc legit - it's a bit odd that they'd invoke grep in this script at all, why not just search the string in the code?

**Comment by bootress** [comment]
I'm having the exact same issue as @anaisbetts. While trying to install the _second_ certificate as part of a pipeline:
```
2019-09-09T14:53:41.6398570Z [command]/usr/local/bin/openssl pkcs12 -in /Users/vsts/agent/2.155.1/work/_temp/macos_developerID_installer.p12 -nokeys -passin pass:*** | /usr/local/bin/openssl x509 -noout -fingerprint -subject -dates
2019-09-09T14:53:41.6577740Z MAC verified OK
2019-09-09T14:53:41.8947020Z SHA1 Fingerprint=3D:50:AB:BF:75:F2:B1:1C:2D:C0:B5:CC:65:27:B0:B4:73:47:D6:25
2019-09-09T14:53:41.8953290Z subject= /UID=8AVSFD7ZED/CN=Developer ID Installer: Electronic Theatre Controls, Inc. (8AVSFD7ZED)/OU=8AVSFD7ZED/O=Electronic Theatre Controls, Inc./C=US
2019-09-09T14:53:41.8954340Z notBefore=Apr 25 20:50:06 2019 GMT
2019-09-09T14:53:41.8955110Z notAfter=Apr 25 20:50:06 2024 GMT
2019-09-09T14:53:41.8970400Z [command]/usr/bin/security unlock-keychain -p *** /Users/vsts/agent/2.155.1/work/_temp/ios_signing_temp.keychain
2019-09-09T14:53:41.8978100Z [command]/usr/bin/security import /Users/vsts/agent/2.155.1/work/_temp/macos_developerID_installer.p12 -P *** -A -t cert -f pkcs12 -k /Users/vsts/agent/2.155.1/work/_temp/ios_signing_temp.keychain
2019-09-09T14:53:41.8979060Z 1 identity imported.
2019-09-09T14:53:41.9001630Z [command]/usr/local/bin/openssl pkcs12 -in /Users/vsts/agent/2.155.1/work/_temp/macos_developerID_installer.p12 -nocerts -passin pass:*** -passout pass:*** | /usr/bin/grep friendlyName
2019-09-09T14:53:41.9002340Z MAC verified OK
2019-09-09T14:53:41.9002910Z     friendlyName: Developer ID Installer: Electronic Theatre Controls, Inc. 
2019-09-09T14:53:41.9020610Z [command]/usr/bin/security set-key-partition-list -S apple-tool:,apple: -s -l Developer ID Installer: Electronic Theatre Controls, Inc. -k *** /Users/vsts/agent/2.155.1/work/_temp/ios_signing_temp.keychain
2019-09-09T14:53:41.9021600Z security: SecItemCopyMatching: The specified item could not be found in the keychain.
2019-09-09T14:53:41.9099340Z ##[error]Error: The process '/usr/bin/security' failed with exit code 1
2019-09-09T14:53:41.9114280Z ##[error]Error: Error setting the partition_id ACL for the private key. Verify that the `Keychain password` is correct, or use a `Temporary Keychain` instead.
```
It says to use a temporary keychain, which I already am doing. Anyone aware of a workaround for this?

**Comment by dan-weiss** [comment]
One fix for this issues is to put both the application and installer certificates in the same .p12 file. The InstallAppleCertificate@2 task will then install both certificates.

**Comment by sgissinger** [comment]
My workaround is to install additional certificates manually.  
That is, download the secure file and register in the keychain created by InstallAppleCertificate@2 task.

In my case, creating a custom keychain did not work because it does not seem to be registered in the system.  
The certificates added in the custom keychain weren’t listed by `security find-certificate -aZ` command.

With this workaround, I re-use `ios_signing_temp.keychain` keychain created by InstallAppleCertificate@2 task.

```  
- task: InstallAppleCertificate@2
  displayName: Install development certificate
  inputs:
    certSecureFile: development.p12
    certPwd: $(developmentCertificatePassword)

- task: DownloadSecureFile@1
    name: distributionCertificate
    displayName: Download distribution certificate
    inputs:
      secureFile: distribution.p12

- pwsh: security import $(distributionCertificate.secureFilePath) -P $(distributionCertificatePassword) -A -t cert -f pkcs12 -k $(Agent.TempDirectory)/ios_signing_temp.keychain
  displayName: Install distribution certificate

- pwsh: security find-certificate -aZ
  displayName: List certificates   
```

`$(developmentCertificatePassword)` and `$(distributionCertificatePassword)` are secret values stored in an Azure DevOps variable library.

`security import` with `-A` flag is considered insecure and is not recommended. See import Section in [https://www.unix.com/man-page/osx/1/security/](https://www.unix.com/man-page/osx/1/security/) for details.

PS: Copied from https://developercommunity.visualstudio.com/t/azure-pipeline-cannot-install-two-apple-certificat/788617#T-N1416650

**Comment by anatolybolshakov** [comment]
Reopened since it stilll seems to be relevant.

**Comment by anatolybolshakov** [comment]
Hi everyone! We've merged fix for this issue - please note that there could be some delays in roll out due to upcoming New Year holidays.

**Comment by anatolybolshakov** [comment]
Hi everyone! Fix for this issue has been already rolled out - closing it as resolved at the moment. Please let us know if you have any other questions.

**Comment by 1RGB1** [comment]
The issue remain the same
