### ISSUE TITLE
Upload all files under the current folder using Set-AzureStorageBlobContent is not working.

### ISSUE THREAD

**Issue by alucardu** [microsoft/azure-pipelines-tasks#10871]
When I use `Set-AzureStorageBlobContent` nothing is actually transferred to the container.

    $context = New-AzureStorageContext -StorageAccountName $env:prSourceBranchName -StorageAccountKey "******"
    Get-ChildItem -Path $env:System_DefaultWorkingDirectory/_ClientWeb-Build-CI/ShellArtifact/out/build
    Get-ChildItem -Path $env:System_DefaultWorkingDirectory/_ClientWeb-Build-CI/ShellArtifact/out/build ls -File -Recurse | Set-AzureStorageBlobContent -Container "embracesomething" -Context $context

![image](https://user-images.githubusercontent.com/779921/60973461-9e37ff00-a328-11e9-8caf-18bdd3685c87.png)

**Comment by alucardu** [comment]
It might have been that my -StorageAccountKey was incorrect. The issue is now resolved. I would like to add a suggestion though. There's no feedback when the -StorageAccountKey is incorrect.

**Comment by rajatagrawal-dev** [comment]
Closing the issue since it is resolved.
@alucardu If we are talking about the Azure File Copy task, then in that case the storage account key is fetched by the task itself, which will be valid. Not clear about the scenario here.
Feel free to open a new issue if you think there are some guidance gaps or anything else.
