### ISSUE TITLE
[error]An error occurred while sending the request (Azure PowerShell v4)

### ISSUE THREAD

**Issue by manuelsidler** [microsoft/azure-pipelines-tasks#10886]
## Required Information

- Type: Bug
- Task Name: Azure PowerShell v4

## Environment
- TFS on-premises: Version 16.131.28601.4
- Agent: Private (OS: Win 2012 R2, Agent Version: 2.144.0)

## Issue Description
We use the Azure PowerShell Task v4 (4.154.4) on our TFS on-premises machine. We've built and installed the task manually. Unfortunately the task fails with an error when connecting to Azure (see error below). To verify we've also setup a pipeline on Azure Dev Ops in the cloud with the same private agent and the same service principals as the TFS on-premises is using. On Azure Dev Ops the task works like a charm.

### Task logs
See zip file in attachments

### Error logs
```
2019-07-11T12:08:47.2351428Z ##[command]Clear-AzContext -Scope Process
2019-07-11T12:08:48.5587285Z ##[command]Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
2019-07-11T12:08:49.7094424Z ##[command]Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud
2019-07-11T12:08:53.9484630Z ##[error]An error occurred while sending the request.
2019-07-11T12:08:53.9497483Z ##[debug]Processed: ##vso[task.logissue type=error]An error occurred while sending the request.
2019-07-11T12:08:53.9998607Z ##[debug]Leaving Initialize-AzModule.
```
[log.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3386209/log.zip)

**Comment by rajatagrawal-dev** [comment]
@manuelsidler Are you able to execute the Azure PowerShell v3 task on the on-premise setup? Please also try the "Azure CLI" task to see if that works for you. Also ensure there are no firewall rules preventing the connection to Azure.

**Comment by Kreism** [comment]
HI @rajatagrawal-dev (i am working with Manuel) The v3 Task is not working, because it needs azureps (old version) we have installed the new AZ Versions. But If we try to connect manually on powershell with the same commands and with the account the build agents work on, it works fine. Firewall is open, because it worked before with v2. Thanks Martin

**Comment by rajatagrawal-dev** [comment]
@Kreism If not already done so, can you try to configure the agent with the same user account as with which you are manually running the commands? Configuring an agent on a different machine is another thing that can be tried.
Since Azure PowerShell task is basically just trying to login using the Connect-AzAccount command on your agent machine (in a powershell session opened using the user credentials used to configure the agent). So generally I would expect this command to work through the task as well.

**Comment by rajatagrawal-dev** [comment]
Closing this for now. Please reopen if you have more info.
