### ISSUE TITLE
Semicolon-separated paths starting with ./ parsed incorrectly

### ISSUE THREAD

**Issue by bender2k14** [microsoft/azure-pipelines-tasks#11009]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLIV2

## Environment
*Server*: Azure Pipelines
*Agent*: Hosted

## Issue Description

I doubt this issue is specific to DotNetCoreCLIV2.  This is just where I encountered it, and I am using it in my minimal working example.  When I use the DotNetCoreCLIV2 task with `pack` for the `command` property, I had unexpected behavior with the `searchPatternPack` property.

In an effort to improve readability, I prefer to start relative paths with `./`.  But when I combined two suchs paths as the value of the property `searchPatternPack`, the second one is not parsed correctly. Only the first project file is found.  See the first set of log events below.

If I remove the initial `./` from my relative paths, then both paths are parsed correctly, and both project files are found.  See the second set of log events below.

A related issue is [#4100](https://github.com/microsoft/azure-pipelines-tasks/issues/4100).

### Task logs

On input `'./A/A.csproj;./B/B.csproj'`, the relevant logs entries are
```
##[debug]searchPatternPack=d:\a\1\s\A\A.csproj;\B\B.csproj
...
##[debug]pattern: 'd:\a\1\s\A\A.csproj'
##[debug]expanding braces
##[debug]pattern: 'd:/a/1/s/A/A.csproj'
##[debug]findPath: 'd:\a\1\s\A\A.csproj'
##[debug]statOnly: 'true'
##[debug]found 1 paths
##[debug]applying include pattern
##[debug]1 matches
##[debug]pattern: '\B\B.csproj'
##[debug]expanding braces
##[debug]pattern: '/B/B.csproj'
##[debug]findPath: '\B\B.csproj'
##[debug]statOnly: 'true'
##[debug]ENOENT
##[debug]found 0 paths
##[debug]applying include pattern
##[debug]0 matches
##[debug]1 final results
##[debug]Found 1 files
##[debug]--File: d:\a\1\s\A\A.csproj
```

On input `'A/A.csproj;B/B.csproj'`, the relevant log entries are
```
##[debug]searchPatternPack=d:\a\1\s\A\A.csproj;B\B.csproj
...
##[debug]pattern: 'd:\a\1\s\A\A.csproj'
##[debug]expanding braces
##[debug]pattern: 'd:/a/1/s/A/A.csproj'
##[debug]findPath: 'd:\a\1\s\A\A.csproj'
##[debug]statOnly: 'true'
##[debug]found 1 paths
##[debug]applying include pattern
##[debug]1 matches
##[debug]pattern: 'B\B.csproj'
##[debug]expanding braces
##[debug]pattern: 'B/B.csproj'
##[debug]findPath: 'd:\a\1\s\B\B.csproj'
##[debug]statOnly: 'true'
##[debug]found 1 paths
##[debug]applying include pattern
##[debug]adjustedPattern: 'd:\a\1\s\B/B.csproj'
##[debug]1 matches
##[debug]2 final results
##[debug]Found 2 files
##[debug]--File: d:\a\1\s\A\A.csproj
##[debug]--File: d:\a\1\s\B\B.csproj
```

**Comment by hiyadav** [comment]
As figured out by you correctly, this issue is derived from the underlying library: [Azure-pipelines-task-lib](https://github.com/microsoft/azure-pipelines-task-lib) that is being used to handle paths/patterns across all folders. Task uses libraries findMatch function.

I would suggest opening the issue on Azure-Pipelines-task-lib repo for better action.

**Comment by jtpetty** [comment]
@hiyadav - I do not believe the issue is with the task-lib. The issue appears to be that the "searchPatternPack" input is set to be of type "filePath", which is what is causing manipulation of the input. A type of "filePath" is to be used for a single file path.

**Comment by dikhakha** [comment]
@elbatk This issue is for pack command can you please take a look ?

**Comment by dikhakha** [comment]
@elbatk The searchPatternPack is semi-colon separated list of file path. Since this input is of type filePath, it tries to resolve the whole thing as one path. The input should be of type string and it should be first processed (using ; as separator) to return array of paths and then resolve individual paths. Thoughts ?

**Comment by tejasd1990** [comment]
Hi @elbatk Can you look into it, since the issue is related to the pack command?

**Comment by tejasd1990** [comment]
Hi @elbatk , ping!!

**Comment by elbatk** [comment]
Sorry for the delay here. A couple of things:
1. We are deprecating these heavy Azure Pipelines task in favor of a model where we help set up auth with tasks and then let you run your custom scripts as you would a command line (like dotnet pack). That would mitigate issues like these. 
2. It looks like there is a valid workaround (just change the file path structure in the command)

Because of 1 & 2, I don't think we'll be looking to update this task with a fix. With that said, these tasks are open source and we are more than happy to take contributions from the community.
