### ISSUE TITLE
How to work with NuGet Package Manager Console in Azure Pipelines?

### ISSUE THREAD

**Issue by sander1095** [microsoft/azure-pipelines-tasks#11015]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: NuGet  

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure PipeLines

- Agent - Hosted or Private: 
Hosted

## Issue Description

Hello!

I have built an application with the https://github.com/marektoman/mechaview library. To get that to work fully, I need to execute `start-app` in the NuGet Package Manager Console in visual studio. Locally, this works great but I sadly can't figure out how to do this in azure pipelines.

Can you guys tell me how I could accomplish this?

**Comment by magleaso** [comment]
Have you tried executing start-app with the powershell task? Not sure which aspects of that package manager console environment are required.

**Comment by satbai** [comment]
I'm unfamiliar with Mechaview but it looks like the [start-app](https://github.com/marektoman/mechaview/blob/c403482e437eecc65bd26232d691c735fe268505/MechaView/MechaView.MahApps/tools/MechaView.psm1#L7) command expects something from Visual Studio. Some of the [hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops) have VisualStudio installed, so you can read the code of the start-app command and make sure everything it expects from the Package Manager Console or Visual Studio are set up properly in your build agent. 

You can probably start the process by trying to run start-app outside of the Package Manager console, from a PowerShell console for example. Once you know how to run it outside of the Package Manager console it might be easier to set up the build environment in your task in Pipelines.

Once you know exactly what you need for your build environment you can try to set up the environment manually by writing a script and using the PowerShell task like magleaso suggested. I don't know if you need to make changes to the MechaView library to achieve this or not. I'm also not sure what the library does exactly and what your end goal is, but since this isn't really an issue with Pipelines but details of an external library, I'm going to close this issue. Good luck with the investigation!
