### ISSUE TITLE
CacheBeta doesn't restore execute bit on cache hit

### ISSUE THREAD

**Issue by Petermo** [microsoft/azure-pipelines-tasks#11042]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheBeta

## Environment
- Server - Azure Pipelines
   - 

- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name:
Ubuntu 1604

## Issue Description
Executable bit not restored correctly for files when applicable.

## Repro steps
Cache project with node_modules with an executable file (eg 'webdriver-manager'), when ran with a cache hit (so, the second time ;)) the permission denied error pops up (exit code 126).

### Error logs
```
success Already up-to-date.
$ webdriver-manager update && node node_modules/phantomjs-prebuilt/install.js
/bin/sh: 1: webdriver-manager: Permission denied
error Command failed with exit code 126.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
:yarn_install FAILED
```

**Comment by archive** [comment]
We had a similar problem with `dtrace-provider` package: _"The specified solution configuration "release|any cpu" is invalid"_. 

We solved it with an extra step after the cache restore, a step that removes the "broken" package from the node_modules folder, so that the `yarn install` would install a non-cached version that worked. Not the nicest way but it solved the problem for now.

**Comment by marcussonestedtbarium** [comment]
+1. Happens in node_modules/.bin on linux. Had to add an extra chmod step, similar to what @archive said above.

**Comment by fadnavistanmay** [comment]
This is now supported.
