### ISSUE TITLE
Timezone interpretation for the PublishTestResults task

### ISSUE THREAD

**Issue by jimhester** [microsoft/azure-pipelines-tasks#11087]
**Question, Bug, or Feature?**  
*Type*: Question / Bug

**Enter Task Name**: PublishTestResults

## Environment
- Server - Azure Pipelines - https://dev.azure.com/jamesfhester/azuretest/_build/results?buildId=197&view=ms.vss-test-web.build-test-results-tab

## Issue Description

How is the timezone for the test results determined? I am outputting ISO8601 in the published XML, with a suffix Z, but the timezones seem to be interpreted in the web UI in my local time EDT.

In particular see the 'Failing since' column below.

![Screenshot 2019-08-07 10 22 06](https://user-images.githubusercontent.com/205275/62630604-47a8eb00-b8fd-11e9-94cb-369211ae69cd.png)

The uploaded XML looks like this

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="foo" timestamp="2019-08-07T14:01:29Z" hostname="3377578cac1e" tests="2" skipped="0" failures="1" errors="0" time="0.16">
    <testcase time="0.14" classname="foo" name="foo_works"/>
    <testcase time="0.02" classname="foo" name="foo_does_not_work">
      <failure type="failure" message="foo() not equal to 2. (@test-foo.R#6)">foo() not equal to 2.
1/1 mismatches
[1] 1 - 2 == -1</failure>
    </testcase>
  </testsuite>
</testsuites>
```

Is there anything I can do to ensure the timestamps are interpreted as UTC, ro that the output will be in the Users' local timezone regardless of what timezone they are in?

**Comment by ArieHein** [comment]
The only reason for it to follow users local timezone is if you use on prem agents. For hosted agents its what ever is in the image (maybe taking the time from the AKS running the docker images). There is one more Time zone setting and that is the organization settings that might be a factor in all timings, including build and release timestamps, creating new workitem timestamps etc

**Comment by jimhester** [comment]
I guess my point is if the timestamp is output in UTC, none of these system specific timestamps should matter, UTC is a fixed time, so no time zone calculation needs to be done.

If the web UI is reporting the time as 4 hours ago when it was actually 10 minutes ago then it is not reading the timestamp as UTC, regardless of what the system timezone or the org specific timezone is set to.

**Comment by roydebalina** [comment]
Sorry for the late reply Jim. 
For Publish Test Results Task, the timestamp parsed from the xml is stored in UTC on the backend but when it is displayed in the UI , it is converted to Locale TimeZone. For the column 'Failing Since', we show the time difference between the failing timestamp and the present time (both always in the 1 particular timezone only that is your Locale Timezone). This time difference should always remain the same irrespective of the time zone in which it is calculated. If the activity has taken place before 48hours , the exact date is displayed in such cases and not the time difference. 
For the XML provided , 'Failing Since' should show Aug 7. A issue where time reported as 4hours ago where it is 10 mins should not happen since this is time difference . There are corner cases when time mismatch can happen i.e. boarder lines of 2 time zones. Example: if the xml had a time stamp "2019-11-21T22:01:29Z" , it will show 21st nov if System time is in UTC and will show 22nd nov if system time is in IST.  So if the time reported as 4hours instead of 10mins require a account details to verify the issue. The link provided is no longer in working state. So it's a request to provide another link to look into the issue. Sorry for the inconvenience caused.

**Comment by navin22** [comment]
Please reopen if you still find an issue with this!
