### ISSUE TITLE
NPM Publish: can't publish tarball to Azure Artifacts registry

### ISSUE THREAD

**Issue by uniqueiniquity** [microsoft/azure-pipelines-tasks#11304]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: npm

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: DevDiv, DevDiv, "TypeScript-IntelliCode NPM Publish"/Release-10

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: ubuntu-16.04

## Issue Description

I have a build definition that produces a tarball containing an npm package (using npm pack) and outputs it as a pipeline artifact. I would like to have a release pipeline that downloads the tarball and publishes it to a private registry in Azure Artifacts (from the command line, this is `npm publish package.tgz`).

However, I can't use the default `npm publish` option in the task, since that only works by running `npm publish` in a working directory with a package.json. Unfortunately, when using the `npm custom` option in the task, setting the "Registries to use" to the desired registry results in an authentication error, despite the registry being part of the same account and team project.

### Task logs

[ReleaseLogs_440236.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3585938/ReleaseLogs_440236.zip)

### Error logs

```
2019-09-06T22:52:43.7889720Z 17 verbose stack Error: Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47, Basic realm="https://pkgsprodwus21.pkgs.visualstudio.com/", TFS-Federated
2019-09-06T22:52:43.7889993Z 17 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:94:17)
2019-09-06T22:52:43.7890033Z 17 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-09-06T22:52:43.7890065Z 18 verbose statusCode 401
```

**Comment by jotaylo** [comment]
What's happening here is that you're specifying a publishConfig/registry in your package.json file. The npm custom task prepares a .npmrc file that sets a registry and authenticates to that registry, however instead of using the feed name in the registry string, it uses the feed's id. Without the publishConfig value in the package.json, this registry would be picked up and published to, however with the publishConfig value, npm is actually trying to authenticate to a "different" registry, and it can't match the registries together to provide the authentication.

Options: 
- Remove the publishConfig value from package.json
- Update the publishConfig value to contain the feedId (found in logs) instead of the feed name
- Use the [npmAuthenticate](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm-authenticate?view=azure-devops) task instead

**Comment by edgarrs** [comment]
Solution has been provided in previous comment

**Comment by QTom01** [comment]
There does not seem to be a good solution to this. I have tried changing the publishConfig value to use the feedId as suggested but this does not work. Looking at the logs from the npm publish tasks I can see this line:

```
; userconfig C:\Agent\_work\7\npm\11803.npmrc
registry = "https://[company-name].pkgs.visualstudio.com/_packaging/[random-guid]/npm/registry/"
```

The GUID is different every time meaning it is impossible to use the publishConfig.registry value as far as I can see?
