### ISSUE TITLE
Created Initialize-Az to mimic functionality of Initialize-Azure

### ISSUE THREAD

**Issue by BLZ3** [microsoft/azure-pipelines-tasks#11467]
*Type*: Question
**Task Name:** Common/VstsAzureHelpers 

I have several custom build tasks created using the AzureRM powershell module.  I am starting the process of converting these tasks over to the Az module.  I have used the Initiliaze-Azure function from VstsAzureHelpers module and noticed that the module lacked an equivalent function for the Az module.  I am wondering if I am have simply overlooked the correct function to use for this or if the new function I have written would be beneficial for others using this module?

**Comment by BLZ3** [comment]
Here is the function I have duplicated from the Initialize-Azure function and the line required to export the function:

```
function Initialize-Az {
    [CmdletBinding()]
    param(
        [string] $azVersion,
        [switch] $strict
    )
    Trace-VstsEnteringInvocation $MyInvocation
    try {
        # Get the inputs.
        $serviceNameInput = Get-VstsInput -Name ConnectedServiceNameSelector -Default 'ConnectedServiceName'
        $serviceName = Get-VstsInput -Name $serviceNameInput -Default (Get-VstsInput -Name DeploymentEnvironmentName)
        if (!$serviceName) {
            # Let the task SDK throw an error message if the input isn't defined.
            Get-VstsInput -Name $serviceNameInput -Require
        }

        $endpoint = Get-VstsEndpoint -Name $serviceName -Require
        Initialize-AzModule -Endpoint $endpoint -azVersion $azVersion
    } finally {
        if (![string]::IsNullOrEmpty($currentWarningPreference)) {
            $WarningPreference = $currentWarningPreference
        } else {
            $WarningPreference = "Continue"
        }
        Trace-VstsLeavingInvocation $MyInvocation
    }
}

Export-ModuleMember -Function Initialize-Az
```

**Comment by niadak** [comment]
You can use Initialize-AzModule function. For example, we are doing so in [AzureFileCopy task](https://github.com/microsoft/azure-pipelines-tasks/blob/4de28e88fd53a2e6e7380a9adeba058198fc461e/Tasks/AzureFileCopyV3/AzureFileCopy.ps1#L68). 

Logic for reading task inputs should be in individual task code instead of in the common function. For example, because of this common function all the tasks are forced to use the task input name as ConnectedServiceNameSelector, ConnectedServiceNameARM, ConnectedServiceName etc which is not correct behavior.
