### ISSUE TITLE
Task input validation is broken when using $ character

### ISSUE THREAD

**Issue by abbottbd** [microsoft/azure-pipelines-tasks#11509]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: All tasks using input validation regex defined in task.json

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    TFS on-premises
    - If using TFS on-premises, provide the version: 
    Azure Devops server 2019 (no patches or updates)
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version:  N/A

## Issue Description
When you define an input validation regex in the task.json it is not applied to the value entered at design time as soon as a $ character is entered in the field. 

Consider this Task.Json:
 "name": "MinorVersion",
      "type": "string",
      "label": "Minor Version",
      "defaultValue": "$(MinorVersion)",
      "required": true,
      "helpMarkDown": "Minor Version Number",
      "validation": {
        "expression": "**isMatch(value,'(^\\d{1,4}$)','IgnoreCase,Multiline')**",
        "message": "Value must either be a 1-4 digit number or a build variable"
The regex should only match 1-4 digit numbers.  Nothing else should be allowed.
However in practice any value that contains a '$' character is accepted:
![image](https://user-images.githubusercontent.com/19344687/66252311-f9eb0c00-e70e-11e9-9181-ffcbccb6c2a6.png)

Ideally I would like to enforce a regex like this: 
        "expression": "isMatch(value,'(^\\d{1,4}$)|(^\\$\\(.*\\)$)','IgnoreCase,Multiline')",
such that a user can only enter a valid number, or a properly formatted build variable, however it is impossible to enforce proper format because a $ character anywhere in the field seems to break the regex evaluation.

**Comment by damccorm** [comment]
@abbottbd I was unable to get a full repro on this - it looks like when you try to save a pipeline with an invalid syntax like the one you showed it fails to save, so the validation itself is working:
![image](https://user-images.githubusercontent.com/42773683/73553088-5a692c00-4417-11ea-9aff-72c58d90f78a.png)

With that said, you don't currently get the live highlighting that its invalid to show up in the UI - expected:
![image](https://user-images.githubusercontent.com/42773683/73553176-7c62ae80-4417-11ea-9ee2-898857110eb3.png)

actual:
![image](https://user-images.githubusercontent.com/42773683/73553215-8e445180-4417-11ea-873c-c85e46320fd7.png)

I think that's ok though. I believe we're more permissive on that check because we don't have access to the dotnet RegEx function we use for the actual matching and don't want to accidentally overrestrict.

**Comment by damccorm** [comment]
I'm going to close here since I think this is actually working as expected, please comment if you'd like me to reopen.
