### ISSUE TITLE
AzureResourceGroupDeployment@2 csmFile path not working if not in root directory

### ISSUE THREAD

**Issue by cnadolny** [microsoft/azure-pipelines-tasks#11520]
## Required Information

*Type*: Bug
Enter Task Name: AzureResourceGroupDeployment@2

## Environment
- Server - Azure Pipelines 

- Agent - Hosted 
    

## Issue Description

Using the AzureResourceGroupDeployment@2 task and providing the file path link to the ARM template via csmFile does not work unless the file is in the root directory. My file is located in a folder called tooling, and I've tried multiple options like so:

tooling/azuredeploy.json
$(Build.SourcesDirectory)/tooling/azureDeploy.json
./tooling/azuredeploy.json
$(Pipeline.Workspace)/tooling/azureDeploy.json

I ran a script to check pwd of the directory:
/home/vsts/work/1/s

 and ls -lha of the root directory:
-rw-r--r-- 1 vsts docker 4.6K Oct  7 22:21 azureDeploy.json
drwxr-xr-x 3 vsts docker 4.0K Oct  7 22:21 tooling

and then of the tooling directory:
-rw-r--r-- 1 vsts docker  213 Oct  7 22:21 azureDeploy.json

Nothing seems amiss, as far as I can tell. Whenever I try running the deployment attempting to use the tooling/azuredeploy.json file, I get this error:
##[error]Error: Could not find any file matching the template file pattern

Otherwise, if I use the root directory azuredeploy.json, it works fine.

**Comment by tejasd1990** [comment]
Hi @cnadolny ,
From the working path of the agent directory '/home/vsts/work/1/s', I assume the agent is linux. On linux machines, paths are case sensitive, so 'tooling/azuredeploy.json' and './tooling/azuredeploy.json' won't work since the filename has is 'azuredeploy.json' in these paths, whereas the actual filename is 'azureDeploy.json'(capital D). 

Also, the path '$(Pipeline.Workspace)/tooling/azureDeploy.json' won't work since '$(Pipeline.Workspace)' would be '/home/vsts/work/1' in this case. 

The path '$(Build.SourcesDirectory)/tooling/azureDeploy.json' should work. I tried to repro this and this path worked for me. Are you sure that you are getting the same error even with this path?

Also, how are you creating the pipeline? Via YAML or the classic editor?

**Comment by tejasd1990** [comment]
Hi @cnadolny ,
were you able to try the suggestion above and did it work?

**Comment by tejasd1990** [comment]
Hi @cnadolny ,
let us know if you were able to get unblocked with this. We will close this issue.
