### ISSUE TITLE
Allow dotnet test with publish --results-directory to be customized

### ISSUE THREAD

**Issue by ktmaul** [microsoft/azure-pipelines-tasks#11536]
*Type*: Feature

**Enter Task Name**: .NET Core - test

## Environment
Server - Azure Pipelines

## Issue Description

Checking the **Publish test results and code coverage** option sets --results-directory to the agent's temporary directory, making it difficult to isolate a single build's test output when publishing the results of multiple data collectors.

Recommendation: Allow --results-directory to be overridden (via textbox) when **Publish test results and code coverage** is checked.

This would allow users to harvest the output for publishing to additional code coverage tools or overcome shortcomings in the existing tooling (such as the code coverage tab only providing a link instead of an html report).

**Comment by ktmaul** [comment]
@bishal-pdMSFT Any updates on this feature request?

**Comment by StingyJack** [comment]
@ShreyasRmsft @shashban - In addition to this OP's use case, this also creates a problem with SonarCloud integration because this task puts test results files in a location where SonarCloud's task does not look for them.  This config option is present and works with the VSTest task, so until this is configurability problem is fixed, we have to use the VSTest task in all of our devops pipelines. 

Also trying to include this parameter in the Arguments field just appends it to the existing CLI and does not replace the value the task submits

**Comment by StingyJack** [comment]
@shashban - why aren't you required to respond before this gets closed?

**Comment by abatishchev** [comment]
@StingyJack @vijayma  Any updates on this feature request?

**Comment by woeterman94** [comment]
Any updates on this feature request?

**Comment by woeterman94** [comment]
Workaround set publishTestResults to false. 
_Enabling this option will generate a test results TRX file in $(Agent.TempDirectory) and results will be published to the server.
This option appends --logger trx --results-directory $(Agent.TempDirectory) to the command line arguments.
Code coverage can be collected by adding --collect "Code coverage" to the command line arguments._
