### ISSUE TITLE
VsTest parallel execution - Anticipated execution time not getting set for tests and thus leading to in-efficient distribution

### ISSUE THREAD

**Issue by migheorghe** [microsoft/azure-pipelines-tasks#11659]
## Description
When executing VsTest task with batches on Azure pipelines some agents seem to be lagging in receiving the batch and executing it.

Concrete case:
Executing 3900 tests with 50 hosted agents and 80 tests per batch

Expected behavior:
49 agents should receive a batch to execute, 1 agent will wait for all the parallel jobs to finish
Actual behavior:
45 agents receive a batch to execute, 2 agents receive 2 batches,  3 agents don't receive any. This behavior causes the entire task to run for twice as long as expected:

The agents that don't execute any tests receive the Start command with almost 9 minutes delay:

2019-10-28T07:59:50.2811567Z Test run with Id 2075764 associated
2019-10-28T08:08:08.6701979Z Received the command : Start

in contrast to the working agents 

2019-10-28T07:59:53.4110229Z Test run with Id 2075764 associated
2019-10-28T08:00:04.3868288Z Received the command : Start

**Comment by migheorghe** [comment]
Please see attached logs bellow. If you look in both of them the string "Received the command : Start" you will see a big difference in "no_batch.txt" between wait time for Start command and the actual received time.

[correct.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3803025/correct.txt)
[no_batch.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3803026/no_batch.txt)

*We have deleted private info.

**Comment by karanjitsingh** [comment]
@migheorghe, i see that testing with no batch takes around ~20. Distribution makes sense when you have long running tests (each test taking a few minutes).

When distributing, each agent actually waits for one of the agents to complete the discovery and send the slices (hence the initial wait).

With large number of agents each agent is not guaranteed to get a slice, even more so when running short tests.

**Comment by migheorghe** [comment]
@karanjitsingh I understand that at first the discovery is done by one agent and this takes a few minutes. We have no problem with this initial time.

Out input is this: 3900 tests, 50 agents, 80 tests batch size. With this we expect that each agent receives one batch to execute .
However as we can see from the files I attached (they are from the same run)  in the "correct.txt" file from the moment the agent started Waiting for "Start" command to the moment it actually received it it only took 1 second.
In the "no_batch.txt" file, the agent waited 14 minutes to received the "Start" command, but once it was received there were no batches left to execute because other agents were assigned a second batch. Because of this the entire run takes 15+ minutes (2 batches on some agents) while other agents do nothing.

**Comment by karanjitsingh** [comment]
@migheorghe, to look deeper into the telemetry data and to know where the agent spent its time please provide me with the account name where this was executed

**Comment by migheorghe** [comment]
@karanjitsingh sent you an email with information on account name and build url

**Comment by karanjitsingh** [comment]
@migheorghe, sent you the list of your slices being queued and completed. If you see there are instances where tests are so small that the agent immediately gets a new slice withing the throttle time of the other agent (agents timeout for 1 minute if they don't get a slice).

Unless your code contains a lot of assembly initialization before starting a batch of tests (prepare the environment, install stuff, etc). Letting the test execution automatically batch tests would make more sense

![image](https://user-images.githubusercontent.com/4632805/68469008-44e0cd80-023f-11ea-8baf-2341078784f3.png)

**Comment by migheorghe** [comment]
We have tried with autoBatchSize, and other combinations but the behavior is the same. Please check email. I’m expecting the tests to be distributed evenly(from the execution time point of view) on all the agents. Are we missing something? 
How to correctly distribute 4000 tests on 50 agents and have no significant time wasted on each job?

**Comment by ShreyasRmsft** [comment]
Agents get slices dynamically from the server and an agent can get more than 1 slice and some agents may not get any slices if another agent completed the allotted slice and requested for one more before the other agent could request for it's first slice due to whatever reason.

And also all agents have to wait till all other agents complete execution. This is by design and cannot be changed.

The issue in this case is that @migheorghe is running PR builds (different set of tests) and CI builds in the same build/pipeline definition. When the current build is running it looks for the last completed build which had a test run associated with it (in this case last completed build was a PR build with different set of tests that ran) and tries to get the test anticipated times from that build which it will not find because the current tests to be run did not run in the CI build did not run in that PR build causing all the anticipated times to be unknown thus causing in-efficient distribution.

This behavior of picking the build is as designed today and is not meant for a definition which runs different sets of tests each time, it is meant for a homogeneous definition only. Whatever the customer is asking is an enhancement and we will pick it up based on priority of our overall backlog.

The workaround is to split the definition into a PR build definition and a CI build definition to make it homogeneous.
