### ISSUE TITLE
AzureRmWebAppDeployment: add option to define deploy.cmd

### ISSUE THREAD

**Issue by ninjaonsafari** [microsoft/azure-pipelines-tasks#11700]
**Type**: Feature
**Enter Task Name**: AzureRmWebAppDeployment@4

## Environment
**Server**: Azure Pipelines
**Agent**: Hosted

## Issue Description
The problem is when I build my project, there are more than one `*.deploy.cmd` files.
Could you add an option the define which cmd file should be excecuted?

The issue is with [this line](https://github.com/microsoft/azure-pipelines-tasks/blob/c9c4827c8d0951c98a9468d83db708c593c7c428/Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/PublishProfileWebAppDeploymentProvider.ts#L109)

### Error logs
```
Error: More than one package matched with specified pattern: D:\a\r1\a\Builds\PackageAPI\*.deploy.cmd. Please restrain the search pattern.
```

**Comment by fhtino** [comment]
I've the same issue. My drop contains 2 zip files coming from 2 different web projects.  

I think the issue is in GetDeployCmdFilePath(). The code looks for *.deploy.cmd instead of the specific file.

`return packageUtility.PackageUtility.getPackagePath(packageDir + "\\*.deploy.cmd");`

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/PublishProfileWebAppDeploymentProvider.ts#L106

A question on StackOverflow about this issue: 
https://stackoverflow.com/questions/56891130/error-more-than-one-package-matched-with-specified-pattern-deploy-cmd-pleas

**Comment by Ben67366** [comment]
My problem is even there is the file, somehow it can't find the .deploy.cmd file.

Is there any how-to documents to explain how to deploy through pubxml file?

**Comment by fhtino** [comment]
Any news on this?

**Comment by kmkumaran** [comment]
@nadesu , @chshrikh for follow up.

**Comment by fhtino** [comment]
Any news on this?

**Comment by chshrikh** [comment]
@fhtino as per current priority we are not able to accommodate this for current quarter, we will consider this for next quarter planning

**Comment by fhtino** [comment]
Any solution, workaround, fix, ...  for this?

**Comment by fhtino** [comment]
Any news on this?  The issue was opened 2 year ago.
