### ISSUE TITLE
Test using X509Certificate2 certificate loaded from resource fails, "the specified network password is not correct."

### ISSUE THREAD

**Issue by WillSullivan** [microsoft/azure-pipelines-tasks#11703]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2 

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

(would prefer to hold that unless necessary)

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name:

(same here)

## Issue Description

I'm getting the following exception when attempting to create an X509Certificate2 instance from a pfx file (either deployed file or resource byte array). The test does not fail when run on development machines, but it fails when run on a hosted build server. 

> Failed   ReproTest
> Error Message:
>  Test method Lerl.TestGoBoom.ReproTests.ReproTest threw exception: 
> System.Security.Cryptography.CryptographicException: The specified network password is not correct.
> 
> Stack Trace:
>     at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
>    at System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromBlob(Byte[] rawData, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx)
>    at System.Security.Cryptography.X509Certificates.X509Utils.LoadCertFromBlob(Byte[] rawData, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle pCertCtx)
>    at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags)
>    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
> 
>    at ReproTests.ReproTest() in d:\a\1\s\Lerl\TestGoBoom\ReproTests.cs:line 22

The repro is pretty simple

``` c#
[TestMethod]
public void ReproTest()
{
	var cert = new X509Certificate2(Properties.Resources.MyPFX, "Password@1", X509KeyStorageFlags.EphemeralKeySet);
}
```

Again, the issue isn't the PFX as this test would pass on a desktop. 

I suspect the issue has something to do with the test being run outside the context of an account, so things like the personal cert store isn't available. 

I've tried pretty much every permutation of X509KeyStorageFlags that might make sense, but none bring the cargo planes back. 

I haven't been able to find any similar issues here or anywhere. Looking for some guidance. 

### Task logs

(Can be provided, but probably won't matter much here)

**Comment by ShreyasRmsft** [comment]
@WillSullivan could you please provide link to sample repro project? Store the same dummy code on a github repo and create a public project with the definition that runs the build or have a yaml based definition so that i can run straight from your repo.

Additionally to isolate the issue to the hosted machine leaving out whether it's the test tasks that are doing something or simply a hosted machine issue you can create an executable console app with the same code and try.

I still don't understand the full scenario here, you are trying to download a cert onto the hosted machine from a private blob? Are you able to get this with let's say an azure VM where you run the code manually? There's seems to be a lot of unknowns for me here, i'll need a good bit more data before i can help you out here.

**Comment by WillSullivan** [comment]
My repro code (included in the question) doesn't try to download anything. Create a byte array from a pfx and try to load it into a cert within a test. In the example, the cert was added as a resource https://docs.microsoft.com/en-us/visualstudio/ide/managing-application-resources-dotnet?view=vs-2019. Standard .NET framework solution, builds fine but the test fails, as is described within the issue.

**Comment by ShreyasRmsft** [comment]
Got it. Makes more sense now. I would still request you do the following though

> Store the same dummy code on a github repo and create a public project with the definition that runs the build or have a yaml based definition so that i can run straight from your repo.

> Additionally to isolate the issue to the hosted machine leaving out whether it's the test tasks that are doing something or simply a hosted machine issue you can create an executable console app with the same code and try.

This avoids the whole back and forth where i miss minor details (specific contents of pfx, exact hosted pool you are using etc.) and makes it simpler for me to act on the problem rather than trying to spend time setting up repro where i might miss details. Thanks.

**Comment by ShreyasRmsft** [comment]
Closing due to no response, please re-open with requested data.
