### ISSUE TITLE
dotnet publish -o functionality has changed

### ISSUE THREAD

**Issue by goalie7960** [microsoft/azure-pipelines-tasks#11740]
**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: dotnet

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: fv-az639

## Issue Description

dotnet publish -o flag seems to place output folder at root instead of inside the project being published

### Task logs

Running this:
"C:\Program Files\dotnet\dotnet.exe" publish D:\a\1\s\(PATH_TO_PROJECT) -o test_output

Used to do this:
PROJECT_NAME -> D:\a\1\s\(PATH_TO_PROJECT)\test_output\

Now it does this:
PROJECT_NAME -> D:\a\1\s\test_output\

EDIT:
I think this is happening b/c the task is defaulting to .NET core 3.x. I am now getting this message when the task starts:

Welcome to .NET Core 3.0!
---------------------
SDK Version: 3.0.100

It used to just say:

Welcome to .NET Core

**Comment by hiyadav** [comment]
Hey @goalie7960,
You're right, this is happening because the Agents have been updated to have latest .Net Core SDK's and CLI. This is the new behaviour in .Net Core CLI 3.0. We tend to keep the same behaviour and not change it.

However, we do understand this can be a problem when publishing multiple projects at once. For that you can do the following:

Use the `Add project name to publish path` (`modifyOutputPath` in YAML) input in .Net Core CLI task: This will create a sub folder with project file’s name, inside the output folder. Hence all your projects will be published under different sub-folder’s inside the output folder.

Sample YAML for task:
_steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-o testpath'
    zipAfterPublish: false
    **modifyOutputPath: true**_

**Comment by goalie7960** [comment]
@hiyadav 
I've tried this but it's not working quite as expected. Given I'm trying to build 2 projects with paths something like this:

:\A\B\C.csproj
:\A\D\E.csproj

What I want to happen is:

:\A\B\test_output
:\A\D\test_output

Instead I get this:

:\A\test_output
:\A\test_output

**Comment by hiyadav** [comment]
You must be getting 
:\A\test_output\C
:\A\test_output\E

However, if this doesn't solve your case and you absolutely need it to work like it used to work in .NET Core 2.2 and below, then you can use UseDotNetV2 task to download .NET Core SDK 2.2 or one of your preference. It will then provide you with old functionality.

**Comment by goalie7960** [comment]
No that's not what's happening, it's working like I specified.

But I have implemented the UseDotNetV2 and that has solved the problem until I have more time to address the problem.

**Comment by hiyadav** [comment]
Hey @goalie7960 ,

Glad to know you're unblocked. I would like to investigate why the other method not work for you, can mind sharing the pipeline logs when you tried using the `Add project name to publish path (modifyOutputPath in YAML)` and it did not create sub directories inside the output path.

You can paste the logs here, or send it over to hiyada@microsoft.com

**Comment by goalie7960** [comment]
@hiyadav Sent

**Comment by hiyadav** [comment]
Hey @goalie7960,

We have identified a bug and also why it is not working in you pipeline. 
**Kindly ensure that `Add project name to publish path (modifyOutputPath in YAML)` is enabled in your pipeline.**
- The folder name for your projects contains `'.'`` like: source.a and source.b. 
- Thus the task will end up creating `source` folder inside output folder, and output of projects in source.a and source.b will go to same folder BaseRepoPath/OutputFolder/Source/

**Workaround**: 
- Enable `Add project name to publish path (modifyOutputPath in YAML)`  in task.
- Change the folderName such that they are different from before the first occurence of `'.'`: like SourceA & SourceB rather than Source.A & Source.B

As a fix, we can take the entire directory name without slicing on `'.'`. But we doubt this will affect currently working pipelines for users.

**Comment by jalajmsft** [comment]
Hey @goalie7960 Did you get a chance to try out the workaround suggested above?

**Comment by goalie7960** [comment]
@jalajmsft Not yet, it's on my list. Will report back when I have a chance.

**Comment by goalie7960** [comment]
Upon further review, I believe the workaround suggested would require me to rename my folder structure, which I don't really want to do.

**Comment by hiyadav** [comment]
> Upon further review, I believe the workaround suggested would require me to rename my folder structure, which I don't really want to do.

I understand the pain in doing so, but due to the permanent behavior change from .NET Core 3.0, the publish -o change is going to stay. 
And since the behaviour of .NET CLI task for `modifyOutputPath` is being used a lot, changing its behaviour would mean breaking another set of customers. We would like to restrict that.

If you have some solution in mind we are open to suggestions :)

**Comment by goalie7960** [comment]
I understand.

For now the best solution for me is to keep using the UseDotNetV2 task. I assume that will not be deprecated?

**Comment by anuragc617** [comment]
Closing this issue as customer is unblocked and the reported behaviour is expected as per task design.
