### ISSUE TITLE
Unable to use Key Vault variable in Install an SSH Key task

### ISSUE THREAD

**Issue by johntyrrell99** [microsoft/azure-pipelines-tasks#11854]
Since the Install an SSH Key task is defined as a pre-job, it runs before all other tasks regardless of position in the pipeline. Therefore it runs before any Key Vault secrets are downloaded. I would prefer to not setup a standalone secret variable in the library for the passphrase but that seems to be the only way I can do it unless I'm missing something.

Am I missing something or is this working as designed?

Full disclosure, I'm new to all this stuff ...

**Comment by Pwd9000-ML** [comment]
Hmmm, I seem to have the same issue.
I have a keyvault secret for this, but yes, it seems this task runs as a Pre-Job and then fails because it is running before the "Azure Key Vault" tasks executes to get the secrets to use in the task??

I guess the question is can the install SSH key task be set to not be a "Pre-Job" task? or at least initialise the azure key vault task before the ssh task?

**Comment by KennyChen0909** [comment]
@Pwd9000-ML We have experienced this issue also. If the pre-job task for SSH key task can be set after the download key vault task. This issue can be resolved.

I checked the code from https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/InstallSSHKeyV0/task.json#L63 

>  "prejobexecution": {
>         "Node": {
>             "target": "preinstallsshkey.js",
>             "argumentFormat": ""
>         }

@damccorm  is it possible for your team to improve this?

**Comment by damccorm** [comment]
Right now this isn't supported, adding as an enhancement

**Comment by mahgo** [comment]
This would be great to have fixed.

**Comment by spoelstraethan** [comment]
The issue remains that if you don't specify the AzureKeyVaultV1 (or V2) task but are using a Variable Group backed by a KeyVault, that does NOT set the RunAsPreJob to `true`.

**Comment by haflidif** [comment]
This is still an issue as @spoelstraethan  mention when using Variable Group linked to a KeyVault, the Keyvault Task PreJob task which comes from KeyVault linked variable group should run before the InstallSSHKey but it doesn't run untill after.

**Comment by cobbled-street** [comment]
There is a workaround.
I also had the same issue because the InstallSSHKey@0 runs as a pre job, when the password was downloaded using a resource group with with key vault access, it runs after the pre job, so the SSH has already run with no secret.

The answer is to use the AzureKeyVault@2 task with RunAsPreJob: true, to download the secrets.
This task will run and download the secrets as a pre job before the InstallSSHKey@0 task. if it is put higher in the YAML.
