### ISSUE TITLE
Tough to recognize task changes for AgentPlugin type tasks

### ISSUE THREAD

**Issue by richardgavel** [microsoft/azure-pipelines-tasks#11894]
**Enter Task Name**: PublishPipelineArtifact

## Environment
- Server - Azure Pipelines
- Agent - Private

## Issue Description

When trying to diagnose issues with, for example PublishPipelineArtifact, and the same build succeeds and then later fails, it's tough to go in and see "ok, what changed" because the version number of the tasks isn't changing. But the underlying task implementation COULD be changing because the task simply points at a plugin residing inside the agent itself. So because the agent updated, it's POSSIBLE that the task logic might have changed. But it's not readily apparent which tasks this applies to via build logs.

**Comment by fadnavistanmay** [comment]
@vtbassmatt - Hey Matt, what is your opinion for the issue? 
Since the task and agent are being developed/deployed independently, this will be the issue.

**Comment by vtbassmatt** [comment]
I agree, this is a challenge with the way we've architected the plugins backing those tasks. The best thing to do in that case is compare agent versions, then diff the contents of that plugin. We take care to tag each release of the agent, so for instance, to compare the pipeline artifacts plugin from agent 2.164.3 against 2.160.0:

```bash
git diff v2.164.3 v2.160.0 -- src/Agent.Plugins/PipelineArtifact/
```

It doesn't seem you can narrow down to a directory, but GitHub will even show you the diff online: https://github.com/microsoft/azure-pipelines-agent/compare/v2.160.0...v2.164.3

I'm open to other ideas on how we could make this better, but I don't see any right now. (Closing this issue since I'm not planning to take any other action on it, but feel free to continue the discussion!)

**Comment by richardgavel** [comment]
1) Does the code for these tasks have to live inside the agent itself or
can it live in this repo?
2) Is there any way of changing the version of the task to match the agent
itself (and then only change when the code for the task code inside the
agent for that task changes). The point is to be able to see (oh, the
version number is different for the task, something DID change). As opposed
to seeing "well, the agent is different, but that could mean ANY kind of
change, maybe in the task, but maybe nothing to do with the task".

**Comment by vtbassmatt** [comment]
Good questions.

1) The agent isn't open for extension (the fact that we call some its parts "plugins" is a historical misnomer) and it really wants to all be built from the same place. We could potentially take a dependency on the tasks repo, but that feels like a big coupling for a small problem.
2) Same problem in reverse, mostly. The tasks want to be built and shipped independently of the agent. We're kidding ourselves here a little bit, since these task do in practice depend on the agent.

The affected tasks should at least be demanding a particular agent version (for example [here](https://github.com/microsoft/azure-pipelines-tasks/blob/2550cc9c1e2a7654695a073b4d8289b1920cb08a/Tasks/DownloadPipelineArtifactV2/task.json#L18)). When that demand changes, it's a good hint that something interesting changed in the agent side.

It's more interesting when that demand _doesn't_ change and yet something breaks. We certainly try not to do that, and in any case, other tasks could have subtle breaks even though they don't depend on a particular plugin.
