### ISSUE TITLE
[Maven] Use predefined JAVA_HOME variable

### ISSUE THREAD

**Issue by rcsilva83** [microsoft/azure-pipelines-tasks#11957]
*Type*: Feature

**Enter Task Name**: Maven

## Issue Description

I'm running my Maven build inside a container with only one JDK and Maven installed. I already have a JAVA_HOME correctly set, so I don't need Maven Task to set it for me.

There is no optimal solution for me now: 1) I can change my Docker image to set a "JAVA_HOME_<VERSION>_<ARCH>" variable that would be used only on Azure Devops; or 2) use "javaHomeOption: 'Path'" which is not as generic as a JAVA_HOME environment variable.

I propose the creation of a new "javaHomeOption" value that uses the predefined JAVA_HOME variable. Perhaps this should be the default option, as "JAVA_HOME" is default on a Java build environment.

**Comment by HughDevlin** [comment]
The conventional method for selecting among installed Java versions, familiar to all java developers, is to set environment variable JAVA_HOME.

In selecting among Javas pre-installed on Azure pipelines, this approach is difficult because it requires an Azure pipeline developer to know the locations of the several Javas, or the several respective environment variables, which are not apparent in the UI and which are not documented.

Further, on Microsoft hosted agents, the currently active Java version is referenced in the PATH  without reference to the JAVA_HOME environment variable, so after setting JAVA_HOME you are not done.

> script: |
>       echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
>       echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)\bin;$(PATH)"
> displayName: "Set java version"

The above circumvention is unsatisfying still since it merely tacks the selected Java on the front of the PATH, leaving the default Java later in the PATH, lengthening the PATH, thus increasing compute time for all program executions.

The Java Tool installer knows how to deal with this, and could accomplish the version selection more accurately and efficiently.
