### ISSUE TITLE
XamarinAndroidV1 does not yet surface the new Android App Bundle publishing format option

### ISSUE THREAD

**Issue by brendanzagaeski** [microsoft/azure-pipelines-tasks#11985]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Xamarin.Android  

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/XamarinAndroidV1/

## Environment

- Server - Azure Pipelines.

### Current behavior

The [Xamarin.Android task](https://docs.microsoft.com/azure/devops/pipelines/tasks/build/xamarin-android) has a dedicated boolean input for `createAppPackage`, described as *Passes the target (/t:PackageForAndroid) during build to generate an APK*:

![image](https://user-images.githubusercontent.com/4934473/70964323-42dd0c00-2040-11ea-92d1-2e5cb384d8e1.png)

### New feature to add

As of the recent Xamarin.Android SDK 10.0 and 10.1 releases, the Xamarin.Android SDK supports a new `AndroidPackageFormat` MSBuild property that allows creating packages that follow the [Android App Bundle publishing format](https://developer.android.com/platform/technology/app-bundle).

Currently, users can select this packaging format by adding an argument like `-p:AndroidPackageFormat=aab` to the `msbuildArguments` input. But since `createAppPackage` is its own input separate from the `target` input, it would be nice to surface the Android App Bundle packaging format similarly.

One option could be to make the `createAppPackage` a multiple choice option instead of a boolean option so that users would have a list of choices similar to:

  * Do not create app package.
  * Create APK.
  * Create Android App Bundle.

**Comment by brendanzagaeski** [comment]
Depending on opinions about best practices, another option might be to encourage users to set the `AndroidPackageFormat` MSBuild property per-configuration within their *.csproj* file instead of via the Xamarin.Android task configuration. In that case, maybe the best change would be to reword the `createAppPackage` description to say something like:

*Passes the target (/t:PackageForAndroid) during build to generate either an APK or Android App Bundle, depending on the AndroidPackageFormat property for the selected configuration.*

**Comment by developer9969** [comment]
@brendanzagaeski  hi there. I have been looking for a solution to this issue . Yes VS2019 16.4 gives us the option to select aab without editing the csproj file.

However it is still not clear to me what we should do in the pipeline.

1. Sign APK  becomes redundant.
2. AAB i guess is build by the proj. 
3. what is there todo since now also the msbuild task that we manually added is redundant too...

Am I missing the obvious. 

It would be nice to have a walkthrough step.

**Comment by brendanzagaeski** [comment]
Hi @developer9969, I'm afraid I don't quite understand the question.

It sounds like you are working on modifying a step that happens after the XamarinAndroidV1 task completes its work? I'm not too familiar with what other steps users tend to use in their pipelines after the XamarinAndroidV1 task builds the *.apk* or *.aab* file (via the `PackageForAndroid` MSBuild target).

What are you trying do with the *.aab* file that isn't working for you yet? Note that *.aab* files do need to be signed to be submitted to Google Play. Is the signing step the part you're wondering about?

**Comment by developer9969** [comment]
Hi there,
many thanks for your time and reply.

All I want to do is to move away from apk and use aab using azure devops.

**APK**

1. Build Android using xamarin android task
2. Sign APK using  Task
3. DONE

**AAB**
I need some clarification whether the android task will build the aab for me without using msbuild as outlined below.

**I am planning to:**
1. Select aab in visual studio android project.
2. MSBUILD task as  outlined in this blog very clearly.
No longer a need to use the android task

https://www.linkedin.com/pulse/android-app-bundle-xamarinandroid-apps-using-azure-devops-popovska/

Do I still need to write an msbuild task with various params as outlined in the blog or  will the android task have a check box eg AAB and nothing for me todo?

many thanks for your time

**Comment by brendanzagaeski** [comment]
Thanks for the additional info. I would say either option would work fine. That is, it is fine to keep using the [MSBuild](https://docs.microsoft.com/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops) task to handle both building and signing, or it would also be fine to use the [Xamarin.Android](https://docs.microsoft.com/azure/devops/pipelines/tasks/build/xamarin-android?view=azure-devops) task. The approach from the article that uses the MSBuild task sounds good to me.

From skimming the source code of the two Azure Pipelines tasks, it looks like the Xamarin.Android task is very similar to the MSBuild task. The main additional convenience feature of the Xamarin.Android task appears to be that it can look up the path for a different Java JDK version, if needed.

For signing, note that the [Android signing task](https://docs.microsoft.com/azure/devops/pipelines/tasks/build/android-signing?view=azure-devops) is not Xamarin-specific, and currently it is only compatible with the APK format (it uses `apksigner` rather than `jarsigner`). But Xamarin.Android projects have built-in functionality for signing during the build itself via the `SignAndroidPackage` target, which is the nice approach used in the article you linked. This matches up with the information from the [Azure Pipelines docs](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/android?view=azure-devops#sign-and-align-an-android-apk) that mention that the Android Signing task is only needed "if your build does not already sign and zipalign." 

* * *

For the Azure Pipelines team:

This discussion raises a useful point that it would be handy to update the https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xamarin to include the latest recommendations on how to build and sign packages, covering both the APK and Android App Bundle publishing formats.

**Comment by bakerhillpins** [comment]
To followup on this conversation about building Android Bundles mostly because it's been a little bit of a battle to get this to work for me. @brendanzagaeski At this point in time I've not seen any of this info integrated into the docs, though I may have missed it.

I didn't find the LinkedIn blog post that @developer9969 posted above, but I did find [this one from James Montemagno](https://devblogs.microsoft.com/xamarin/android-app-bundles-azure-devops/) very useful and in the end was able to make it all work from what he wrote. However, I learned a few things that I thought I'd share here.

- You don't need to enable any of the apk/aab output options in the Android project settings (under the Android Options tab) unless you'd like them to be built on your desktop.
- Using the "Additional arguments" as both articles suggest works. Making sure to upload your .keystore to the Secure Files tab of the Library and define a variable group using protected variables for your passwords/alias.
- If, as James M. suggests, you want **both** output types, you need to perform the XamarinAndroid@1 task 2 times in your pipeline. The first task should produce the .aab (Bundle) output, followed immediately with a second task to create the .apk. You can then archive your output once as both the .apk/.aab will be in the output dir. **The order of these two tasks is important** as production of the .aab will delete the .apk file in the output dir. (The order wasn't clear in his article and took a bit of trial and error to figure out)
-Signing of either output can occur in between/or after.
-Remember to disable the Clean option on the 2nd XamarinAndroid@1 task to avoid deleting the previous task outputs.
