### ISSUE TITLE
Surface same pipeline logs in Pipeline UI with Local Agent

### ISSUE THREAD

**Issue by mswilson4040** [microsoft/azure-pipelines-tasks#12037]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: All  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version:  Mac OS

## Issue Description
Is there a way to get the same logging output as we see in the azure devops pipline UI in the console when running a local agent?
[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by damccorm** [comment]
Could you be a little more specific about what you mean? How are you triggering builds? If you're asking if we can output the same logs directly on the agent that we send to the azure pipelines UI, we currently do not support that as an option. You could file a feature request at https://github.com/microsoft/azure-pipelines-agent if that's something you need, though I don't think that we'd take it - there's some things that happen on the server (e.g. secret masking) that need to happen there for security boundary reasons which would make it tricky to do this.

**Comment by mswilson4040** [comment]
Yea, that was basically what I was getting at. Right now, the logs are just "Listening for Jobs", "Job Started", "Job Finished". So not much. Since I run a local agent, I don't have a big need to login to Azure DevOps and see the build logs unless there is an error so it would be nice if there was an option to spit out a little more information.

**Comment by damccorm** [comment]
Ok. Like I said, I think that's probably not something we're going to do, you can open a feature request at https://github.com/microsoft/azure-pipelines-agentto continue that conversation if you'd like though.

The reason I don't think we'd do that is that the server has some important information that we need in order to produce logs that we can't send to the agent for security boundaries. The easiest example I have is secrets - one of our security boundaries is that:
(a) secrets only get sent to the agent when they are explicitly scoped into a step within that job
(b) secrets get masked from logs, regardless of whether they were scoped into a step (we tend to err on the side of aggressively overmasking)

I don't think we can maintain both of those if we output directly from the agent.

I'm going to close here, we should move any follow up to https://github.com/microsoft/azure-pipelines-agent

**Comment by mswilson4040** [comment]
Fair enough. Thanks for explaining the "why", @damccorm
