### ISSUE TITLE
VSTest 2.163.1 supported .Net Framework 4.6.2

### ISSUE THREAD

**Issue by wenn32** [microsoft/azure-pipelines-tasks#12170]
Hi,

Could anyone please help me change back the version of VSTest to 2.163.0 under VSTS/Azure devops tasks?
Problem is VSTest 2.163.1 requires .Net framework 4.6.2 and the latest framework installed in build server is 4.6.1.
Its almost impossible to involve server admin guys to install 4.6.2.
Almost 3 priority pull request are failing tests due to this automatic upgrade.

`steps:
- task: VSTest@2
  displayName: 'UnitTest execution'
  inputs:
    testAssemblyVer2: |
     **\xyzbr.Tests.dll
     **\xyz.Tests.dll
     !**\obj\**
    codeCoverageEnabled: true
`

Thank you

**Comment by sulabh-msft** [comment]
@wenn32 ,
Can you please enable debug logging (System.Debug) and please provide the **full** zip file containing all the logs?

Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

Also, 
You will need to update the .Net framework version to latest one (.NET 4.7.2 ) in the build agent machine ( if the issue is indeed the framework version installed on the build agent )

**Comment by wenn32** [comment]
As a workaround, I had renamed older working version folder to 2.163.1 and made it work.
Finally asked server admins to install framework 4.6.2.
Would have been nice if VStest had possibility to select version from pipeline task. As its not always possible to install frameworks ondemand during priority.
