### ISSUE TITLE
AzureIoTEdgeV2  "Build Module images" task produces expanded deployment in 'undefined' path

### ISSUE THREAD

**Issue by toolboc** [microsoft/azure-pipelines-tasks#12264]
**Description of issue:**

Using default settings for AzureIoTEdgeV2 "Build module images" task:

![image](https://user-images.githubusercontent.com/2018336/73489583-7239a500-4370-11ea-8df2-fd1bf315c725.png)

Results in the creation of expanded deployment in 'undefined' path:

![image](https://user-images.githubusercontent.com/2018336/73489637-841b4800-4370-11ea-8682-5773420f4b4e.png)

This is in contrast to the behavior of the "Push module images" task, which produces output in "./config" path:

![image](https://user-images.githubusercontent.com/2018336/73489655-909fa080-4370-11ea-83d8-036063eb12e4.png)

The "Generate Deployment manifest" task allows for specifying the output path:

![image](https://user-images.githubusercontent.com/2018336/73473618-aef6a380-4352-11ea-8dbf-a72fdfb88dc1.png)

**Suggested Resolution:**

Produce expanded deployment from "Build Module images" task in ./config directory similar to the behavior of the "Push module images" task

OR

Allow specific a user-defined Outputh path similar to the behavior of the "Generate Deployment manifest" task

**Comment by blackchoey** [comment]
@toolboc It's recommended to use `Generate Deployment manifest` to generate the final manifest for deployment since it has better flexibility. The file generated in `Build/Push Module images` is just kept for backward compatibility.
Please let us know if there's scenario that can't be covered by the `Generate Deployment manifest` task.
