### ISSUE TITLE
Unclear how to use project's provisioning settings using Xcode@5

### ISSUE THREAD

**Issue by sfuqua** [microsoft/azure-pipelines-tasks#12364]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Xcode

## Environment
Azure Pipelines, microsoft, definition ID 48886
Hosted Mac agents. 

## Issue Description

My team has been using Xcode@2 for a while to build and archive signed .ipa files for our iOS application. Our pipeline installs all necessary profiles and certs and then we use the Xcode task to build/archive using the project's signing settings (which match the things we install).

I have been trying to switch to Xcode@5 but have no idea which combination of settings will work. Looking at the source code for the task, I **think** I want manual signing to get plistBuddy to update the automatically generated plist with the profiles I need, but I don't want to have to specify those profiles in the task because it's redundant with the xcodeproj.

My goal is to use the provisioning profile info that is baked into the xcodeproj (so manual signing, but letting the project specify), but neither "project defaults" nor "manual" are working for me.

If I use "project defaults", the task fails to find a pbxProject (because there isn't one), falls back to automatic signing with no profiles, and the export fails:

```
##[warning]The provisioning style was not found in a pbxProject file. Automatic signing will be used. If the project uses manual signing, auto-export may fail. As a workaround, `Export options` can be set to `Plist` or `Specify`.
...
Error Domain=IDEProvisioningErrorDomain Code=9 ""<name>.app" requires a provisioning profile." UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription="<name>.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}
```

If I opt into manual signing **without specifying a profile**, because the project already does that, the build fails immediately:

```
 error: "<project>" requires a provisioning profile. Select a provisioning profile in the Signing & Capabilities editor. (in target '<project>' from project '<project>')
```

Meanwhile if we use Xcode@2 with these settings, everything works fine:

* Check _Create App Package_
* "Override Using" _Identifiers_ (the task installs all necessary certs/profiles)
* Everything else under "Signing & Provisioning" is blank/unchecked
* "Package Options" > "Export Options" is _Auto_

Can't figure out the equivalent of these settings in Xcode@5. We could probably just try manual signing and specifying the profiles in the ADO task, but if it's working in an older version it would be nice to not have to do that since we already specify these settings in the project itself.

### Task logs

Happy to share privately.

**Comment by daniil-shumko** [comment]
I have the same issue with my build. I want to use the project settings from Xcode and not rely on manually setting up signing process on Azure Pipelines.

@sfuqua Have you found a solution that works for you?

**Comment by sfuqua** [comment]
> I have the same issue with my build. I want to use the project settings from Xcode and not rely on manually setting up the signing process on Azure Pipelines.
> 
> @sfuqua Have you found a solution that works for you?

Sorry, missed this question! No, my team never found a solution and we're still using version 2 of this task.

**Comment by jloehr** [comment]
As this one reads quite similar to my issue #14994, I'll link my issue that contains a temporary workaround, that may also work for your issues.

**Comment by sfuqua** [comment]
Still relevant, shouldn't be stale.

**Comment by sfuqua** [comment]
For those interested/still following this topic, my team is investigating no longer using the Xcode build task at all. Between the signing confusion and an issue where we discovered the Xcode task was inadvertently double-building our app (and has been forever), we've opted to just try and call `xcodebuild` directly for our needs:

See this issue on the double-build problem: https://developercommunity.visualstudio.com/t/why-is-xcode-ado-task-building-our-ios-project-twi/1222720

The primary value I think the `Xcode@` task provides is using `PlistBuddy` to magically generate the .plist file needed for exporting an archive - but that magic is exactly what's been causing trouble in this issue.

My team's new approach will probably be to just use a script block in our YAML with the following:

```bash
# Specify Xcode version
sudo xcode-select [xcode developer path]

# Build a .xcarchive
# [-params] come from the existing Xcode task params (-sdk, -workspace, -configuration, -scheme, -archivepath)
xcodebuild [-params] clean archive

# You'll need an ExportOptions.plist file with export options that specify provisioning profiles, etc
# You can use PlistBuddy yourself (this is what Xcode@ does) or just commit it to your repo (what I'll be doing)

# Export the .xcarchive into a signed .ipa
xcodebuild -exportArchive -archivePath [whatever you used above] -exportPath [whatever] -exportOptionsPlist ExportOptions.plist
```

**Comment by BruceYou2022** [comment]
##[warning]The provisioning style was not found in a pbxProject file. Automatic signing will be used. If the project uses manual signing, auto-export may fail. As a workaround, `Export options` can be set to `Plist` or `Specify`.

**Comment by anatolybolshakov** [comment]
Hi @sfuqua have you tried to use [Install Apple Provisioning Profile task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=azure-devops) - to install related provisioning profile?

**Comment by sfuqua** [comment]
Yes, the profiles and certs are installed, that is not the issue.
________________________________

**Comment by charmipatalia** [comment]
I am facing similar issue like this, is there any update?

**Comment by toddthomas** [comment]
I too have encountered this issue. Looking at the [code](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/XcodeV5/xcode.ts) for the Xcode task, I think I see why it's happening.

We want the Xcode task to use the signing configuration defined in the project file, so we've set `signingOption` to `default`. We also want the convenience of the task generating the export options plist, so we've set `exportOption` to `auto` (or left it unspecified as `auto` is the default).

But when the export options plist generation code is [determining](https://github.com/microsoft/azure-pipelines-tasks/blob/ca3a679bae1cf3c8cf5d8ff57d3199a6db3194aa/Tasks/XcodeV5/xcode.ts#L428) how to set the `signingStyle` string property in the plist, if the task was configured with `signingOption: default`, it relies solely on attempting to parse that out of the project file, using the function [`getProvisioningStyleFromPbxProject()`](https://github.com/microsoft/azure-pipelines-tasks/blob/ca3a679bae1cf3c8cf5d8ff57d3199a6db3194aa/Tasks/XcodeV5/xcodeutils.ts#L164).

That function will always fail (at least with my project files) because it's looking for lines that match
```
ProvisioningStyle = Automatic
```
or
```
ProvisioningStyle = Manual
```
None of my project files (created with a variety of Xcode versions over the last few years, and all currently being used with Xcode 13.x and 14.x) contains those lines. Instead they have
```
CODE_SIGN_STYLE = Manual
```
or
```
CODE_SIGN_STYLE = Automatic
```
But even if this function was fixed to look for the correct string, there's a bigger problem: the project file has one of those lines for _each target_, yet the function is only looking for the first matching line. In my case, the Debug target's line is first, and has the value Automatic, but I'm building the Release target, which has the value Manual. The first match would be the wrong answer.

I think trying to parse target-specific settings out of the Xcode project file is fraught with peril and should be avoided, but I also don't think it's necessary.

`xcodebuild -h` says this about the export options plist's `signingStyle` property:

> The signing style to use when re-signing the app for distribution. Options are manual or automatic. Apps that were automatically signed when archived can be signed manually or automatically during distribution, and default to automatic. Apps that were manually signed when archived must be manually signed during distribtion, so the value of signingStyle is ignored.

If I am reading that correctly, the export options plist only needs to contain the `signingStyle` property if the app being resigned was automatically signed when archived, _and_ you want the export process to manually resign it. If the app was manually signed when archived, it can only be manually resigned and you don't need to specify that, and if the app was automatically signed when archived, by default the resigning style will be automatic.

It seems `signingStyle` only needs to be included in the plist in a very specific circumstance that could be specified by a new `exportSigningStyle` argument to the Xcode build task. Otherwise, don't include it in the plist and `xcodebuild -exportArchive` will do the right thing based on what it finds in the archive.

I'd like to test this theory in a fork of the Xcode build task, but I need to study how to do that. If anyone knows and can try it or tell me how to do it, I'd appreciate it.

**Comment by toddthomas** [comment]
> I'd like to test this theory in a fork of the Xcode build task

I haven't had time to try this. For now I've replaced the Xcode build task in my team's pipelines with these two bash scripts:
```yaml
- task: Bash@3
  displayName: Build clean archive
  inputs:
    targetType: 'inline'
    script: |
      set -ex

      ${{ parameters.xcodeDeveloperDir }}/usr/bin/xcodebuild -version
      ${{ parameters.xcodeDeveloperDir }}/usr/bin/xcodebuild -workspace **/*.xcodeproj/project.xcworkspace -scheme ${{ parameters.buildScheme }} -sdk iphoneos -archivePath ${{ parameters.buildScheme }} clean archive

- task: Bash@3
  displayName: Export from archive
  inputs:
    targetType: 'inline'
    script: |
      set -ex

      # Generate export options plist.
      PLISTBUDDY=/usr/libexec/PlistBuddy
      TASK_TMP_DIR=_taskTmp
      mkdir -p $TASK_TMP_DIR
      EXPORT_OPTS_PLIST=$TASK_TMP_DIR/_exportOptions.plist
      ARCHIVE=${{ parameters.buildScheme }}.xcarchive
      APP=$(ls -d $ARCHIVE/Products/Applications/*.app)
      BUNDLE_ID=$($PLISTBUDDY -c "Print CFBundleIdentifier" $APP/Info.plist)
      PROVISIONING_PROFILE_PLIST=$TASK_TMP_DIR/_provisioning_profile.plist
      security cms -D -i $APP/embedded.mobileprovision > $PROVISIONING_PROFILE_PLIST
      PROVISIONING_PROFILE_NAME=$($PLISTBUDDY -c "Print Name" $PROVISIONING_PROFILE_PLIST)
      PROVISIONS_ALL_DEVICES=$($PLISTBUDDY -c "Print ProvisionsAllDevices" $PROVISIONING_PROFILE_PLIST)
      if [[ $PROVISIONS_ALL_DEVICES == true ]]; then EXPORT_METHOD=enterprise; else EXPORT_METHOD=app-store; fi
      $PLISTBUDDY -c Clear $EXPORT_OPTS_PLIST
      $PLISTBUDDY -c "Add method string $EXPORT_METHOD" $EXPORT_OPTS_PLIST
      $PLISTBUDDY -c "Add provisioningProfiles dict" $EXPORT_OPTS_PLIST
      $PLISTBUDDY -c "Add provisioningProfiles:$BUNDLE_ID string ${PROVISIONING_PROFILE_NAME%.*}" $EXPORT_OPTS_PLIST
      $PLISTBUDDY -c Print $EXPORT_OPTS_PLIST

      # Export.
      ${{ parameters.xcodeDeveloperDir }}/usr/bin/xcodebuild -exportArchive -archivePath $ARCHIVE -exportOptionsPlist $EXPORT_OPTS_PLIST -exportPath output/$(SDK)/$(Configuration)

      # Delete temp files.
      rm -rf $TASK_TMP_DIR
```
This is working with our projects that use enterprise provisioning profiles. I haven't yet tested the App Store profile case.

**Comment by FredyMunevar** [comment]
> > I'd like to test this theory in a fork of the Xcode build task
> 
> I haven't had time to try this. For now, I've replaced the Xcode build task in my team's pipelines with these two bash scripts:
> 
> ```yaml
> - task: Bash@3
>   displayName: Build clean archive
>   inputs:
>     targetType: 'inline'
>     script: |
>       set -ex
> 
>       ${{ parameters.xcodeDeveloperDir }}/usr/bin/xcodebuild -version
>       ${{ parameters.xcodeDeveloperDir }}/usr/bin/xcodebuild -workspace **/*.xcodeproj/project.xcworkspace -scheme ${{ parameters.buildScheme }} -sdk iphoneos -archivePath ${{ parameters.buildScheme }} clean archive
> 
> - task: Bash@3
>   displayName: Export from archive
>   inputs:
>     targetType: 'inline'
>     script: |
>       set -ex
> 
>       # Generate export options plist.
>       PLISTBUDDY=/usr/libexec/PlistBuddy
>       TASK_TMP_DIR=_taskTmp
>       mkdir -p $TASK_TMP_DIR
>       EXPORT_OPTS_PLIST=$TASK_TMP_DIR/_exportOptions.plist
>       ARCHIVE=${{ parameters.buildScheme }}.xcarchive
>       APP=$(ls -d $ARCHIVE/Products/Applications/*.app)
>       BUNDLE_ID=$($PLISTBUDDY -c "Print CFBundleIdentifier" $APP/Info.plist)
>       PROVISIONING_PROFILE_PLIST=$TASK_TMP_DIR/_provisioning_profile.plist
>       security cms -D -i $APP/embedded.mobileprovision > $PROVISIONING_PROFILE_PLIST
>       PROVISIONING_PROFILE_NAME=$($PLISTBUDDY -c "Print Name" $PROVISIONING_PROFILE_PLIST)
>       PROVISIONS_ALL_DEVICES=$($PLISTBUDDY -c "Print ProvisionsAllDevices" $PROVISIONING_PROFILE_PLIST)
>       if [[ $PROVISIONS_ALL_DEVICES == true ]]; then EXPORT_METHOD=enterprise; else EXPORT_METHOD=app-store; fi
>       $PLISTBUDDY -c Clear $EXPORT_OPTS_PLIST
>       $PLISTBUDDY -c "Add method string $EXPORT_METHOD" $EXPORT_OPTS_PLIST
>       $PLISTBUDDY -c "Add provisioningProfiles dict" $EXPORT_OPTS_PLIST
>       $PLISTBUDDY -c "Add provisioningProfiles:$BUNDLE_ID string ${PROVISIONING_PROFILE_NAME%.*}" $EXPORT_OPTS_PLIST
>       $PLISTBUDDY -c Print $EXPORT_OPTS_PLIST
> 
>       # Export.
>       ${{ parameters.xcodeDeveloperDir }}/usr/bin/xcodebuild -exportArchive -archivePath $ARCHIVE -exportOptionsPlist $EXPORT_OPTS_PLIST -exportPath output/$(SDK)/$(Configuration)
> 
>       # Delete temp files.
>       rm -rf $TASK_TMP_DIR
> ```
> 
> This is working with our projects that use enterprise provisioning profiles. I haven't yet tested the App Store profile case.

Hi Todd, your solution worked fine for me but I couldn't change the bundle version for the exported app, could you please give some advice to do that?

**Comment by dombarnes** [comment]
Try adding
`$PLISTBUDDY -c "Add manageAppVersionAndBuildNumber bool 0" $EXPORT_OPTS_PLIST`

**Comment by schjonhaug** [comment]
I solved this by adding `ProvisioningStyle = Manual;` to my target’s user-defined build settings.
