### ISSUE TITLE
nuget restore doesn't properly load a private nuget feed from Nuget.config

### ISSUE THREAD

**Issue by lukeschlather** [microsoft/azure-pipelines-tasks#12529]
## Required Information

*Type*: Bug

**Enter Task Name**: NuGetRestore@1

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/NuGetRestoreV1

## Environment

I made a sample project in Azure Devops that illustrates the problem we're having (and the workaround.) Basically, nuget restore doesn't properly load a private nuget feed from Nuget.config, dotnet restore does.

[Failed build - netcore and netframework projects are using different versions of the package.](https://dev.azure.com/lukeschlather/Test/_build/results?buildId=30&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3)

[Successful build - netcore and netframework are using the same versions of the package](https://dev.azure.com/lukeschlather/Test/_build/results?buildId=29&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by jmyersmsft** [comment]
I see no evidence that your nuget task is picking up your nuget.config at all. In builds where it works, I'm guessing the appropriate package is already in the machine's local cache when nuget restore runs. Make sure the task is configured with the correct location of nuget.config.

We're moving away from our "Swiss-army knife" tasks to a model where you use the NuGet Authenticate task with a plain script task to run whatever commands you want. This will not use the nuget.config-modifying dance you can see in your nuget restore task logs. If you switch over, I recommend updating your NuGet Installer task to target `>=5.4.0` since there have been relevant improvements.

**Comment by lukeschlather** [comment]
The nuget config file is in the same (the dotnet restore is using the same file, which as you say is how it loads in the "working" case.)

**Comment by jmyersmsft** [comment]
I's the nuget task specifically configured to point to that nuget.config file?

**Comment by lukeschlather** [comment]
https://dev.azure.com/lukeschlather/_git/Test
https://dev.azure.com/lukeschlather/_git/Test?path=%2Fsteps.yml&version=GBmaster
https://dev.azure.com/lukeschlather/_git/Test?path=%2FNuGet.Config

**Comment by jmyersmsft** [comment]
The `NuGetRestore` task is really old and might not work with project-scoped feeds. I suggest at least moving to the `NuGetCommand` task like so:
```yaml
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution:  'FrameworkApp/FrameworkApp.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.Config'
```

**Comment by lukeschlather** [comment]
I added the NuGet Authenticate task to a different pipeline, which seemed to yield better behavior except it's intermittently barfing despite using Nuget 5.5.x

https://developercommunity.visualstudio.com/content/problem/1014284/nuget-restore-fails-due-to-credentialprovidermicro.html
https://developercommunity.visualstudio.com/content/problem/1015250/intermittent-nuget-restore-failure-credentialprovi-1.html

**Comment by herenhuang** [comment]
@lukeschlather - we're closing this issue. If you have problems with the new Nuget Authenticate task please let us know!
