### ISSUE TITLE
Error message when UseDotNetV2 task fails to download releases-index.json incorrectly mentions release-index.json

### ISSUE THREAD

**Issue by rikogeln** [microsoft/azure-pipelines-tasks#12743]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet 

## Environment
- Server - Azure Pipelines

## Issue Description
Error message when download fails incorrectly mentions "release-index.json" (should be release**s**-index.json). 
The code in /Tasks/UseDotNetV2/versionfetcher.ts has the correct filename, but the error message dropped the s (in all possible languages it seems) 

![image](https://user-images.githubusercontent.com/40666347/80111648-0d10dc80-8578-11ea-93ae-8ae31051ff60.png)

**Comment by poke** [comment]
This was actually caused by GitHub where it failed to respond with the `release-index.json` file and instead threw an internal server error. This is working on my end again but depending on your location might require a bit more time until GitHub servers catch up.

Regarding the underlying issue, I have opened #12742 in an attempt to make the task a bit smarter when it is restoring a fixed SDK version, so that it will look at the cache first. This would have solved the issue in your case too since you depend on `3.0.100`.

**Comment by rikogeln** [comment]
@poke this ticket is about the incorrect error message when we fail to download the file. The file is release**s**-index.json. the error message mentions release-index.json (a file which actually does not exist)

**Comment by poke** [comment]
@rikogeln Oh sorry, I only really looked at the screenshot and didn’t really read what you were reporting. Really sorry about that!

**Comment by rikogeln** [comment]
@poke no worries

**Comment by rikogeln** [comment]
@bishal-pdMSFT - thanks for the fix. Some translation strings still contain the release-index.json e.g the [japanese translation](https://github.com/microsoft/azure-pipelines-tasks/blob/91c78025f96435f93745d96bc64ca8352e29894c/Tasks/UseDotNetV2/Strings/resources.resjson/ja-jp/resources.resjson).
