### ISSUE TITLE
Az Cli Task fails with no error before executing the inline script

### ISSUE THREAD

**Issue by govenkat-ms** [microsoft/azure-pipelines-tasks#12777]
**Required Information**
This is a bug.

**Error Logs**
![image](https://user-images.githubusercontent.com/37309608/80427784-4eb5c600-889d-11ea-9296-571eb59f6f96.png)

**Agent Pool** => Azure Pipelines Hosted Ubuntu 16.04

**Az Cli Task Version 1**

**Comment by govenkat-ms** [comment]
The az path seems incorrect. I looked at other executions, and they use the path [command]/usr/bin/az  instead of [command]/home/vsts/work/r1/a/bin/az. Why is this execution of the task using a different path?

**Comment by issacnitin** [comment]
@govenkat-ms As discussed here: https://developercommunity.visualstudio.com/content/problem/1012413/az-cli-task-for-release-fails-before-execution-of.html
This must have been because of the "Setup Agent" script that was part of the pipeline. I see that you've resolved the issue by yourself. I'm closing this ticket as this is a duplicate for the above linked one. 

Please update how you've managed to resolve, for future reference. If you're still facing the issue, feel free to re-open this ticket.
