### ISSUE TITLE
Speed-up the Job initialization phase: pre-deploy the ADO Tasks

### ISSUE THREAD

**Issue by iambernics** [microsoft/azure-pipelines-tasks#12803]
Dear All,

We are building our Agents via IaC. 
The Agent VMs are reverted from snapshot after the Jobs are completed, the solution is similar like on the Azure Pipelines (Hosted Agents).
All Jobs are getting a blank environment in this method due to security and compliance reasons.

The Job initialization phase is a bit longer than the "static" Agents due to the continuous Tasks deployments to the Agents.

We would like degrees this time as possible.
Is there any way for register the latest ADO Task collection manually to the Agent?

I think this is more than just a simple file copies.

Thanks a lot!

Regards,
Gabor

**Comment by damccorm** [comment]
Hey @iambernics - we don't offer this since generally task download is pretty fast, most of our built in tasks are pretty small. If you'd like to suggest it as a feature, https://developercommunity.visualstudio.com/spaces/21/index.html is probably the best place for that so that it finds its way to the right eyes :)
