### ISSUE TITLE
Please reopen #12532

### ISSUE THREAD

**Issue by bada09089** [microsoft/azure-pipelines-tasks#12877]
*Type*: Feature

**Enter Task Name**: HelmDeploy@0  

## Issue Description

Please reopen the following issue: #12532

**Comment by shigupt202** [comment]
@bada09089 Would it help if we add an input for `failOnNonZeroExitCode`? You can set it to false when using `helm diff --detailed-exitcode`, and the task won't fail in case of non zero exits codes.

**Comment by bada09089** [comment]
Hi @shigupt202 , thanks for your response. 
This would definitely be an option and would help a lot. Unfortunately, in case of an error we would then not directly see that the "Helm diff" task failed. Would it maybe be possible to do that but only with exit code 2? Because other exit codes than 0 and 2 would still mean that something went wrong.
```
0 = Succeeded with empty diff (no changes)
1 = Error
2 = Succeeded with non-empty diff (changes present)
```

**Comment by shigupt202** [comment]
@bada09089 I agree it's not the most appropriate solution. Actually, I'm sceptical about adding the explicit handling for exit code in the task because helm diff is not a supported command in HelmDeploy task currently like upgrade and package. 
Could you use the command line as a work around for this scenario, while we talk things out with the PM's and come up with a proper solution for this?

**Comment by bada09089** [comment]
Hi @shigupt202 , we will stick to our current process until there is a solution for it. Lots of thanks and we look forward to hearing from you again.

**Comment by anraghun** [comment]
@bada09089 Thanks for your inputs. Unfortunately, we cannot handle an exit-code specifically within the task especially since helm diff is a plugin. Taking an array of status codes which are exempted from failure seems like a doable solution but again, it is very specific to the helm diff scenario. We will wait and see if more customers require this and add it accordingly.
