### ISSUE TITLE
Deployment Gate URL suffix field doesn't evaluate user-defined variable

### ISSUE THREAD

**Issue by gradyal** [microsoft/azure-pipelines-tasks#12885]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Invoke REST API Deployment Gate task  

## Environment
- Server - Azure Pipelines 
    
    - If using TFS on-premises, provide the version: 
    
    - Account name: ctg1
    - Team project name: CTG Projects
    - Release definition name: Driver Profile (uses classic release, not YAML)

- Agent - Private: 
    
    - OS: Windows NT version 6.3.9600, x64 

## Issue Description

I'm trying to query a REST API using the Invoke REST API deployment gate option. The "URL suffix and parameters" field does not accept a user-defined variable by itself, but it accepts variables as part of a string. I cannot find any documentation that specifies that a user-defined variable is not accepted in this field and we heavily use variables for fields like this throughout our tasks.

Example 1 (works): api/jiraPrerequisites/$(Build.Repository.Name)/$(Build.SourceVersion)
Example 2: (doesn't work): $(Jira.Gate.UrlSuffix)

**NOTE** Jira.Gate.UrlSuffix is a user-defined variable scoped to the release. It's value is the same as example 1. I can also see it evaluated correctly in the "Initialize Job" task of one of the stages.

**Comment by ds-ms** [comment]
@ankitk94 to take a look

**Comment by ankitk94** [comment]
Hi @gradyal , we do support use of custom variables in deployment gates, but as of now we don't support resolving variables for more than 1 level for server task (or agentless task). You are able to see the value in "Initialize Job" because that is a part of agent job (and hence able to resolve variable). 

If you try to provide a simple value to a user defined variable (and not another variable as value), it should work.

**Comment by gradyal** [comment]
@ankitk94 Thanks for the response. Can you tell me if multiple levels will be supported at some point? Is there a feature request out there for that?

**Comment by ankitk94** [comment]
@gradyal As of now we are not planning to add support for the same. We do have a support of resolving it to 2 levels in yaml pipelines but not in classic release. You can try to use it and instead of deployment gates policy in RM you can add Invoke REST API check on a resource for yaml pipelines for similar experience.
