### ISSUE TITLE
VSTest treat failed tests as warnings

### ISSUE THREAD

**Issue by jozefizso** [microsoft/azure-pipelines-tasks#13071]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: VSTest@2

## Environment
- Server - Azure Pipeline
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/netoffice/NetOffice/_build?definitionId=4&_a=summary
- Agent - Hosted

## Issue Description

We run integration tests using VSTest task in a single stage in our pipeline. These integration tests may often fail. Is there a way to treat these failed tests not as errors in the tasks but as warnings instead?

**Comment by ShreyasRmsft** [comment]
There is an option to ignore failed tasks in the pipeline, it's a generic feature. Check if this servers your purpose 
![image](https://user-images.githubusercontent.com/25194518/84026741-7bd0ba80-a9ab-11ea-8a63-053a1715fefa.png)

Otherwise we do not have any of way of achieving the above. You can mark individual tests as flaky though https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops and if those fail then the task ignores the failures.

**Comment by jozefizso** [comment]
Thanks for the reply, I will try to look at flaky tests.
