### ISSUE TITLE
Dollar sign ($) in variable causes variable to not show correctly

### ISSUE THREAD

**Issue by kingcoyote** [microsoft/azure-pipelines-tasks#13092]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShell

## Environment
- Server - Azure Pipelines
- Agent - Hosted (vs2017-win16)

## Issue Description

I'm trying to send an email that contains a URL with a $ in it but nothing I do can get the URL to show correctly in the email. After trying various escape sequences or storing the URL as a cross task variable, I discovered that even putting a $ in a cross task variable causes problems. 

This problem can be seen by running these two inline PowerShell tasks:

```
$urlbase = 'https://foobar.blob.core.windows.net/$' + 'web/software/'
Write-Host "##vso[task.setvariable variable=DownloadURLBase;isOutput=True]$urlbase"
```

```
echo $(DownloadURL.DownloadURLBase)
```

The first script needs the Output Variable reference name set to DownloadURL, otherwise the second script won't recognize the variable or display it at all, even malformed.

In the second task, I expect the log to say `https://foobar.blob.core.windows.net/$web/software`, but instead I see `https://foobar.blob.core.windows.net//software`.

I intentionally split the string in half at the dollar sign to try and prevent Azure Pipelines from performing macro processing on the token `$web`. But as I said, no combination of escaping, string concatenation, using single / double quotes or anything else I can think of is getting the phrase "$web" to show up in the log (and email body) as expected.

**Comment by egor-bryzgalov** [comment]
Hello, @kingcoyote!

Could you please try to escape the `$` sign with backquote?
````
$urlbase = 'https://foobar.blob.core.windows.net/`$' + 'web/software/'
````
Please let me know whether it helps. Thank you!

**Comment by egor-bryzgalov** [comment]
Hello, @kingcoyote!

Is this issue is still relevant for you?
We are looking forward to hearing from you.

**Comment by egor-bryzgalov** [comment]
I'm closing this issue. Please feel free to reopen it if it's still relevant to you.

**Comment by lazarillo** [comment]
Was this ever solved?

Forcing an escape character is a very poor solution.  In my case, the mangling occurs with a *secret* key vault-associated variable that I would prefer not to have access to.

I have tried the exact same Powershell command on my local machine, and it works without a problem.  But in the pipeline, it keeps getting mangled.

Specifically, my command is this:

```pwsh
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        $encrypt_pwd = ConvertTo-SecureString ${env:SECRET} -Force -AsPlainText | ConvertFrom-SecureString
        $encrypt_pwd | Set-Content ./variables/encrypted.txt
    env:
      SECRET: $(password)
```

If the value of `$(password)` is `silly`, then there is no problem.  If the value is `sil$ly&`, then it does not work.  In fact, it yields `sil&`, so you can see that the `$ly` is being interpreted as a (non-existent) variable.

I have tried `"${env:SECRET}"`, `${env:SECRET}`, `$env:SECRET`, or `$(password)`.  No luck.

**Comment by lazarillo** [comment]
I realized that I made a mistake: the variable was being passed correctly, but it was difficult to *validate* that it was correct, since secrets are not printed to screen.  I had made an error with the validation script.  (Accidentally used double quotes for the raw value instead of single quotes.)

---

I will say, though, that there is still a difficult challenge in passing this information:  the reason I am writing the password to an encrypted file is because the secret is passed from Powershell to Python to Powershell.  This is why I am writing it to a file; I gave up on finding any successful ways to make those multiple passes.

**Comment by egor-bryzgalov** [comment]
Hi @lazarillo 
Thank you for the information provided. Could you please clarify if the task works as expected for you? Am I right that your password is passed correctly?

**Comment by lazarillo** [comment]
Hi @egor-bryzgalov,

Sorry it took me a while to respond:

- The *azure pipeline* works fine.  So you can close this issue.

- But to answer your follow up question: no, my password is not passed correctly, but this is a Powershell problem, not an Azure pipelines problem.  I will explain it since you asked:
  - I call `pytest` from within the Azure Pipeline Powershell command (specifically `AzureCLI@2`, `scriptType: 'ps'`).
  - From within `pytest`, I make a `subprocess` call to Powershell where I try to log in to a remote machine -- the test is to ensure that IaC resources were deployed properly.  I make an SSH call into a Windows machine, using Powershell.
  - There is no way to pass the variables from Powershell to Python and to Powershell again, if those variables contain special characters.
  - I have found an ugly solution by generating Powershell `PSCredential` object, then creating an encrypted password using `ConvertFrom-SecureString`, then saving that encrypted password to a file, then reading that encrypted password file using Powershell and creating a `PSCredential` again, then finally calling the `Password` attribute from the `PSCredential` and deleting the file with the encrypted password.

I have not been able to find a better way to deal with passing secret credentials between languages.

I am not complaining, as I said, this is not an Azure pipelines issue.  It is a Powershell issue.  And I found a solution.  It is robust, or seems so.  It is just such a hassle to do something that I felt must be fairly common.

**Comment by egor-bryzgalov** [comment]
@lazarillo 
Thank you for the explanation. I understand your situation. 
So I'm closing this issue. Please feel free to create a new one if you face any problems.
