### ISSUE TITLE
DownloadPipelineArtifact task with tag not work in the multi stage

### ISSUE THREAD

**Issue by liushuanggang** [microsoft/azure-pipelines-tasks#13101]
## Required Information

DownloadPipelineArtifact task with tag not work from previous build stage:

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Latest DLLs'
      inputs:
        source: 'specific'
        project: $(System.TeamProjectId)
        pipeline: $(System.DefinitionId)            
        runVersion: 'latestFromBranch'
        runBranch: $(Build.SourceBranch)
        tags: 'myBuildTag'
        allowPartiallySucceededBuilds: true
        artifact: myArtifactName            
        patterns: '**/IntegrationTests/**/*'                      
        path: '$(Agent.TempDirectory)\myArtifactName'
      continueOnError: true

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPipelineArtifact

## Environment
Azure devops

- Agent - Hosted
   
## Issue Description

https://stackoverflow.com/questions/62294343/downloading-latest-pipeline-artifact-from-branch-based-on-tag/62316756#62316756

**Comment by wouterroos** [comment]
Hi, 

This also doesn't seem to be working on a single-stage pipeline when referencing a build definition other than the one that is currently running. Our use-case is to download an artifact from another pipeline based on a given tag.

**Comment by wouterroos** [comment]
Please do not close this.

**Comment by sgtwilko** [comment]
This is also affecting us on a single stage pipleine.

**Comment by xamadev** [comment]
I'm also trying to achieve this but without tags. Came across this [post](https://developercommunity.visualstudio.com/content/problem/1088543/downloadpipelineartifact-2.html):

> Publishing and downloading the artifact within the same pipeline is not supported with source = 'specific'. Only source = 'current' is supported.

Is it true? Can't find any documentation about it [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops).

**Comment by gavincampbell** [comment]
Same use case as wouterroos , specifying a build tag along with `latestFromBranch` causes `No builds currently exist in the pipeline definition supplied`; removing the tag filter downloads the latest from the branch.

**Comment by jplck** [comment]
I actually ran into the same problem some minutes ago. After some digging I realised, that the problem was, that I was setting the tag to a run rather than to a specific build. So check that you have added your tags either via the UI or cli (https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/build/tag?view=azure-cli-latest) to your builds. In my case that helped.

**Comment by james-bjss** [comment]
Hi, @liushuanggang  - I realise this is closed but wanted to leave this comment here to help others avoid the pain I have been through. I spent all evening trying to solve it thought I would share.

The reason no artifacts are found is due to the ambiguity of of the `Tag` parameter.  This is neither the Tag on the Git Repo, nor the tag that can be applied via the UI on a specific `Run`. As @jplck says it is a Tag on a `Build` resource.

This can be set using the Az Cli using the azure Devops Pipeline extension; however there is a far easier way. You can simply set a variable from a shell script task and this will be added to the build like so:

```yaml
   - task: Bash@3
      displayName: Tag Build
      inputs:
        targetType: 'inline'
        script: |
          # Magic incantation to tag the ADO build
          echo ''##vso[build.addbuildtag]YourTagGoesHere''
```
Once tagged the task will work as expected!

**Comment by swenkeratmicrosoft** [comment]
@james-bjss 
Thanks so much for your comment - it helped me tremendously!

In my case, I have:
pipeline 1 creates a git tag (git tag FOO_int / git push origin FOO_int) where 'int' is a unique integer.
pipeline 2 is triggered using triggers: branches: include: - refs/tags/FOO_*

I'm using tag triggers because pipeline completion triggers are branch specific.  I want to be able to run pipeline 1 in ANY branch and have its successful completion trigger pipeline 2 in that SAME branch, and you can't do that with pipeline completion triggers.

Now, I want pipeline 2 to download artifacts from the specific run of pipeline 1 that triggered it under the assumption that pipeline 2 has access to the unique integer.

As you pointed out, it didn't work at first to simply use  tags: FOO_int
And that's because DownloadPipelineArtifact doesn't use git tags.  I was banging my head against the wall on this.

But adding this line to a pipeline 1 script (windows cmd in my case) made it work just fine.
          echo ##vso[build.addbuildtag]FOO_int

Now, for each run of pipeline 1, I have both a uniquely-identified standard git tag and a "download pipeline artifacts tag" (which is bizarrely still called a 'tag' but completely different), but they have the same name so they can be used in both git and DownloadPipelineArtifact contexts.

Even a Microsoft full-timer like myself finds this stuff arcane and has trouble getting any answers or help, so thanks again!

**Comment by woter1832** [comment]
@swenkeratmicrosoft,

Thanks you for your detailed response.

I thought I had this working, but when I recreated the pipeline, it wasn't. I expect this was because through my trial and error, I set the attribute `buildType: current`, which would have cached the artefact. This is lost when a pipeline is created.

Out of curiosity, is your artefact consumed in a new stage or job?

Thanks again.

**Comment by swenkeratmicrosoft** [comment]
@woter1832  - Neither, really - I'm actually consuming artifacts generated in pipeline A from entirely separate pipeline B.

**Comment by wouterroos** [comment]
Commenting to prevent closure since this hasn’t been solved yet as far as I know.

**Comment by surajkrishan** [comment]
not yet resolved.

**Comment by mikerains** [comment]
I had a situation like this see 
[YMLS DownloadPipelineArtifact@2 fails to find tagged build](https://github.com/microsoft/azure-pipelines-tasks/issues/16811)

Essentially, the tagged builds were all created while debugging, and each of them / all of them had a failed stage.  The defaut behavior of DownloadArtifactPipeline@2 is to not include failed builds, and so the result is the error "No builds currently exist in the pipeline definition supplied.".

By adding the input:
````
allowFailedBuilds: true
````
the download is successful.  You might need to add this during development/debugging, and then disable it in production if you don't want artifacts from failed pipeline runs to be considered for DownloadPipelineArtifact@2 tagged build artifacts.

**Comment by mikerains** [comment]
> 

I see the Package Build stage has a failure.  By Default, DownloadPipelineArtifact@2 will not include artifacts from pipeline runs that contains a failed stage.  If this is the case, try adding 
````
allowFailedBuilds: true
````
You might need this while developing/debugging, and then set it to false in deployment.  

See more details in https://github.com/microsoft/azure-pipelines-tasks/issues/16811

**Comment by viv3k1** [comment]
I am not able to find this even with allowed failed true.
I am using this in the same pipeline, I don't want to build again, should be able to release it whenever required .
at build stage
- task: PublishPipelineArtifact@1
displayName: 'Publish Artifact'
inputs:
artifactName: ${{ parameters.artifactName }}
targetPath: '$(build.artifactstagingdirectory)'

- task: PowerShell@2
  displayName: 'Set artifact tag'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##vso[build.addbuildtag]test_tag"
at deploy stage

        - task: DownloadPipelineArtifact@2
          displayName:
          inputs:
            buildType: "specific"
            path: "$(Pipeline.Workspace)"
            artifact: ${{ parameters.artifactName }}
            pipeline: $(System.DefinitionId)
            project: $(System.TeamProjectId)
            buildVersionToDownload: "latest"
            allowPartiallySucceededBuilds: true
            tags: "test_tag"
            branchName: "$(Build.SourceBranch)"
            allowFailed: true
          continueOnError: true
From my understanding :
If you have separate stages for build and deploy in different YAML files, then the pipeline will work as expected. But if you try to combine both stages in a single pipeline and trigger only the deploy stage, it will not function properly. This is because when you set the tag or use the latest from the branch in a multi-stage pipeline, it requires a full successful execution of the pipeline for it to work. So, it's better to split the pipeline into two different YAMLs for build and deploy stages and trigger only the deploy stage.

**Comment by aslan-im** [comment]
I didn't get clear exploration in what cases pipeline artifact with tags can be downloaded and in what cannot. Please provide the clear description.
