### ISSUE TITLE
Variable for kubernetesServiceEndpoint in Kubectl task can handle only Global Variables

### ISSUE THREAD

**Issue by iasha102** [microsoft/azure-pipelines-tasks#13262]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Kubectl task

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
- Agent -  Private: 
     

## Issue Description

Variable for kubernetesServiceEndpoint in Kubectl task can handle only Global Variables
and Stage Variable are not recognized

When using kubectl task and login command the kubernetesServiceEndpoint accepts only the Global Variable 
When setting the variable inside stage the `kubectl task login` complains it can't find the resource. 
Service endpoint is private and security is set to all pipelines 

![image](https://user-images.githubusercontent.com/2816201/87186600-73460980-c2f4-11ea-954b-844e6b69a1ed.png)
when echoing the variable is reflected `KubeTest` 
![image](https://user-images.githubusercontent.com/2816201/87186816-ccae3880-c2f4-11ea-9688-25f5b5eec564.png)

this is how variable is set. 
```- stage: DeployToTest
  displayName: Deploy to Test
  variables:
  - name: k8sNamespace
    value: wso2is
  - name: k8sReleaseName
    value: test
  - name: k8sService
    value: KubeTest
  - group: test-wso2is
  jobs:
```

this is how is used: 

```
- task: Kubernetes@1
  displayName: Login to Kubernetes
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(k8sService)
    command: login
```

### Task logs

N/A

## Troubleshooting
When setting the variable in the global variables, deployment stage accept it and can work with variable. 
When hardcoding the Kubernetes endpoint also everything works fine. 

### Error logs
Error message appears even before any stage starts. 
```
There was a resource authorization issue: "The pipeline is not valid. Job DeployTest: Step input kubernetesServiceEndpoint references service connection $(k8sService) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."```

**Comment by ds-ms** [comment]
AFAIK this is by design.

cc: @chshrikh to comment

**Comment by iasha102** [comment]
I had more days to test everything. 
And come to this: 
If I declare the variable in the global section and then redeclare it in the staging section, then everything works fine. 
And this does not happen with other variables.

**Comment by ds-ms** [comment]
That's probably because whenever you use an endpoint in your pipeline, there's some preprocessing done by the server before it's handed off to the agent. The preprocessing involves fetching the serviceEndpoint and setting variables in a way the task SDK understands. 

To avoid setting variables globally, you could leverage a feature called `Environments` and `Kubernetes Resource` where you can bind a stage to a K8s resource and the service connection get patched automatically in those flows.

**Comment by mfmayer** [comment]
At least for me this is not working. I was trying to do so by adding the "kubernetes ressource" to an environment. But this failed because I don't have the appropriate rights to do so in the according azure subscription and/or cluster  (RBAC is used). At least if I interpret the error messages correctly while adding the cluster with correct namespace to the devops environment. It only works for clusters where I do have cluster-admin rights.

But in this case, all I have is a set of service connections to specific namespace roles in staged kubernetes clusters that allow me to create deployments, pods, etc. within these namespaces (do the actual deployment things). I can easily script all these things, but it's just hard to wire them in the yaml pipeline so that it works as intended, because there seem to be a lot of hidden restrictions like the one above that must be somehow worked around.

As @iasha102 mentioned, it works by introducing a global variable, which can be overwritten/redeclared in the stages.

**Comment by iasha102** [comment]
Have made some more experiments. According to the @ds-ms advice have tried not to specify any kubernetes conection in a helm task but as environment specify the resource, and indeed that has worked. 
But still this is not intuitive to not be able to setup a variable in a stage without declaring it in the global ones. 
Also different k8s clusters setups don't feet always with the resource scenario.  for example rancher cluster are not eligible to be connected to the resource via the serviceaccount.  
This needs either better documentation and transparency, either the same behavior as any other variable. 
Found only one place in documentation that says KubernetesManifest jobs can benefit from this functionality, but we have also helm task, kubectl task

**Comment by davidljuba15031979** [comment]
If there is

```yaml
  - task: Bash@3
    displayName: Log k8sService
    inputs:
      targetType: 'inline'
      script: echo $(k8sService)
```

in replacement to 

```yaml
  - task: Kubernetes@0
    displayName: Deploy master ingress
    inputs:
      kubernetesServiceEndpoint: $(k8sService)
     # ...
```

then there is no exception.

**Comment by harlandgomezQred** [comment]
I saw this somewhere which works for me:
`{{ variables.k8sService }}` instead of `$(k8sService)`

**Comment by harlandgomez** [comment]
I saw this somewhere which works for me:
`{{ variables.k8sService }}` instead of `$(k8sService)`

**Comment by mikependon** [comment]
@harlandgomez - it works as well if used it with parameter via this interpolation `{{ parameters.serviceConnection }}`, in which the `serviceConnection` is our parameter to the manifest. In short, interpolation matters on this regards.
