### ISSUE TITLE
VSTest feature request: Fail VSTest task immediately when a single test fails (fail fast option)

### ISSUE THREAD

**Issue by gvermaosi** [microsoft/azure-pipelines-tasks#13366]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: VSTest 

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines

- Agent - Hosted or Private: 
    Private Agent

## Issue Description

Could there be a setting on the VSTest task to immediately fail the entire task when a single test fails (fail fast option)? It would be helpful to speed up deployment time when we are not as concerned with knowing which tests failed and just want to know a pass fail result.

**Comment by ShreyasRmsft** [comment]
This feature would be easier to implement at the vstest testplatform layer since it has a better hook to those events. Raise the request at https://github.com/microsoft/vstest.

Additionally you can consider authoring a custom [datacollector](https://github.com/microsoft/vstest-docs/blob/master/docs/extensions/datacollector.md) that kills the test process when a failed test event arrives. This would be the quickest way for you to get this functionality by leveraging the extensibility provided by the testplatform and also my personal recommendation.

If the platform offers the feature to fail fast then you can configure it to do so using the runsettings file that the task allows you to pass. Or if you go via the datacollector route you can use customer data collectors in the vstest task.

**Comment by ShreyasRmsft** [comment]
There's already a datacollector that kills the testprocess on potential hangs, you can leverage some of the code it uses to get the testprocess' process id and listening to test completed events https://github.com/microsoft/vstest/blob/63e623f23c6dfd63990c101c957860dfd22fd6c4/src/Microsoft.TestPlatform.Extensions.BlameDataCollector/BlameCollector.cs#L167
