### ISSUE TITLE
Docker cleanup tasks

### ISSUE THREAD

**Issue by kanadaj** [microsoft/azure-pipelines-tasks#13360]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Docker

## Environment
- Server - Azure Pipelines
        
## Issue Description

Currently, Azure Pipelines is responsible for managing the lifecycle of Docker containers all the way except for the cleanup - retention policy only affects the artifacts on Azure Devops / TFS, effectively leaving orphaned containers in the docker registry. 

I feel it would make sense to allow "cleanup tasks" to be ran when Azure Pipelines releases are removed to allow cleaning up external resources tied to the given builds/releases.

**Comment by ds-ms** [comment]
@N-Usha could you take a look

**Comment by N-Usha** [comment]
Thanks for reaching out @kanadaj. We acknowledge that this is would be a valuable addition to the Azure Pipelines' offerings to manage & deploy docker containers and we will surely consider this for future investments in the area. However we do not have any timelines to commit at this time given that we prioritize our investments by impact and severity for a broad set of customers; the impact of this problem is limited relative to other existing problems that we are currently investigating. 
Thanks again and please continue to give us your valuable feedback.
