### ISSUE TITLE
Azure Key Vault task converts %3B in secrets to ;

### ISSUE THREAD

**Issue by coreyasmith** [microsoft/azure-pipelines-tasks#13380]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureKeyVault@1 (https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureKeyVaultV1)

## Environment
- Server - Azure Pipelines
- Agent - Hosted, `windows-2019`

## Issue Description

The Azure Key Vault task is converting all instances of `%3B` in a secret to `;`.

To reproduce, create a secret in a key vault with `%3B` in the value somewhere. Use the Azure Key Vault task to download the secret and observe that all instances of `%3B` in the value are converted to `;`.

For the screenshots below I created a secret with the value `a%3B`:

![image](https://user-images.githubusercontent.com/6156761/89051247-f2da5d80-d321-11ea-92e3-69d8fe25fefd.png)
![image](https://user-images.githubusercontent.com/6156761/89051324-14d3e000-d322-11ea-9a74-ce39827406af.png)

This issue seems to be isolated to the task because neither the Azure CLI nor the Azure PowerShell commandlets are affected:

![image](https://user-images.githubusercontent.com/6156761/89051523-654b3d80-d322-11ea-87bf-384563bf2f14.png)

#### Pre-job: Azure Key Vault
```
2020-07-31T15:31:03.1714670Z SubscriptionId: lkjfdsalkjfdsa.
2020-07-31T15:31:03.1716309Z Key vault name: asdfjklasdfjkl.
2020-07-31T15:31:03.1717118Z ##[debug]set SYSTEM_UNSAFEALLOWMULTILINESECRET=true
2020-07-31T15:31:03.1731143Z ##[debug]Processed: ##vso[task.setvariable variable=SYSTEM_UNSAFEALLOWMULTILINESECRET;issecret=false;]true
2020-07-31T15:31:03.1732048Z ##[debug]Downloading selected secrets from subscriptionId: lkjfdsalkjfdsa, vault: asdfjklasdfjkl
2020-07-31T15:31:03.1734255Z ##[debug]Promise for downloading secret value for: TestEncoding
2020-07-31T15:31:03.1743918Z Downloading secret value for: TestEncoding.
2020-07-31T15:31:03.1776021Z ##[debug][POST]https://login.windows.net/***/oauth2/token/
2020-07-31T15:31:03.7384649Z ##[debug][GET]https://asdfjklasdfjkl.vault.azure.net/secrets/TestEncoding?api-version=2016-10-01
2020-07-31T15:31:03.9161950Z ##[debug]SYSTEM_DONOTMASKMULTILINESECRETS=undefined
2020-07-31T15:31:03.9164575Z ##[debug]set TestEncoding=********
2020-07-31T15:31:03.9186635Z ##[debug]Processed: ##vso[task.setvariable variable=TestEncoding;issecret=true;]***
2020-07-31T15:31:03.9191134Z ##[debug]set TestEncoding=********
2020-07-31T15:31:03.9199821Z ##[debug]Processed: ##vso[task.setvariable variable=TestEncoding;issecret=true;]***
2020-07-31T15:31:03.9202240Z ##[debug]task result: Succeeded
2020-07-31T15:31:03.9217134Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]
2020-07-31T15:31:03.9493121Z ##[section]Finishing: Azure Key Vault: asdfjklasdfjkl
```

### Error logs
The task does not produce any errors.

**Comment by coreyasmith** [comment]
I just tested all hex values in the ASCII table and `%5D` (converted to `]`) is affected as well. No other values seem to be affected.

**Comment by sandupetrasco** [comment]
It looks like the backtick symbol ( ` ) is also affected by this bug. If there is at least one backtick contained by the secret, we can meet these situations:
- The secret contained in the KeyVault: **a`Sa** <-> The secret returned by the AzureKeyVaultTask: **aSa**
- The secret contained in the KeyVault: **a`na** <-> The secret returned by the AzureKeyVaultTask: **a(newline)a**
etc.
@tauhid621 do you have any updates related to this issue?

**Comment by XristophD** [comment]
I also do have issues here that seems to be related: 
Secrets with the following format are being shortened: 

Secret: aaaa$bbbbb@!c#cc
Value returned: aaaa@!c#cc

Seems like $bbbbb is shortened away.

**Comment by sandupetrasco** [comment]
@XristophD, indeed, we also found out the issue with the dollar sign ($). It looks like the Azure Key Vault task is, somehow, parsing the output.
In order to solve that, we managed to come with a .yml template solution, that has a `AzurePowerShell` task that uses the `Set-AzKeyVaultAccessPolicy` and `Get-AzKeyVaultSecret` commands to have access to the Azure Key Vault and extract all the info. Then, you can simply use the `Write-Host "##vso[task.setvariable variable=$($secret.Name);]$secretValueText"` command, to set the environment variables.
This solution works as the AzureKeyVault task should, fixing the issues we introduced above 😉

**Comment by sivetic** [comment]
Any updates on whether this is considered a priority?  I've filed an identical bug without realizing it is this old: #14610 

The issues seems to be in how AzureKeyVault passes values to be set using ##vso task.setvariable

**Comment by doittjdoughty** [comment]
We are having the same issue.
When retrieving Key Vault secrets that contain $ the **incorrect** value is returned to the pipeline causing login failures. We created two work arounds for this issue but would like to see the task code updated to correct the underlying problem. 

1. Temp Work Around - add a \ in front of each $ in the stored secret value. By adding a \ before the problem characters the AzureKeyVault@1 returns the correct value, however the value is returned as plaintext instead of ***.
2. Use azure cli to get the secret and pass to a variable.

What is the estimated time to get this issue fixed? Our team supports hundreds of pipelines across 100+ azure subscriptions and Key Vault is our primary secrets management service.

**Comment by tauhid621** [comment]
Closing this as V2 of this task is being rolled out which fixes the issue

**Comment by t03apt** [comment]
> I also do have issues here that seems to be related: Secrets with the following format are being shortened:
> 
> Secret: aaaa$bbbbb@!c#cc Value returned: aaaa@!c#cc
> 
> Seems like $bbbbb is shortened away.

@tauhid621 
I am getting the same issue using AzureKeyVault@2.
