### ISSUE TITLE
Support for `cargo build` task ?

### ISSUE THREAD

**Issue by gdhuper** [microsoft/azure-pipelines-tasks#13396]
## Required Information
*Type*: Feature
**Enter Task Name**: N/A  

## Environment
- Azure Pipelines

## Issue Description
I realize this might be a repeated feature request for adding `cargo build` task but I couldn't find any information here. Are there any plans to add support for `rust/cargo` build tasks to Azure Pipelines in the near future? If not, could this feature request be added to the backlog? I would like to contribute. Thanks

**Comment by damccorm** [comment]
Hey @gdhuper for new task requests, please use https://developercommunity.visualstudio.com/spaces/21/index.html - this repo is for issues with existing tasks. That will also allow others to vote on it/will help us prioritize if we want to do this. My guess is that we probably will not add it due to lack of demand, but you can also always publish your own task on the marketplace - https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops
