### ISSUE TITLE
FileTransform correctly applies all transforms but still reports Error Unable to apply transformation for the given package - Changes are already present in the package.

### ISSUE THREAD

**Issue by Zhaph** [microsoft/azure-pipelines-tasks#13588]
## Required Information

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: FileTransform

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      - Account: PromontoryNetwork
      - TeamProject: newco.com
      - Definition: 2
      - Build Number: 0.2.18

- Agent - Hosted or Private: 

    - If using Hosted agent, provide agent queue name: **windows-latest**

## Issue Description

I have a multi-stage YAML pipeline, that has the following Filesystem Transform task defined in a Deployment Job:

```
- task: FileTransform@2
  displayName: 'Apply Release Transforms'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)\$(artifactName)\deploy\'
    enableXmlTransform: true
    xmlTransformationRules: |
      -transform *.Release.config -xml *.config
      -transform *.$(Environment.Name).config -xml *.config
      -transform config\**\*.Release.config -xml config\**\*.config
      -transform config\**\*.$(Environment.Name).config -xml config\**\*.config
    xmlTargetFiles: |
      web.config
```

We have two configuration files in the root of the application that need at least the Release transform applied (web.config and ApplicationInsights.config) as well as optional environment transforms.
Similarly there are a number of .config files in the config folder, that have optional release and environment transforms.

Looking at the logs and the transformed files, all transforms are being correctly applied to the target files, but we are still getting the following error reported from the task (note that this is not stopping the deployment, but it is creating noise in the reports that makes it look like an error has occurred):

```
##[error]Unable to apply transformation for the given package - Changes are already present in the package.
```

### Task logs

[23.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5261355/23.txt)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
##[error]Unable to apply transformation for the given package - Changes are already present in the package.
```

**Comment by AmrutaKawade** [comment]
This is as per design https://github.com/microsoft/azure-pipelines-tasks/issues/12277

**Comment by Zhaph** [comment]
I would respectfully suggest then that the design is wrong.

There are no meaningful errors in the tasks, and they are successfully applying the transforms and replacements, but the tasks are erroneously reporting an error back to the pipeline and showing as errors on the report when in fact everything is behaving as expected.

How is this "by design"?

**Comment by AmrutaKawade** [comment]
There are some other requirements which made us to add this change. https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/FileTransformV2

> The new File Transform Task version fails when no substitution has been applied (i.e. the changes were already present in the package).

If you don't want to fail task, you can check "Continue On Error" checkbox.

**Comment by sharpjs** [comment]
For anyone landing here who wants to squelch this error when doing JSON-only transforms:

```yaml
xmlTransformationRules: ''
```

**Comment by shemsiu** [comment]
> For anyone landing here who wants to squelch this error when doing JSON-only transforms:
> 
> ```yaml
> xmlTransformationRules: ''
> ```

Just to follow up with an example:

```yaml
- task: FileTransform@2
  inputs:
    folderPath: 'myFolder'
    jsonTargetFiles: 'appsettings.json'
    xmlTransformationRules: ''
```

**Comment by alenroki** [comment]
I can confirm that @shemsiu solution works. The error is not displayed when using xmlTransformationRules: ''

**Comment by arialdomartini** [comment]
> If you don't want to fail task, you can check "Continue On Error" checkbox.

This is a terrible suggestion. I *do want* the pipeline to stop on errors.

Instead, that error is wrongly reported as it is not an error at all.

**Comment by farinha** [comment]
I ran into this issue while using Classic Pipelines.
It seems to me that this happens when there are no variable substitutions to be made.

I was in the process of creating a new stage and all existing variables were scoped specifically to other (existing) stages.
As soon as I added a valid variable to the new stage's scope the problem went away.

It does seems useful to be notified when no transformations take place, as it highlights that some configuration might be missing. But for this to cause the task to trigger an error seems overkill and counterproductive. A warning seems like it would be more helpful.

**Comment by crlmrlck** [comment]
> I would respectfully suggest then that the design is wrong.
> 
> There are no meaningful errors in the tasks, and they are successfully applying the transforms and replacements, but the tasks are erroneously reporting an error back to the pipeline and showing as errors on the report when in fact everything is behaving as expected.
> 
> How is this "by design"?

I feel like the error is misleading as well. It implies that transformations are happening twice, rather than transformations not happening. I spent _wayyyyyyyyyyyyyyy_ too much time trying to find out why I was getting this error until I discovered this thread. Why in the world would I suspect `XmlTransformationRule: ""` would be the solve based on the error given.

This either needs to be set as an "Info" block, or the messaging needs to be updated to be more specific on what the issue really is.

**Comment by Appelg** [comment]
This is so broken. 

Why should I have to enter an empty **xmltTransformationRules** property just to suppress an error when I only specified **jsonTargetFiles**? 

Or use continue on fail? That will suppress actual failures...

Somtimes I get astonished/disappointed about the level of code/functionality that comes from Microsoft. I would have never let this task pass QC.

**Comment by poxenham-myp** [comment]
I agree that this is very unhelpful. We have created a Task Group to run the same steps in all environments, including variable substitution in JSON and XML. In our production environment there is no variable substitution as the application is deployed with a prod override json config file with no need to replace any variables. In lower regions there is a test override json config file but we also substitute 3 or 4 configs depending on the test environment. I upgraded to V2 of this task as it did JSON and XML in one hit, instead of 2 v1 tasks and the behaviour changed and broke when deploying to production.

In my eyes this is a regression from V1 and prevents good CI practices of using the same steps in all regions with differences via variables etc.

**Comment by MartinK-eu** [comment]
I also agree with people above me. If there's no meaningful error, the pipeline should not return an error, nor should I have to suppress real errors, just for the task to function (and even then, I would still have Warnings making pipelines look faulty). While the xmltTransformationRules solution works fine in our YAML pipelines (and to reiterate, while working fine, it is still a workaround to a design error), sadly it does not work in our very few Classic Release pipelines. In those, we simply decided to switch back over to V1 until, if ever, this issue is fixed.

**Comment by caleb-terry** [comment]
Like many others, I stumbled upon this issue while building a YAML pipeline and needed to transform an appsettings.json. @shemsiu 's suggestion worked, but like many others, I think requiring a blank XML transform makes little sense when you only want to do a JSON transform.

**Comment by danheinz** [comment]
I'm having this issue with the Classic Pipeline.  The file is being transformed successfully, but I get the error.
I'm only transforming a json file.
I tried putting a space in the XML target files field, but this had no effect. 
Has anyone worked around this issue using the Classic Pipeline?

**Comment by mprather** [comment]
Adding myself to the chorus who thinks this is a bad design. This is a broken design. We have a ton of version 1 tasks that we've decided to upgrade (to remove deprecation warning messages). Should be easy-peasy to upgrade w/o having to deal with errors.

Documentation says rules are only applied when enableXmlTransform==true. However, the error message still appears. Only fix is to blank out the rules?

**Comment by alexisaraya** [comment]
I have a similar problem, using version 2.249.1 of the task “FileTransform” , I also tried with version 2.246.1 and the same error.

`  - task: FileTransform
      inputs:
        folderPath: '$(Pipeline.Workspace)/drop/publish'
        jsonTargetFiles: 'ocelot.json' 
        xmlTransformationRules: ''
      displayName: 'Replace ENVIRONMENT in ocelot.json'`

Error message
2025-02-26T20:26:15.8620138Z ##[section]Starting: Replace ENVIRONMENT in ocelot.json
2025-02-26T20:26:15.8625893Z ==============================================================================
2025-02-26T20:26:15.8626050Z Task         : File transform
2025-02-26T20:26:15.8626156Z Description  : Replace tokens with variable values in XML or JSON configuration files
2025-02-26T20:26:15.8626295Z Version      : 2.249.1
2025-02-26T20:26:15.8626396Z Author       : Microsoft Corporation
2025-02-26T20:26:15.8626490Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/file-transform
2025-02-26T20:26:15.8626646Z ==============================================================================
2025-02-26T20:26:16.2016850Z Applying JSON variable substitution for ocelot.json
2025-02-26T20:26:16.2074999Z Applying JSON variable substitution for /home/vsts/work/1/drop/publish/ocelot.json
2025-02-26T20:26:16.2098588Z ##[error]Error: Failed to apply JSON variable substitution. Changes are already present in the package.
2025-02-26T20:26:16.2166595Z ##[section]Finishing: Replace ENVIRONMENT in ocelot.json

**Comment by jaalsh** [comment]
@alexisaraya 

If xmlTransformationRules is set like `xmlTransformationRules: ''` then double check that you have variables scoped to the stage.
