### ISSUE TITLE
KubernetesManifest@0 : Kubernetes configuration file is group-readable

### ISSUE THREAD

**Issue by Exanis** [microsoft/azure-pipelines-tasks#13684]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesManifest@0

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/KubernetesManifestV0

## Environment
- Server - Azure Pipelines 
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
       Account name : bvacx
       Team project name : PCX
       Build definition name : Services from staging
       Build ID : 13103 (20201008.3)

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
Pool: Azure Pipelines
Image: ubuntu-latest
Agent: Azure Pipelines 3

## Issue Description

When using KubernetesManifest to bake Helm chart into a kubernetes manifest, a warning appear blocking the build. Here is the error displayed in the task :

##[error]WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/vsts/work/_temp/kubectlTask/1602159611717/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/vsts/work/_temp/kubectlTask/1602159611717/config

A temporary solution to fix the problem is to change the mode of the file before using this task :

  - task: Bash@3
    displayName: "Fix permissions"
    inputs:
      targetType: 'inline'
      script: |
        chmod 0600 /home/vsts/work/_temp/kubectlTask/*/config

Here is the current task settings :

  - task: KubernetesManifest@0
    displayName: 'Bake K8s from Helm'
    name: Manifest${{ parameters.suffix }}
    inputs:
      action: bake
      helmChart: manifests
      overrides: |
        application.name:$(TARGET_NAME)
        application.replicas:$(REPLICAS)
        application.image:$(CONTAINER_IMAGE)
        application.version:$(CONTAINER_VERSION)
        application.logging:$(LOGGING)
        application.secret:$(imagePullSecret)
        application.livenessprobe.enable:$(LIVENESSPROBE_ENABLE)
        application.livenessprobe.initialDelaySeconds:$(LIVENESSPROBE_INITIALDELAYSECONDS)
        application.livenessprobe.periodSeconds:$(LIVENESSPROBE_PERIODSECONDS)
        application.readinessprobe.enable:$(READINESSPROBE_ENABLE)
        application.readinessprobe.initialDelaySeconds:$(READINESSPROBE_INITIALDELAYSECONDS)
        application.readinessprobe.periodSeconds:$(READINESSPROBE_PERIODSECONDS)
        application.healthCheckPath:$(HEALTH_PATH)
        resources.limits.cpu:$(LIMITS_CPU)
        resources.limits.memory:$(LIMITS_MEMORY)
        resources.requests.cpu:$(REQUESTS_CPU)
        resources.requests.memory:$(REQUESTS_MEMORY)
        ingress.enable:$(USE_INGRESS)
        ingress.port:$(ingress_port)
        ingress.path:$(INGRESS_PATH)
        ingress.host:$(INGRESS_HOST)
        ingress.timeout:$(INGRESS_TIMEOUT)
        ingress.maxBodySize:$(INGRESS_MAX_BODY_SIZE)

**Comment by ds-ms** [comment]
@shigupt202 to take a look

**Comment by Davidsv** [comment]
I'm also getting this issue.
![image](https://user-images.githubusercontent.com/2641528/95465091-01c13a00-097b-11eb-83a1-8c1e0866ba8c.png)

**Comment by ds-ms** [comment]
This is a known bug we fixed for the `HelmDeploy` task: https://github.com/microsoft/azure-pipelines-tasks/pull/13633 

Until this is fixed, you could use the same workaround @Exanis suggested. 😄

**Comment by shigupt202** [comment]
@Exanis Could you please tell what all tasks you are using in your pipeline that could be setting the Kubeconfig file? From your workaround, it looks like you are using KubernetesV1 task, but that task removes the Kubeconfig file post execution. So, ideally this warning shouldn't have been appearing because of KubernetesV1 task. Also I was not able to repo this issue. Would it be possible to share the entire pipeline?

**Comment by Exanis** [comment]
@shigupt202 sorry for the delay. I can send you the whole pipeline in a private message ; however it's quite a long one, using multiple imbricated templates

**Comment by shigupt202** [comment]
@Exanis Maybe then, it would be better if you could tell which task is generating the Kubeconfig in your pipeline? (If you think it's KubernetesV1, try printing in a CmdLine task in a subsequent step. Because ideally this task should have removed the Kubeconfig in [this step](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesV1/src/clusterconnection.ts#L79)).
FYI the issue is occurring because there's a Kubeconfig on the agent with group (and world) read permissions when a Helm command is being executed, which is not allowed in [latest Helm releases](https://github.com/helm/helm/commit/82398667dfe208407be9fe499ac96240aa8ce54b).

**Comment by Exanis** [comment]
@shigupt202 I think I found where our Kubeconfig file is generated (and why it's not removed).

`task: Kubernetes@1
              displayName: Initialize kubernetes staging connection
              inputs:
                command: login`

Here is what my pipeline really do :
- Log in to my staging env
- For each service in my app, look in my staging env, get the image tag currently present in my staging environment
- Also retrieve some variables from my env
- Write some files that will be used as input for helm (.txt files, not related to kubeconfig)
- Use helm to generate a chart for this service
- Append this chart to my "global" deploy chart (to use the auto-rollback tool from kube if a part of the chart fail to deploy)
- When every service was taken into account, log out from my staging env
- Log in to my prod env
- Deploy my global chart

I also have a dev deploy (of course) and this one, as well as the staging deploy, doesn't trigger this bug and doesn't have the initial login to the staging env (we use helm to bake the chart then log in to the target env and deploy).

So I guess that the real problem here would be that Kubernetes@1 create the file with bad rights ?

If needed, I'll send the whole pipeline files to the email you mentionned.

**Comment by shigupt202** [comment]
Thanks @Exanis for the details. This explains the problem. We do not expect the Kubeconfig generated during KubernetesV1 login command to be deleted, so that it can be used in subsequent steps. I'll work on the fix. However, the deployment can take a few weeks to reach all the customers. In the mean time, you can use older versions of Helm or logout command of KubernetesV1 before the bake step, as a work around.
