### ISSUE TITLE
Temporary Pipeline Artifacts

### ISSUE THREAD

**Issue by junalmeida** [microsoft/azure-pipelines-tasks#13756]
**Question, Bug, or Feature?**: Feature  
**Enter Task Name**: PublishPipelineArtifact  

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
- Agent - Hosted or Private: Hosted, but can be both
    
## Issue Description

Consider the use case where you need to publish an artifact to be consumed in the same pipeline run, for example to combine results of multiple jobs into a single artifact. In this case you might have a "temporary" artifact only useful during the pipeline run itself, and those could be safely deleted after the pipeline completes. 
This feature request is to create a new flag in this task to indicate the artifact can be deleted after the entire pipeline completes.

**Comment by bsegault** [comment]
We have a similar need in my organization.

We currently use PublishBuildArtifacts for temporary artifacts, because PublishPipelineArtifacts fails on multiple attempts (for instance, with unstable tests).
We also need to use DownloadPipelineArtifacts, because of #6739.

So we currently have a warning reported and must clean the downloaded artifacts manually to avoid conflicts.

Having an option for temporary pipeline artifacts would be nice. Or at least an option to force overwrite of existing artifact for the active pipeline run.
