### ISSUE TITLE
Azure Pipelines Windows image is much slower than other images

### ISSUE THREAD

**Issue by earlbread** [microsoft/azure-pipelines-tasks#13760]
In Azure Pipelines, the windows-2019 image is very slow, not always, but once every few times.
![Screen Shot 2020-10-24 at 12 27 52 AM](https://user-images.githubusercontent.com/5907919/97022940-c3896480-158f-11eb-82cb-b320ae61c6d7.jpg)

I used the `Bash@3` task to run the tests.

The result link:
https://dev.azure.com/waydi1/waydi1/_build/results?buildId=1025&view=logs&j=251538d5-9091-5b0f-9f9e-6014c2ac1eb8

The repository:
https://github.com/earlbread/libplanet/tree/azure-windows-slow-branch

Logs:
[windows.log](https://github.com/microsoft/azure-pipelines-tasks/files/5430420/windows.log)
[macos.log](https://github.com/microsoft/azure-pipelines-tasks/files/5430421/macos.log)
[linux.log](https://github.com/microsoft/azure-pipelines-tasks/files/5430422/linux.log)

**Comment by max-zaytsev** [comment]
Hi @earlbread - it doesn't look like an issue with bash task. This repo mostly holds issues with specific tasks. And it seems that this is the expected behavior for windows image. Please address general issues at  https://developercommunity.visualstudio.com/spaces/21/index.html - this should be the right place to get the answer to your question

**Comment by earlbread** [comment]
Hi @max-zaytsev. Thanks for your answer, I'll post my question there.
