### ISSUE TITLE
Custom Docker Command on Docker@1

### ISSUE THREAD

**Issue by damianon** [microsoft/azure-pipelines-tasks#13846]
Our on-prem agents for on-prem DevOps run as Docker containers.
Therefore we have to use Docker@1 to build docker images, as @2 apparently removed the setting dockerHostEndpoint.
However now the docker host get's filled with images and we'd like to issue a cleanup command (docker rmi) after pushing the image to our acr.

Is there a way to execute a custom docker command on the docker host using the configured docker host endpoint?

**Comment by ds-ms** [comment]
The command section of both docker@1 and docker@2 are editable dropdowns. You can supply the command you want to run and additional arguments in the `arguments` input.

**Comment by damianon** [comment]
as far as i understand it, the command is just a selection of predefined values. at least according to the docs here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops
(however i am unsure how to find the docs for older task versions)

**Comment by ds-ms** [comment]
You should still be able to supply that as an input, especially because it's an editable dropdown. I'm sure it'll work.

>the command is just a selection of predefined values.

Yes it is, but it still allows you to use the task like this:
![image](https://user-images.githubusercontent.com/25762922/100264308-abcd4380-2f74-11eb-87b3-e7636131d557.png)


I'm closing this issue for now, if you run into some issues while trying the same feel free to reopen it
