### ISSUE TITLE
DockerHostEndpoint for Docker@2 Task

### ISSUE THREAD

**Issue by damianon** [microsoft/azure-pipelines-tasks#13845]
Why has that setting been removed from the Docker task?
Our self-hosted agents are docker instances, so they can't use the docker build command and our only way for now is using Docker@1 and accessing the docker host.

## Required Information

Entering this information will route you directly to the right team and expedite traction.

*Type*: Question

**Enter Task Name**: Docker@2

## Environment
- Server DevOps on-prem
    
    - If using TFS on-premises, provide the version: Dev18.M170.6

- Agent - Hosted or Private:  private docker images

    - If using private agent, provide the OS of the machine running the agent and the agent version: Ubuntu 18.04 and Windows Agents

## Issue Description
Docker Host not available in Agents running as Docker Containers

**Comment by ds-ms** [comment]
@ajinkya599 could you address @damianon question.

**Comment by damianon** [comment]
No reply yet

**Comment by ajinkya599** [comment]
This was removed in DockerV2 in order to simplify the YAML specification of the task, as it was not being used widely.
To work-around this, you will need to set-up the environment ([Docker cli environment variables](https://docs.docker.com/engine/reference/commandline/cli/#environment-variables)).  [Pipeline secrets](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables) can be used to pass the secrets for the environment.
