### ISSUE TITLE
List all CI variables

### ISSUE THREAD

**Issue by chr0m1ng** [microsoft/azure-pipelines-tasks#13970]
Hi, I'm trying to list all my CI defined variables of the tab "variables" with a bash script but I couldn't find any information on how to, just to get the value of a specific variable.

Example:
At my Pipeline I have created these variables.

![image](https://user-images.githubusercontent.com/11679657/100158097-66344c00-2e8a-11eb-9e13-5212528f165f.png)

And at my bash script I wan't to iterate over the names like:

```sh
for x in $(env | grep framework); do
  echo $x
done
```

But seems like the variables defined there aren't available at `env`, how can I achieve that?

**Comment by EzzhevNikita** [comment]
@chr0m1ng All the user defined variables is injected as environment variables for your platform. In case it seems that you are expecting that variable will be _framework_ but in fact it will be _FRAMEWORK_ because when variables are turned into environment variables, variable names become uppercase.
You can find more info about it [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#environment-variables)

**Comment by anatolybolshakov** [comment]
Hi @chr0m1ng is this issue still actual for you?

**Comment by chr0m1ng** [comment]
Sorry about the delay (I was on vacation), the answer provided by @EzzhevNikita is right. Thanks for the help!
