### ISSUE TITLE
HelmDeploy@0 not masking secrets in pipeline logs when provided as "overrideValues"

### ISSUE THREAD

**Issue by UmairSyed** [microsoft/azure-pipelines-tasks#13985]
I am trying to pass app insights instrumentation key as a parameter to the Helm Chart so that it can be used as a value for environment variable for azure function that is running as a container. The issue is that the step that is using HelmDeploy@0 is actually printing the key in the logs like so:
2020-11-26xx [command]/usr/local/bin/helm upgrade --namespace dev --install --set functions.podIdentity.resourceId=/subscriptions/x/resourcegroups/x/providers/Microsoft.ManagedIdentity/userAssignedIdentities/x,functions.config.appInsightsInstrumentationKey=xyz
This value is obtained in a previous stage by using az cli command in 'pscore' like so:
"##vso[task.setvariable variable=APP_INSIGHTS_INSTRUMENTATION_KEY;issecret=true;]$($appInsightsInstrumentationKey)"
is there a way to hide this value from the logs?

**Comment by ds-ms** [comment]
> "##vso[task.setvariable variable=APP_INSIGHTS_INSTRUMENTATION_KEY;issecret=true;]$($appInsightsInstrumentationKey)"

This command should help you set the secret. But the syntax is probably wrong

`##vso[task.setvariable variable=APP_INSIGHTS_INSTRUMENTATION_KEY;issecret=true;]$appInsightsInstrumentationKey` Use it like this and try again. I'm assuming you're fetching this value, during runtime and setting it to this variable: `appInsightsInstrumentationKey` 

You should be doing it before this task's step. If you're setting in a different stage; then the context of the agent would change so perhaps that's why it was failing for you.

**Comment by ds-ms** [comment]
Closing this issue. Feel free to reopen if the problem persists.
