### ISSUE TITLE
AzureRMWebAppDeployment@4 doesn't seem to repect the SetParametersFile parameters

### ISSUE THREAD

**Issue by shamglam** [microsoft/azure-pipelines-tasks#14012]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureRMWebAppDeployment@4

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Given a task defined as such AzureRMWebAppDeployment@4 

    - task: AzureRMWebAppDeployment@4
      displayName: Azure App Service Deploy
      inputs:
         ConnectionType: PublishProfile
         PublishProfilePath: 'back-end\SBS\SBS.Web\Properties\PublishProfiles\inte-WebDeploy.pubxml'
         PublishProfilePassword: $(publishprofilepassword)
         packageForLinux: '$(Pipeline.Workspace)/art/**/*.zip'
         WebAppName: sbsinte
         DeploymentType: webDeploy
         enableCustomDeployment: true
         SetParametersFile: '$(Build.SourcesDirectory)\back-end\SBS\SBS.Web\dummy.xml'

the setparametersfile is totally ignored instead the one msbuild added is used.

### Task logs

2020-12-02T13:50:52.1115781Z [command]C:\windows\system32\cmd.exe /D /S /C "D:\a\1\art\SBS.Web.deploy.cmd /Y /A:basic /U: "/P:***" "/M:https://.azurewebsites.net:443/msdeploy.axd?site=nte" -enableRule:DoNotDeleteRule -retryAttempts:6 -retryInterval:10000"
2020-12-02T13:50:52.2255328Z SetParameters from:
2020-12-02T13:50:52.2255723Z "D:\a\1\art\SBS.Web.SetParameters.xml"
2020-12-02T13:50:52.2256409Z You can change IIS Application Name, Physical path, connectionString
2020-12-02T13:50:52.2256879Z or other deploy parameters in the above file.
2020-12-02T13:50:52.2257204Z -------------------------------------------------------
2020-12-02T13:50:52.2289353Z  Start executing msdeploy.exe
2020-12-02T13:50:52.2290965Z -------------------------------------------------------
2020-12-02T13:50:52.2332583Z  "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:package='D:\a\1\art\SBS.Web.zip' -dest:auto,computerName="https://.azurewebsites.net:443/msdeploy.axd?site=inte",userName="",password="***",authtype="basic",includeAcls="False" -verb:sync -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -setParamFile:"D:\a\1\art\SBS.Web.SetParameters.xml"  -enableRule:DoNotDeleteRule -retryAttempts:6 -retryInterval:10000

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by asranja** [comment]
Publish Profile based deployment uses the web app's deploy.cmd file to publish web package. If you look at the contents of this file, you will notice that `_DeploySetParametersFile` is explicitly set to point to SetParameters.xml file. 
```bash
set RootPath=%~dp0
if /I "%_DeploySetParametersFile%" == "" (
set _DeploySetParametersFile=%RootPath%WebApplication3.SetParameters.xml
)
```
The deploy.cmd file doesn't seem to provide a way to override the value of `_DeploySetParametersFile`. 

If you want to use a different SetParameters file, try using Azure Resource Manager connection type instead of Publish Profile.

**Comment by asranja** [comment]
Thanks for bringing this up to our attention. This will be fixed as part of the above PR. 

If you want to quickly unblock yourself, set the variable `_DeploySetParametersFile` in pipeline with value equal to your expected set parameters file path. 

```yaml
variables:
  _DeploySetParametersFile: $(System.DefaultWorkingDirectory)/AppService/setparams.xml
```

**Comment by LordZoltan** [comment]
For anyone who's been trying to get this to work with an AzureRM connection type , I can confirm it works if you explicitly set the `useWebDeploy` and `deploymentType` task parameters:

```
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: subscription_name
    appType: webApp
    WebAppName: myWebApp
    package: 'path/to/package.zip'
    useWebDeploy: true
    deploymentType: 'webDeploy'
    SetParametersFile: 'path/to/set_parameters_file.xml'
```

If you look at the `task.json` files you'll see that these values must also be set in order for the UI to show the `SetParametersFile` field.  This is a bit broken, because I think it means that even if the task eventually decides to use web deploy, it'll ignore the setparameters file unless you explicitly set these properties.

Still, I'm glad it works at least one way - otherwise I was going to have to rethink my entire release strategy for about the 20th time!
