### ISSUE TITLE
Publish Test Results task - please add output variable for RunId

### ISSUE THREAD

**Issue by bfreezer99** [microsoft/azure-pipelines-tasks#14068]
*Type*: Feature Request

**Enter Task Name**: Publish Test Results task
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishTestResultsV2

## Environment
Azure Devops Server 2020 On-Premise
Private Agent - Windows 10 with agent version 2.175

## Issue Description

Hello, 
I really need the 'RunId' from the Publish Test task as an output variable.  I was able to do this easily by adding a line of Powershell in the V1 version of this task, but with the switch to Typescript I was unable to figure out how to output the variable.  The runid is used to tag a copy our test log files, in order to easily provide a link to our QA analysts.  If you could create an output variable with the RunId in this task, it would be greatly appreciated.  I can see the RunId in the output of the task, but have no way of capturing it.  Thanks.

**Comment by RobDBob** [comment]
Is there way to capture run id via variable? Is there an example?

**Comment by thwr** [comment]
I'm running against the same wall, want to attach some screenshots to a test result. There's a way by parsing the log files of the Publish Test Results Task (like https://stackoverflow.com/questions/67534289/azure-devops-pipeline-logs-for-a-specific-task for example), but that's a terrible idea IMHO. One could also fetch the latest published test run, which is another terrible idea because of possible parallel runs - files could be attached to the wrong test run.

Publish Test Results should expose a pipeline variable containing the `runId` of the test so we could get additional parameters like `testCaseResultId` and finally attach files using https://docs.microsoft.com/en-us/rest/api/azure/devops/test/attachments/create-test-result-attachment?view=azure-devops-rest-6.0
