### ISSUE TITLE
VSTest task forms a wrong filter to rerun failed tests

### ISSUE THREAD

**Issue by Roman-Rostovtsev** [microsoft/azure-pipelines-tasks#14099]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest

## Environment
- Server - Azure Pipelines
- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account name: nsq20040061
Build definition: CC-23860 ( https://dev.azure.com/nsq20040061/VSTestExperiment/_build?definitionId=18 )
Build number:  398
- Agent - Private
   
- If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows 10 x64
Agent 2.174.2

## Issue Description
We've faced the issue that it's not possible to re-run failed tests using our custom adapter. It happens because the VSTest task forms a wrong filter to select failed tests.
In order to demonstrate this issue, I've created a simple test adapter which always finds 2 tests in any .testContainer file with FullyQualifiedNames "test1" and "test2":
[MyDemoAdapter.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5714134/MyDemoAdapter.zip)
It also always says that the test1 passes, and the test2 fails.
I've put an empty file with "Container1.testContainer" name to the Git repository and created a build pipeline which starts tests from "**\\*.testContainer" files and turned on failed tests rerun. As a result, a such build is unable to rerun the failed test, it posts the following error to a log:
_No tests were discovered while attempting to rerun failed tests._
You can also find the following message
_No test matches the given testcase filter `FullyQualifiedName=Container1.test2`_
 in the build log 
https://dev.azure.com/nsq20040061/VSTestExperiment/_build/results?buildId=398&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=023e7c10-1b10-57e0-8fcd-191cc0e0ded0
So you can see that the VSTest task corrupts FullyQualifiedName of tests (the filename is prepended to an actual FullyQualifiedName), and tests cannot be found.

### Task logs

https://dev.azure.com/nsq20040061/VSTestExperiment/_build/results?buildId=398&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=023e7c10-1b10-57e0-8fcd-191cc0e0ded0

**Comment by katiekloss** [comment]
I'm also having this issue. In my pipeline, the VSTest2 task passes the TestCaseFilter parameter to vstest as:

`/TestCaseFilter:"FullyQualifiedName=CPP.Tests.Rules_CA_CADriverBase_DriverAgeMinimumValidation.Rules_CA_CADriverBase_DriverAgeMinimumValidation(CPP.Tests.Rules_CA_CADriverBase_DriverAgeMinimumValidation+DriverAgeMinimumValidationTestCaseData)"`

VSTest throws the error "An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Missing Operator '|' or '&'."

According to the [TestCaseFilter documentation](https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md), some characters need to be escaped. In this example, the task isn't escaping the parentheses in the method name. When I escape them like the following and run VSTest, it runs correctly:

`/TestCaseFilter:"FullyQualifiedName=CPP.Tests.Rules_CA_CADriverBase_DriverAgeMinimumValidation.Rules_CA_CADriverBase_DriverAgeMinimumValidation\(CPP.Tests.Rules_CA_CADriverBase_DriverAgeMinimumValidation+DriverAgeMinimumValidationTestCaseData\)"`

**Comment by ShreyasRmsft** [comment]
As captured in the docs over [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops#i-am-running-into-issues-when-running-data-driven-xunit-and-nunit-tests-with-some-of-the-task-options-are-there-known-limitations) if adapters have custom implementations of fully qualified names are formed then vstest task was not engineered to handle those scenarios.

Some of the advanced features (line re-run failed tests) of the task that depend on the fully qualified name of the tests will not work.

If you take a look at the trx published by your run you'll see a class name and a name field which is definition for fully qualified name. In order to be able to use the re-run feature your custom adapter should have the capability to identify tests using their fully qualified names which is nothing but a concatenation of the class name and name fields present in the trx.

![image](https://user-images.githubusercontent.com/25194518/104306027-73b59c00-54f3-11eb-9be5-1d8d72ce0f0f.png)

Having said that, closing this issue since modifying the behavior is currently not in our roadmap.

**Comment by Roman-Rostovtsev** [comment]
The link you provided with relates to data-driven xUnit and NUnit tests, it is not my case. So it seems such behavior is documented nowhere and it is also illogical and inconsistent.
