### ISSUE TITLE
DotNetCoreCLI@2 with command=publish ignores "projects" argument and selects arbitrary wrong csproj instead

### ISSUE THREAD

**Issue by sandersaares** [microsoft/azure-pipelines-tasks#14205]
## Required Information

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**:
DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://skype.visualstudio.com/DefaultCollection/SCC/_build?definitionId=9928&_a=summary
- Agent - Hosted or Private: Private, Windows 10, 2.169.1

## Issue Description

My YAML says this:

```yaml
      - task: DotNetCoreCLI@2
        displayName: .NET Core publish
        inputs:
          command: publish
          projects: xxx.sln
          arguments: --configuration Release
          workingDirectory: $(projectRoot)
```

When I run the build, the task runs the command `D:\a_work\_tool\dotnet\dotnet.exe publish D:\a_work\321\s\xxx\DevPlayer\DevPlayer.csproj --configuration Release`

My expectation was something along the lines of: `D:\a_work\_tool\dotnet\dotnet.exe publish D:\a_work\321\s\xxx\xxx.sln --configuration Release`

Notably, the project file is completely wrong. The task seems to entirely ignore the value I enter in the `projects` parameter and always pick this "DevPlayer" project for whatever reason (which is part of my solution, but not the only project in there). My goal is to publish all .NET Core projects in the solution.

Also tried various alternatives for `projects` value, with no difference.

Is the task just overwriting my `projects` variable without a care in the world? See https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L351

Yes, that seems to be. What in the world is such a fundamentally disruptive setting doing as a default? Even if technically by design, this is a big UX defect.

### Task logs

Logs with debug output accessible here for MSFT users: https://skype.visualstudio.com/DefaultCollection/SCC/_build/results?buildId=38531869&view=logs&j=518a43f1-9e9c-5e03-8567-3796dcbb14f5&t=bcc15253-5413-56d2-ed86-472e79afb69b&l=33568

I see the correct (?) inputs in the log at the start:

```text
2021-01-09T15:46:33.5151370Z ##[debug]command=publish
2021-01-09T15:46:33.5153840Z ##[debug]projects=middle-lane.sln
2021-01-09T15:46:33.5156064Z ##[debug]arguments=--configuration Release
2021-01-09T15:46:33.5157945Z ##[debug]publishWebProjects=true
2021-01-09T15:46:33.5159347Z ##[debug]zipAfterPublish=true
2021-01-09T15:46:33.5161395Z ##[debug]workingDirectory=D:\a_work\321\s\xxx
```

But immediately after that the task seems to start some search for csproj files starting from my repo root:

```
2021-01-09T15:46:33.5472384Z ##[debug]pattern: '**/*.csproj'
2021-01-09T15:46:33.5492855Z ##[debug]findPath: 'D:\a_work\321\s'
2021-01-09T15:46:33.5493710Z ##[debug]statOnly: 'false'
2021-01-09T15:46:33.5494191Z ##[debug]findPath: 'D:\a_work\321\s'
2021-01-09T15:46:33.5494743Z ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
2021-01-09T15:46:33.5495325Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2021-01-09T15:46:33.5495886Z ##[debug]findOptions.followSymbolicLinks: 'true'
```

**Comment by ashwinsangem** [comment]
Hi @sandersaares, this is expected behavior.
the _projects_ input is valid only when _publishWebProjects_  is false. See [this](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreCLIV2/task.json#L105). The [help text](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreCLIV2/task.json#L98) of _publishWebProjects_  input is also helpful in understanding its behavior.
Not all task inputs are relevant in every case. When building a YAML pipeline, the valid inputs and their help texts can be seen through the `show assistant`  button.
![image](https://user-images.githubusercontent.com/4964038/104725338-f2127800-5757-11eb-80c5-5db37b42c1cc.png)

Below are the various options for publish once you enable `show assistant`
![image](https://user-images.githubusercontent.com/4964038/104725445-1bcb9f00-5758-11eb-8b7b-8041770a82ca.png)
![image](https://user-images.githubusercontent.com/4964038/104725469-24bc7080-5758-11eb-9db6-0869066e8f39.png)

**Comment by ashwinsangem** [comment]
Let me know if you have any questions.

**Comment by sandersaares** [comment]
I do not have any questions. I understand how the task operates. This feedback is intended to emphasize that the way the task operates is problematic and difficult to understand. I recommend the task be redesigned without this "modality".

**Comment by ashwinsangem** [comment]
@sandersaares makes sense. I'll escalate this to the PM and see what can be done. Thanks for the feedback :)

**Comment by biiiipy** [comment]
We wasted couple of hours on this. The way this works is just absurd. If we provide `projects` property, why would it go and try to find web projects on it's own? We literally specify what to publish.
`publishWebProjects` and `projects` are mutually exclusive properties, but because `publishWebProjects` is `true` by default, this whole thing just breaks down.
`publishWebProjects` should be `false` by default, and should be ignored if `projects` is specified.

**Comment by brandon-hurler** [comment]
@biiiipy Agreed. I am increasingly concerned about how the DotNetCoreCLI@2 processes commands. Me and my team just wasted hours trying to get dotnet restore to work with arguments. The restoreArguments property didn't work and neither did arguments. Beyond this, it's crazy to me that restoreArguments was created to begin with. Every other command accepts arguments.

The code behind this feels like spaghetti.

**Comment by tcartwright** [comment]
I just spent several aggravating hours investigating the same issue. Very glad to find this issue and understand how to resolve it. Very unhappy that this was an issue from the get go.  

Very poor design. If anything the projects property should take precedence over the publishWebProjects property. 

In fact, I dont understand the need for the publishWebProjects property at all. In my mind a publishStartupProject would make more sense for a more generic design.

**Comment by brandon-hurler** [comment]
Tasks should be able to infer intent by what is being directly invoked. If any setting default is made invalid by a direct CLI command, the command should take precedence without you needing to know the setting exists at all. 

Otherwise, you have read the documentation on the task and check every setting default to see if it conflicts with your args every time you add or update a command.

**Comment by sathishreddy48** [comment]
how we can pass project(s) names dynamically ? 
I tried passing **xx.csproj**  with spaces it is not accepting
