### ISSUE TITLE
Get-AzWebApp "Unable to deserialize the response" when ipSecurityRestriction is of type ServiceTag

### ISSUE THREAD

**Issue by krispenner** [microsoft/azure-pipelines-tasks#14215]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell@4

## Environment
- Server: Azure Pipelines
- Agent: Hosted

## Issue Description
When my Web App has an IP security restriction defined of type `ServiceTag`, I am not able to retrieve it using `Get-AzWebApp`.

```js
    "ipSecurityRestrictions": [
      {
        "ipAddress": "AzureFrontDoor.Backend",
        "action": "Allow",
        "tag": "ServiceTag",
        "priority": 101,
        "name": "Allow-FrontDoorService"
      },
```

It seems the AZ module it not the latest version, even though I have `azurePowerShellVersion: LatestVersion` set on the task.

**Comment by aksm-ms** [comment]
@krispenner Can you please share logs?

**Comment by brekus** [comment]
Having the same exact issue. Here is a log output. 
[tasklog_6.log](https://github.com/microsoft/azure-pipelines-tasks/files/5887373/tasklog_6.log)

**Comment by 20shivangi** [comment]
@krispenner From the logs attached, az module version is 4.7.0 and the commandlet `Get-AzWebApp` must be available in that version.
Can you install this version locally on your machine and try to run the same az script that you are running using task and check if that is working for you ?

**Comment by krispenner** [comment]
@20shivangi yes when I run my script locally it works because the version of the az module is newer than whatever the “latest” version is on the YAML task. The issue seems to me that “latest” doesn’t actually mean the latest and there seems to be no way to specify a specific version of az to download and install.

**Comment by 20shivangi** [comment]
@krispenner Can you let us know what is the version of Az module in which your script is working ? On hosted agent, latest version corresponds to 4.7.0
Also, what you can do to verify if the problem is not with task, use private agent instead of hosted one and then specify the az module version that is in your machine

**Comment by 20shivangi** [comment]
@krispenner Addtion of latest versions of az module is in our backlog. Please have patience and we will surely add support for the latest az modules in hosted agent.
In the mean time to unblock yourself, you can use private agent instead of hosted one, install the latest az module on your machine locally and then specify same version in yout task in `specify version` block

**Comment by AmrutaKawade** [comment]
@krispenner we are currently working on upgrading az version on agent and by March end it will be available. till then you can follow above approach using private agent
