### ISSUE TITLE
Cancelling a Build does not kill Maven Task process

### ISSUE THREAD

**Issue by sarod** [microsoft/azure-pipelines-tasks#14228]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven

## Environment
- Server - Azure Pipelines       
   https://dev.azure.com/semarchy/Build Project/_build/results?buildId=3799

- Agent - Hosted agent Agent Pool: "Azure Pipelines" https://dev.azure.com/semarchy/Build%20Project/_settings/agentqueues?queueId=9&view=jobs

## Issue Description

Cancelling the build does not kill the maven task which runs until the timeout kills it

### Task logs

Not available

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

No log available

**Comment by FrancescElies** [comment]
I believe this issue is affecting other tasks too, I am having similar issues with custom builds too.

Even though I configured all my jobs with `cancelTimeoutInMinutes: 1` when I click cancel tasks are being executed until the end.

E.g. https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=49292&view=logs&s=01df7332-ddd3-5c82-f240-d009192798a8&j=79b13df5-4950-54f0-8a25-090624fa8a5b

**Comment by FrancescElies** [comment]
My problem was that I had jobs that specified a condition without checking for `succeeded()`

Problem:

    condition: and(eq(dependencies.A.outputs['A1.printvar.shouldrun'], 'true'))

Solution:

    condition: and(succeeded(), eq(dependencies.A.outputs['A1.printvar.shouldrun'], 'true'))
    
@sarod might this be your case too?

**Comment by sarod** [comment]
I'm in this case however I expected cancelTimeoutInMinutes to apply still
