### ISSUE TITLE
Courtesy push pipeline failures

### ISSUE THREAD

**Issue by damccorm** [microsoft/azure-pipelines-tasks#14230]
## Issue Description

Our courtesy push pipeline has started to fail consistently, we should get that fixed up. Its failing on the update unified deps step - https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=14098132&view=logs&j=39b35c2a-6bbc-5806-91b1-4f11d00d1f59&t=ab027f4d-fc26-5299-7183-aa2f205e36b6

I'm routing this to our ABTT team, I'm happy to help out on this one though, just ping me or tag me here if any questions pop up

**Comment by egor-bryzgalov** [comment]
`Error: Cannot find module 'D:\a\1\s\azure-pipelines-tasks\ci\courtesy-push\courtesy-push.js'` This exact error can appear if it's not a 3rd sprint week as per `whatsprintis.it`. AzureDevOps checkout is skipped in this case and hence the path previously mentioned becomes invalid since the tasks' repo is cloned to `D:\a\1\s\` directly. it seems that we can't just override the `WEEK` variable since it's set within the pipeline. 
The first failure occurred due to the following error at Build all tasks / Run tests step: `The job running on agent Azure Pipelines 33 ran longer than the maximum time of 90 minutes.`. It seems that it was scheduled to run in a week and it has failed as expected due to the week number mismatch. The last attempt was made at the 3rd week is [this one](https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=14038517&view=logs&j=9784995b-f699-5f68-c70b-00631acf7dd7&t=78de6dee-ba86-5fdc-91e5-70c262d96e1f) and it failed at the 'push release branch' step. It seems that it was required to pull commits from remote before pushing since the 'branch appeared to be behind its remote counterpart'

**Comment by egor-bryzgalov** [comment]
Merged the PR.
A fix was applied to avoid build failing if the pipeline runs not on the third week of a sprint (some steps are expected to be skipped in this case instead of build failing).
A fix was applied to avoid build failing if some commits are pushed to a release branch before a sprint ends.
