### ISSUE TITLE
"Resource file has already set to" warning at the KubernetesManifest@0 task

### ISSUE THREAD

**Issue by sadedil** [microsoft/azure-pipelines-tasks#14284]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesManifest@0  

## Environment

Azure Pipelines
Both of the Microsoft Hosted and On-Premise agents

## Issue Description

We are started to getting this error at the beginning of all `KubernetesManifest@0` tasks.

```bash
==============================================================================
Task         : Deploy to Kubernetes
Description  : Use Kubernetes manifest files to deploy to clusters or even bake the manifest files to be used for deployments using Helm charts
Version      : 0.181.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-k8s-manifest-tsg
==============================================================================
##[warning]Resource file has already set to: /home/vsts/work/_tasks/KubernetesManifest_dee316a2-586f-4def-be79-488a1f503dfe/0.181.0/node_modules/azure-pipelines-tasks-kubernetes-common-v2/module.json
==============================================================================
			Kubectl Client Version: v1.19.0
			Kubectl Server Version: v1.18.10
==============================================================================
````

### Task logs

Logs above

**Comment by ds-ms** [comment]
This is a warning. It wouldn't impact your release in any way. It's probably a side effect of us upgrading the underlying `task-lib` version to `3.0.6-preview`. 

@shigupt202 could you take a look?

**Comment by shigupt202** [comment]
This is happening probably because KubernetesV1 is dependent on azure-pipelines-tasks-azure-arm-rest-v2 which has the an older version of `azure-pipelines-task-lib`, while we have specified the latest version in it's package.json. This should not have any effect on the pipeline run.
@ds-ms Any suggestion what we should do here? Should we downgrade the task-lib version of this task, or ask the owners to update azure-pipelines-tasks-azure-arm-rest-v2?
