### ISSUE TITLE
AzureFileCopy@4 SubscriptionId parameter is not avalible

### ISSUE THREAD

**Issue by ld0614** [microsoft/azure-pipelines-tasks#14366]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug?

**Enter Task Name**: AzureFileCopy

## Environment
- Server - Azure Pipelines
- Agent: Hosted (windows-latest)

## Issue Description

When a Service Connection has been configured with access to multiple subscriptions it is not possible to upload to a storage account in any subscriptions apart from the default (or original) subscription.  

```
Error Message: ##[error]Storage account: STORAGEACCOUNTNAME not found. The selected service connection 'Service Principal' supports storage accounts of Azure Resource Manager type only.
```

The resolution was to create a connector for each subscription individually however it would be nicer if there was an optional parameter to select the Subscription.  This has already been done in AzureResourceManagerTemplateDeploymentV3 which allows for the same service connector to deploy to multiple subscriptions

### Task logs

Available privately on request

## Troubleshooting

To verify this behaviour I created a new service connector with only the desired subscription but using the original service principle.  This shows that the permissions on the service principle are correct and its just the task not identifying the correct subscription to read from.  

redeploying the storage account from ARM template into the default subscription also worked.  

### Error logs

##[error]Storage account: STORAGEACCOUNTNAME not found. The selected service connection 'Service Principal' supports storage accounts of Azure Resource Manager type only.

**Comment by 20shivangi** [comment]
@ld0614 We do not support a service connection with access to multiple subscriptions in the task . Try to use manual spn with access to single subscription and azure powershell with combination of `set-azcontext`  to provide access to other subscriptions to use the same.

**Comment by cstrempfer** [comment]
This is a constant struggle with Azure Pipelines. I reported the same issue in #14359 for another task.

Even worse some tasks do not even support service connections for subscriptions, e.g. PythonScript. That means basically you have to manage:

- one service connection for every subscription, because tasks do not support management groups
- service principal credentials in pipeline variables for tasks that do not support service connections
- optionally, you can add service connections for management groups for the rare case that a task supports that

I would need 3 service connections for management groups, but actually I'm managing 25 sets of credentials because of this.

I'm not satisfied with contributors marking this as enhancement. It should be a bug. Why were service connections and management groups introduced in the first place, if not even Azure itself is supporting them?

**Comment by ashokirla** [comment]
@cstrempfer Thanks for the feedback. As of today, we dont have support for service connections with multiple subscriptions. 
Adding @ninallam/@vijayma to take this feedback.

**Comment by ninallam** [comment]
@cstrempfer Thanks for the feedback We have take a note and will look out for more requests on this.

**Comment by 20shivangi** [comment]
@cstrempfer @ld0614 As mentioned above, we have taken your request into our feedback and will look out more for such requests.
Thank you for providing your input. Thereby closing this issue.
