### ISSUE TITLE
Azure App Service Deploy task: Error: 'credentials' cannot be null

### ISSUE THREAD

**Issue by MikielAgutu** [microsoft/azure-pipelines-tasks#14373]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: `AzureRmWebAppDeploymentV4` (Appears in the UI As 'Azure App Service Deploy')

## Environment

Azure DevOps, Pipeline. Hosted agent.

## Issue Description

When attempting to deploy with the Azure App Service Deploy task, I get the error `'credentials' cannot be null`. Nowhere in the UI am I asked for credentials.

### Task logs

Log is attached.

[tasklog_8.log](https://github.com/microsoft/azure-pipelines-tasks/files/5957979/tasklog_8.log)

**Comment by 20shivangi** [comment]
@MikielAgutu  In Azure app service deploy task, we have two connection, Publish Profile and ARM. 
From the logs attached, I can see that you are using publish profile, have you tried to use ConnectionType = PublishProfile instead of Azure Resource Manager?

**Comment by MikielAgutu** [comment]
I don't quite understand.  Is there an actual reason why Azure Resource Manager doesn't work for me? Or is it just broken?

The publish profile asks me to enter the profile I made in Visual Studio. Well I'm not using Visual Studio - so how can I create a publish profile?

**Comment by 20shivangi** [comment]
@MikielAgutu From the logs attached, it can be seen that you are using `Publish Profile` as connection type and credentials are null, due to which it is giving error

![image](https://user-images.githubusercontent.com/45754171/108028914-925b0580-7052-11eb-9be3-07e87c8270af.png)


**Please see the below snippet to use the correct service connection and provide credentials for the same**

![image](https://user-images.githubusercontent.com/45754171/108029197-11e8d480-7053-11eb-8b2b-50cbbc660568.png)

**Comment by 20shivangi** [comment]
@MikielAgutu Any update here ?

**Comment by MikielAgutu** [comment]
I was not using Publish Profile - I had already specified Azure Resource Manager in the first instance. Now I think the issue was something to do with the service connection. I had to ask our IT department to sort it out.

So I suppose this is resolved. Although it would be nice to have a clearer error message.
