### ISSUE TITLE
Helm3 support for KubernetesManifest

### ISSUE THREAD

**Issue by florin-szilagyi** [microsoft/azure-pipelines-tasks#14379]
## Note  
Helm3 support for KubernetesManifest

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Feature/question

**Enter Task Name**:  KubernetesManifest

## Environment
 All environments
## Issue Description

Will the KubernetesManifest support Helm3 (right now it's working with Helm2). If not, why not?

**Comment by ds-ms** [comment]
@florin-szilagyi it supports `Helm3` right now. 
You can checkout this code: 

https://github.com/microsoft/azure-pipelines-tasks/blob/b908bffea681a03d1b8925e299d2a2b794bc035e/common-npm-packages/kubernetes-common-v2/helmutility.ts#L18..L24

If your environment has `Helm2` it'll use `Helm2` otherwise it downloads the latest release.
