### ISSUE TITLE
Add labels with base image information to docker images

### ISSUE THREAD

**Issue by jcfiorenzano** [microsoft/azure-pipelines-tasks#14650]
## Required Information

**Question, Bug, or Feature?** 
*Type*: Feature

**Enter Task Name**: Docker

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

Add labels _org.opencontainers.image.base.digest_ with the base image digest and _org.opencontainers.image.base.ref.name_ for the base image name. In the case of multistage builds use the latest base image.

This information can be used for other tasks that extract metadata from the image that was just built.

**Comment by ajinkya599** [comment]
@N-Usha Are you okay with these labels?

**Comment by ajinkya599** [comment]
@ninallam Can you please review the labels?

**Comment by ajinkya599** [comment]
@ajinkya599, @ds-ms and @ammohant discussed this and here are our thoughts on the required changes:
@ninallam - Please let us know if you have any other thoughts.

- Add an environment variable `DOCKER_TASK_BUILT_IMAGES` that captures the list of built images. Each build from Docker (V0, V1, V2) should append to this list.

- Add a new output variable `DockerOutputPath` in `DockerV0` and `DockerV1` that stores the path to the file that contains the output of the Docker task. (The behaviour of `DockerOutput` variable should not change).

- Instead of adding partial set of OCI labels, lets add the required labels without following the OCI conventions (keeping parity with the current build/release labels)
  - `image.base.digest`
  - `image.base.ref.name`

- There should be a way to control the addition of the new labels to the built image in all the versions of the task.
@ninallam Should this be an environment variable or a first-class input? Also, can you please recommend a name?

**Comment by ninallam** [comment]
The above approach looks good. 

```
There should be a way to control the addition of the new labels to the built image in all the versions of the task.
@ninallam Should this be an environment variable or a first-class input? Also, can you please recommend a name?
```
Regarding giving a control the to add the new labels, we should have this in Docker V2. For Docker V0, V1 we will add these by default. If customers want to turn off the labels they can  upgrade to the latest version.

**Comment by ajinkya599** [comment]
> Regarding giving a control the to add the new labels, we should have this in Docker V2. For Docker V0, V1 we will add these labels by default. If customers want to turn off the labels they should upgrade to the latest version.

@ninallam - Shouldn't we have a way to turn it off even for the older versions as well? The idea is to have a quick mitigation if hypothetically it breaks something for the users. The default can be on in all the versions.

**Comment by ninallam** [comment]
@ajinkya599 If we meed a quick mitigation, let's have a similar task input for all the versions of the task.

**Comment by krokofant** [comment]
This feature always pulls the latest image so the cache on the build agents can't be fully used without disabling it.

**Comment by ggirard07** [comment]
Is it possible to add this variable into [official task documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-v2?view=azure-pipelines&tabs=yaml#output-variables)?
