### ISSUE TITLE
Override parameters with brackets '(', '[', '{' parsed incorrectly (AzureResourceGroupDeploymentV2)

### ISSUE THREAD

**Issue by SvenEV** [microsoft/azure-pipelines-tasks#14711]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceGroupDeploymentV2  

## Environment

- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

We are using the "Override template parameters" field of the task to assign variable values from a classic Azure DevOps release pipeline to ARM template parameters and noticed a strange behavior when these values contain parentheses, brackets or braces enclosed in quotes.

More specifically, some of our pipeline variables contain minified (single-line) JSON strings of the form `{"ClientId": "...", "ClientSecret": "...", ...}` where the ClientSecret may contain special characters like '[', causing the issue described above.

### Example

For example, let "Override template parameters" be
```
-param1 "$(variable1)" -param2 "$(variable2)"
```
where variable1 = `"va[ue1"` (note the quotes and bracket) and variable2 = `value2`.
Then param1 receives the string `"va[ue1"" -param2 "value2` and param2 is not populated at all.

### Root Cause

The problem seems to be caused by `PowerShellParameters.parse` expecting brackets to be balanced for some reason, i.e. it expects to find a closing bracket ']'.

Unfortunately, I cannot disclose detailed information about our release pipelines.  
However, the issue can be easily reproduced in isolation:
[Link to TypeScript Playground with simple examples that break the parser](https://www.typescriptlang.org/play?ssl=230&ssc=16&pln=230&pc=55#code/PTBQIAgBQQwJwM4EsB2BzCBjA9gEwKYQAuMA1vihAGZzYC24wEAFkUQA4IBcIaSRzAK4AjAHQ46wOkky0E2KkWAwAXoLj4AtOyTt8AG1T4EmkglIJgw-dmFSYCIvjjAAKg4vAAgmo0AlY2x1THwAcVpBdgARfHYbAE86CiIANQAmYGw9OBgiJGwUS1gcpKc4YoRnUSIERlBQVDKqGBCIADkYJJSYfUF8WCQ4CABvUAhxiBRO-C4IRzhUNABuMYmANx6+2fnFlYBfesx9BwRobAB3ZwBlZgN9Yumy09HV8cgK42JbuaIF9AgYChcBANEQ+oUAXAcvEIAoIOR4poNr1COwYINahMIOwRIZMD9cjJsfBKgAKVA4ojbX6LAA0IPwdGwa3wAEVBNgnAgAPyzYTYbD6fCA+nGTAwPQAYWY8BaZV5Pz+aAAlLMOl1Nv10XAANoAXRGryxECQVAgpIAhBaxRL8NLZZgysrDcbXV8kAhRDapTKco7nBAALwQb1231y5wrN0QA7RjZDDQIQT6KntabdFEDXUG4P6qNu+MmoH4AAeQYgAAZ867C7YAFZq9OarPl4aTaazABEnfpyK2EG7MZWRqxFMERHLY6I1QWdFJyuH0fOzCQQvNqAIZYAPEXKaIhegBM7RtGsYXDGUelFcjBywIPaIqBuADL8Zw9ckoSn0jelhcjgt4EmUsiAASWLMtgwvd99GvEhxHUDQUCIKBsGQPICmrU9CxlBArj0TAkB6e0-TKctoJyWCb1EXD8PwQjiPDf04CwuMgIonpJy-cdRCTYR5k-Td6RQEDwM3CBNCLTdlRnJA53-U8JlNc1709D11XwUkOP0elaIIoj9BIiM4GVY8AMU5TSXrUQpiSMzFMUxNk2nHEEGYKzhDrBSHOjetW3bJIux7CA+xmAdOyHczT1jHyJhAPj5moWg6Ck0sIAARmIbAGSZFkIAAck0fKiy+QhHHgPJ-jhbSot8zybOmci30o3iRAE9L6W0-cKDQI9WLdGLFIMSoXVi8ZrNCprL30frHOMZzRFc9z628sa-ODNtbLC7te01ILIp8g5aqUiDyxEkswNOgBqDLZpjepo0s6ytvshynJTRbBDcjyvLuwbjUsq0NFytkOS5V7FKobAhlJQstpK96iAh2LEZ1La9VESbg1R9HMc1UQNDiFpNOAAA9TtSVEAAqZVOwAEmAel8rp9L8tW6KoqO6NVK9BBxR9B0yODTsAANOyWCBIACSo2EWEM+dtLAmLKKLQXUShEawrm4qYK5nAMpAVE+ARUVlUoA3gaEssVRYjRxawiXKvJ8UqBYekNzS0RKfAnkbDVM21fVVRt-4T0AhN5pTctuzuyyvceZwEGR6MoZhwskHLKsTQgHd4-NxBusPZgJaQK6ruThy47Nn3E51JAMZe0axqxRGICu4XNAim685rxA64bxqboi8Xjtdf6fKr72nn7vGUQrsbW-b4kp9r+vZ76NuBwHO7o3HgbOYet01bgDXI+nGl5K1w-xntvECWd6gNwAMQxIhSR732039vos31YSOxDiqJuxp06nWDJodKd1U7mnTpnEuOdl4JwLgeXqxc25XSQPPAGZp37V2nmvLa1RsDPguM4SUDhNLOkDNQgK+AiEkMuHAchZJTLAInmAk0O83TCA0GQLh4w94CNVj7dWqUSxXyNJAGIQouSlUfogCc2BMCYHUICVocIP4BmUqWD0NQARAgZGCE+pwTYQAIDI-AwJQp21xI7EgD9zE11wSvRAft8AZh-oHPU-9AqAODhpDxWpBiGiioWRxTgxJpXAZA0JQFwmWMCWdZMM1r7GkgC-AxT4FGwmUaolAIRYlDHiZEyC7pPRPiBC-BRzikEIB8fgf8UVIBXBgHlW8OB2AwkBMCaRNcoqWWKadAAfMGCsWCsTxNwIk4MmiC4IDiDITSgyhIZWVDqCseo-qpJbiIk+ZiDA1ymZqCRWJ2ALA2E4e+RJ1LTC0s1Ho1IlS6QcHRBihllbOD5AKIUgJg78kFMKSgYdXTH0oNpdZOYaGFWKgAMhhRAC0el6IGSMsxCAcKTQIA6G0UkbRBB0GEM4O501TInImGcpAFyyr2KJBU3Ar5pqfm-FgRCyRULoXyCgLBOEXn6UYoLAMwZmj6EqFA6G5oJYqKhGytC-BOUIKnIXVBkrWXIXZXKgoZdxlKRwVOHUUqkIoVlRhFAkKt4RQAD4Wt3OOfVqqjUcoKGazsAAdIgnZtWumgaSFV0q1XGvlTuRVKCBC+sNeqk1Wq2HN0snqg1MrHWUBuulA0FphZbwxXG+1Eb5XJtTcLN1Hro3NwmDw4UpB+EcxLdrMaZa+Gj3uj5YahBY3cSIHav1DqNWmqDMLUkRbgWxXjf6xNd4VzlI3JKGwyB0AACE-TkEupuJl456TDq7SazeHUBy03Zj5JFbzUVC2IHAPolbBHGmbSaXVbaO3hoDU63tA4dQDobViddOaChjofHSqdsq50Lp9iUldRA13ZofUmjK9JOx6g9ZWrEB6UUfKGMGX4Z6G0XqxFe1tlI70Ju7c64Yr6S0fog9+idQI-0zrQPOloi7gNTjA52z9kHt2dj2HBt9ExEP8tIoKk96HDoNuwze3DpHE3Opdd2T1aTgDkFiBANA2A5Z5H0PoMpsIRJYGncYLj4xxPdvI4+Sd07Fjsk5PgBjbamP3tHcm6DUnOMlp4+8gVKGBP4HPcJkVLbRO2oMya51+ViPNxAPJ9ginlP-FU+p1SmnCBHDQrpkj4HR2ofHcZyjpn0DmYiRBEDNn8ObvswOYLe6HIuaPfxtDnmMPeZGjh-zqWCNPp5qGKrJli2ngC5ysu8HuO8uRbx4yd5T21ZLZZHrX6Rk2unCG5gMnox1orXpxtDka3GgvaCkYLLmMQdmFNlAzy8J8tc3xuAsxKvIYOhMDbFKqVXPxL+7LNHANLtLAV3btnu1rpe7RzAi7g4oHxYSoYg6sTerDUVwNs2lWhq+9DzV5cuujj8+2w7ZrEvUf+4DlH3DeEraE02nz171y3ox0+imIWxqHaM89-9r26NAfy4xhHI7DMlY9U59b9XfNk7E81wLlOX2LYmLT9LP6TMM5x8z5drPaec9g+VsevPScgbw+zoXNDOxEdF-pwX8qJcUdwFRxYMv3slk+wrqDA4OPK826rxr6ODePu145vXbON2G7KZlk3L3cuWZZ9Zz3LGt0Oek154nDW0ca69674WZW8eunFz7+n1GA9WeZdbtjZXI8ORE-zpre2JOtYy+15DHvDt9dW5Nl3lAZvBp6keJPp5lv9aEUT-ewijGUEO2Sm+5zcjUsJE9qX6ewaB7l8Hw7v2GcB6wZDkPZGg1trh2gqvyPwduid7HljZq2sKwFudyvdfq8TZwbThvq-5se6xG31bmHbuO5jxTmhWOzMT49-fzvKvu+iL70aHdoPpck7ESOXm5tHGLPsPUCAIwBAM+D7PlCYsYBOKYl7K7BaHUJAG0BZrMAAOplSRBxAwimIICNQ4AoBPgYBEDZQiyoSMI3B3APD5yejoGaSiAcHKgiwAgmLfDQxIB8BTDqY4AEAsDOAzBwGsAcDcC8D8BCBiASBSAyByAKBKCqDqBaA6B6CGAiQmBmCeDWC2D2CODOBuAeCWA+AaHSxBBwAhDhBBDRCxAJBJDITpCZDZCEgFCWDWHBBhARDsDVAIAADEz4AAzGkAAGx1CgAUGODEAoGnC5hGhb7jB5BEBChdgACqKAAAjhPlYpqD2P0m2rMCLNoGbJlKFJlOUSUGkCFJqGkCLIAbSMkVFGkRkQOAHgUSiEUY9CURAGUXnJlJ2FURFDUZ0HUSMQ0aLM0a0dzPwB0Z2F0fUSiBAOcHIbCHoCgHLDwkzu6i0X0ZSKUeMXQMMRsDqH0OlGMXnJMaFGkDMViHsAcRMCkcQAsdtMsZNOsQIJsRQDsW9iVHkRZggMFJAHFs0KuJiNvv0YMRUeFOcZcYOCcbcdMU0Y8c8eMK8e0R8fkSsRvN8cwL8dsf8LsQDj7CVKGMCECVyKCUwOCeiCKsUUcQMSccMVJgifgOlI5hJDcQOHcQ8bdi0XqPUN6jIvEXEXCFyDUMjLEYouOJSOWPQdcLcGpswb3KwSSJpFKaIKzjVkzC6i6mzEaLEQCvuNgGgKSNqdicqMaV4aaTYBaUEBwOODaQcEAA)

I have copied over the parsing code from this repository and added some test cases at the end to test various input strings. When you run the code, you can see that in two cases, only a single NameValuePair is produced instead of two.

**Comment by anuragc617** [comment]
@SvenEV This is an expected behaviour, if an override template parameter value contains value contains '{', '{', '\', '[' user needs to escape such characters.  Can you try passing the pipeline variables enclosed with double quotes in override template parameters. Ex -> -param2 "$(variable2)". I have tried it out and it is working fine.

**Comment by SvenEV** [comment]
@anuragc617 
> Can you try passing the pipeline variables enclosed with double quotes in override template parameters

This is what we are already doing. We specify something like `-param1 "$(variable1)"` which I guess expands to something like
`-param1 "{"ClientId": "...", "ClientSecret": "abc[de", ...}"`.
I'm not sure if the inner quotes are automatically escaped like this:
`-param1 "{\"ClientId\": \"...\", \"ClientSecret\": \"abc[de\", ...}"`
But it does not matter anyway, the issue occurs in both cases as you can see in the sample code I linked.

I also tried escaping the bracket itself as follows, but it does not make a difference:
`-param1 "{"ClientId": "...", "ClientSecret": "abc\[de", ...}"`

**Comment by anuragc617** [comment]
@SvenEV can you please share the debug logs with `system.debug` set to `true` to confirm it is an issue in PoweShellParameters?

**Comment by SvenEV** [comment]
@anuragc617 Here's an excerpt from the debug logs (I removed some sensitive information):
```
...
2021-04-19T08:11:52.0567628Z ##[section]Starting: Deploy ARM Template
2021-04-19T08:11:52.0702070Z ==============================================================================
2021-04-19T08:11:52.0702450Z Task         : Azure resource group deployment
2021-04-19T08:11:52.0702995Z Description  : Deploy an Azure Resource Manager (ARM) template to a resource group and manage virtual machines
2021-04-19T08:11:52.0703377Z Version      : 2.184.1
2021-04-19T08:11:52.0703630Z Author       : Microsoft Corporation
2021-04-19T08:11:52.0704019Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
2021-04-19T08:11:52.0704527Z ==============================================================================
2021-04-19T08:11:52.0910173Z ##[debug]Using node path: C:\agents\2.184.2\externals\node10\bin\node.exe
2021-04-19T08:11:52.2687761Z ##[debug]agent.TempDirectory=D:\a\_temp
2021-04-19T08:11:52.2715925Z ##[debug]loading inputs and endpoints
...
2021-04-19T08:11:52.8746232Z ##[debug]Loading Parameters File.. D:\a\r1\a\<redacted>
2021-04-19T08:11:52.8747065Z ##[debug]Detecting file encoding using BOM
2021-04-19T08:11:52.8747810Z ##[debug]Unable to detect File encoding using BOM
2021-04-19T08:11:52.8748823Z ##[debug]Detecting file encoding without BOM
2021-04-19T08:11:52.8749782Z The detected encoding for file 'D:\a\r1\a\<redacted>' is 'utf-8'
2021-04-19T08:11:52.8772627Z ##[debug]Loaded Parameters File
2021-04-19T08:11:52.8777716Z ##[debug]Overriding Parameters..
2021-04-19T08:11:52.8790931Z ##[debug]Overriding key: <redacted>
2021-04-19T08:11:52.8791990Z ##[debug]Overriding key: <redacted>
2021-04-19T08:11:52.8793951Z ##[debug]Overriding key: _artifactsLocation
2021-04-19T08:11:52.8794939Z ##[debug]Overriding key: _artifactsLocationSasToken
2021-04-19T08:11:52.8795691Z ##[debug]Overriding key: instance
2021-04-19T08:11:52.8796454Z ##[debug]Overriding key: api-client-credential-default
2021-04-19T08:11:52.8797419Z There was an error while overriding 'api-client-credential-default' parameter because of 'SyntaxError: Unexpected token T in JSON at position 3', make sure it follows JavaScript Object Notation (JSON)
2021-04-19T08:11:52.8798371Z ##[debug]Overriding key: api-client-credential-no-permissions
2021-04-19T08:11:52.8799446Z There was an error while overriding 'api-client-credential-no-permissions' parameter because of 'SyntaxError: Unexpected token C in JSON at position 3', make sure it follows JavaScript Object Notation (JSON)
2021-04-19T08:11:52.8806430Z ##[debug][POST]https://login.windows.net/***/oauth2/token/
2021-04-19T08:11:52.8820991Z (node:3160) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2021-04-19T08:11:52.9714940Z ##[debug][GET]https://graph.windows.net/***/servicePrincipals?$filter=appId%2520eq%2520'***'&api-version=1.6
2021-04-19T08:11:53.0696571Z Starting template validation.
...
2021-04-19T08:16:45.4577143Z Successfully deployed the template.
2021-04-19T08:16:45.4580878Z ##[debug]task result: Succeeded
2021-04-19T08:16:45.4584218Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]
2021-04-19T08:16:45.4696683Z ##[section]Finishing: Deploy ARM Template
```

The "Override template parameters" field in the release definition contains these three parameters (and a few more):
```
-api-client-credential-default "$(api-client-credential-default)" -api-client-credential-no-permissions "$(api-client-credential-no-permissions)" -api-client-credential-only-tax-details "$(api-client-credential-only-tax-details)"
```

All three variables contain valid JSON. For example, the value for "api-client-credential-no-permissions" is `{"ClientId":"1234","ClientSecret":"abc[def"}`.

Note that the logs do not mention the parameter "api-client-credential-only-tax-details" because the parser "merged" it into the previous parameter due to the '[' character in the JSON. This is the same behavior that can be observed in the TypeScript playground.

**Comment by anuragc617** [comment]
@SvenEV thanks for sharing logs. This is not an issue in PoweShellParameters. It is failing in [castToType](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureResourceGroupDeploymentV2/operations/ResourceGroup.ts#L305) as it is going to case: string  because you would have defined ARM template parameters as string. If you define these ARM template params as object then it will work. I have tested it. Thanks

**Comment by SvenEV** [comment]
@anuragc617 It **is** an issue in PowerShellParameters. I think we are talking about two different issues here.

The error you see in the debug log is not directly related. I understand that defining the ARM template parameter as object or secureobject may prevent the error message. However, in [updateOverrideParameters(...)](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureResourceGroupDeploymentV2/operations/ResourceGroup.ts#L339) you can see that the code still proceeds when this error is logged. (In general it is quite odd that an ARM parameter of type string causes a JSON-related error. But as I said, this is a different topic.)

The actual issue occurs earlier in the parsing phase, i.e. at [PowerShellParameters.parse(...)](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureResourceGroupDeploymentV2/operations/ResourceGroup.ts#L326). Even though I cannot step through the code, the evidence is quite clear: There are three parameters specified in "Override template parameters", but only the first two occur in the debug log. The third one is missing. This clearly shows that the parser does not return the correct NameValuePairs. And this particular issue can be easily reproduced with the link in the issue description. Have you checked that link and can you confirm that the parsing behavior is unexpected?

**Comment by anuragc617** [comment]
@SvenEV sorry by looking at error logs I looked into different issue. For the issue you are pointing out in  PowerShellParameters.parse(...), this is an expected behaviour and user has to escape the special characters like double quotes by "\\".  
For your example try override parameters as:
-param1 "{\\"ClientId\\": \\"...\\", \\"clientSecret\\":\\"abc[as\\"\\}" -param2 "value2"` -param2 "value2"
Updated [typescript playground ](https://www.typescriptlang.org/play?#code/PTBQIAgBQQwJwM4EsB2BzCBjA9gEwKYQAuMA1vihAGZzYC24wEAFkUQA4IBcIaSRzAK4AjAHQ46wOkky0E2KkWAwAXoLj4AtOyTt8AG1T4EmkglIJgw-dmFSYCIvjjAAKg4vAAgmo0AlY2x1THwAcVpBdgARfHYbAE86CiIANQAmYGw9OBgiJGwUS1gcpKc4YoRnUSIERlBQVDKqGBCIADkYJJSYfUF8WCQ4CABvUAhxiBRO-C4IRzhUNABuMYmANx6+2fnFlYBfesx9BwRobAB3ZwBlZgN9Yumy09HV8cgK42JbuaIF9AgYChcBANEQ+oUAXAcvEIAoIOR4poNr1COwYINahMIOwRIZMD9cjJsfBKgAKVA4ojbX6LAA0IPwdGwa3wAEVBNgnAgAPyzYTYbD6fCA+nGTAwPQAYWY8BaZV5Pz+aAAlLMOl1Nv10XAANoAXRGryxECQVAgpIAhBaxRL8NLZZgysrDcbXV8kAhRDapTKco7nBAALwQb1231y5wrN0QA7RjZDDQIQT6KntabdFEDXUG4P6qNu+MmoH4AAeQYgAAZ867C7YAFZq9OarPl4aTaazABEnfpyK2EG7MZWRqxFMERHLY6I1QWdFJyuH0fOzCQQvNqAIZYAPEXKaIhegBM7RtGsYXDGUelFcjBywIPaIqBuADL8Zw9ckoSn0jelhcjgt4EmUsiAASWLMtgwvd99GvEhxHUDQUCIKBsGQPICmrU9CxlBArj0TAkB6e0-TKctoJyWCb1EXD8PwQjiPDf04CwuMgIonpJy-cdRCTYR5k-Td6RQEDwM3CBNCLTdlRnJA53-U8JlNc1709D11XwUkOP0elaIIoj9BIiM4GVY8AMU5TSXrUQpiSMzFMUxNk2nHEEGYKzhDrBSHOjetW3bJIux7CA+xmAdOyHczT1jHyJhAPj5moWg6Ck0sIAARmIbAGSZFkIAAck0fKiy+QhHHgPJ-jhbSot8zybOmci30o3iRAE9L6W0-cKDQI9WLdGLFIMSoXVi8ZrNCprL30frHOMZzRFc9z628sa-ODNtbLC7te01ILIp8g5aqUiDyxEkswNOgBqDLZpjepo0s6ytvshynJTRbBDcjyvLuwbjUsq0NFytkOS5V7FKobAhlJQstpK96iAh2LEZ1La9VESbg1R9HMc1UQNDiFpNOAAA9TtSVEAAqZVOwAEmAel8rp9L8tW6KoqO6NVK9BBxR9B0yODTsAANOyWCBIACSo2EWEM+dtLAmLKKLQXUShEawrm4qYK5nAMpAVE+ARUVlUoA3gaEssVRYjRxawiXKvJ8UqBYekNzS0RKfAnkbDVM21fVVRt-4T0AhN5pTctuzuyyvceZwEGR6MoZhwskHLKsTQgHd4-NxBusPZgJaQK6ruThy47Nn3E51JAMZe0axqxRGICu4XNAim685rxA64bxqboi8Xjtdf6fKr72nn7vGUQrsbW-b4kp9r+vZ76NuBwHO7o3HgbOYet01bgDXI+nGl5K1w-xntvECWd6gNwAMQxIhSR732039vos31YSOxDiqJuxp06nWDJodKd1U7mnTpnEuOdl4JwLgeXqxc25XSQPPAGZp37V2nmvLa1RsDPguM4SUDhNLOkDNQgK+AiEkMuHAchZJTLAInmAk0O83TCA0GQLh4w94CNVj7dWqUSxXyNJAGIQouSlUfogCc2BMCYHUICVocIP4BmUqWD0NQARAgZGCE+pwTYQAIDI-AwJQp21xI7EgD9zE11wSvRAft8AZh-oHPU-9AqAODhpDxWpBiGiioWRxTgxJpXAZA0JQFwmWMCWdZMM1r7GkgC-AxT4FGwmUaolAIRYlDHiZEyC7pPRPiBC-BRzikEIB8fgf8UVIBXBgHlW8OB2AwkBMCaRNcoqWWKadAAfMGCsWCsTxNwIk4MmiC4IDiDITSgyhIZWVDqCseo-qpJbiIk+ZiDA1ymZqCRWJ2ALA2E4e+RJ1LTC0s1Ho1IlS6QcHRBihllbOD5AKIUgJg78kFMKSgYdXTH0oNpdZOYaGFWKgAMhhRAC0el6IGSMsxCAcKTQIA6G0UkbRBB0GEM4O501TInImGcpAFyyr2KJBU3Ar5pqfm-FgRCyRULoXyCgLBOEXn6UYoLAMwZmj6EqFA6G5oJYqKhGytC-BOUIKnIXVBkrWXIXZXKgoZdxlKRwVOHUUqkIoVlRhFAkKt4RQAD4Wt3OOfVqqjUcoKGazsAAdIgnZtWumgaSFV0q1XGvlTuRVKCBC+sNeqk1Wq2HN0snqg1MrHWUBuulA0FphZbwxXG+1Eb5XJtTcLN1Hro3NwmDw4UpB+EcxLdrMaZa+Gj3uj5YahBY3cSIHav1DqNWmqDMLUkRbgWxXjf6xNd4VzlI3JKGwyB0AACE-TkEupuJl456TDq7SazeHUBy03Zj5JFbzUVC2IHAPolbBHGmbSaXVbaO3hoDU63tA4dQDobViddOaChjofHSqdsq50Lp9iUldRA13ZofUmjK9JOx6g9ZWrEB6UUfKGMGX4Z6G0XqxFe1tlI70Ju7c64Yr6S04EKAC-c2A0AgbwyOgjEBlRvomB+iD36J1Aj-TOtA86WiLuA1OMDnbP2Qe3Z2PYcHGPjEQ-y0igqT3ocOg27DN7cPMcTc6l13ZPVpOAOQWIEA0DYDlnkfQ+gymwhElgadxgJMssEyx1D47HyTunYsdknJ8B8bbQJ+9o7k3QY0+JktUn3kCpQ3J-A57FMipbcp21qm6M0M7PlYjzcQC6fYPpwz-xjOmdUuZwgRw0LWZI+B0dDmf3Of-WgNzESIIge8-hzdfmBzJb3Q5YLR7ZNoYixhqLI0cNxdKwl8rnpQydZMsW088XI1XXgxMDryG7ynp6yWyy035UjJtdOENzAtPRjrRWmzmGJjHfGNsk7wijFAtsz57tsx1sFGeXhPlIWZNwFmAt0LB0Lt23ObkalhJ8S-pcwBnjQG6v8Zu41zla6QdccA0jWYKB8WEqGIOrE3qw3Q6-UGttSrQ1Q9ozNrTA320PZ7TQwrnHuOYEXXt0tvDDsKabdF6965b3k+df2+n4xyesac+xuHNPeMQ684TjduaoM7sCw5U7IZWek5oxLx9iWX08-F0J-nwOqvC-B8uyHfPmswZl4pOXSn2cqaGyawjKWxp85GwL3AHHFi66XaWerGuWNG7E21sefWYsW8G3ZtTT7XWacm9Ge3ZTHfO-QDVjzovmWG6l2Hk3VaHLm+o5z0PrWI9uijzzbXnH4+eaT1byXInWuRZZ-12LZPy8q4d2N5D6vydlzm+MNbDfKCbeDT1I8efFIHY7422XB9LuiPJ2Sm+f3LlO1pZV4vYME-67F+T2HVX49YMx570duO9w7ax0TzlUb0dukV9nmhPNm+hdb939vNmu-B+7RAXveOdvq6xMPo7vWa8B6z93malTq5svurt-szvvBPnslPkaDWtiLPgDg-Dfm9tHGLPsPUCAIwBAM+D7PlCYsYBOKYl7K7BaHUJAG0O5rMAAOplSRBxAwimIICNSkZPgYBEDZQiyoSMI3B3APD5yejEGaSiDCHKgiwAgmLfDQxIB8BTCmY4AEAsDOAzBYGsAcDcC8D8BCBiASBSAyByAKBKCqDqBaA6B6CGAiQmBmCeDWC2D2CODOBuAeCWA+DGHSxBBwAhDhBBDRCxAJBJDITpCZDZCEgFCWBuHBBhARDsDVAIAADEz4AAzGkAAGx1CgCkaODEAEGnC5iSJMCDqQBYh5BEBChdgACqKAAAjsvlYpqD2HkQDG2rMCLNoGbJlKFJlK0SUGkCFJqGkCLA0XsLSA0QUUwEUfwKUQOPHrUSiPUViIUSdJSM0V0Z0JlJ2B0RFCsXQD0esX0aLIMcMViGfuMMUZMZ2NMb0SiBAOcJobCHoCgHLDwmDu6ocefk0RAC0XnGscMC6hplOkgMkKBLgL8Z2LMCCcIaICCfSCCUcACchHrLID7CCVwCCTAMIJgDqA4CCb8WJhJHnDsaFGkPsViEMSMQ0eMSUdtBcZNDcQIHcRQI8QjiVNUe5ggMFJAHls0KuJiDrI0UsR8VsWsRphsDqH0OlAFniWbASXsQMfMUwKSUcVFKcVSTUZcRvLScwPSQ8f8E8bTj7CVKGMCCyVyOyUwJyeiCKv0u8Z8W0QOMKTAKKfgOKYOFsdKSiESbKSdsMXqPUN6jIlkZkXCFyDUMjBkYouOJSOWFwdcLcCZnwb3AISSJpMGaIJDt1v5hpgxu+qEeRjYFRimcqVmUxjmUKBRlRkEBwOOAxgcEAA)example provided by you.

**Comment by SvenEV** [comment]
@anuragc617 Thanks for your patience with this! I can now confirm that escaping the double quotes solves the issue.

What I think is unfortunate is the fact that escaping is not needed in most cases, only in edge cases like the one I presented (opening, but no closing bracket). But the conclusion for me is that, to be on the safe side, we should always escape double quotes.

I'd suggest to document this somewhere so that others are aware of it.
