### ISSUE TITLE
[UniversalPackages@0] Support cache directory when downloading

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/azure-pipelines-tasks#14784]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**
*Type*: Feature

**Enter Task Name**: UniversalPackages@0

## Environment

Sorry, but I don't think I can share this...

## Issue Description

The UniversalPackages task leverages artifacttool.exe to do the actual downloading, which supports caching through the `--cache-directory` argument or `ARTIFACTTOOL_CACHEDIRECTORY` environment variable. We plan on using a long-lived private agent to download very large universal packages with significant duplication, so being able to leverage the artifacttool cache would really help us out here.

The feature request is: **Add an option to the UniversalPackages task that controls the cache directory**.

**Comment by 50Wliu** [comment]
Still relevant.

**Comment by 50Wliu** [comment]
Still relevant.

**Comment by 50Wliu** [comment]
Still relevant.

**Comment by sandeep-ma** [comment]
Why does no one from MS respond to these performance issues with UniversalPackages@0? 

Only the robots come and close them while no human responds. Same thing happened to #13120. And it has been in version 0 for years. 

Please reopen and jack up the priority. 

Our critical deployment pipelines have multiple internal timeouts and take few extra hours as the artifacttool keeps getting downloaded again and again with each call to the task. Moreover, why is it downloaded from this unreliable and slow host in version 0? Please put in a high performance CDN since it is for customer use, not just internal employees. 

When will UniversalPackages task exit from beta?

**https://05xvsblobprodcca13.vsblob.vsassets.io/artifacttool/artifacttool-linux-x64-Release_0.2.350.zip?sv=2019-07-07&sr=b&sig=-REDACTED-&spr=https&se=2024-09-19T18%3A04%3A25Z&sp=r&P1=1726768765&P2=11&P3=2&P4=UcXCjTQVYVbMnQczE3Ywp7OyILxI0hRKV5IuBEMQJKE%3d**

**Comment by sandeep-ma** [comment]
Could someone help clarify why it takes 2 minutes just for the task to start? It is downloading it's own artefact tool for 2 minutes while the download of the actual artefact which is much larger is a few seconds. And the website hosting the artefact tool zip file is not at all stable and we get frequent timeouts which results in it taking even longer. We do not have such performance issues with DevOps and Azure, only with **vsblob.vsassets.io**

See this log from pipeline below where it took two minutes to just download the artefact tool. As we have this task hundreds of times in the pipeline, it adds up to 2 to 4 hours just spent on downloading this artefact tool while the pipeline only takes one hour apart from that.
 
2024-09-19T1**8:55:03**.3065217Z Downloading: https://05xvsblobprodcca13.vsblob.vsassets.io/artifacttool/artifacttool-linux-x64-Release_0.2.350.zip?sv=2019-07-07&sr=b&sig=-REDACTED-&spr=https&se=2024-09-19T19%3A55%3A06Z&sp=r&P1=1726775406&P2=11&P3=2&P4=34eqpKL8iy1RCRqkfPe8u3Vbgf%2fMBak2YQQe8O6AVfU%3d
2024-09-19T**18:56:45**.3860670Z Caching tool: ArtifactTool 0.2.350 x64
