### ISSUE TITLE
Handshake connection timeout in SSH setting does not change timeout

### ISSUE THREAD

**Issue by tohewi** [microsoft/azure-pipelines-tasks#14823]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SshV0

## Environment
- Server - Azure Pipelines
    - Account: outokumpu
    - Project: Outokumpu business object library
    - Pipeline: Deploy ShinyApp
    - any release on any build.

- Agent - Hosted or Private: 
    - private agent
    - Windows 2019
    - 2.183.1

## Issue Description
SSH task Time Out Setting for SSH Handshake does not seem to affect timeout. Handshake times out in 20 seconds independent of the value entered into Advanced parameter "SSH handshake timeout"
![image](https://user-images.githubusercontent.com/82122655/117570296-237dcd80-b0d2-11eb-89d5-70e4dfd5b9cb.png)

### Task logs
[ReleaseLogs_6.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6447368/ReleaseLogs_6.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by DenisRumyantsev** [comment]
Hey @tohewi, It seems that this issue is related to some intermediate error, not to the SSH task itself since this error is related to the fact that the task cannot connect to the remote host. So could you please re-check that authentication data in the service connection is correct and share more details about the remote host and your environment? 

Also, it will be great if you can provide a sample for repro it may speed up our investigation.

**Comment by DenisRumyantsev** [comment]
Hi @tohewi, is this issue still actual to you?

**Comment by DenisRumyantsev** [comment]
@tohewi, for now, I am closing the issue. Feel free to reopen it if you still have trouble with this task.
