### ISSUE TITLE
How to exclude stages from a release in Azure DevOps?

### ISSUE THREAD

**Issue by msrinivascharan** [microsoft/azure-pipelines-tasks#14888]
I have a CD pipeline in Azure DevOps. There are total 4 stages in my pipeline, stage1-qa1, stage2-qa2, stage3-qa3 and finally stage3-production deployment. stage3-qa3 not applicable for some app features in a particular release

My requirement is, sometimes, for a particular release I have to exclude qa3 stage and include/run only qa1 and qa2 and production deployment stages.

How to achieve this in Azure DevOps ?

Note: I tried option Azure DevOps -> Organization settings -> Pipelines -> Settings -> “Disable stage chooser”, issue is, it is useful with only YML based multi stage pipelines, not with classic editor based pipelines.

**Comment by rohit-batra** [comment]
Hi , 
This is pipeline task repo. issue is not related to tasks per say. For any release related issues,  You can send a mail to rbatra[at]microsoft[dot]com or for any azure devops related questions.  and i will try to get the right person involved. (on Pipelines side)

Feature to allow Cherry picking stages (for automated triggers) based on some releases is not possible. You can right some scripts and add them at the start of the stage to facilitate that stage's execution or skipping .
If stages are automated or depended on other stages , they will follow the same order defined and wont get auto skipped.
You can select manual deploy trigger on stages rather than automated/Stage dependent when defining release definition or while creating a release, and then deploy only the stages you want for a particular release to get the desired behavior. 

Thanks
