### ISSUE TITLE
Maven V3 - JaCoCo - Sonar - Maven - Multimodule

### ISSUE THREAD

**Issue by Jispry** [microsoft/azure-pipelines-tasks#15233]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: MavenV3

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/MavenV3

## Environment
 - Azure Pipelines

## Issue Description

Maven Multimodule project with JaCoCo and Sonar option

```yaml
- task: Maven@3
    inputs:
      mavenPomFile: pom.xml
      goals: verify
      options: -B -Drevision-suffix=$(Build.BuildNumber)
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      codeCoverageToolOption: 'JaCoCo'
      codeCoverageClassFilesDirectories: [valid options set]
      codeCoverageSourceDirectories: [valid options set]
      javaHomeOption: JDKVersion
      jdkVersionOption: '1.11'
      mavenVersionOption: Default
      mavenOptions: -Xmx3072m
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: true
      isJacocoCoverageReportXML: true
      sqMavenPluginVersionChoice: 'latest'
```

The Coverage is only processes for 1 child module, other modules have 0%

Additional information could be found on Sonar community pages:
* https://community.sonarsource.com/t/jacoco-code-coverage-from-maven-doesnt-work-anymore-azure-devops/29714/15
* https://community.sonarsource.com/t/incomplete-jacoco-code-coverage-in-multimodule-maven-project/34910
* https://community.sonarsource.com/t/devops-maven-multimodule-project-reporting-incorrect-code-coverage/36329/7
### Task logs

for all child modules
```
[INFO] 07:10:15.241 Importing 1 report(s). Turn your logs in debug mode in order to see the exhaustive list.
[DEBUG] 07:10:15.245 Reading report '[valid path]/CCReport43F6D5EF/jacoco.xml'
[INFO] 07:10:15.272 Sensor JaCoCo XML Report Importer [jacoco] (done) | time=37ms
```

**Comment by Jispry** [comment]
> Hello, can't reproduce your problem. Could you provide please your pom.xml file. Also could you please set an additional variable System.Debug=True and give the full log output.

Hello Alexander please take a look at this post

> I confirm JaCoCo configuration through Azure interferes with the manual JaCoCo configuration from pom.xml, and does not support both multi-modules and SonarCloud analysis.

https://community.sonarsource.com/t/devops-maven-multimodule-project-reporting-incorrect-code-coverage/36329/4

I do not have any sonnar/jacoco settings in parent nor child pom.xml files. I totally rely on the MavenTask. We have Sonar Version 9.1

As mentioned in the initial post and log the scanner picks up the aggregated summary file(`CCReport43F6D5EF/jacoco.xml`) when running on every maven submodule.
```shell
[INFO] 07:10:15.241 Importing 1 report(s). Turn your logs in debug mode in order to see the exhaustive list.
[DEBUG] 07:10:15.245 Reading report '[valid path]/CCReport43F6D5EF/jacoco.xml'
[INFO] 07:10:15.272 Sensor JaCoCo XML Report Importer [jacoco] (done) | time=37ms
```
But the resulting Coverage report in Sonar only incorporates coverage report from last submodule run and others have 0%

Additionaly `sonar.jacoco.reportPaths` is deprecated (https://community.sonarsource.com/t/sonar-jacoco-reportpaths-removed-in-7-9-4-instead-of-8-2/33376)
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MavenV3/maventask.ts#L315
```typescript
    // Apply argument for the JaCoCo tool, if enabled
    if (typeof execFileJacoco != "undefined" && execFileJacoco) {
        mvnsq.arg('-Dsonar.jacoco.reportPaths=' + execFileJacoco);
    }

    if (isJacocoCoverageReportXML && summaryFile) {
        mvnsq.arg(`-Dsonar.coverage.jacoco.xmlReportPaths=${summaryFile}`);
    }
```

**Comment by Jispry** [comment]
@AlexanderBadalov was the provided information useful ?

**Comment by Jispry** [comment]
@AlexanderBadalov @alexander-smolyakov any news ?

**Comment by ackermangrace** [comment]
I am having the same issue. What's happening is when the `codeCoverageToolOption: 'JaCoCo'` is set, it automatically injects `-Dsonar.jacoco.reportPaths=/home/vsts/work/1/s/CCReport43F6D5EF/jacoco.exec` into the Maven command that is run in the pipeline, even if the `isJacocoCoverageReportXML: true` is also set in the Maven task. This causes the exec file to be sent over to Sonar regardless (and Sonar can no longer use the exec format).

**Comment by baincd** [comment]
Here is a workaround for getting full code coverage in SonarQube for multi-module maven projects.  

(Disclaimer: I am no way affiliated with Microsoft.  I am sharing this information and workaround for anyone who may find it beneficial.  YMMV)

### Background

In the [Maven Azure DevOps task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops), when `codeCoverageToolOption: JaCoCo` is set the task modifies the POM before building- adding the [jacoco:prepare-agent](https://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html) and [jacoco:report](https://www.eclemma.org/jacoco/trunk/doc/report-mojo.html) goals and configuring the paths jacoco uses (destFile, dataFile, and outputDirectory) to absolute paths.

The jacoco-maven-plugin normally writes the native Jacoco file (jacoco.exec) and reports (XML, HTML) under each module's target directory, but because the Maven Azure DevOps task configures the plugin to use  absolute paths for all these files, the same path is used for *each module*.  The plugin does append to jacoco.exec, and therefore it will contain code coverage for all modules.  However the plugin overwrites the reports for each module, and therefore the XML report will only contain the code coverage for the last module built.

SonarQube [stopped supporting using jacoco.exec for code coverage in 8.2](https://community.sonarsource.com/t/lts-7-9-3-jacoco-exec-coverage-not-longer-supported/23225/8), and instead the XML report should be used (which the Maven task will configure on the command line when `isJacocoCoverageReportXML: true`).  However, as noted above the way the Maven Azure DevOps task configures jacoco-maven-plugin to the build, the XML report will only contain coverage for the last module built.

To summarize:

| SonarQube | Maven Projects |Maven Pipeline Task | How it works |
| --- | --- | --- | --- |
| < 8.2 | all | `codeCoverageToolOption: JaCoCo` | Uses absolute-path jacoco.exec |
| 8.2+ | single-module | `codeCoverageToolOption: JaCoCo`<br/>`isJacocoCoverageReportXML: true` | Uses absolute-path jacoco.xml |
| 8.2+ | multi-module | N/A | Does not work |


### Workaround

One workaround is, instead of having the Maven task add and configure the jacoco-maven-plugin to the project before it builds, to add it to the project yourself.  This way, you can leave the paths (destFile, dataFile, and outputDirectory) as their default, and the plugin will generate the coverage in each module's target/ directory.  And the sonar-maven-plugin will by default use the Jacoco files in their default locations, resulting in code coverage being reported for all modules.

1. Remove `codeCoverageToolOption: JaCoCo` from the Maven Azure DevOps Task

2. Add the Jacoco plugin prepare-agent and report goals to the parent pom.xml (if you don't want to have jacoco always run by default, add the plugin under profiles/profile then enable in maven with the option `-Pprofile-id` )

```xml
<plugin>
    <groupId>org.jacoco</groupId>
    <artifactId>jacoco-maven-plugin</artifactId>
    <version>0.8.7</version>
    <configuration>
      <!-- any necessary Jacoco configuration... -->
    </configuration>
    <executions>
        <execution>
            <id>jacoco-prepare-agent</id>
            <goals>
                <goal>prepare-agent</goal>
            </goals>
        </execution>
        <execution>
            <id>jacoco-create-report</id>
            <goals>
                <goal>report</goal>
            </goals>
            <phase>test</phase>
        </execution>
    </executions>
</plugin>
```

The Sonar plugin will automatically find the code coverage from the default jacoco locations under each modules target/site/jacoco/jacoco.xml.

#### Azure DevOps Published Code Coverage

Note that, while this workaround will fix code coverage in Sonar, code coverage will not be published to Azure DevOps.  This has no effect on SonarQube, but may be undesirable.

You can use the Azure DevOps Publish Code Coverage Task, however this task [only supports publishing a single code coverage report](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops#is-code-coverage-data-merged-when-multiple-files-are-provided-as-input-to-the-task-or-multiple-tasks-are-used-in-the-pipeline).  Therefore, you must first merge the Jacoco code coverage into a single report.

1. Create a new code-coverage-merge module that uses the maven-antrun-plugin to run the [Jacoco Ant report task](https://www.eclemma.org/jacoco/trunk/doc/ant.html#report) to create a merged report contains code coverage of all the modules

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.company.awesome-app.pipeline</groupId>
  <artifactId>code-coverage-merge</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Awesome App Code Coverage Merge</name>
  <description>Merge Code Coverage from all modules</description>
  <properties>
    <maven.install.skip>true</maven.install.skip>
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>1.8</version>
        <executions>
          <execution>
            <phase>generate-resources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <echo message="Generating JaCoCo Reports" />
                <taskdef name="report" classname="org.jacoco.ant.ReportTask">
                  <classpath path="{basedir}/target/jacoco-jars/org.jacoco.ant.jar" />
                </taskdef>
                <report>
                  <executiondata>
                    <file file="${project.basedir}/../awesome-app-module1/target/jacoco.exec" />
                    <file file="${project.basedir}/../awesome-app-module2/target/jacoco.exec" />
                    <file file="${project.basedir}/../awesome-app-module3/target/jacoco.exec" />
                  </executiondata>
                  <structure name="Jacoco report">
                    <group name="awesome-app-module1">
                      <classfiles>
                        <fileset dir="${project.basedir}/../awesome-app-module1/target/classes" />
                      </classfiles>
                      <sourcefiles encoding="UTF-8">
                        <fileset dir="${project.basedir}/../awesome-app-module1/src/main/java" />
                      </sourcefiles>
                    </group>
                    <group name="awesome-app-module2">
                      <classfiles>
                        <fileset dir="${project.basedir}/../awesome-app-module2/target/classes" />
                      </classfiles>
                      <sourcefiles encoding="UTF-8">
                        <fileset dir="${project.basedir}/../awesome-app-module2/src/main/java" />
                      </sourcefiles>
                    </group>
                    <group name="awesome-app-module3">
                      <classfiles>
                        <fileset dir="${project.basedir}/../awesome-app-module3/target/classes" />
                      </classfiles>
                      <sourcefiles encoding="UTF-8">
                        <fileset dir="${project.basedir}/../awesome-app-module3/src/main/java" />
                      </sourcefiles>
                    </group>
                  </structure>
                  <html destdir="${project.build.directory}/site/jacoco" />
                  <xml destfile="${project.build.directory}/site/jacoco/jacoco.xml" />
                  <csv destfile="${project.build.directory}/site/jacoco/jacoco.csv" />
                </report>
              </target>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>org.jacoco.ant</artifactId>
            <version>0.8.7</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
</project>
```

2. Choose one of the following to create a merged code coverage report with this new module
    - Add the code-coverage-merge module as a module in the aggregator project
    - Add the code-coverage-merge module as a module in a profile in the aggregator project, and active the profile with -Pprofile-id
    - Add a separate Maven task in the pipeline to run the code-coverage-merge module

3. Add a pipeline task to publish the merged XML report to Azure DevOps

```yaml
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Merged Code Coverage'
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: $(System.DefaultWorkingDirectory)/code-coverage-merge/target/site/jacoco/jacoco.xml
    reportDirectory: $(System.DefaultWorkingDirectory)/code-coverage-merge/target/site/jacoco
```
