### ISSUE TITLE
Cannot Access Secret Variable with a name reference form other variable (indirection)

### ISSUE THREAD

**Issue by doanminhtu** [microsoft/azure-pipelines-tasks#15348]
**Question/ Feature**  
I want to access secret variable as reference or indirection way like bash (access the secret environment with the name is from a variable).

## Issue Description
In Azure Key Vault, I have  secret name `my-storage-key`.
In pipeline, I have an environment variable:
`secret_name=my-storage-key`
I could easily access these information:
```
echo $my-storage-key  # output: ***
echo $secret_name      # output: my-storage-key
```
### Expectation
In normal bash, we have something call indirection variable, we can get value of "my-storage-key" by calling:
`echo ${!secret_name}`  which is equal to `echo ${my-storage-key}`

### Issue
However, I could not do this in azure pipeline command line task. I have already tried these ways, but nothing work.
#### Call it like indirection in bash
```
echo $(!secret_name)
echo ${!secret_name}
```
Both of them output nothing.

#### Using eval
```
eval 'tmp=$('$secret_name')'
echo $tmp
```
Error: my-storage-key command not found.
That means, the eval could work and call `$(my-storage-key)` but it understood my `my-storage-key` as a command, instead of secret variable.

## Why I need this feature?
I know that I can map secret environment or something like that. But I want to access the secret environment with the name is from an other variable.
The reason I want to use this method is to reduce the variable I have to declare in YAML pipeline. I kept a file containing lots of secret name, then I read the file line by line to get the secret name. Finally, gather value from the previous given name.

**Comment by anatolybolshakov** [comment]
Hi @doanminhtu this repo is mostly for pipeline tasks related issues - I would suggest to open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it.
Not really sure if this scenario is supported somehow.

**Comment by ransagy** [comment]
I've come across the same thing - essentially, I wanted to create a task group that can be reused where you would pass in the names of the secrets to download from KV and then the rest of the pipeline could use them via env vars or the like - Rather than having the explicit names in design time.

The KV test doesn't seem to have an output variable/reference name either.

As it seems something more specific to the KV task - is this not the right forum for it?

**Comment by anatolybolshakov** [comment]
@doanminhtu I'm closing this at the moment as external here - please let us know if you have any other questions.
@ransagy this seems to be more likely related to how secrets are being tasks rather than task itself - but you can also open a ticket for task itself if you see that there is some possible task related issue (you can also ping owners of this task using [codeowners](https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/CODEOWNERS) page)
