### ISSUE TITLE
Execute Git commands using token of a GitHub Service Connection

### ISSUE THREAD

**Issue by ranikamadurawe** [microsoft/azure-pipelines-tasks#15466]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Bash@3  

## Environment
- Server - Azure Pipelines

- Agent - Hosted
   
## Issue Description
I am currently using an Azure DevOps pipeline to trigger a terraform plan against an existing infrastructure.

Within this pipeline during the terraform init stage, terraform will analyze the scripts and download modules from an external repository. During the initial stage of running this pipeline we encountered the following error.

```
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
This can be resolved using a PAT as follows, The mentioned command will be executed before any of the Terraform commands are executed

```
git config --global url."https://$(GITHUB-USER-ACCT):$(GITHUB-PERSONAL-ACCESS-TOKEN)@github.com".insteadOf https://github.com
```
Is it possible to change this to an OAuth token of a GitHub Service connection instead, Similar to how `System.AccessToken` can be used to run git commands against a repository hosted in Azure Devops. I have configured and installed the AzurePipeline Application on the repository which the pipeline would access and created a service connection. The same service connection is used to access the repository that holds the Azure devops pipeline.

**Comment by anatolybolshakov** [comment]
Hi @ranikamadurawe as far as I know service connections are not designed to work this way - variables approach would be more appropriate here. Although for more details I would suggest to open a ticket in https://developercommunity.visualstudio.com/search?space=21 - since this repo is mostly for pipeline tasks - but this question is more about service connections.
Closing this here since it's not related to the tasks itself - please feel free to ask any further questions.
