### ISSUE TITLE
Android signing – Support Task groups

### ISSUE THREAD

**Issue by CarMatt** [microsoft/azure-pipelines-tasks#15472]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Android signing

## Issue Description

We use Android Signing Task to sign all our apps (Task group), so we parameter set all inputs, including keystore filename. from version 2 you can only put explicit keystore file (from secure file area) in this task.

Feature - ability to set only the name of the keystore file (as a parameter) and the job finds the correct keystore file from the secure files area.

**Comment by anatolybolshakov** [comment]
Hi @CarMatt sorry for the delay - at the moment 'keystoreFile' input of AndroidSigningTask has 'secureFile' type - which is not supposed to work this way (I believe there are security concerns to work it like this). Since this is related to more generic issue with secureFile task input types - could you please open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by anatolybolshakov** [comment]
Closing this at the moment here since it's not related to the issue with task itself - please let us know if you have any other questions.
