### ISSUE TITLE
Question: How to resolve “Unable to fetch script status due to timeout.” error when run script in pipeline?

### ISSUE THREAD

**Issue by yorkzhang** [microsoft/azure-pipelines-tasks#15893]
I encountered error"[error]Error: Unable to run the script on Kudu Service. Error: Error: Unable to fetch script status due to timeout. You can increase the timeout limit by setting 'appservicedeploy.retrytimeout' variable to number of minutes required." 
I wonder how to change this timeout? 

Thanks.

**Comment by denis-tikhomirov** [comment]
@yorkzhang, please specify which task do you use?

**Comment by denis-tikhomirov** [comment]
It looks like message "[error]Error: Unable to run the script on Kudu Service. Error: Error: Unable to fetch script status due to timeout. You can increase the timeout limit by setting 'appservicedeploy.retrytimeout' variable to number of minutes required." is applicable for ArtifactsAndLibraries's tasks.

@pipeline-environment-team for assistance

**Comment by awesid** [comment]
@denis-tikhomirov I am facing the same issue when trying to deploy an App Service

**Comment by yorkzhang** [comment]
@denis-tikhomirov The task name is "Azure App Service deploy".

**Comment by aawad-ctelecoms** [comment]
any updates on this issue?

**Comment by stuti24m** [comment]
facing this issue while deploying to webapp using the task "Azure App Service deploy", trying to run a post-deployment script - npm install

**Comment by deenairn** [comment]
We're also seeing this recently. I don't think this issue is stale, just nobody from @microsoft/pipeline-environment-team has responded.
