### ISSUE TITLE
Caching in Azure DevOps Server

### ISSUE THREAD

**Issue by bitbonk** [microsoft/azure-pipelines-tasks#15919]
**Question, Bug, or Feature?**  
*Type*: Feature

**Task Name**: Cache  

## Environment
- Server - Azure DevOps Server 2020 Update 1.1
- Agent - Private: v2.181.2 on Windows Server 2019

## Issue Description

I just learned (https://github.com/microsoft/azure-pipelines-tasks/issues/13937) that the Cache task is not available on Azure DevOps Server. What would be the official or preferred way to cache assets created by a pipeline run across multiple runs of different pipelines? If there is none, are there any plans to support the Cache task on Azure DevOps Server too?

**Comment by bitbonk** [comment]
Can you give us a hint how to cache assets between pipelines runs then?

**Comment by bitbonk** [comment]
@leidegre Can you give us a hint how to properly cache assets between pipelines runs then?

**Comment by bitbonk** [comment]
@johnterickson Can you give us a hint how to cache assets between pipelines runs then?

**Comment by johnterickson** [comment]
Most self-host agents for on-premises deployments are not re-imaged between runs.  Assuming, so, all package managers AFAIK can be configured to cache packages in a particular folder.  You can configure that to point to a directory that does not get scorched between runs.

**Comment by bitbonk** [comment]
Yes for package managers this is no problem but not all assets can be retrieved via package managers, like for example the postgres binaries, vcredist or sometimes even the .NET SDK.

**Comment by InternetPseudonym** [comment]
> Yes for package managers this is no problem but not all assets can be retrieved via package managers, like for example the postgres binaries, vcredist or sometimes even the .NET SDK.

Binaries do not belong to the inventory of package managers - like: at all. If you mix these two concepts you probably should re-think almost everything regarding your build & deployment - system because you're doing it wrong.

**Comment by bitbonk** [comment]
An agent runs many different pipelines for many different products. Each pipeline has a set of dependencies needed to build the artifacts. Some of those dependencies are *not* managed by a package manager and never could be. 

The pipeline's tasks is to get these dependencies because it knows best what it needs to build its artifacts.

These dependencies that a pipeline fetched should be cached so a subsequent run of the same pipeline does not have to do the expensive fetching of the dependencies again.

It does not make sense to install or update the build agent each time a new pipeline comes along or an existing pipeline is changed. The pipeline should fetch the stuff it needs and then cache it.

I am surprised to learn that Azure DevOps Server does not have means built in to do just that.

**Comment by InternetPseudonym** [comment]
> An agent runs many different pipelines for many different products. Each pipeline has a set of dependencies needed to build the artifacts. Some of those dependencies are _not_ managed by a package manager and never could be.

And exactly there is your problem - projects which uses dependencies which cannot be managed are erroneous by design. Simple as that. They need to be rewritten. Porting legacy code over to "modern" CI/CD sometimes can be difficult and time-consuming. Welcome to the world of DevOps.

> The pipeline's tasks is to get these dependencies

No - not at all.

> because it knows best what it needs to build its artifacts.

No, only projects / repositories themselves "know" anything about dependencies - by design.

> I am surprised to learn that Azure DevOps Server does not have means built in to do just that.

Literally no other CI/CI-platform or package manager on the world has the means to pull non-dependencies into the current dependency-tree. Because that doesnt make any sense.

**Comment by bitbonk** [comment]
One example:

The artifacts that are being built by a pipeline is an application that needs a local postgres server to run. The installer of the application (that is also built by the pipeline) will unpack these postgres binaries so the application can start an instance of it. The app installer will also install a specific version of the Visual C++ redistributable binaries.

The usual idiomatic way to solve this is to make the pipeline download these binaries once from the official download location at postgresql.org and microsoft.com and cache it and then build them into the artifacts (embed them in the installer).  

This simple and effective solution worked just fine in Azure DevOps Cloud but is tedious to do in Azure DevOps Server.

**Comment by InternetPseudonym** [comment]
> The artifacts that are being built by a pipeline is an application that needs a local postgres server to run. 

Thats the next design error right there - applications never should need anything "local". It needs to be rewritten.

> The app installer will also install a specific version of the Visual C++ redistributable binaries.

see above.

> The usual idiomatic way to solve this

... does not exist because only very few, if anyone professionals create that kind of deployment - which seems to be a semi-permanent system modification on EACH AND EVERY RUN. Thats unnecessary and honestly pretty weird

> This simple and effective solution worked just fine in Azure DevOps Cloud but is tedious to do in Azure DevOps Server.

Because these two products are inherently different. Cloud services spins up entirely new build-VMs each time; because the VMs are highly optimized and deployment of each image has exact, tested dependencies it does so within few minutes, sometimes even less than 1. This is obviously not the case with on-premise solutions which require the DevOps team / developers to CREATE THEIR OWN ARCHITECTURE around VM-deployment. If you want to avoid that ... use the cloud services.

**Comment by jackmorizo** [comment]
> This is obviously not the case with on-premise solutions which require the Ops team / DevOps team / developers to CREATE THEIR OWN ARCHITECTURE around VM-deployment. If you want to avoid that ... use the cloud services.

I think the issue here is not the fact that DevOps teams need to create their own architecture but the fact that the very creation of the architecture it self is made hard by design. Let me elaborate. We have all that awesome documentation and those awesome certifications programs for azure devops only to find out that essential features like caching are are not supported by the on-premise solution. 

To me this sounds like a reason to switch from azure devops to gitlab ... I'm disapointed since I like the Azure-Ecosystem

**Comment by zleight1** [comment]
Ran into this again after investigating this about a year ago. 

(So now while the builds are reloading the modules I have time to write this comment...)

Does anyone have any workarounds? 

I had some ideas for providing a sidecar/volume to the agent images and then basically just reimplementing the cache task... but it seems silly to reinvent the wheel here.

Which begs the question, why such feature parity between the managed and cloud solutions? What's the strategy here for this?

There are many valid uncontrollable reasons why some customers need to manage their own instances (and pay quite nicely for it) and it just seems the feature differences are growing with every release. 

This a really basic and super impactful feature literally saving time (and money) and there's no solution or even a recommended workaround.

Is there any roadmap that includes this, or could be upvoted somehow to get some traction?

**Comment by InternetPseudonym** [comment]
> Which begs the question, why such feature parity between the managed and cloud solutions? What's the strategy here for this?

The strategy: extend Azure cloud way beyond Azure server and drop server immediately afterwards. The simply want to make more money - which is perfectly doable with "real" cloud products, hosted by Microsoft but not at all with self-hosted ones - in fact the self-hostes solutions always generate additional *spendings* in the long run. Thats why ;-)

**Comment by InternetPseudonym** [comment]
The cache task has been released for Azure 2022 - its missing a very important option to set the cache storage path ... but at least its usable

**Comment by florinciubotariu** [comment]
On `AzureDevopsServer_20240806.7`, if the pipeline contains the Cache@2 task then I receive the following error right from the start of the run.
`##[error]TF400734: This service is only available in hosted Azure DevOps.```
Agent version is 3.238.0

So I suppose it still unsupported.
