### ISSUE TITLE
different actions in 20220227.1 azure-cli 2.33.1 and 20220306.1 azure-cli 2.34.1

### ISSUE THREAD

**Issue by AiHaibara** [microsoft/azure-pipelines-tasks#16018]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Azure CLI@2

## Environment
- Agent - Hosted or Private: 
    
```
    Agent name: 'Hosted Agent'
    Agent machine name: 'fv-az302-113'
    Current agent version: '2.200.2'
    Operating System
    Virtual Environment
    Environment: ubuntu-20.04
    Version: 20220227.1
```
20220227.1 use the azure cli version 2.33.1
```
    Agent name: 'Hosted Agent'
    Agent machine name: 'fv-az102-467'
    Current agent version: '2.200.2'
    Operating System
    Virtual Environment
    Environment: ubuntu-20.04
    Version: 20220306.1
```
20220306.1 use the azure cli version 2.34.1
## Issue Description
az storage blob upload-batch

2.34.1 recognized arguments: --overwrite if i don't use overwirte, it will tips me blob exists error.
but the 2.33.1 has the ERROR: unrecognized arguments: --overwrite, if i don't use overwrite, it successfully.
is this are a break change for the default action(overwrite)?

and some Microsoft-Hosted agent are 2.33.1, some Microsoft-Hosted agent are 2.34.1 in 2022/03/10
should i always upgrade az? or just caused by agent are upgrading?

### Error logs

2.33.1 has the ERROR: unrecognized arguments: --overwrite

2.34.1 without --overwrite
ERROR: The specified blob already exists.
RequestId:773f41df-f01e-007b-7158-348947000000
Time:2022-03-10T08:27:11.0284194Z
ErrorCode:BlobAlreadyExists

**Comment by mattmiller85** [comment]
Same problem here, build failed last week on 3/10 because the az blob upload command couldnt overwrite an existing blob without the --overwrite flag.  So, I added it thinking I'd be good.  Then, today, the cli version is back down to 2.33 in the hosted agents and failing because it doesn't know about the --overwrite flag: 
From today
<img width="636" alt="image" src="https://user-images.githubusercontent.com/1819787/158235898-a98d7c04-d0db-40eb-905d-0e6de7f61ccf.png">
From 3/10:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/1819787/158236053-7f5a6e22-9dfc-40da-8f08-337e3895541c.png">

**Comment by BorisWilhelms** [comment]
We also ran into this issue and simply extended our Azure CLI script to check the version.

```
      VERSION=$(az version --output yaml | grep "azure-cli:" | cut -d ' ' -f2)
      OVERWRITE=$([ "$VERSION" == "2.33.1" ] && echo "" || echo "--overwrite true")
      az storage blob upload-batch -d XXX --account-name XXX -s XXX $OVERWRITE
```

Sure, thats properly not 100% save, but it does work for us.

**Comment by stroborobo** [comment]
pscore version:

```powershell
$azversion = az version | ConvertFrom-Json
$overwrite = if ($azversion.'azure-cli' -like "2.33*") { "" } else { "--overwrite" }
```
