### ISSUE TITLE
[GoToolV0] Go 1.18 not available

### ISSUE THREAD

**Issue by eqinox76** [microsoft/azure-pipelines-tasks#16043]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: 
GoToolV0

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    xtp/Development/Pipelines/XTP.TCA.BenchmarkServer/
- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name:
Pool: Azure Pipelines
Image: ubuntu-20.04
Agent: Hosted Agent

## Issue Description

`https://storage.googleapis.com/golang` seems to only contains up to go 1.17.4 binaries. Checking the [offical](https://golang.org/dl/) page it seems that `https://golang.org/dl/` should be used.

Therefore the following task definition is not working.
```
  - task: GoTool@0
    inputs:
      version: '1.18.0'
```

### Task logs
```
Starting: GoTool
==============================================================================
Task         : Go tool installer
Description  : Find in cache or download a specific version of Go and add it to the PATH
Version      : 0.180.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/go-tool
==============================================================================
Downloading: https://storage.googleapis.com/golang/go1.18.0.linux-amd64.tar.gz
##[error]Failed to download version 1.18.0. Please verify that the version is valid and resolve any other issues. Error: Unexpected HTTP response: 404
Finishing: GoTool
```

**Comment by dagood** [comment]
(FYI, I'm not on the Azure Pipelines Tasks team, I just also have interest in this build task. 🙂)

I tried out using `GoTool@0` to get 1.18, and it worked for me. I think this is the issue:

> version: '1.18.0'

If I change my version from 1.18 to 1.18.0, I hit the same failure you do. However, Go doesn't include the trailing `.0` in its official toolset versions, and that makes the `GoTool@0` task calculate the filename incorrectly. The real file is:
https://storage.googleapis.com/golang/go1.18.linux-amd64.tar.gz (works)
but the task tries to download:
https://storage.googleapis.com/golang/go1.18.0.linux-amd64.tar.gz

The task is pretty simple, using the `version` string you give it without any processing to find the URL: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/GoToolV0/gotool.ts

---

I do think it would be reasonable for `GoTool@0` to support `1.18.0` by interpreting it as `1.18` and downloading that, but maybe this will help you work around the problem for now until the Tasks team replies.

* Related: https://github.com/microsoft/azure-pipelines-tasks/issues/15825
  * Because "1.18" sometimes means "latest version of `go1.18*`, maybe it should actually be handled that way, and 1.18.0 should just be a way to force the old version to be used.

**Comment by eqinox76** [comment]
I love the latest ability. And thanks for finding a workaround!
