### ISSUE TITLE
Cannot checkout to $(Build.SourcesDirectory)

### ISSUE THREAD

**Issue by d5han** [microsoft/azure-pipelines-tasks#16093]
## Required Information

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: checkout  

## Issue Description
The `checkout` task cannot make use of the `$(Build.SourcesDirectory)` variable in its `path` argument because it is a "rooted" path. This requires working around the issue by knowing what the SourcesDirectory will resolve to, and what working directory the `checkout` task will run in (especially since it doesn't take a `workingDirectory` argument). 

If the reason for blocking rooted paths is concern the task will create files outside of its pipeline workspace, allowing an exception to this error when the argument to `path` is within `$(Pipeline.Workspace)` would be a good resolution.

### Example: 

```
- checkout: example-repo
  path: $(Build.SourcesDirectory)/example-repo
```

Results in:

```
##[error]/home/agent/myagent/_work/13/s/example-repo can not be a rooted path.
```

**Comment by anatolybolshakov** [comment]
Hi @d5han at the moment it is by design - checkout task supports only relative paths and chooses root directory by itself - depending on set of repositories used/build definition/project collection (see [docs](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/checkout-path.md#control-the-checkout-location-of-code) for more details).
We also have another [enhancement ](https://github.com/microsoft/azure-pipelines-agent/issues/1506) in a backlog and PRs on review which add capability to re-use repositories outside of working directory - feel free to track progress around these changes here.

**Comment by mgillespie-ext** [comment]
Documentation implies this is a perfectly OK thing to do. 

https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines

"  path: string # Where to put the repository. The root directory is $(Pipeline.Workspace)."

**Comment by Marko5211** [comment]
2 years later and still not working. What a surprise. I am unable to checkout to ANY SPECIFIC FOLDER. This is the reason why people hate microsoft.

**Comment by sreich** [comment]
I agree. Seriously though... I have also just wasted a bunch of time on this design mistake, further helped by the broken documentation...this needs fixed

P.S. I have never struggled so much back when using Jenkins, I've got pages of azdo issues and errata and most of them are not being addressed, not surprised, they've shown their forward focus is github, hence why yaml pipelines are still completely unusable for secure environments

**Comment by Marko5211** [comment]
So i found the fix. 
Congrats microsoft. Next time try to hire someone who is able to use brain. Thanks
But the solution:
USE F*KIN "s/" at the begin of the path. How retarded had to be someone who created this functionality? And what about the guy, who reviewed that?

**Comment by stevekuznetsov** [comment]
@anatolybolshakov not sure if you're still on this team but it would be nice to support this feature. ADO's "implicit" mode where everything "just works" until it doesn't can be a real frustration, especially since the path where things are checked out is different when you have one repo, many repos, a list with `self`, etc. Being explicit about where each repo goes lets someone reading a pipeline definition then understand where the working directory paths end up coming from for future steps.
