### ISSUE TITLE
UsePythonVersion@0 doesn't work with service containers

### ISSUE THREAD

**Issue by MrCordeiro** [microsoft/azure-pipelines-tasks#16133]
*Type*: Bug

**Enter Task Name**: UsePythonVersion@0

## Environment
- Server - Azure Pipelines: 
- account name: pluckd
- team project name: pluckd
- build number: #20220410.8

## Issue Description

Whenever I use the `UsePythonVersion@0` task in conjunction with service containers, I get one of the following error whenever I call `pip`, `python3` or `python`:

`/__w/_temp/114bae27-4b79-449b-a114-c10064c5ee12.sh: /__t/Python/3.9.12/x64/bin/pip: /opt/hostedtoolcache/Python/3.9.12/x64/bin/python: bad interpreter: No such file or directory`

or 

`python3: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or director`

### Task logs

[logs_94.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8466399/logs_94.zip)

**Comment by HansBecker** [comment]
I'm experiencing the same issue. Is there any workaround at present?

**Comment by HansBecker** [comment]
A possible workaround is running your job in a Python container. My particular use case is running Django unit tests against a PostgreSQL container 

`- job: Test
    displayName: Run unit tests

    container: python:3.10
    services:
      db: db
    steps:
    - task: PythonScript@0`
       ...

**Comment by maldouk** [comment]
Is there an update or a workaround that doesn't involve making a container? 
We are transitioning some services from cloud to on-premise, and we need to be able to use UsePythonVersion@0 on local agents.
From what I see the issue seem pretty old as I see people posting on it close to 4 years (!!!) [ago.](https://github.com/microsoft/azure-pipelines-tasks/issues/11070)

We are running the agent on a kubernetes cluster, everything is running Ubuntu server 20.04. The container itself is running Ubuntu 20.04 as well. The problem seems to be that, either the libraries aren't linked properly, or that they should be on $PATH but they aren't.
