### ISSUE TITLE
Powershell task fails when writing to error stream, even though error stream is redirected

### ISSUE THREAD

**Issue by pefoo** [microsoft/azure-pipelines-tasks#16825]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShellV2

## Environment
Azure DevOps Servier on premise.

Version Azure DevOps Server 2020 Update 1.1

Self hosted agent. 
OS: Windows Server 2016 LTSC
Agent Version: 2.181.2

## Issue Description

Redirecting stderr in a powershell task (either inline oder script execution) terminates the pipeline. 

```yaml
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 
      Write-Error 'This should go to hell. No one should care' 2>$null
    failOnStderr: false
```

![image](https://user-images.githubusercontent.com/12524622/187696425-fb3fe1f4-902e-4d06-b548-2ef4604710a9.png)

Since I redirect stderr, I do not expect the pipeline to fail. Nor do I expect to see the error nonetheless. 

I noticed the issue while working with external commands that are executed in background jobs. 
I am using the following fragment to cancel the job on custom timeouts. The recieve-job part takes all output of the external command and stores it. Later I retrieve the errors and return a result object that contains output, errors and stuff like that. 

Works like a charm on Powershell 5 and 7 on my machine. Azure fails as soon as someone touches the error stream. 

```powershell 
$job = Start-Job -ScriptBlock $block -ArgumentList $argumentList
$completedInTime = $true

if (-not (Wait-Job $job -Timeout $timeoutSeconds)) {
  Stop-Job $job
  $completedInTime = $false
}
[System.Collections.ArrayList]$output = @(Receive-Job $job -Force -Wait 2>&1)
$errors = $output | Where-Object { $_ -is [System.Management.Automation.ErrorRecord] }
```

Using the commandline task and running my powershell script there works. I consider that a workaround

```yaml
- task: CmdLine@2
  inputs:
    script: |
      C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -File $(System.DefaultWorkingDirectory)\tests.ps1
```

**Comment by DmitriiBobreshev** [comment]
Hi @pefoo, thank you for the request, failOnStderr when it's false will rely on the exit code to determine failure.  When you do the command ` Write-Error 'This should go to hell. No one should care' 2>$null` it returns exit code 1, and when you run it just from powershell.exe all will be normal, only $LASTEXITCODE will be 1, but if you try to run this from another ps script the behaviour will be the same.

PowerShell task, when you set failOnStderr: false watching, fistly, hat do you have in `$_ -is [System.Management.Automation.ErrorRecord]` and show it in the console, and, secondly, on the $LASTEXITCODE and if it's not 0 do the code(throw error):
```
if ($LASTEXITCODE -ne 0) {
            $failed = $true
            Write-VstsTaskError -Message (Get-VstsLocString -Key 'PS_ExitCode' -ArgumentList $LASTEXITCODE)
        }
```

If you want to see errors in the logs you can run tasks like this: 
```
- task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
              Write-Error 'This should go to hell. No one should care';
          failOnStderr: false
          errorActionPreference: 'continue'
```
In this case in the pipelines log you'll see all errors, but PowerShell tasks will finish successfully

**Comment by pefoo** [comment]
Hi @DmitriiBobreshev 
$LASTEXITCODE is not set by any of the cmdlets. Its there for external commands. See [this](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.2#lastexitcode) for reference.
![image](https://user-images.githubusercontent.com/12524622/187902894-2f01e195-aa00-4b58-be7a-89aca578f273.png)

You might confuse things with ``$?``

Your second assumption is not true too. To demonstrate: 

> call.ps1
```powershell
. "$PSScriptRoot/callme.ps1"

Write-Host 'iam still standing lol'
```

> callme.ps1
```powershell 
Write-Error 'Error'
Write-Host 'Still going'
```

![image](https://user-images.githubusercontent.com/12524622/187904565-2b6b2eee-1a5c-4386-b503-1ff50856a467.png)

Setting the error preference to silently continue is just a really bad idea. 

Again, I want the pipeline to fail if things go wrong. But I don't want it to fail just because someone touches the error stream. 


> PowerShell task, when you set failOnStderr: false watching, fistly, hat do you have in $_ -is [System.Management.Automation.ErrorRecord] and show it in the console, and, secondly, on the $LASTEXITCODE and if it's not 0 do the code(throw error):

Using $LASTEXITCODE is, again, not helpful here. And as I said, the code above should not raise errors nor should it make the pipeline fail. But lets concentrate on the simple example using write-error.

**Comment by DmitriiBobreshev** [comment]
@pefoo, sorry, I probably wrote it a little confusing way, let me try to explain how Powershell task work.

When you run it as an inline-script like this: `script: Write-Error 'This should go to hell. No one should care' 2>$null` (or as a file) it basically wraps it with variables [that you passed](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#arguments)(such as warningPreferenceand etc.) in [another ps file](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PowerShellV2/powershell.ps1#L132), and after that run this files via [Invoke-VstsTool](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PowerShellV2/powershell.ps1#L173).  You can see that agent run it in the pipeline on your screen(_temp/e6166a0f-0924-476-916-b12013370ca7.ps1)

The problem is, that when you run your ps script just as is from windows powershell, by default, the option [errorActionPreference set as continue](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.2#erroractionpreference), but for PowerShell task, [the default value is stop](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#arguments) ([github](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PowerShellV2/powershell.ps1#L33)), you can try it by running to pretty similar ps1 files, when you run it as it, with default value of errorActionPreference:
 
![image](https://user-images.githubusercontent.com/106314398/187920241-102a554e-721a-4a33-9149-02db17375123.png)

but if you try similar file but with option which set on default in PowerShell Task you see this: 
![image](https://user-images.githubusercontent.com/106314398/187920632-6d281023-8598-4fe8-9402-709c0a07cb7c.png)

The option $ErrorActionPreference = 'stop' is set by default [according to doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#arguments), and probably that's why you got this error, so if you want behaviour like in powershell.exe, you need to set this option as continue, but in this case, you won't see error output. 
And, probably, that's why 
```
- task: CmdLine@2
  inputs:
    script: |
      C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -File $(System.DefaultWorkingDirectory)\tests.ps1
```  
working as you expect, because it running with default ErrorActionPreference which is continue.

Also when I said that if you want to see the error and do not terminate your pipeline, I meant that you could see something like this in your output:

![image](https://user-images.githubusercontent.com/106314398/187926391-1af2dc8f-5781-4916-89f1-6de17fbece67.png)

**Comment by pefoo** [comment]
@DmitriiBobreshev Thank you very much for making this clear. I did not notice that the task uses a different error action preference than regular powershell. 

Thanks to you, I managed to get the behavior I want: 
```yml
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Error 'This should go to hell. No one should care'
        exit 17
      errorActionPreference: continue
```
Displays the error, but does not exit because of it. Exit 17 makes the step fail (as I expect). With this I should be able to get my stuff working without calling the command line task :)

Tank you.
