### ISSUE TITLE
VSBuild fails on windows-2022 agent for solution with .sqlproj with MSB3644 (.NETFramework,Version=v4.5 not found)

### ISSUE THREAD

**Issue by msuarez-rmr** [microsoft/azure-pipelines-tasks#16822]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSBuild 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
- Agent - MS Hosted 

## Issue Description

To Reproduce:

- Create a .Net solution with 1 to many .csproj projects using .Net Core 6
- Add an SSDT database project to the solution (.sqlproj)
- Create a build pipeline, using an MS hosted agent with a windows-2022 image, containing the following task:
 ```
  task: VSBuild@1
   inputs:
     solution: '**/*.sln'
     platform: 'Any CPU'
     configuration: 'Release'
  ```
- Run the build pipeline.
- Instead of a successful build, you will see the following error:
 > ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1220,5): Error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
 
- Without the inclusion of the .sqlproj, this error doesn't occur, which proves that the build fails because of the database project.
- This same exact build pipeline definition succeeded when the cs projects referenced .Net Core 5, and the image being used was windows-2019.
- Neither reverting back to .Net Core 5 & windows-2019 nor removing the .sqlproj from the solution would be considered viable solutions.

**Comment by msuarez-rmr** [comment]
I updated the xml in the .sqlproj file
from:
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
to:
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>

Given that I typically don't associate database projects as being dependent on any version of .net, nor do I see any place in the IDE to define this, it didn't occur to me to make this change at first... But lo and behold, it appears to work without any side effects noticed yet.

**Comment by DmitriiBobreshev** [comment]
Hi @msuarez-rmr, thank you for your request, as I can see windows-2022 using Microsoft Visual Studio Enterprise 2022, according to [MSDoc](https://docs.microsoft.com/en-us/visualstudio/releases/2022/compatibility#-visual-studio-2022-support-for-net-development), new Visual Studio supports development pack only .net 4.6.2+, so that's why you got this error on windows-2022 image and didn't get it on windows-2019 (where Visual Studio 2019 installed), so in your case, you can change
TargetFrameworkVersion(as you did in the upper comment) or use windows-2019 image if you need exactly .net 4.5

**Comment by DmitriiBobreshev** [comment]
Hi @msuarez-rmr do you have any updates?

**Comment by msuarez-rmr** [comment]
The Build Pipeline has been running smoothly with the TargetFrameworkVersion tag updated directly in the xml of the .sqlproj (since the framework isn't listed in the IDE on any of the tabs of the project properties screen). This was my only option since the other projects in the solution were upgraded to .Net Core 6.0 and needed VS 2022 to build.

Just for reference, why is it that the a sql project, which doesn't contain any .Net code is dependent on any version of .Net? Or put another way, why even have the TargetFrameworkVersion defined by the project at all, as opposed to just taking the version of SSDT that's compatible with whatever version of VS is building the solution?

**Comment by DmitriiBobreshev** [comment]
@msuarez-rmr I'm not sure why we need to define TargetFrameworkVersion in SQL project but based on a similar question for other projects such as on pure c++, it needs not for SQL but for MSBuild,  as I see in [MSBuild docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2022#target-framework-and-profile): " Specification of a target framework is required because it enables compiler features and assembly references that are exclusive to that version of the framework.". So basically even if you don't need it for compiler features in your project MSBuild requires it

**Comment by msuarez-rmr** [comment]
Thanks for the explanation. It's helpful to know the reason. In any case, it seems as though I'm all set here, so I am marking as closed. Thanks for your assistance.
