### ISSUE TITLE
Need NodeJS Version Communications & Plan

### ISSUE THREAD

**Issue by davidcorrigan714** [microsoft/azure-pipelines-tasks#17099]
We've gotten bit a few times this week, and earlier this year, by a lack of communication around the NodeJS plans for the tasks. Is there a document somewhere describing the roadmap and expectations of what versions of NodeJS the pipeline agent tasks are expected to be able to use? Also specifically what versions it shouldn't be using so we can set reasonable policies on our agent's endpoint monitoring to alert (or not) on EOL versions of NodeJS.

**Comment by jessehouwing** [comment]
Is there a doc for extension developers too? There are a number of constraints we need to work with to support older TFS server versions that are still out there in the field and that don't ship with Node16 handlers. 

I see in the tasks updated so far that both the Node and Node16 handlers point to the same js file, but if they use any node16 features, I suspect they'll break on Node 6 and Node 8 and Node 10 that shipped with older TFS and Azure DevOps Servers.

I tried compiling some of my extensions to 8, 10 and 16, but then the file size for the extension becomes too large for the marketplace, and I can't publish the extension.

I also see the MinAgentVersion being raised by quite a bit, that means none of these tasks can be installed into Azure DevOps Server 2020 or below to fix bugs it looks like.

**Comment by davidcorrigan714** [comment]
I just noticed that some details are on the Azure DevOps Roadmap page [here](https://learn.microsoft.com/en-us/azure/devops/release-notes/features-timeline#pipelines-agent-node-lifecycle). Looks like they should all be Node 16 relatively soon actually. Though there's still the challenge of figuring out what other versions the rest of our extensions are actually using. Some flag in the runner to restrict or warn on older versions would be really nice.

**Comment by jessehouwing** [comment]
What's missing in the documentation is how to properly handle targeting multiple TFS/ADS and Azure DevOps versions.

If I need to make changes to the code or pull in different dependency versions for say TFS 2018 support, should I package 2 folders with 2 cross compiled versions of the task each with their own node_modules? Cause in that case I'm likely going to hit the 20MB size limit for extensions.

Or should I add a new major version of the task and leave other versions on the last major version? This will also consume space in the extension zip.

I can't split the extension in a node10 and a node16 version without breaking my consumers since the taskid and she task name are forced to change and people will need to change all their yml files and ui pipelines.

I have extensions that still support TFS 2015 all the way up to ADS 2022 and since the marketplace doesn't provide any metrics I can't easily deprecate some of them. 

Ideally the team would ship an update for old servers versions that contains the new agent and provide official support on that. It's a security patch, depending on how you look at it.

**Comment by vijayma** [comment]
A blog post for task authors is coming up soon.
