### ISSUE TITLE
FTP Upload V2 Task fails with an "FTPError: 426 Failure reading network stream."

### ISSUE THREAD

**Issue by kalozoya-gregal** [microsoft/azure-pipelines-tasks#17125]
*Type*: Bug

**Enter Task Name**: FTP Upload V2

## Environment

- Pool: Azure Pipelines
- Agent: Hosted Agent

## Issue Description

FTP Upload V2 Task fails with an "FTPError: 426 Failure reading network stream."
Protocol: ftps://

I am using.
![imagen](https://user-images.githubusercontent.com/47449787/199712800-62658163-9914-4f81-8cc1-67f6a2430a5f.png)

with "windows-latest" also fails.

### Task logs

![imagen](https://user-images.githubusercontent.com/47449787/199714402-476c8fbb-0bfc-42de-80b8-f632bd85d8c8.png)
![imagen](https://user-images.githubusercontent.com/47449787/199714682-56c00eb7-b556-4c44-95db-d8370dc218e7.png)

I need help, I use this for CI/CD.

Thanks.

**Comment by DmitriiBobreshev** [comment]
Hi @kalozoya-gregal, thank you for reporting I checked the task with my ftps server on uploading ~10k files in different sizes and it seems working. 
Are you sure that the problem is exactly with the task? FTPUploader task using basic-ftp library to connect and upload files, and I found some explanation from the author why the [error appears](https://github.com/patrickjuchli/basic-ftp/issues/170), and sometimes it may happen if FTP server has multiple uploads from a different source. You can try to specify [retryCountOnTaskFailure](https://learn.microsoft.com/en-us/azure/devops/release-notes/2021/pipelines/sprint-195-update#automatic-retries-for-a-task) option in case your server break the connections. 

But to be clear is that a problem with the task or server, can you please try to upload the same directory with the same files directly from your working machine through [lftp](https://lftp.yar.ru/) for Linux machines or [WinSCP](https://winscp.net/eng/download.php) for windows.

As I temporary solution(as I see that some files uploading correctly, and probably the problem is in the number of files), I could recommend you try to archive the directory and upload an archive with [ArchiveFiles Task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/archive-files?view=azure-devops) and then manipulate it via [SSH](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops) task

**Comment by kalozoya-gregal** [comment]
More information from server:
![imagen](https://user-images.githubusercontent.com/47449787/200295956-492d0b7b-01a5-47b2-bbb6-83e224991904.png)

FTPUploader task:
![imagen](https://user-images.githubusercontent.com/47449787/200298427-2e1ab19d-631f-4134-ab03-70a77c3bac00.png)

At the moment, it happens with files larger than 30 KB

I have tried with retryCountOnTaskFailure option to 2, but I have the same error. It's starting the whole file upload again.
With WinSCP I have uploaded the files correctly.

Searching for information about the error I found these "issues" on FruentFTP as well. Last week it seems they published a new release fixing it.
Main issue: https://github.com/robinrodricks/FluentFTP/issues/996
https://github.com/robinrodricks/FluentFTP/issues/573
https://github.com/robinrodricks/FluentFTP/issues/763

Hope that helps.
