### ISSUE TITLE
Do not ignore by default the return code for BashV3 and CMDLineV2

### ISSUE THREAD

**Issue by azachar** [microsoft/azure-pipelines-tasks#17156]
Hello,

By default any tasks represented by for example:

```
- script:
    <what ever command with a non-zero return code>
```

running on linux should do not fail when a return code is non zero.  Which is super confusing. By default you want that if something goes wrong, the pipeline fails not the opposite!

But this line in the code prevent that, could you please change it, otherwise we are force to set to each and every script command `set -e` which is super intrusive. Also we noticed the same behavior for BashV3 task too.

https://github.com/microsoft/azure-pipelines-tasks/blob/7b5260ead94b76ced6856775d6ed5666698fd962/Tasks/CmdLineV2/cmdline.ts#L48

Thank you for your consideration!

Best regards,
Andrej

**Comment by DmitriiBobreshev** [comment]
Hi @azachar, as I see this behaviour started 7 years ago from [this commit](https://github.com/microsoft/azure-pipelines-tasks/commit/e6da15a0c2e41229501219289c184c6690c7ba21), and unfortunately can't be undone, because now tasks like CmdLine using a lot of customers and it will break a lot of pipelines which expect `failOnStderr: false`  as the default behaviour.
But, I think you can use it with a [shortcut](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml#yaml-snippet), according to docs!
i checked it in the playground and 
```
- script: |
      cd /nonExistingDirectory
      echo '123'
  failOnStderr: true
``` 
works the same as 
```
- task: CmdLine@2
  inputs:
    failOnStderr: true
    script: |
      cd /nonExistingDirectory
      echo '123'
```

**Comment by DmitriiBobreshev** [comment]
@azachar closing this, please feel free to reopen it if you have some questions.
