### ISSUE TITLE
AzureKeyVault fails with 'endpoints_resolution_error'

### ISSUE THREAD

**Issue by kwasiak** [microsoft/azure-pipelines-tasks#17485]
Question, Bug, or Feature?
*Type*: Bug

**Enter Task Name**: AzureKeyVault

## Environment

- Agent - Private, running under Azure DevOps
- OS: RHEL 8.6
- Version: 2.214.2

## Issue Description

Secrets downloading takes 30+ sec to complete with the following error: 

`"Could not fetch access token for Azure. Status code: endpoints_resolution_error, status message: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter."`

## Update - 18 Dec 2022

I've managed to mitigate the error by removing the HTTP proxy and going directly to the internet to download the secrets. So whatever change has been done to the AzureKeyVault to download secrets, it doesn't take into consideration that the secrets download can be done from behind a proxy. And yeah, we set all the proxy environment variables; they're just being ignored.

## Update - 18 Jan 2023

We're getting the same problem AGAIN with Version: 2.215.0. I can't believe we pay all that money to MS for this platform....

**Comment by jtterry2856** [comment]
I am seeing this issue as well. When trying to do a recent deployment we received an error during Download Secrets step which uses AzureKeyVaultV2 task. We noticed there was recent version downloaded 1.214.2 which seems to introduce the error. I am running azure devops agent on windows server 2019 with proxy configured.

Initialize Job Step:
![image](https://user-images.githubusercontent.com/29108797/208010928-e523d3c3-1e90-4813-b785-beff3f243aac.png)

Error during Download Secret step that occurs about 30 seconds later:
![image](https://user-images.githubusercontent.com/29108797/208011225-1599e6d0-a4e3-4580-9b37-ca502a6b6c3f.png)

**Comment by RaviChandraMadipadiga** [comment]
@jtterry2856 - Are you running on Self Hosted Agent ?
I got this error only when i am running on Self Hosted Agent with proxy enabled

**Comment by jtterry2856** [comment]
@RaviChandraMadipadiga yes I am running self hosted agent

**Comment by edohussl** [comment]
I am experiencing the same issue since 2 days now. Also running release agents (2.213.2) fetching secrets from a keyvault (using the Azure Key Vault version 2.214.2) on a VM (self hosted) behind a proxy.

Is there already a solution or change we have to apply in our configuration? All of our deployments are defined in 'classic' release definitions relying on these self hosted agents needing secrets from keyvaults.

**Comment by RobRybber** [comment]
We're experiencing the same issue since the 14th. Self hosted agent (ver 2.193.0) using a proxy.

`Could not fetch access token for Azure. Status code: endpoints_resolution_error, status message: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.`

**Comment by edohussl** [comment]
It seems to be related to the AzureKeyVault task 2.214.2. When we use the previous version (2.211.1), deployments succeed again.

However, I am not aware of an elegant way of forcing the agent to use a specific version for this task, since it is automatically selected because of a linked variable group, linked to the keyvault. Anyone?

**Comment by RaviChandraMadipadiga** [comment]
@edohussl - Yes , i tried now changing the version to 1* in Azure Key Vault task and it succeeded but whereas with the Azure key vault variable group it is auto picking the version to latest as 1.214.3 as so the issue is occurring. Do we have any feasibility to change the version of the task to pick for key vault variable group ?

**Comment by kwasiak** [comment]
@RaviChandraMadipadiga Nope, you can't select the minor plugin version in the release pipeline. You can do that in the YAML pipeline, but YAML pipelines don't support the Deployment Groups. You can use Environments for YAML pipelines, but those don't support sharing of the VMs - as you can't have the same VM in multiple Enviornments... 'Consistency' wasn't apparently a key concern on mind of whoever design this entire thing. Maybe Jenkins isn't that bad after all... If we're blocked for too long I'll be making the case for CloudBees....

**Comment by ChristianFehlinger** [comment]
We have the same problem and we are not able to deactivate the proxy.
Is there a possibility to set max version of a task for the agent setup?

**Comment by edohussl** [comment]
We are not able to enable direct internet access on our VMs. However, we did implement a workaround (it's more like hack though) to ensure the agent uses an older version of the AzureKeyVault task. We simply copied over the files from the old version (2.211.1) to the new version (2.214.2) in the '_work\_tasks\AzureKeyVault_...' folder.

I do think this is an issue that has to be fixed in the task or agent. How do we get this under the attention of Microsoft?

**Comment by armin-pfaeffle** [comment]
For me it works again! It seems that the task has been updated to **2.214.3** and now it runs smoothly.

**Comment by RaviChandraMadipadiga** [comment]
@kwasiak - Seems like they have updated the task version now to 214.3 and it's working fine now.
Thank you for raising this issue in GitHub by seeing my question in community forum.it really helped all of us .

**Comment by jtterry2856** [comment]
Works for me as well when I tested pipeline today. New version 1.214.3 was downloaded and "download secrets" step completed successfully. 

![image](https://user-images.githubusercontent.com/29108797/208765445-e9fc7eae-71dd-412e-82cf-d9d3ac8f461e.png)

**Comment by edohussl** [comment]
Same here, works with 2.214.3. Although, it is strange that I see version 2.214.3 reported and other see 1.214.3 reported.

**Comment by StuhlfauthKlaus** [comment]
Thanks @ all,
the new AzureKeyVault task 1.214.3 works for us too.

**Comment by prfj** [comment]
the new AzureKeyVault task 1.215.0 have the same error again...

**Comment by enginhorzum** [comment]
It is happening again with the newly installed AzureKeyVault task 2.215.0.

**Comment by kwasiak** [comment]
correct, just got an update from our DevOps team... I really need to start thinking about Jenkins....

**Comment by vireshov** [comment]
I was troubleshooting a network/proxy related issue (407) regarding the AzureKeyVault task, but during the troubleshooting yesterday, I ran into the "endpoints_resolution_error". I came across this issue here and indeed what happened is that they pushed a new version of this task (2.215.0) yesterday, in which it is broken again ("endpoints_resolution_error"). However, a few hours later they pushed 2.215.1 and that one seems to be working fine again.

**Comment by aomerkii** [comment]
I faced the same problem with delete item in adf task. it may relate...
In my case solved by add prerequisite task to set HTTP_PROXY env to the session.

steps:
- powershell: 'Write-Host "##vso[task.setvariable variable=HTTP_PROXY;]http://{proxy_host}:{port}"'
