### ISSUE TITLE
"No message found for this issue" - AzureResourceManagerTemplateDeploymentV3

### ISSUE THREAD

**Issue by lcrok** [microsoft/azure-pipelines-tasks#17483]
**Question, Bug, or Feature?**  
*Type*: BUG

**Enter Task Name**: AzureResourceManagerTemplateDeployment

## Environment
- Server - Azure Pipelines

- Agent - MS Hosted 
    
Pool: Azure Pipelines
Image: windows-latest
Agent: Hosted Agent

## Issue Description

This pipeline is running with template from another repository in the same project. RM Service Connection is set to allow any pipeline in the project to consume it.

When running the AzureResourceManagerTemplateDeployment@3 task against a bicep file, I´m getting this error in the Build dashboard:

![image](https://user-images.githubusercontent.com/6450454/207610580-a93032ea-9401-4d4b-be42-452d860cced7.png)

However, when I click on the error, I do not see any error in the pipeline. Deployment occurs successfully, deployment is created in Azure and completes with no errors:

![image](https://user-images.githubusercontent.com/6450454/207617014-18698f12-3269-4ebf-83a7-81903969d7d8.png)

The deployment completes successfully in Azure:

![image](https://user-images.githubusercontent.com/6450454/207611491-943a55ce-625f-42ee-98f1-e31d2ce5b25b.png)

Only way to see something related to this error is when I enable System Diagnostics, then I see some MSAL/Graph errors as shown below.

### Error logs

```
2022-12-14T13:20:10.2356187Z ##[debug]MSAL - getMSALToken called. force=undefined
2022-12-14T13:20:10.2356992Z ##[debug]MSAL - ServicePrincipal - clientSecret is used.
2022-12-14T13:20:10.2357918Z ##[debug][Wed, 14 Dec 2022 13:20:10 GMT] : @azure/msal-node@1.14.3 : Info - acquireTokenByClientCredential called
2022-12-14T13:20:10.2371243Z (node:3444) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2022-12-14T13:20:10.7910765Z ##[debug][GET]https://graph.microsoft.com/1a6803a4-????-????-????-????????b09d/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6
2022-12-14T13:20:10.8228481Z ##[debug]Processed: ##vso[task.logissue type=error;code=BadRequest;]
2022-12-14T13:20:10.8231117Z ##[debug]Error while fetching Service Principal details: [object Object]
2022-12-14T13:20:10.8232156Z Starting template validation.
2022-12-14T13:20:10.8232762Z Deployment name is DEV-BRANDS-20221214.1
```

_* replaced part of the personal info for client´s privacy_

**Comment by jdaugherty** [comment]
We started seeing this occur in our pipelines as of this morning.  Turning on debug shows a similar error.

    ##[debug]MSAL - getMSALToken called. force=undefined
    ##[debug]MSAL - ServicePrincipal - clientSecret is used.
    ##[debug][Wed, 14 Dec 2022 17:59:34 GMT] : @azure/msal-node@1.14.3 : Info - acquireTokenByClientCredential called
    (node:5580) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    ##[debug][GET][https://graph.microsoft.com/***/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6](https://graph.microsoft.com/***/servicePrincipals?$filter=appId%20eq%20%27***%27&api-version=1.6)
    ##[debug]Processed: ##vso[task.logissue type=error;code=BadRequest;]
    ##[debug]Error while fetching Service Principal details: [object Object]
    Starting template validation.

**Comment by albindevs** [comment]
Also stared seeing this ghost error message from Az devops "No message found for this issue" in task AzureResourceManagerTemplateDeployment@3

Debug logs:
`##[debug][GET][https://graph.microsoft.com/19eee545-4131-45c6-9a60-1a17e5cc507d/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6](https://graph.microsoft.com/19eee545-4131-45c6-9a60-1a17e5cc507d/servicePrincipals?$filter=appId%20eq%20%27***%27&api-version=1.6)
##[debug]Processed: ##vso[task.logissue type=error;code=BadRequest;]
##[debug]Error while fetching Service Principal details: [object Object]`

**Comment by DSPolicyFilter** [comment]
I also see this for AzureResourceManagerTemplateDeploymentV3 3.214.0

##[debug]MSAL - getMSALToken called. force=undefined
##[debug]MSAL - ServicePrincipal - clientSecret is used.
##[debug][Wed, 21 Dec 2022 16:13:13 GMT] : @azure/msal-node@1.14.3 : Info - acquireTokenByClientCredential called
(node:1012) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
##[debug][GET][https://graph.microsoft.com/e391faf5-07a0-490b-9055-ef2f8a1fba90/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6](https://graph.microsoft.com/e391faf5-07a0-490b-9055-ef2f8a1fba90/servicePrincipals?$filter=appId%20eq%20%27***%27&api-version=1.6)
##[debug]Processed: ##vso[task.logissue type=error;code=BadRequest;]
##[debug]Error while fetching Service Principal details: [object Object]
Starting template validation.

**Comment by josliebenah** [comment]
also seeing this issue

**Comment by ozanovus** [comment]
This issue has been addressed and fixed for upcoming update will be released as 3.216.x or later version in a few weeks.

**Comment by tloy1966** [comment]
also seeing this issue

**Comment by denniselit** [comment]
Also seeing this issue using windows-latest (windows-2022)

**Comment by keithmitworks** [comment]
> This issue has been addressed and fixed for upcoming update will be released as 3.216.x or later version in a few weeks.

Thank you. I have recently discovered this on multiple tasks including AzureAppServiceManage@0 and AzureKeyVault@1 are these tasks included in the upcoming fix?

**Comment by aliquid** [comment]
+1

**Comment by karpikpl** [comment]
I'm on ` 3.220.0` and still see this issue

**Comment by karpikpl** [comment]
Hey @ozanovus 
here's what I get:
```
(node:7984) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
##[debug][GET][https://graph.windows.net/58be8688-66***xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6](https://graph.windows.net/58be8688-66***xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20%27***%27&api-version=1.6)
##[debug]Encountered a retriable error:ECONNRESET. Message: read ECONNRESET.
##[debug][GET][https://graph.windows.net/58be8688-66***xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6](https://graph.windows.net/58be8688-66***xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20%27***%27&api-version=1.6)
##[debug]Encountered a retriable error:ECONNRESET. Message: read ECONNRESET.
##[debug][GET][https://graph.windows.net/58be8688-66***xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6](https://graph.windows.net/58be8688-66***xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20%27***%27&api-version=1.6)
##[debug]Encountered a retriable error:ECONNRESET. Message: read ECONNRESET.
##[debug][GET][https://graph.windows.net/58be8688-66***xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6](https://graph.windows.net/58be8688-66***xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20%27***%27&api-version=1.6)
##[debug]Encountered a retriable error:ECONNRESET. Message: read ECONNRESET.
##[debug][GET][https://graph.windows.net/58be8688-66***xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6](https://graph.windows.net/58be8688-66***xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20%27***%27&api-version=1.6)
##[debug]Processed: ##vso[task.logissue type=error;code=ECONNRESET;]
##[debug]Error while fetching Service Principal details: read ECONNRESET
```

I guess in my case it might be connectivity to  graph.windows.net but the deployment is successful regardless?

**Comment by erstert3st** [comment]
same here

**Comment by TomasMalecek** [comment]
Older issue generating the same error in the pipeline run log: https://github.com/microsoft/azure-pipelines-tasks/issues/13797

~~Wonder if the generic message can be somehow replaced to make the issues better recognizable.~~ _Seems the "No message found for this issue" is produced by the logging command `##vso[task.logissue type=error]` when no message is passed. Or maybe when the message starts with a newline. :-)_

**Comment by TomasMalecek** [comment]
Can we please reopen this? Or should I create a new issue? I am seeing something very similar in AzureResourceManagerTemplateDeployment@3.254.0:
```
##[debug]MSAL - Graph - GraphManagementClient - useMSAL = false
##[debug]MSAL - Graph - GetServicePrincipal - useMSAL = false
##[debug]MSAL - Graph - GetServicePrincipal - requestURL = https://graph.microsoft.com/326c0a61-9f37-4dce-8adc-xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6
##[debug]CLIENT_RESETSTREAMONRETRY=undefined
##[debug][POST]https://login.windows.net/326c0a61-9f37-4dce-8adc-xxxxxxxxxxxx/oauth2/token/
(node:16237) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
##[debug]CLIENT_RESETSTREAMONRETRY=undefined
##[debug][GET]https://graph.microsoft.com/326c0a61-9f37-4dce-8adc-xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6
##[debug]Processed: ##vso[task.logissue type=error;code=BadRequest;]
##[debug]Error while fetching Service Principal details: Invalid version.
```

By the way, the DEP0005 warning from Node should hopefully be solved by https://github.com/microsoft/azure-pipelines-tasks/pull/20994, i.e., in AzureResourceManagerTemplateDeployment@3.256.0.

**Comment by TomasMalecek** [comment]
Looks like the problem is in the azure-pipelines-tasks-azure-arm-rest NPM package, specifically in its azure-graph.ts, in the ServicePrincipals class: https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/main/common-npm-packages/azure-arm-rest/azure-graph.ts#L51 The `deferred.reject(azureServiceClientBase.ToError(response));` line generates the problematic error -- the ToError() method makes the broken task.logissue logging command call without a message, leading to the "No message found for this issue" message being used. https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/main/common-npm-packages/azure-arm-rest/AzureServiceClientBase.ts#L38

```
export function ToError(response: webClient.WebResponse): AzureError {
    var error = new AzureError();
    error.statusCode = response.statusCode;
    error.message = response.body;
    if (response.body && response.body.error) {
        error.code = response.body.error.code;
        error.message = response.body.error.message;
        error.details = response.body.error.details;

        console.log("##vso[task.logissue type=error;code=" + error.code + ";]");
    }

    return error;
}
```

The code in ServicePrincipals is called from DeploymentScopeBase.getServicePrincipalName() in AzureResourceManagerTemplateDeploymentV3. https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureResourceManagerTemplateDeploymentV3/operations/DeploymentScopeBase.ts#L116

```
    protected async getServicePrincipalName(): Promise<string> {
        try {
            var graphClient: azureGraph.GraphManagementClient = new azureGraph.GraphManagementClient(this.taskParameters.graphCredentials);
            var servicePrincipalObject = await graphClient.servicePrincipals.GetServicePrincipal(null);
            return !!servicePrincipalObject ? servicePrincipalObject.appDisplayName : "";    
        } catch (error) {
            tl.debug(tl.loc("ServicePrincipalFetchFailed", (error.message || error)));
            return "";
        }
    }
```


That method is itself called right at the top of DeploymentScopeBase.performAzureDeployment():

```
    protected async performAzureDeployment(retryCount = 0): Promise<void> {
        if(!this._spnName && this.taskParameters.authScheme == "ServicePrincipal") {
            this._spnName = await this.getServicePrincipalName();
        }

       ...
```

The _spnName field is initialized to null and overwritten in the code above by an actual principal name or by empty string on error. The sad part is that it is actually read just in the printServicePrincipalRoleAssignmentError() method, and it seems that it just provides context to deployment creation failures with response status 403 Forbidden. https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureResourceManagerTemplateDeploymentV3/operations/DeploymentScopeBase.ts#L100

```
    private printServicePrincipalRoleAssignmentError(error: any) {
        if(!!error && error.statusCode == 403) {
            if(this.taskParameters.authScheme == "ServicePrincipal") {
                if(this.taskParameters.deploymentScope == "Resource Group") {
                    tl.error(tl.loc("ServicePrincipalRoleAssignmentDetails", this._spnName, this.taskParameters.resourceGroupName));
                } else if(this.taskParameters.deploymentScope == "Subscription") {
                    tl.error(tl.loc("ServicePrincipalRoleAssignmentDetails", this._spnName, this.taskParameters.subscriptionId));
                } else if(this.taskParameters.deploymentScope == "Management Group") {
                    tl.error(tl.loc("ServicePrincipalRoleAssignmentDetails", this._spnName, this.taskParameters.managementGroupId));    
                }
            } else if(this.taskParameters.authScheme == "ManagedServiceIdentity") {
                tl.error(tl.loc("ManagedServiceIdentityDetails", this.taskParameters.resourceGroupName));    
            }
        }
    }
```

**Comment by TomasMalecek** [comment]
I am seriously confused by the ServicePrincipals class's request URI format. This is the code:
```
        httpRequest.method = 'GET';

        ...

        const clientCredentials = this.client.getCredentials();
        const useMSAL = clientCredentials.getUseMSAL();
        tl.debug(`MSAL - Graph - GetServicePrincipal - useMSAL = ${useMSAL}`);
        const requestUriFormat = (useMSAL ? "v1.0/" : "") + "{tenantId}/servicePrincipals";

        var filterQuery = util.format("appId eq '%s'", clientCredentials.getClientId());
        httpRequest.uri = this.client.getRequestUri(requestUriFormat,
            {
                '{tenantId}': clientCredentials.getTenantId()
            },
            ['$filter=' + encodeURIComponent(filterQuery)]
        );

        tl.debug(`MSAL - Graph - GetServicePrincipal - requestURL = ${httpRequest.uri}`);
```

And these are the two relevant log lines:

```
##[debug]MSAL - Graph - GetServicePrincipal - useMSAL = false
##[debug]MSAL - Graph - GetServicePrincipal - requestURL = https://graph.microsoft.com/326c0a61-9f37-4dce-8adc-xxxxxxxxxxxx/servicePrincipals?$filter=appId%20eq%20'***'&api-version=1.6
```

It looks like [List servicePrincipals using Microsoft Graph API v1.0](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&tabs=http), filtered by appId. The URI host graph.microsoft.com, the GET method, and the "servicePrincipals" path step, filter syntax, and the appId property correspond to that.

But there are severe discrepancies from the API docs.
 1. In Microsoft Graph API, the tenant ID is passed as the tid claim in the access token, not via the URI. That looks more like the [retired](https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview "August 31, 2025: End of extended access to Azure AD Graph. Azure AD Graph will be fully retired.") Azure AD Graph API, even though it was hosted on graph.windows.net and [had no "servicePrincipals" endpoint](https://learn.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-supported-queries-filters-and-paging-options). The [documented pattern of calls for Azure AD Graph API](https://learn.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-operations-overview#endpoint-addressing-) is `https://graph.windows.net/{tenant_id}/{resource_path}?{api_version}`. Its [ServicePrincipal entity](https://learn.microsoft.com/en-us/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#serviceprincipal-entity) also has the appId property.
 2. Microsoft Graph API does not use the api-version query string parameter. `api-version=1.6` hints at Azure AD Graph API again.
 3. Use of MSAL should not influence whether the "v1.0" path step is used -- the API requires it. The [documented pattern of calls for Microsoft Graph API v1.0](https://learn.microsoft.com/en-us/graph/use-the-api#call-a-rest-api-method) is `{HTTP method} https://graph.microsoft.com/{version}/{resource}?{query-parameters}`. Without MSAL (my case, as seen in the logs), the "v1.0" step is omitted, which seems to be the source of the "Invalid version." message sent as part of the 400 Bad Request response that triggers the problematic task.logissue logging command.

Is this just all due to broken migration from Azure AD Graph API to Microsoft Graph API inside this DevOps pipelines tasks infrastructure?
