### ISSUE TITLE
Invalid step task reference AzureContainerApps@V0

### ISSUE THREAD

**Issue by Basssiiie** [microsoft/azure-pipelines-tasks#17543]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: [AzureContainerApps@V0](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureContainerAppsV0)

## Environment
- Server - Azure Pipelines (account name/team name can be supplied in private)
- Agent - Hosted 

## Issue Description

When trying to use the new task  AzureContainerApps@V0 released last month, I get the following error when validating or trying to run a Azure Pipelines yaml:

> Invalid step task reference AzureContainerApps@V0

This specific task is also not available in the tasks assistant in the Azure Pipelines yaml web editor, nor is it recognized by the VS Code extension (though that may be out of scope for this issue).

Do I need to wait for an (undocumented?) scheduled release cycle? Are there some manual actions required to get the newest tasks available to use? We are not self hosting anything in this situation. Looking forward to hearing from you.

Thank you for your time!

**Comment by cormacpayne** [comment]
@Basssiiie Hey there, apologies for the delayed response -- the `AzureContainerApps@1` task is now generally available and shouldn't give you any issues when referencing it in the Azure Pipelines YAML web editor.

You can find relevant documentation outlining how to use the generally available stable version of this Azure Pipelines task [here](https://learn.microsoft.com/en-us/azure/container-apps/azure-pipelines).

Please feel free to let me know if you have any additional questions or comments! I'm going to close this issue since I don't believe there are any actionable items required from our side, but please feel free to let me know otherwise and I'll be happy to re-open this issue.
