### ISSUE TITLE
AzureContainerAppsRC@0 0.1.8 appSourcePath is required

### ISSUE THREAD

**Issue by martinstanek** [microsoft/azure-pipelines-tasks#17687]
Hi there, 
I'd like to report what seems to be a bug within the given task.

*Type*: Bug
**Task Name**: AzureContainerAppsRC@0 - Azure Container Apps Deploy (Release Candidate)

## Issue Description

With the version 0.1.8 we are facing the error when trying to deploy into the container app:
`The arguments appSourcePath and acrName must either be provided together or not at all.`

This was not the case with version 0.1.7 yesterday. 
The condition does not make sense, there is an image provided to the task to be deployed.
The task really should not be concerned about a `appSourcePath`.

We've tried to put a random text into the `appSourcePath` property => the same result.

Many thanks & Cheers,
Martin

'Hosted Agent'
2023-01-31T09:50:06.4800933Z Agent machine name: 'fv-az457-471'
2023-01-31T09:50:06.4801207Z Current agent version: '2.214.1'
2023-01-31T09:50:06.4840062Z ##[group]Operating System
2023-01-31T09:50:06.4840298Z Ubuntu
2023-01-31T09:50:06.4840528Z 22.04.1
2023-01-31T09:50:06.4840655Z LTS
2023-01-31T09:50:06.4840845Z ##[endgroup]
2023-01-31T09:50:06.4841010Z ##[group]Runner Image
2023-01-31T09:50:06.4841200Z Image: ubuntu-22.04
2023-01-31T09:50:06.4841421Z Version: 20230122.1

**Comment by derSchtefan** [comment]
We are seeing the same issue. The task seems to suddenly "infer" what is to be done by the parameters provided. This is a tiny bit confusing, especially because the task documentation says that "acrName" can be specified for authentication purposes when imageToDeploy is specified. 

Instead of inferring what to do, the task should have a command parameter that is "publish", "buildAndPush", just like the Docker build task.

**Comment by heitor-marcos** [comment]
I'm facing the same problem. 
I want to set only the Azure Container Registry Name value in my release pipeline, since my image has already been built and pushed to the container registry by the build pipeline that i have. 
With version 0.1.7 this was possible, but now i'm getting the error:
`the arguments appSourcePath and acrName must either be provided together or not at all.`
if i try to delete the "Azure Container Registry Name" and leave it blank the erro changes because some values become undefined in this commad:
`[command]/usr/bin/bash -c CA_ADO_TASK_ACR_ACCESS_TOKEN=$(az acr login --name undefined --output json --expose-token --only-show-errors | jq -r '.accessToken'); docker login undefined.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p $CA_ADO_TASK_ACR_ACCESS_TOKEN > /dev/null 2>&1`

As can be seen  --name undefined and  docker login undefined.azurecr.io
in version 0.1.7  with only acrName filled in it would generate correctly  replacing the "undefined" with the filled in value in acrName.

**Comment by martinstanek** [comment]
Fixed in the referenced repo:
[****](https://github.com/Azure/container-apps-deploy-pipelines-task/issues/11)
