### ISSUE TITLE
Azure CLI Extension V2 is not respecting the .proxy file in agent folder and the login fails

### ISSUE THREAD

**Issue by Divya1388** [microsoft/azure-pipelines-tasks#17752]
We are using AzureCLI@2 extension on self hosted RHEL agents behind proxy and we have configured the devops agent to use proxy and .proxy file is set up properly in the root of agent folder. However when azure CLI@2 tries to login the task fails with the following error:

failed with error: ERROR: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /***/v2.0/.well-known/openid-configuration (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

Is there a way to let the task use https_proxy instead of going directly.

**Question, Bug, or Feature?**  
*Type*: Bug/Feature

**Enter Task Name**: AzureCLI@2

## Environment
- Server - Azure Pipelines 
 
- Agent - Hosted or Private: 
    
    - Hosted on RHEL Agent and behind proxy

**Comment by Divya1388** [comment]
Hi @rvairavelu  @nadesu  any update on this?

**Comment by rvairavelu** [comment]
We will investigate and share the updates 
@PhilipsonJoseph @v-nagarajku

**Comment by Divya1388** [comment]
@rvairavelu thanks much. Please let me know if we need any further details

**Comment by Divya1388** [comment]
May be if there is a way to inject additional Environment variables to the task, we could inject HTTPS_PROXY and that would solve the issue

**Comment by Divya1388** [comment]
I got this working by usice version 2.* of the task where we can inject environment variables.

**Comment by Divya1388** [comment]
We would still want the extension to respect the .proxy file

**Comment by ycamargo** [comment]
I've dealt with this issue on a recent project. At that time, we moved part of our failing pipeline to a non self-hosted agent. That was a weird workaround because we had to split part of the execution to be on a non self-hosted and part on a self-hosted (with proxy). 
Digging a little bit, I've found that the Azure Pipeline Tasks SDK has a lib module to help with that:  
[Azure Pipelines Task Lib - Proxy module](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/docs/proxy.md)
So, the solution would be to add this lib module to the Azure CLI v2 module.

I will investigate and see if I can do a PR with that fix.

**Comment by ycamargo** [comment]
@rvairavelu or @manolerazvan could you please review my pull request. 
It was a very simple change to add the Proxy module call to inject the HTTP(S)_PROXY variables before running the CLI commands.

**Comment by ycamargo** [comment]
@Divya1388 and @saswatmohanty01 please test it.

**Comment by ycamargo** [comment]
@nadesu / @rvairavelu, I think this bug can be closed.
