### ISSUE TITLE
HelmDeploy@0 task does not support Helm > 3.7.0 for OCI

### ISSUE THREAD

**Issue by stevendick-work** [microsoft/azure-pipelines-tasks#17779]
I am trying to use HelmDeploy@0 to push a Helm chart to our ACR using OCI.

I am using Helm 3.11.1 and received the following error from my ADO pipeline:

/opt/hostedtoolcache/helm/3.11.1/x64/linux-amd64/helm version --client --short
v3.11.1+g293b50c
/opt/hostedtoolcache/helm/3.11.1/x64/linux-amd64/helm chart save /agent/_work/1/s/sample-microservice acrietvdeveuwe1/helm/***/helm/sample-microservice
##[error]Error: unknown command "chart" for "helm"

I was confused why the Helm command 'chart' was being used as this is not documented at helm.sh. Further investigation shows that the 'chart' command was removed in Helm 3.7.0 which was published on 2021-09-15.

As far as I can tell HelmDeploy@0 cannot be used to publish Helm charts as OCI artifacts when using Helm >= 3.7.0.

OCI support in Helm was GA as of 3.8.0, published on 2022-01-22. This task is lagging for over a year with Helm's CLI support for OCI charts.

**Comment by tibitoth** [comment]
This is a serious issue with lack of support for first-party pipeline tasks...

**Comment by TomasTokaMrazek** [comment]
For those poor souls like me, who only have ACR service connection availible without ARM service connection and with no access do Azure tenant, here's the solution.

1) Use `Docker` task with command `login` and proper service connection. The task will create `config.json` under temporary subfolder with random gemerated name. The task luckily exports the directory path as environment variable `DOCKER_CONFIG`.
2) Skip `helm repository login` command, won't be needed.
3) Use `Script` task for commands `helm pull` and `helm push`. Specify argument `--registry-config ${DOCKER_CONFIG}/config.json`. Since Helm uses [same](https://github.com/helm/helm/issues/10156#issuecomment-998545580) auth json structure like Docker, this will work.

Gotta love those hacky reverse engineered solutions.

**Comment by tibitoth** [comment]
bump

**Comment by Patafix** [comment]
This ticket need support

**Comment by ericmattingly** [comment]
This was addressed in the new HelmDeploy@1 task in this PR https://github.com/microsoft/azure-pipelines-tasks/pull/19630
