### ISSUE TITLE
[BUG]: Capturing deployment metadata failed with error: TypeError: Cannot read property 'getAllPods' of undefined

### ISSUE THREAD

**Issue by ewertonhm** [microsoft/azure-pipelines-tasks#17958]
### Task name

HelmDeploy

### Task version

v0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Task log

```shell
##[debug]set helmOutput=Release "csharp-testes" has been upgraded. Happy Helming!
NAME: csharp-testes
LAST DEPLOYED: Thu Mar 16 17:36:42 2023
NAMESPACE: paladinos
STATUS: deployed
REVISION: 6
TEST SUITE: None

##[debug]Processed: ##vso[task.setvariable variable=helmOutput;issecret=false;]Release "csharp-testes" has been upgraded. Happy Helming!%0ANAME: csharp-testes%0ALAST DEPLOYED: Thu Mar 16 17:36:42 2023%0ANAMESPACE: paladinos%0ASTATUS: deployed%0AREVISION: 6%0ATEST SUITE: None%0A
##[debug]publishPipelineMetadata=true
##[debug]which '/azp/_work/_tool/helm/3.11.2/x64/linux-amd64/helm'
##[debug]found: '/azp/_work/_tool/helm/3.11.2/x64/linux-amd64/helm'
##[debug]/azp/_work/_tool/helm/3.11.2/x64/linux-amd64/helm arg: get
##[debug]/azp/_work/_tool/helm/3.11.2/x64/linux-amd64/helm arg: manifest
##[debug]/azp/_work/_tool/helm/3.11.2/x64/linux-amd64/helm arg:  csharp-testes
##[debug]/azp/_work/_tool/helm/3.11.2/x64/linux-amd64/helm arg: --namespace paladinos
##[debug]exec tool: /azp/_work/_tool/helm/3.11.2/x64/linux-amd64/helm
##[debug]arguments:
##[debug]   get
##[debug]   manifest
##[debug]   csharp-testes
##[debug]   --namespace
##[debug]   paladinos
##[debug]chartType=FilePath
##[warning]Capturing deployment metadata failed with error: TypeError: Cannot read property 'getAllPods' of undefined
##[debug]Processed: ##vso[task.issue type=warning;]Capturing deployment metadata failed with error: TypeError: Cannot read property 'getAllPods' of undefined
##[debug]connectionType=None
Finishing: Helm Deploy
```

### Relevant log output

```shell
##[warning]Capturing deployment metadata failed with error: TypeError: Cannot read property 'getAllPods' of undefined
```

### Aditional info

```shell
HelmDeploy gives the following warning even if the deploy if successful:

##[warning]Capturing deployment metadata failed with error: TypeError: Cannot read property 'getAllPods' of undefined


```yaml
steps:
- task: HelmDeploy@0
  displayName: 'Helm Deploy'
  name: helm
  inputs:
    connectionType: None
    namespace: '$(Library.appNamespace)'
    command: upgrade
    chartType: FilePath
    chartPath: '$(appType)'
    releaseName: '$(appName)'
    overrideValues: |-
      replicaCount=$(Global.replicaCount)
      appName="$(appName)"
      namespace="$(Library.appNamespace)"
      environment="$(Stage.environment)"
      deployment_strategy="$(Global.deploymentStrategy)"
      useEnvKeyVaulName='$(Global.useEnvKeyVaultName)'
      keyVaulName="$(Global.keyVaultName)"
      hpa.status="$(Global.hpaStatus)"
      hpa.replicaCount.min=$(Global.hpaReplicaMinCount)
      hpa.replicaCount.max=$(Global.hpaReplicaMaxCount)
      hpa.metrics.targetAverageValue=$(Global.hpaTargetValue)
      hpa.metrics.metricName=$(Global.hpaMetricName)
      resources.limits.cpu="$(Global.resourcesLimitsCpu)"
      resources.limits.memory="$(Global.resourcesLimitsMemory)"
      resources.requests.cpu="$(Global.resourcesRequestsCpu)"
      resources.requests.memory="$(Global.resourcesRequestsMemory)"
      image.repository="$(Global.urlDockerImageRepository)/$(Library.appNamespace)/$(appName)"
      image.imagePullSecret="$(Global.imagePullSecret)"
      image.tag="$(Build.SourceBranchName)-$(Build.BuildNumber)"
      ingress.host="$(prefixoUrlApp)$(Stage.sufixoUrlApp)"
      ingress.enabled="$(ingressEnabled)"
    valueFile: '$(appType)/values.yaml'
    resetValues: true
    force: false
    failOnStderr: true
```
Task Logs:
https://dev.azure.com/HavanLabs/PALADINOS/_build/results?buildId=18503&view=logs&j=920e684c-1d90-57b8-9ac0-16a0f623a670&t=f356c033-eb04-5b3f-668d-19d3e8ce5a0b
```

**Comment by qianz2** [comment]
Hi @ewertonhm,

i'm looking into this issue and was able to reproduce the case here:
`##[warning]Capturing deployment metadata failed with error: TypeError: Cannot read property 'getAllPods' of undefined
`
Looks that kubectlCli will not be initialized if we set `connectionType==None`, that's why getAllPods() function will throw undefined error message here. We'll need to think about the logics here. Should we remove  `command !== "package" && command !== "save" && **connectionType !== "None"**;` from the isKubConfigSetupRequired function.

var isKubConfigRequired = isKubConfigSetupRequired(command);
    var kubectlCli: kubernetescli;
    if (isKubConfigRequired) {
        var kubeconfigfilePath = command === "logout" ? tl.getVariable("KUBECONFIG") : await getKubeConfigFile();
        **kubectlCli = new kubernetescli(kubeconfigfilePath);**
        kubectlCli.login();
    }

function isKubConfigSetupRequired(command: string): boolean {
    var connectionType = tl.getInput("connectionType", true);
    return command !== "package" && command !== "save" && **connectionType !== "None"**;
}

const allPods = JSON.parse((kubectlCli.getAllPods()).stdout);


`##[debug]Processed: ##vso[task.setvariable variable=helmOutput;issecret=false;]Release "stella-release" has been upgraded. Happy Helming!
NAME: stella-release
LAST DEPLOYED: Tue Jun  6 23:03:39 2023
NAMESPACE: default
STATUS: deployed
REVISION: 4
TEST SUITE: None

##[debug]publishPipelineMetadata=true
##[debug]which '/usr/local/bin/helm'
##[debug]found: '/usr/local/bin/helm'
##[debug]/usr/local/bin/helm arg: get
##[debug]/usr/local/bin/helm arg: manifest
##[debug]/usr/local/bin/helm arg:  stella-release
##[debug]exec tool: /usr/local/bin/helm
##[debug]arguments:
##[debug]   get
##[debug]   manifest
##[debug]   stella-release
##[debug]releaseName:  stella-release
##[debug]manifests: test
##[debug]chartType=FilePath
##[debug]kubectlCli: true
##[warning]Capturing deployment metadata failed with error: TypeError: Cannot read property 'getAllPods' of undefined
##[debug]Processed: ##vso[task.issue type=warning;]Capturing deployment metadata failed with error: TypeError: Cannot read property 'getAllPods' of undefined
##[debug]connectionType=None
`

**Comment by qianz2** [comment]
Hi @ewertonhm, we're updating helm.ts file in this PR: https://github.com/microsoft/azure-pipelines-tasks/pull/18517, in the case when customers are using connectionType None and external kubelogin authentication, by setting up KUBECONFIG environment variable to be the kube config file path, it can run kubectl command and get pods command without issues.
