### ISSUE TITLE
[enhancement]: Enable Cache Overwrite

### ISSUE THREAD

**Issue by emohandesi** [microsoft/azure-pipelines-tasks#18708]
### Task name

Cache@2

### Describe your feature request here

Cache overwrite needs to be enabled so that the caching feature will be useful for BitBake and the Yocto project.
The current caching features make it almost useless when building a Yocto project using BitBake. The reason is the way these projects use their cache. I have explained it in more detail below.

**Simplified Version of How Cache is Handled in Yocto**
In the Yocto project, there are a huge number of tasks that are built. When they were built the output of each built task is stored in a subdirectory path of the sstate-cache directory. The following is an example file hierarchy of the cache structure where everything is a directory except the ones that start with `signature`.
```
machine
   ┣━━ sstate-cache
   ┃   ┣━━ ab
   ┃   ┃    ┗━━ cd
   ┃   ┃         ┗━━ signature_cache_abcdxyz123
   ┃   ┃
   ┃   ┣━━ ef
   ┃   ┃    ┗━━ gh
   ┃   ┃         ┗━━ signature_cache_efghxyz456
   ┃   ┗ ...
   ┗ ...
```
In a real-life example, there will be hundreds of such directories. Suppose a cache already exists and we run a new build. There might be some new tasks built that will add some directories to the above hierarchy as shown below.
```
machine
   ┣━━ sstate-cache
   ┃   ┣━━ ab
   ┃   ┃    ┣━━ cd
   ┃   ┃    ┃    ┗━━ signature_cache_abcdxyz123
   ┃   ┃    ┗━━ ij
   ┃   ┃         ┗━━ signature_cache_abijxyz789
   ┃   ┣━━ ef
   ┃   ┃    ┗━━ gh
   ┃   ┃         ┗━━ signature_cache_efghxyz456
   ┃   ┗ ...
   ┗ ...
```
Here, we do not want to re-write the whole cache, instead, we want just the added tasks to be added to the previous cache.
Please notice that there are hundreds of such tasks in a regular BitBake build of the Yocto project and the cache size is in the order of gigabytes.
For more information on how the Yocto cache works, please refer to https://docs.yoctoproject.org/overview-manual/concepts.html#shared-state-cache.

**Comment by markbrockhoff** [comment]
Hi, I belive to have the same issue.

I'm using [Turborepo](https://turbo.build/repo) in my monorepo to cache already built npm packages.
When using a cache key like: `turbo | "$(Agent.OS)"` only the first run of my pipeline on main will be cached. As future runs don't seem to overwrite the cache I basically never have a cache hit...

Expected behavior:

If there's no cache hit, the artifact should be cached for the current scope. If there is a cache hit in a future run the latest version of the cache for the given key should be restored. At the end of the run the existing cache should be updated with the latest artifact of the current run.

As this might not be relevant for the common use case of caching dependencies where one could use the hash of the lockfile to bust the old cache, I'd suggest to make this an opt in feature. For example adding a parameter "overwrite" to the Cache@2 task could do the trick in a non breaking mannor. This would make the task useful for all the monorepo / caching tools out there.

Example:

```yml
- task: Cache@2
      displayName: "♻️ Cache Turborepo"
      inputs:
          key: 'turbo | "$(Agent.OS)"'
          path: $(TURBO_CACHE_DIR)
          overwrite: true
```
