### ISSUE TITLE
[Question]: Can I use a version of the Bash task that's just before 3.226.2? 

### ISSUE THREAD

**Issue by jovere** [microsoft/azure-pipelines-tasks#18844]
### Task name

Bash

### Task version

3.226.2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04 / Ubuntu 14.04 32-bit container

### Question

The latest update for the default bash command (bash@3) has broken my pipeline build:

```shell
/__w/_tasks/Bash_6c731c3c-3c68-459a-a5c9-bde6e6595b5b/3.226.2/bash.js:9
async function runBashPwd(bashPath, directoryPath) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```

This is because I'm using an old version of node (the newest I have available) on a 32-bit container of Ubuntu. I installed node into the container by using the following lines:

```
# Getting node v6 because there's no newer precompiled version in trusty-i386
RUN curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - \
    && curl -sL https://deb.nodesource.com/setup_6.x | bash - \
    && apt-get update && apt-get install -y nodejs

LABEL "com.azure.dev.pipelines.agent.handler.node.path"="/usr/bin/nodejs"
```

Unfortunately, my target application must run on Ubuntu 14.04 32-bit, which is why I'm doing the build inside a container. Is there any way to use the previous revision of the `bash` task that doesn't require node 10 or newer? Or, can somebody direct me how to build a more modern version of node that I can run inside my container, so I can still do my builds? Any help would be greatly appreciated.

**Comment by DmitriiBobreshev** [comment]
Hi @jovere, thank you for the question. Unfortunately, I can't help you with running node10+ on ubuntu 14.04, but, you can pin the task version by using Bash@3.225.0, or any version which is available for your organization.
But I'm afraid that the Bash task started to use node10 a long time ago, as I see [the migrated PR](https://github.com/microsoft/azure-pipelines-tasks/pull/13878/files#diff-b8db794860e72de81068aedb682adbabd99ba3058a0271a283df21bc2ef4f934L115) was 3 years ago and the last version which supported node6 handler was 3.178.0. 
In case your organization doesn't contain the last node6 version of the task, you could [build it](https://github.com/microsoft/azure-pipelines-tasks/blob/a3ab71a48de6991c262590886deecb0d7a38c38f/docs/contribute.md#build-and-test) by yourself, upload to your organization using [tfx-cli](https://github.com/microsoft/tfs-cli/blob/master/docs/buildtasks.md#upload) and use [NodeTaskRunnerInstaller](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/node-task-runner-installer-v0?view=azure-pipelines) to install node6 runner to the agent in some cases, because some agents could not have node6 binaries [inside it](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Misc/externals.sh#L7) (better to check is you agent was built with node6 or not, all node version which agent uses placed in externals folder).

**Comment by jovere** [comment]
@DmitriiBobreshev Thank you very much for your help! I knew I could use top level versioning, but it didn't occur to me that I could get that granular. You have saved me a lot of stress.

I'm also looking into getting the latest node build for this system, but it's going to take a lot of compiling intermediate tools.

Thanks again,
Jeremy
