### ISSUE TITLE
[BUG]: UseNode fails with version set to "18.x" | Cannot read properties of null (reading 'forEach')

### ISSUE THREAD

**Issue by jensheidrich-acn** [microsoft/azure-pipelines-tasks#19315]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

UseNode

### Task version

1.231.0

### Issue Description

We use the task "UseNode" with version as "18.x" and "Check for Latest Version".

Builds are failing since today (2023-11-22) with error:
`##[error]Cannot read properties of null (reading 'forEach')`

Setting a concrete version, e.g. "18.18.2" let it run successful.

I guess the latest changes of the task introduced this issue:
https://github.com/microsoft/azure-pipelines-tasks/pull/19243/files

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04.3

### Relevant log output

```shell
##[error]Cannot read properties of null (reading 'forEach')
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by nsiak** [comment]
We saw the same thing with the same version of the task (1.231.0)

We are running self hosted windows agens and use "version: '20.x'", "checkLatest:  true".
Our quick fix was to set "checkLatest: false", then the tool did use the last cached version (20.9.0)

Now it's working again even when "checkLatest: true", and its now downloading version 20.10.0 of node.

My theory is that https://nodejs.org/dist/index.json returned a empty response. Maybe because of the load with the new version of node.

It does not seem as there is any resilience if nodeVersion:INodeVersion is emtpy, it would be a good idea to fallback to cached versions if this happens. Code:
https://github.com/microsoft/azure-pipelines-tasks/blob/083955360c1ec3878fc3930896293b3b28d3d0ff/Tasks/UseNodeV1/installer.ts#L128C1-L136C8

**Comment by mklenbw** [comment]
Can confirm this error on task-version 1.231.2 with agent 3.230.0.

This broke maybe hundreds of pipelines. Please fix this asap.

**Comment by DenisRumyantsev** [comment]
It is an external issue. The same issue was reported [here](https://github.com/nodejs/nodejs.org/issues/6136).
