### ISSUE TITLE
[BUG]: PublishTestResults@2 fails when searching folder with emojis since v.2.233.2

### ISSUE THREAD

**Issue by yy-2020** [microsoft/azure-pipelines-tasks#19645]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

PublishTestResults@2

### Task version

2.233.2

### Issue Description

The pipeline runs well in v2.233.1. Since 2.233.2 it fails with the error: 
##[error]Error: Failed find: ENOENT: no such file or directory, lstat 'J:\azure-agent\_work\1\s\.git\logs\refs\remotes\origin\wonderland🦄🍭'

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

3.236.1

### Operation system

windows-2019

### Relevant log output

```shell
##[error]Error: Failed find: ENOENT: no such file or directory, lstat 'J:\azure-agent\_work\1\s\.git\logs\refs\remotes\origin\wonderland🦄🍭'
```

### Full task logs with system.debug enabled

<details>
  2024-03-15T12:21:20.9857720Z ##[debug]  D:\a\1\s\.git\logs\refs\remotes\origin\release\32.0 (file)
  2024-03-15T12:21:20.9858260Z ##[debug]  D:\a\1\s\.git\logs\refs\remotes\origin\release\32.1 (file)
  2024-03-15T12:21:20.9877966Z ##[debug]task result: Failed
  2024-03-15T12:21:20.9924075Z ##[error]Error: Failed find: ENOENT: no such file or directory, lstat 'D:\a\1\s\.git\logs\refs\remotes\origin\wonderland🦄🍭'
  2024-03-15T12:21:20.9935935Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Failed find: ENOENT: no such file or directory, lstat 'D:\a\1\s\.git\logs\refs\remotes\origin\wonderland🦄🍭'
  2024-03-15T12:21:20.9937519Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Failed find: ENOENT: no such file or directory, lstat 'D:\a\1\s\.git\logs\refs\remotes\origin\wonderland🦄🍭'
  2024-03-15T12:21:20.9939178Z ##[debug]Release.ReleaseUri=undefined
  2024-03-15T12:21:20.9951305Z ##[debug]Release.ReleaseId=undefined
</details>

**Comment by DmitriiBobreshev** [comment]
Hi @ thank you for reaching us.
We've released a fix, can you please confirm that the error is fixed and could you please specify your current task version?

**Comment by qianz2** [comment]
Thanks for reaching out to us, looks that we'll need to update node version to 20.11.0 which includes a fix to this emoji issue in node library.

**Comment by yy-2020** [comment]
Thank you for the fix. but since Task version 2.240.1, this bug is there again. Could you please have a look? Thank you.

**Comment by DmitriiBobreshev** [comment]
HI @yy-2020, could you please specify an agent version? 
The error itself is node20 problem which was fixed in [20.12.0](https://github.com/nodejs/node/issues/48673#issuecomment-2027996846). If you're using the agent from the started topic(3.236.1) it distributes with [node 20.11.1](https://github.com/microsoft/azure-pipelines-agent/blob/2b80cee166a93abe784c22bb99a1f5f8fac393fe/src/Misc/externals.sh#L20). Could you please try to use latest agent [3.240.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.240.1) with [node 20.13.1](https://github.com/microsoft/azure-pipelines-agent/blob/04e4b9830a9582fbf5c5d9bbe7142caf4d9968e7/src/Misc/externals.sh#L21)?

BTW, checked with the latest agent and seems like everything works well 
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/106314398/438fab8f-efd2-4119-aaed-d74825be9245)

**Comment by yy-2020** [comment]
@DmitriiBobreshev. Yes, after upgraded agents to 3.240.1, pipeline runs well. Thank you. 

Interesting is the combination: agent version 3.236.1 + task version 1.238.0 works well too.

**Comment by DmitriiBobreshev** [comment]
@yy-2020, Task version 1.238.0 runs on node16 which does not have such problems, but, unfortunatelly, this version is EOL so we're migrating the tasks to node20 now, that's why the error started to happen
