### ISSUE TITLE
AzurePowerShell@3 - Failed to Initialize Existing Az modules

### ISSUE THREAD

**Issue by QuickScoP3s** [microsoft/azure-pipelines-tasks#20062]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzurePowerShell

### Breaking task version

5

### Last working task version

5

### Regression Description

Since today, our pipelines are broken with the following warnings & errors:
```
##[warning]Failed to Initialize Existing Az modules, fallback to installation
```
```
##[error]Failed to create access policy: The term 'Set-AzKeyVaultAccessPolicy' is not recognized as the name of a cmdlet...
```

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-2022

### Relevant log output

```shell
##[warning]Failed to Initialize Existing Az modules, fallback to installation
Install-Module -Name Az.Accounts -RequiredVersion 2.19.0 -Force -AllowClobber -ErrorAction Stop -SkipPublisherCheck
Import-Module -Name Az.Accounts -Global -PassThru -Force -RequiredVersion 2.19.0
##[warning]Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide
Imported module Az.Accounts, version: 2.19.0
Update-AzConfig -DisplayBreakingChangeWarning False -AppliesTo Az
Enable-AzureRmAlias -Scope Process
Install-Module -Name Az.Resources -RequiredVersion 6.15.1 -Force -AllowClobber -ErrorAction Stop -SkipPublisherCheck
Import-Module -Name Az.Resources -Global -PassThru -Force -RequiredVersion 6.15.1
Imported module Az.Resources, version: 6.15.1
Install-Module -Name Az.Storage -RequiredVersion 6.1.1 -Force -AllowClobber -ErrorAction Stop -SkipPublisherCheck
Import-Module -Name Az.Storage -Global -PassThru -Force -RequiredVersion 6.1.1
Imported module Az.Storage, version: 6.1.1
Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Clear-AzContext -Scope Process
Clear-AzConfig -DefaultSubscriptionForLogin
Connect-AzAccount 

...

## Initializing Azure Complete
## Beginning Script Execution
##[error]Failed to create access policy: The term 'Set-AzKeyVaultAccessPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by v-schhabra** [comment]
Hi @QuickScoP3s 
Thanks for reporting! Could you please share the complete debug logs of the pipeline at v-schhabra@microsoft.com?

**Comment by QuickScoP3s** [comment]
@v-schhabra Apologies for the delay, sent the logs to your email
Thanks!

**Comment by feliasson** [comment]
This occurs because you have not installed / imported / loaded the `Az.Keyvault` module which contains the `Set-AzKeyVaultAccessPolicy` cmdlet, which should be the reason why your code does not recognize the command as the name of cmdlet. 

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/45947114/fa05274c-6763-4cf1-b13b-cb452961f9b5)
 

#### Note about Windows 2022 image
In the MS-hosted `windows-2022` image the following software exists:
https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md

In this we can see the following:
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/45947114/1a508cce-05a5-4cd5-a3b1-f448ca20cb32)

In [Azure Powershell module 2.1.0](https://www.powershellgallery.com/packages/Az/2.1.0) we can under `Package Details` that module `Az.Keyvault` is installed with version `1.2.0`:
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/45947114/f8b90493-ebeb-42d5-bbc6-db80f9c69515)

So the `Az.Keyvault` module should already exist on the image, but with an really old version, I have no idea why they are not loaded in your code though.

**Comment by v-schhabra** [comment]
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/100183307/b1657d33-7543-4a4b-8eea-82a2806113b8)
Closing this issue as cx is using task AzurePowerShell@5 and it is working fine for them.
