### ISSUE TITLE
NuGet task should log a message saying no files matched the pattern

### ISSUE THREAD

**Issue by emanuelquintero** [Microsoft/azure-pipelines-tasks#4905]
When providing a pattern to the NuGet task and no files were found, the task should inform the user that no matches were found and possibly partially succeeding the task so it's apparent to the user that something didn't really go entirely right.

**Comment by alexmullans** [comment]
Closing this as WF. In the upcoming quarter, we'll be moving away from the full-featured Artifacts-related tasks (which have many issues like this because they mask the underlying tool's output) and recommending calling NuGet directly. See the [design here](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/artifacts-in-pipelines.md) for more details.
