### ISSUE TITLE
TFS 2017 Test Run - Cannot manage test run manually like stop and restart tests

### ISSUE THREAD

**Issue by MSTestAuto** [Microsoft/azure-pipelines-tasks#5314]
In Test Manager, Test Runs can be stopped, and tests can be reset back to active so that they can be rerun again. 

But when the test run is started with the new vnext Build/Release, there is no way of performing these same actions on TFS. Even if the Build/Release that started it is stopped, the Test Run is still In Progress.

Please implement these same features with TFS 2017. We shouldn't lose functionality that we depend on when we chose to upgrade to a later version as it makes it much more difficult for us to work with them.

**Comment by RanjanarMS** [comment]
Thanks for the feedback. I am adding @PBoraMSFT our product owner to take this forward.

**Comment by PBoraMSFT** [comment]
@MSTestAuto - can you specify your scenario, please? 
Are you running tests from a TestPlan using the TestHub ? 
Or are you running tests in the build/release pipeline? If build/release pipeline, are you running using the Visual Studio Test task or the Run Functional Tests task?

**Comment by abhishkk** [comment]
Closing this issue as we haven't got any response for a while. Please reopen the issue if required.

**Comment by smithdws** [comment]
Can we please re-open this issue? I am encountering it. We use TFS 2017 and execute using the browser based Test Hub. My test scenario is that I tried to start a manual test case Run and the Run window never showed. I ended up having to kill the Edge process and re-open Edge (On windows 10) and login to TFS again. I then, in Test Hub, reset the test to active since I couldn't get the Run to open again. I was able to execute the test again and successfully complete the test case. However, when I go to the test run explorer, it shows the original test as In Progress. I can click into it and see all the info contained in it, but I can't stop or mark the test case failed. There just isn't an option to do that I can find on the page.

**Comment by arvindkr-ms** [comment]
Hello @smithdws. I apologize for the inconvenience caused. 

To fix the status of the original test run, you can use the Testmanagement APIs. 

You can use this API: https://docs.microsoft.com/en-us/rest/api/azure/devops/test/results/list?view=azure-devops-rest-5.0 to list all the test results for your in progress run, use the update test results API to mark a particular test as failed if you desire, and use the [Update test run API ](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/runs/update?view=azure-devops-rest-5.0) to change the test run status to Completed. Please let us know if this helps.

**Comment by SadagopanRajaram** [comment]
We have fixed this by aborting the run if the pipeline (build or release) has been cancelled in the latest release of [Azure DevOps Server](https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2019?view=azure-devops). This is also available if you are using Azure Devops Services. I am closing this issue but please do let us know if you need any clarification.
