### ISSUE TITLE
dotnet commands (test/pack) do not work if project depends on authenticated feed

### ISSUE THREAD

**Issue by emanuelquintero** [Microsoft/azure-pipelines-tasks#5319]
There's dotnet commands which implicitly build the projects and implicitly restore packages if needed.
In the case for dotnet pack, the task should probably pass the --no-restore to avoid restoring packages.
There should also be documentation saying that if the project depends on packages coming from authenticated builds, a dotnet restore should be put in place before other dotnet tasks.

**Comment by baywet** [comment]
Ran into the same issue, it's too bad that the preview task for dotnet when in pack mode doesn't accept arguments (like test does for example)

**Comment by alexmullans** [comment]
Closing this as WF. In the upcoming quarter, we'll be moving away from the full-featured Artifacts-related tasks (which have many issues like this because they don't provide the full range of commands supported by the underlying tool) and recommending calling dotnet directly. See the [design here](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/artifacts-in-pipelines.md) for more details.
