### ISSUE TITLE
Azure Resource Group Deployment - Missing override template parameters error should be warning.

### ISSUE THREAD

**Issue by cornillemichiel** [microsoft/azure-pipelines-tasks#5898]
## Environment
- Server - VSTS     

## Issue Description

In our current **VSTS** release pipeline we use the **Azure Resource Group Deployment** step.
(Create Or Update Resource Group)

Every time a new PBI that contains ARM template changes passes we hit the same roadblock.
A developer adds override template parameters  to the VSTS step during feature branch work, and deploys a test release _before merging master._

These new parameters are obviously missing from the current "stable" version of the ARM template (rt/rtp) files. 
Currently the step notifies us about this using an error which stops the release.

**Could you change that error into a warning?**

**Why?**
When we need to hotfix master, the hotfix release won't deploy because the parameters are missing from the old version of the ARM template.  Also consecutive CI merges won't release either.

Currently we resort to creating 'Draft' releases and then copy everything over after merging, but that's an incredible hassle (partly because the person merging into master isn't always the same as the original developer doing the feature branch work.)

**Comment by sachinma** [comment]
@cornillemichiel is it possible for you to use the template parameter file for these inputs. That can be checked in along with the template file. I understand that will not be desirable when the template change has a new secret variable when you would not like to use the check-in the secret. But is that often the case?

I think in general we would like to keep these as errors since that is probably the expected behavior. We can however expose a new setting somewhere in advanced or through a variable to control. @RoopeshNair  can you weigh in on how to expose this functionality

**Comment by cornillemichiel** [comment]
I would argue that this an error is NOT the expected behavior. Version A and version B should both deploy using the same Release pipeline. (How else would could one roll-back to a previous version of the code when things go south?)

Template parameter file is not an option here, in fact, we are planning to move away from using it altogether based on some best-practices advice.  

We have a lot of key vault secrets and we don't want them checked in. 

Would it make sense to "check-in" the "override template parameters" as a settings file?
e.g. vs-arm-parameters.json 

This way it could reside within the same repository as the changed ARM code, and avoid UX clutter in the VSTS task.

**Comment by sachinma** [comment]
If the parameters are secrets, then it would be right to define them as release variables. For other parameters - parameters file might be just fine. However, I understand that it doesn't work for you.
 
The error that you observe is coming from Azure ARM API call. Why I feel that the expected behavior is to fail, is because it might indicate an error while authoring; which we don't want to hide if Azure's behavior is to fail in those cases. Also consider the case, where you want to remove a parameter in the newer version of the template. In such cases, the override parameters will become unmanageable after a time with variables with various versions of template.

The best option would be to source control the parameters file along with the template. I liked the proposal where parameters file can reference the variables defined in the release definition. @RoopeshNair on his view on this or any other alternates to solve this problem.

**Comment by cornillemichiel** [comment]
An alternative idea... 
Is it absurd to just override all parameters that match a VSTS variable by default? Is this purely because of name incompatibilities? Because then override template parameters could change to "Map template parameter variable names"

e.g. 

In keyvault "some-secret-name-1" :"some-secret-value-1"
In ARM template "secret-name-1"

- Auto Override Parameters with same name: [_V_]
- Map template parameter names: "-some-secret-name-1 'secret-name-1'"

**Comment by RoopeshNair** [comment]
@cornillemichiel, for now, you have following options. Manage the secrets in Azure KeyVault and have [template parameters json ](https://azure.microsoft.com/en-in/blog/keyvault-support-for-arm-templates/)which reference these variables. Or you can have tokenize step before ARM template deployment step which can replace the tokens with secrets from release variables

**Comment by cornillemichiel** [comment]
This issue can be closed. YAML multi stage completely resolves my underlying concerns.
