### ISSUE TITLE
Task: "Index Sources & Publish Symbols" v2 does not work on Linux

### ISSUE THREAD

**Issue by CumpsD** [Microsoft/azure-pipelines-tasks#5919]
## Environment
- Server - VSTS or TFS on-premises? VSTS
- If using VSTS, provide the account name, team project name, build definition name/build number: 
https://agiv.visualstudio.com/Vlaamse%20Basisregisters/Vlaamse%20Basisregisters%20Team/_build/index?buildId=38007&_a=summary

- Agent - Hosted or Private:  Hosted
- If using Hosted agent, provide agent queue name: Hosted Linux Preview

## Issue Description

I tried to use the Index Sources & Publish Symbols as described at https://docs.microsoft.com/en-us/vsts/build-release/symbols/index?toc=/vsts/package/toc.json

However, it seems this does not work on Linux?

```
2017-11-24T11:41:14.8776090Z ##[section]Starting: Publish symbols path: 
2017-11-24T11:41:14.8820260Z ==============================================================================
2017-11-24T11:41:14.8833820Z Task         : Index Sources & Publish Symbols
2017-11-24T11:41:14.8847750Z Description  : Index your source code and publish symbols to a file share or Visual Studio Team Services Symbol Server
2017-11-24T11:41:14.8861380Z Version      : 2.0.3
2017-11-24T11:41:14.8876850Z Author       : Microsoft Corporation
2017-11-24T11:41:14.8890870Z Help         : See [more information](https://go.microsoft.com/fwlink/?LinkID=613722) on how to use this task. The Visual Studio Team Services Symbol Server is in private preview. See [these instructions](https://go.microsoft.com/fwlink/?linkid=846265) on how to participate in the private preview.
2017-11-24T11:41:14.8904330Z ==============================================================================
2017-11-24T11:41:15.0321090Z ##[error]A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.
2017-11-24T11:41:15.0364740Z ##[section]Finishing: Publish symbols path: 
```

**Comment by Rabadash8820** [comment]
I am getting this same error.  I am using a private agent: Ubuntu 16.04 hosted on an AWS EC2 instance.  Everything works fine in my ASP.NET Core build definition except for the Publish Sources task.  I can't find any documentation anywhere that says this task shouldn't run on Ubuntu, so some Microsoft feedback here would be appreciated!

**Comment by xtumiox** [comment]
Are there any updates on this? I'm having the same issue on a macOS private agent.

**Comment by mitchdenny** [comment]
Thanks for reporting this (and sorry for the delay on following up). Currently symbol publishing is only supported on Windows agents. The Visual Studio team is working on adding .NET Core source linking support for VSTS to the debugger. When that lands we will look at what we need to do to bring the symbol publishing experience to Linux and macOS agents.

At this stage, this limitation is by design but we would like to change that once he other necessary elements are in place.

**Comment by CumpsD** [comment]
Use this: https://github.com/ctaggart/SourceLink/blob/master/README.md#package-pdb-in-nupkg

works on linux :)

**Comment by brent-robinson** [comment]
Thank you @CumpsD! SourceLink worked well to index the PDBs. I used the [official Microsoft version](https://github.com/dotnet/sourcelink/) which wasn't available when this issue was raised.

Having indexed the PDBs, I tried to them publish using the VSTS task, however even with indexing turned off (`indexSource: false`) the task still fails to run on Linux.

In light of [this discussion](https://github.com/aspnet/Universe/issues/131#issuecomment-363269268) on the matter I'm going to include my indexed PDBs into my NuGet package. The package is for private use only. For anyone else, the last 4 comments of that discussion are worth reading to understand the reasoning.

**Comment by blushingpenguin** [comment]
I get the following out of the task:

```##[section]Starting: Publish symbols path
==============================================================================
Task         : Index sources and publish symbols
Description  : Index your source code and publish symbols to a file share or Azure Artifacts symbol server
Version      : 2.0.16
Author       : Microsoft Corporation
Help         : See [more information](https://go.microsoft.com/fwlink/?LinkID=613722) on how to use this task.
==============================================================================
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
##[section]Finishing: Publish symbols path
```

not sure why it's been closed?

**Comment by totollygeek** [comment]
Is this fixed now? On our On-Premises AzureDevOps server, which should be latest version, still does not work...

**Comment by dozer75** [comment]
@mitchdenny wrote:
> Thanks for reporting this (and sorry for the delay on following up). Currently symbol publishing is only supported on Windows agents. **The Visual Studio team is working on adding .NET Core source linking support for VSTS to the debugger. When that lands we will look at what we need to do to bring the symbol publishing experience to Linux and macOS agents.**
> 
> At this stage, this limitation is by design but we would like to change that once he other necessary elements are in place.

I think that this should be reopened since the reason why this issue was closed has failed. .NET Core Source Linking does not work with .NET Core 3 or later due to issues with changes done during builds of applications based on .NET Core 3 and it seems not to be any priority fixing this from the dotnet/sdk team (root issue dotnet/sdk#1458 has been open for over 3 years). 

Source Link with Azure DevOps artifacts is not supported since Azure DevOps artifacts doesn't support `snupkg` packages and the ["Alternative PDB distribution"](https://github.com/dotnet/sourcelink#alternative-pdb-distribution) doesn't work in .NET Core 3 or later (and in addition .NET Framework) due to lacking support to copying the pdb file to the build directory. The only (and [recommended way](https://github.com/dotnet/sourcelink/issues/274#issuecomment-502193122_)) to do this now in Azure DevOps is to use the PublishSymbols with Azure pipelines which again doesn't work on Linux.

This issue dotnet/sourcelink#628 describes the Source Link issue quite well.

**Comment by cmenzi** [comment]
> I think that this should be reopened since the reason why this issue was closed has failed.

Absolutely agree. The issue is not solved and because .NET Core / SourceLink has Linux support, Azure Artifacts should really support that.

**Comment by johnterickson** [comment]
Please upvote an existing feature request (or create a new one) on https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea

**Comment by Grimlek** [comment]
As a workaround what I did, build everything on the linux box, and publish the artifact. 

On a windows agent download the artifact (don't forget - checkout: none), rename the .snupkg to .zip, and extract the .zip file. From there I pushed the .pdb file to the symbol server.

`stages:
- stage: BuildAndPublish
  displayName: 'Linux Build/Publish & Windows Publish Symbols'
  jobs:
  - job: LinuxBuildAndNugetPush
    displayName: 'Linux Build Agent, Replace Tokens, .Net Build/Pack, and Nuget Push'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace tokens in **/*.config'
      inputs:
        targetFiles: |
         **/*.config
          **/*.csproj
        escapeType: none
        verbosity: detailed
        keepToken: true
    
    - task: DotNetCoreCLI@2
      displayName: '.Net Build & Pack'
      inputs:
        command: pack
        packagesToPack: '**/*.csproj'
        arguments: '-p:SymbolPackageFormat=snupkg --output $(Build.ArtifactStagingDirectory) --configuration $(buildConfiguration)'
        versioningScheme: 'off'
        includeSymbols: true
        includeSource: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts for Windows Agent'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'NupkgWithSymbols'
        publishLocation: 'Container'
    
    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;$(Build.ArtifactStagingDirectory)/*.snupkg'
        nugetConfigPath: 'nuget.config'
        publishVstsFeed: 'PayTelVSTSNuGet'
        allowPackageConflicts: true
        versioningScheme: 'off'
        nobuild: true
  
  - job: WindowsPublishSymbols
    displayName: 'Publish Symbols to Azure Symbol Server'
    dependsOn: LinuxBuildAndNugetPush
    pool:
      vmImage: 'windows-latest'
    
    steps:  
    - checkout: none

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts from Linux Agent'
      inputs:
        buildType: 'specific'
        project: 'myProject'
        pipeline: 'myPipeLineId'
        buildVersionToDownload: 'specific'
        buildId: $(Build.BuildId)
        allowPartiallySucceededBuilds: true
        downloadType: 'single'
        artifactName: 'NupkgWithSymbols'
        downloadPath: '$(Build.ArtifactStagingDirectory)'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $sourceFiles = Get-ChildItem "$(Build.ArtifactStagingDirectory)\**\*.snupkg"
                    
          foreach ($file in $sourceFiles) {
              $newfilename = "NupkgWithSymbols.zip"
              Write-Host "Attempting to rename file $($file.fullName) to $($newfilename)"
              Rename-Item $file.fullName -NewName $newfilename 
              Write-Host "Rename File Success"
          }

    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '$(Build.ArtifactStagingDirectory)\**\*.zip'
        destinationFolder: '$(Build.ArtifactStagingDirectory)'
        cleanDestinationFolder: false
        overwriteExistingFiles: false
          
    - task: PublishSymbols@2
      displayName: 'Publish Symbols'
      inputs:
        SearchPattern: '$(Build.ArtifactStagingDirectory)\**\*.pdb'
        SymbolServerType: 'TeamServices'
`

**Comment by cmenzi** [comment]
I've created an Azure Function and upload the nuget to its blob. Then I unzip it and use symbol.exe to index them.
