### ISSUE TITLE
Feature Request: Add an option to check if the target file is new or the same

### ISSUE THREAD

**Issue by ironicnet** [microsoft/azure-pipelines-tasks#6111]
Currently we are using an FTP Upload to upload some files.
But right now, each FTP Upload is overwriting everything, when actually some little files changed only.

I think that it would be great to have some kind of "Overwrite if source is newer or has changed".

I'm pretty sure that the "remoteExists" could be changed to "getRemoteInfo" to retrieve stuff like the length of the remote or last write datetime. Or null (or false) if inexistant.

https://github.com/Microsoft/vsts-tasks/blob/9be07f68e51eded68b24e33549935eb4b12165a1/Tasks/FtpUpload/ftputils.ts#L176

**Comment by ArieHein** [comment]
from a devops perspective overwriting is safer, no chance unwanted files or manually changed files get to stay in the ftp folder. Id even make sure its completely empty before the copy. This way I know exactly what was moved and when.
Other option is move all every time and then add a step to remotely do a robocopy with /MIR from the ftp folder and add exclusion based on file properties.

**Comment by kalexii** [comment]
Hey, guys. Any news regarding this issue? Full overwriting FTP upload takes 15 minutes for my scenario, with only 4 files changed.

**Comment by yacaovsnc** [comment]
This isn't planned yet.  It would be a really useful feature, however we need to be careful about how to determine that files are identical - many config files don't change size (for example, if a secret is rotated in the file), then we can only rely on timestamps, but clocks on the remote ftp server could be skewed.  In any case, please open a feature suggestion ticket on [developer community](https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea) so others can find that ticket more easily and upvote the issue.

**Comment by ArieHein** [comment]
@kalexii what prevents you from creating your own mechanism of sending the content of the folder into a file like txt or scv or json / xml before and since you know what you sent last time you can either do a compare to that or actually get the info from the ftp and then just decide what to copy based on your own paramters. Use powershell to query content namd make the appropriate decision or go a head and use the extension marketplace for things like
https://marketplace.visualstudio.com/items?itemName=januskamphansen.ftpupload-task
