### ISSUE TITLE
Insufficient privileges while running Azure Active Directory command on powershell

### ISSUE THREAD

**Issue by mohantyrr2003** [Microsoft/azure-pipelines-tasks#6159]
Hi,

I am getting error "insufficient privileges" while running an AD command to my Azure Data Lake Store account I am creating via PowerShell. I am able to create the DLS account, however when I am trying to assign a group (admin group) to be the owning group, it fails with error "insufficient privileges". The command goes like this.

PS H:\> Set-AzureRmDataLakeStoreItemOwner -AccountName $dataLakeStoreName -Path / -Type Group -Id (Get-AzureRmADGroup -SearchString $owninggroup).Id

Please suggest what needs to be done to get past the error.

P.S - It's happening when I am trying on powershell as well as on VSTS using PS script to create the DLS account in a CICD manner.

Thanks,
Radha

**Comment by xenalite** [comment]
@mohantyrr2003 I had a similar issue when assigning a group to Azure Key Vault access policies.
It also failed with "insufficient privileges" error message. 
Luckily, Azure PowerShell command had a flag -IgnoreObjectIdValidation or something like that.
If I tried to query for a group with `Get-AzureRmADGroup`, it would return nothing - so you have to know the object ID of the group ahead of the time.

If you use Service Principals, they do not have access to query Azure AD by default. This is by design - only AAD user identities can query AAD. To query AAD with a Service Principal, you need a tenant administrator to grant you permissions to `Read directory data`.

Another use case I had was to use a Service Principal to manage other AAD Web API applications (add reply URLs dynamically in CI). This is not possible without tenant administrator granting you those rights.

An alternative is to use a user identity and log in via normal PowerShell task, e.g my task to add reply URL:
```
$securePassword = ConvertTo-SecureString -String '$(AzureAdManagementPassword)' -AsPlainText -Force
$credentials = [PSCredential]::new('$(AzureAdManagementUsername)', $securePassword)
Login-AzAccount -Credential $credentials -Scope Process

Import-Module '$(PowerShellModulePath)' -Force
Add-ReplyUrlToAzureAdApp -ReplyUrl '$(ReplyUrl)'

Logout-AzAccount -Scope Process
```

**Comment by vincentdass** [comment]
@mohantyrr2003  Can you try the recommendation provided by @xenalite and reopen the thread if it doesn't work?
