### ISSUE TITLE
DotNetCore currently does not support using an encrypted Api Key

### ISSUE THREAD

**Issue by lostmsu** [microsoft/azure-pipelines-tasks#7160]
Problem: can't push packages to nuget.org with dotnet nuget push task without exposing API key in build definition

## Environment
- Server - VSTS Online
- Agent - Hosted 2017

### Error logs

Using authentication information for the following URI: https://api.nuget.org/v3/index.json
Error: DotNetCore currently does not support using an encrypted Api Key.
Packages failed to publish

**Comment by bryanmacfarlane** [comment]
Can you detail what you mean by "exposing API key"?  Something in a log?   Something else?

**Comment by lostmsu** [comment]
@bryanmacfarlane everyone who can read build definition can read the API key.

Previously I used NuGet Publisher task, that allowed to pick a preconfigured connection, which would store credentials on the VSTS side. The new dotnet task + nuget push command also allows to pick the same connection, however it fails with the error above.

**Comment by aldoms** [comment]
Using an ApiKey is currently not supported in dotnet because the required libraries for encrypting the  key are not available, sorry for the inconvenience. You should be able to use a service endpoint configured with a username/password combination. If you can only use an ApiKey, I would suggest using the nuget 2.* task to push.

**Comment by alexmullans** [comment]
Using the NuGet task is the correct workaround here, as @aldoms recommends. We're currently working 
with the NuGet and dotnet teams (https://github.com/NuGet/Home/issues/6486) to improve the story for authenticated feeds and dotnet. As Aldo mentioned, some of the cryptography libraries that NuGet.exe uses on Windows don't have .NET Core (i.e. Mac/Linux compatible) equivalents yet, which is why this scenario doesn't work today.

**Comment by ChristopherLClark** [comment]
The issue with failing build when configuring dotnet nuget push task for external feed using managed credentials still worth addressing.

This does not work for us either.

**Comment by ChristopherLClark** [comment]
We must be able to do this through managed external feeds.

**Comment by astaerk** [comment]
I moved to the NuGet task like recommended by @aldoms  and @alexmullans 
This works, but dotnet nuget push also pushes symbols.
What is the workaround for publishing symbols? It seems like the NuGet task can't do it and the 'Index Sources & Publish Symbols' task only can publish to vsts or to a file share, but not to any official repo, right?

**Comment by alexmullans** [comment]
The NuGet task can also publish symbols - you just need to remove the `;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg` section of the default "Path to NuGet package(s) to publish" field, if it's still present.

**Comment by astaerk** [comment]
Ok, I already tried that, but I tried it with TFS. But now I realize this is a restriction of TFS. So you're saying this works with the official NuGet.org? Ok, I'll give that a try. Thanks!

**Comment by alexmullans** [comment]
Closing this due to age and inactivity.

**Comment by SpyderHunter03** [comment]
Why did we close this ticket?  The issue is still a valid issue that should get fixed.  If you offer a "service" and the "service" doesn't work, then it is a bug and should be fixed one way or another.  You can initially offer workarounds, but you should be actively fixing the issue and not just closing it.

**Comment by ScottyMac52** [comment]
> If you put the secret in a variable on the variables tab and click the lock, it puts it in a strong box encrypted and readers of the definition can't read it. It's set once. At run time the service will include it in the encrypted job message to the agent and the agent will only make it available to that task.

That reply did not solve the issue he was having and now I am having it. It was unprofessional to close this ticket!

**Comment by alexmullans** [comment]
@SpyderHunter03 @ScottyMac52 sorry for the closure, was in a triage pass trying to get a handle on our (substantial) bug count in this area. You're right that we should not have closed this.

Since we last updated the .NET Core task's NuGet functions (`restore`, `pack`, and `nuget push`), .NET Core has updated and added the ability to provide an API key on the command line and publish. If memory serves (it's been a while), this wasn't available then. I'll reopen this for tracking. We expect to make substantial updates to these tasks in Q2.

**Comment by marcwittke** [comment]
Well, this is biting me, too.

Pain started, when I wanted to push my nuget package with symbols. Learned, that the preferred way is the `snupkg` format, so I was goning down that alley. (Also learned that myget does not support it yet, but that's another story)

First try, using the nuget task (version 2.*):
```
[command]/usr/bin/mono /home/agent/agent/~/agent/work/_tool/NuGet/4.1.0/x64/nuget.exe push /home/agent/agent/<bla>.snupkg -NonInteractive -Source https://api.nuget.org/v3/index.json -ApiKey *** -ConfigFile /home/agent/agent/work/_temp/Nuget/tempNuGet_4322.config -Verbosity Normal
2019-06-27T11:19:39.5055024Z 400 (Snupkg upload failed. Please use latest NuGet clients (v 4.9.0 or above) and a V3 endpoint to push Symbol packages. For details, refer https://docs.microsoft.com/nuget/create-packages/symbol-packages-snupkg)
```

Okay, the nuget task is using an outdated nuget.exe. Well, there is `dotnet nuget push` as well. But:
```
 ##[error]Error: DotNetCore currently does not support using an encrypted Api Key.
```

😠 , well, let's do this as a custom task and write the API Key into the params... But:
```
[command]/home/agent/agent/work/_tool/dotnet/dotnet nuget push /home/agent/work/r1/a/<bla>.nupkg -s https://api.nuget.org/v3/index.json -k {{mykey}}
No executable found matching command "dotnet-nuget push"
##[error]Error: The process '/home/agent/agent/work/_tool/dotnet/dotnet' failed with exit code 1
```

WTF? copying and pasting the command into a shell works like a charm. So what's going on, at least the last one should work.

Sure, I could run a bash script, but this cuts the possibility to use the globbing feature 😢

**Comment by lrushl** [comment]
> WTF? copying and pasting the command into a shell works like a charm. So what's going on, at least the last one should work.

@marcwittke , in order to fix this please make sure your task looks like this 
```yml
- task: DotNetCoreCLI@2
  displayName: Push Nuget Package
  inputs:
    command: custom
    custom: nuget
    arguments: >
      push $(Build.ArtifactStagingDirectory)/*.nupkg
      -s $(NuGetSourceServerUrl)
      -k $(NuGetSourceServerApiKey)
```

But yeah, still duplication is needed (nupkg/snupkg), unfortunately :(

**Comment by RehanSaeed** [comment]
It should also be noted that the `allowPackageConflicts` argument only exists on `NuGetCommand`. There seems to be no way with with `DotNetCoreCLI` to get it to publish several .nupkg's when one of them returns 409 Conflict because the package already exists.

**Comment by twsI** [comment]
Any ETA, when we can expect a proper solution to this issue?

**Comment by Postlagerkarte** [comment]
This issue is open now for 531 days, 12 hours, 10 minutes and 23 seconds and there is still no solution? At least throw us an explanation of why it takes so long?

**Comment by aasim** [comment]
Hi @Postlagerkarte - sorry for the delay, but I think we do have a solution to your original issue now. 
 
We have recently released the NuGetAuthenticate task that can be used in a pipeline to authenticate with Azure Artifacts and/or other NuGet repositories. The design philosophy behind this task is that we would authenticate all the repositories you describe in this task, and get out of the way leaving you fully in control of running your nuget or dotnet commands in the pipeline as you see fit. You can read more about the NuGetAuthenticate task [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops). It also gives some examples on how to configure the task.

In your case, you can create a [service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-nuget) to nuget.org and add the NugetAuthenticate task at the start of your pipeline with this service connection as input. After that you can add just a regular powershell task to run `dotnet nuget push`, and it should work as expected. Let me know if this solution doesn't work for you and we can fix any other underlying issues.

Aasim

**Comment by twsI** [comment]
This is not really a sastisfying solution to the issue. I expect the dotnet commands to work just like on my own machine. Having to use workarounds is quite annoying.

**Comment by MarkKoz** [comment]
@aasim That is not correct. The [docs state](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops#how-do-i-configure-a-nuget-package-source-that-uses-apikey-nuget-api-keys-such-as-nugetorg) that task also doesn't support service connections using API keys. We basically have to do [this](https://github.com/Microsoft/azure-pipelines-tasks/issues/7160#issuecomment-509044113).

**Comment by Jin-JBA** [comment]
@aasim  as mentioned by @MarkKoz, NuGetAuthenticate task does not support API key, I am getting the error below while using this task.

`ApiKey service connections are not supported in this task. Instead, use -ApiKey (NuGet) or --api-key (dotnet) when invoking the tool itself. See the task documentation for more details.`

**Comment by knight1219** [comment]
I can confirm that the NugetAuthenticate task doesn't support APIKeys still.

**Comment by winstonhenke** [comment]
So many hoops to jump through just to use a private NuGet feed. So I if I need to build a project that uses X private feeds I'll need to add X tasks like the one above? That seems slow and bloated.

**Comment by babelshift** [comment]
2 years later and no progress on this. Is this on any roadmap to be addressed?

**Comment by edgarrs** [comment]
Take a look at this "how do I" answer:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops#how-do-i-configure-a-nuget-package-source-that-uses-apikey-nuget-api-keys-such-as-nugetorg

**Comment by ScottyMac52** [comment]
So, you post an article from 8/2019 and then simply close the issue? That's
really poor customer service!

**Comment by babelshift** [comment]
Are we to assume that this will never be addressed now that the issue is
closed?

**Comment by ScottyMac52** [comment]
That certainly was my reasonable assumption.

**Comment by twsl** [comment]
The nuget solution has been posted over and over. Closing this by saying "ignore this bug, use another method" is a really shitty decission.

**Comment by lostmsu** [comment]
@edgarrs the workaround in the second post actually works. The problem is that **user interface** for creating a .NET Core CLI `push` task permits you to select a service connection, that was established with an API key.

The proper fix would be to:
1. In the .NET Core CLI push task UI show an error when unsupported connection is picked.
2. Add the docs link you provided to the UI.
3. Add a field to enter arguments to .NET Core CLI push task so that I could type `--api-key $(NuGetOrgKey)` there like in the build task:
![image](https://user-images.githubusercontent.com/239520/89700202-3401dd00-d8e1-11ea-8608-08a728e4f5ad.png)

**Comment by anmalkov** [comment]
I confirm - the issue is still there. Unfortunately, it's affected my customer. But using NuGetCommand@2 instead of DotNetCoreCLI@2 solved the problem. But I think it is not a solution, just a workaround.

**Comment by yozepi** [comment]
August, 2021 and the issue still exists. It's horrible that you believe sparsely documented workarounds is a satisfactory. Instead you are satisfied to let poor slobs like me waste **HOURS** fumbling through posts like these to try and find an answer. Shame on you MS!

**Comment by Camble** [comment]
Nobody is going to check on this issue as it's closed.

**Comment by woeterman94** [comment]
I created a new issue for the same problem: https://github.com/microsoft/azure-pipelines-tasks/issues/15569

**Comment by tpaulshippy** [comment]
> > WTF? copying and pasting the command into a shell works like a charm. So what's going on, at least the last one should work.
> 
> @marcwittke , in order to fix this please make sure your task looks like this
> 
> ```yaml
> - task: DotNetCoreCLI@2
>   displayName: Push Nuget Package
>   inputs:
>     command: custom
>     custom: nuget
>     arguments: >
>       push $(Build.ArtifactStagingDirectory)/*.nupkg
>       -s $(NuGetSourceServerUrl)
>       -k $(NuGetSourceServerApiKey)
> ```
> 
> But yeah, still duplication is needed (nupkg/snupkg), unfortunately :(

One thing to note on this workaround - if you are on a windows agent, the slash before *.nupkg has to go the other way.

**Comment by JoshStrauss** [comment]
Any updates this is still happening! Also happens for restore
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/35844167/2f2a0f5f-86f1-451b-a735-fad1b5d385d1)

**Comment by rklec** [comment]
This is really a pain and should be fixed. I have an access-restricted feed (`restore` is restricted!) in a different Azure DevOps collection/organisation. This is a pain because:
1. "TfsAuth" with `externalFeedCredentials` does not work. (due to this issue I guess/IIRC)
2. "API Key auth" via `externalFeedCredentials` does not work (due to this issue).
3. the recommend workaround [here](https://github.com/Microsoft/azure-pipelines-tasks/issues/7160#issuecomment-509044113) via specifying the API key manaually does not work for `restore` [as `restore` cannot be supplied an API key via the CLI](https://stackoverflow.com/questions/62914467/how-to-use-an-api-key-with-dotnet-restore-with-private-nuget-server#64185328) for whatever strange reason
4. manually saving the (encrypted, this is the only way it works) in `Nuget.config` does not work.
5. Switching to `Nuget` task does not work due to `mono` missing then in the .NET SDK docker image, see https://github.com/microsoft/azure-pipelines-tasks/issues/13499 [or here](https://stackoverflow.com/questions/69275451/install-mono-for-nuget-deployment-in-azure-devops). If I install it afterwards (`apt install mono-complete`), it still fails.
6. the workaround from https://stackoverflow.com/questions/62914467/how-to-use-an-api-key-with-dotnet-restore-with-private-nuget-server by adding a custom source to your Nuget config file using username/password credentials (with a login I have assigned contributor access to the other custom feed) still does not work. You just get:
   > error NU1301: Unable to load the service index for source
  https://stackoverflow.com/questions/72816517/azure-devops-nuget-restore-fails-with-unable-to-load-the-service-index-for-sour
7. Even setting the other feed as an upstream from one organisation to another is not possible.

All in all, I find **no way at all** to somehow restore a different feed from a different organization. 

And this just happens because of some strange bug here that api keys do not work and you have to jump through everywhere and find nothing documented about this except _closed_ GitHub issues. This is really a pain!

**Comment by rklec** [comment]
Also https://learn.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops&tabs=classic#restore-nuget-packages-from-a-feed-in-a-different-organization is a guideline explicitly about this issue at hand and IIRC I have tried it with an access token before and this also ends in this error here, because it only works with Nuget, not the `dotnet` task.

**Comment by theolivenbaum** [comment]
Any updates on this? as @halllo mentioned, this is now problematic as the latest ubuntu image on Azure Devops does not support the NuGetCommand@2 task anymore.

**Comment by JeffreyH89** [comment]
Hello,

After the recent change on this task (https://github.com/microsoft/azure-pipelines-tasks/commit/7772a38426aa7559ccb3822d65e83fb225403ad3) we are also encountering this issue.

When we remove the argument feedsToUse: 'config' then it works again.

**Comment by WoozChucky** [comment]
Any updates on this ?
I'm also encountering the same problem using an external feed (Nexus) and self hosted DevOps and tryint to push a nuget.

**Comment by methode-user-1** [comment]
Any update on this?
