### ISSUE TITLE
VSTS | .NET Core Task | Custom command should support feed authentication

### ISSUE THREAD

**Issue by letmaik** [Microsoft/azure-pipelines-tasks#7359]
I'm trying to run `dotnet add` via the custom command option of the .NET Core task, however this then fails if the package to add is in a VSTS feed since this custom command option does not support feed authentication. Does it make sense to add support for that?

**Comment by alexmullans** [comment]
@sachinma sure. something we're interested in, but not coming in the next few sprints. We're first working on bringing Credential Provider support to dotnet (which gives us the hooks we need to do auth well in the build tasks)

**Comment by jim-paton** [comment]
Any progress on this? I need to install a .Net Core Global Tool from my private Azure Artifacts feed as part of a release pipeline, I tried using the **custom** command to do this, but unlike the **restore** / **push** commands, it doesn't appear to support access to the Azure Artifacts feeds? If not, can someone suggest a workaround?

**Comment by alexmullans** [comment]
Closing this as WF. In the upcoming quarter, we'll be moving away from the full-featured Artifacts-related tasks (which have many issues like this because they combine authentication with the command you're trying to run) and recommending calling dotnet directly. See the [design here](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/artifacts-in-pipelines.md) for more details.
