### ISSUE TITLE
tl.loc doesn't work in securefiles-common.ts

### ISSUE THREAD

**Issue by hashtagchris** [Microsoft/azure-pipelines-tasks#7491]
`tl.loc('ErrMsg')` doesn't work in securefiles-common.ts, unless you add the resource string to the consuming tasks. Adding the message to module.json isn't sufficient, at least in the case of InstallAppleCertificateV2. Based on the conversation in #7486, it looks like we need to move to v2.2.0 of the task lib. That will probably requiring moving all consuming tasks to v2.2.0 of the task lib, unless common can somehow have it's own task lib version.

**Comment by bryanmacfarlane** [comment]
Only tasks that (1) use common and (2) don't want to duplicate strings need to go to that task-lib version which has the capability.

It's not clear what work this issue is tracking other than stating how it works.

IMHO, common causes more issues than it's often worth (npm packages are better or sometimes just copying a function).

**Comment by hashtagchris** [comment]
Fixing this issue is blocked by [a mocking issue](https://github.com/Microsoft/vsts-task-lib/issues/372).

**Comment by brcrista** [comment]
Agree with @bryanmacfarlane , our "common" code should not be long for this world.

**Comment by madhurig** [comment]
Closing this old issue since we have a workaround.
