### ISSUE TITLE
Dotnet Custom - How to specify package version to be the one defined in options/build number format?

### ISSUE THREAD

**Issue by malovicn** [microsoft/azure-pipelines-tasks#7653]
I am trying to setup Nuget pack with --include-symbols and seems I have to use dotnet custom but once using that not sure how to specify the package version to be automatic (as it is on dotnet pack)

Here are my attempt of dotnet custom

![2018-07-08_1121](https://user-images.githubusercontent.com/1417610/42418764-55310768-82a7-11e8-8038-b5dde9496761.png)

Here are my options 
![2018-07-08_1203](https://user-images.githubusercontent.com/1417610/42418746-058763ba-82a7-11e8-9008-0c20ecdd6c24.png)

Here is the relevant part of logs
[Logs.txt](https://github.com/Microsoft/vsts-tasks/files/2173612/Logs.txt)

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!

For this issue, you could maybe look into nuget instead of dotnet.
