### ISSUE TITLE
Azure App Service Deploy task: Set ACR credentials on Web App during deploy

### ISSUE THREAD

**Issue by nphmuller** [microsoft/azure-pipelines-tasks#7654]
In version 4.1.10 of the Azure App Service Deploy task it's possible a Web App for Containers.
This basically settings the app setting `DOCKER_CUSTOM_IMAGE_NAME`.

For private registries the following settings are also required:
- DOCKER_REGISTRY_SERVER_URL
- DOCKER_REGISTRY_SERVER_USERNAME
- DOCKER_REGISTRY_SERVER_PASSWORD

These settings can currently not be set through the task.

It would be great if the task would offer an options to select an ACR and set these settings for me.

**Comment by SumiranAgg** [comment]
@nphmuller We had support for this before but had to remove it as sensitive information like DOCKER_REGISTRY_SERVER_PASSWORD was exposed in Azure portal as application settings. 
Hence we have removed it for now till Azure fixes the issue. This is in our backlog and we will update on this thread once the feature is available.
Thanks for reporting the issue.

**Comment by nphmuller** [comment]
@SumiranAgg Great! Do you perhaps know how Azure's planning to fix this? Because it's also one of the issues I'm running into with setting api keys, etc, through application settings. It would be great if app settings could be marked as secret.

**Comment by stweedie** [comment]
Is there any update on this?

Scratching my head as to why I can't deploy a container from my ACR onto an app service using VSTS.

**Comment by SumiranAgg** [comment]
@stweedie This feature addition is planned work and should be available in couple of sprints. We will update the thread once feature is ready for use.

**Comment by stweedie** [comment]
Awesome! Thanks for the update. We can modify the container versions manually for the time being

**Comment by yvovandoorn** [comment]
@SumiranAgg any update on this? I see code determining Registry vs ACI in `operations/ContainerBasedDeploymentUtility.ts` but nothing wiring it to the task.json (it is marked as a TODO). 

Would be great to push this one through :-)

**Comment by azooinmyluggage** [comment]
Hi all,
There are two scenarios:

**“Private Docker Hub” and “Private registry” scenarios:**
     You can use the App settings feature of the task:
![image](https://user-images.githubusercontent.com/6857119/51308411-0e478580-1a68-11e9-832d-8b58ab3738ac.png)
   The only problem with this approach is that the app settings has a secret (registry password) which will be visible in the Azure Portal (when you click to edit).
![image](https://user-images.githubusercontent.com/6857119/51308499-44850500-1a68-11e9-96ed-bbccfdf9837b.png)
We are working with App Service team to improve this.

**“Azure Container Registry” (ACR) scenario:**
	You  don't have to provide user name, password, url details to Web App for Container if you are using an ACR in the same subscription. Azure Web App is able to obtain it. Just providing image details is enough.
![image](https://user-images.githubusercontent.com/6857119/51308696-b6f5e500-1a68-11e9-9fb9-aaf12e826da5.png)

**Comment by JerryWang20** [comment]
how this can work on Azure Pipeline

**Comment by SumiranAgg** [comment]
@JerryWang20  can you elaborate the question?
Do you mean how can we implement this i task? If yes, you can add a Azure web app on container task. For Private dockerhub you can add app settings as mentioned by @azooinmyluggage 
For Azure container registry in same subscription as the attached service connection in task, you just need to provide full image name, i.e. registry/imageName:tag

**Comment by JerryWang20** [comment]
I use the pipeline task to publish the to web app from ACR, but it fail with connection with ACR
steps:

 - task: AzureRmWebAppDeployment@4

 displayName: 'Deploy App'

 inputs:

 azureSubscription: '$(appName)-$(subscriptionId)'

 appType: webAppContainer

 WebAppName: '$(appName)'

 DockerNamespace: $(azureContainerRegisterName).azurecr.io

 DockerRepository: $(appName)/api

 DockerImageTag: '$(Build.BuildId)'

Error: 2019-05-16 05:04:40.051 ERROR - Image pull failed: Verify docker image configuration and credentials (if using private repository)
2019-05-16 05:04:50.120 INFO  - Pulling image from Docker hub: dowcontainerreg.azurecr.io/dowtemplatenetcoreapi/api:38946
2019-05-16 05:04:50.139 ERROR - DockerApiException: Docker API responded with status code=InternalServerError, response={"message":"Get https://dowcontainerreg.azurecr.io/v2/dowtemplatenetcoreapi/api/manifests/38946: unauthorized: authentication required"}

**Comment by JerryWang20** [comment]
So does AzureRmWebAppDeployment@4 work for web App container from ACR?

**Comment by wrong42** [comment]
I'm having the same problem as @JerryWang20. 

For some reason, after the AzureAppServiceDeploy@4 task completes, the web app is trying to pull the image from Docker hub, not from Azure Container Registry. 

In my AzureAppServiceDeploy@4 task the "Registry or Namespace" filed is set to "my-registry.azurecr.io".

What's the status on this?

**Comment by wrong42** [comment]
Ok, I found why.. Is this part commented out because of the security issue mensioned by @azooinmyluggage?

![image](https://user-images.githubusercontent.com/10200065/69665604-02b2eb00-108b-11ea-854d-c87aedfd5bdf.png)

**Comment by vishnu2017** [comment]
Have the same issue, provide an update if any. Thanks

**Comment by MunnaTelik** [comment]
Hi,
I am having the same issue. My ACR in a separate subscription  and App service is in another. I tried to set the appnsettings but still getting auth error.
Thanks
Munna

**Comment by JerryWang20** [comment]
do we have updating on this issue?

**Comment by JoseFMP** [comment]
Same issue here. Cannot deploy from Azure DevOps a new image that is hosted in Azure Container Registry.

**Comment by JKrag** [comment]
@JerryWang20 @wrong42 In my experience I can deploy ACR hosted images without a hitch from my pipeline, provided that we have at some point manually through the UI switched the "Image Source" setting from `Docker Hub` to `Azure Container Registry`. 

After this has been done once, future deploys from the pipeline work. 

I consider this a barely usable workaround for now, because it would stop working if somebody accidentally switches it back to Docker Hub. (which has happened at least once).

Apart from the fundamental "wrongness" of this work-around, I also find it particularly challenging as there are some access right restrictions that make this rather annoying in our setup. I can't "just" switch the Image source, as it will not let me actually press save without choosing an existing image, and even though I have the credentials to deploy anything to this environment from the pipeline, I can't *choose* an image in the UI because i seemingly don't have `Microsoft.ContainerRegistry/registries/listCredentials/action` rights. This means that while I can do everything else, I have to get an admin to make the Image source switch, and choose any random image and save, before I can get the pipeline to deploy the stuff we actually want.

From what I can see, it would be very helpful if `AzureAppServiceDeploy@4` just had a `ImageSource` property that could be set to e.g. AzureCR instead of DockerHub, but I might be missing something. It should be able to figure out which registry to connect to based on the "DockerNameSpace" property?

**Comment by sudheeranguluri** [comment]
Having same issue. I was able to manually switch the image source in lower environment. But soon we will be going to PROD and I don't think I can do the same. Any update on this?

**Comment by mb345345** [comment]
yup same here. I can set connection strings with passwords in, etc. but not the container registry password. this should not be hard!

**Comment by care4pet** [comment]
![image](https://user-images.githubusercontent.com/70435067/93897959-f8856b80-fcf2-11ea-98d8-a414f74f908d.png)

Why? Just why?

**Comment by damianon** [comment]
This issue has been open for more than 2 years. 
Is there a way to do this now? 
When we switch to ACR in the UI like @JKrag mentioned it works once, but changes back to Docker Hub on the next deploy, so unfortunately that's not a viable solution.

**Comment by igor-bakhtoiarov-8451** [comment]
@damianon Welcome on the 'lack of support' boat.

As previously described the following App Service configuration settings should be set before deploying anything to the App Service:
- DOCKER_REGISTRY_SERVER_URL
- DOCKER_REGISTRY_SERVER_USERNAME
- DOCKER_REGISTRY_SERVER_PASSWORD

I use Terraform to do that, but probably there is a CLI way. And manual via UI of course.

The AzureRmWebAppDeployment task updates only docker image name.

**Comment by damianon** [comment]
@igor-bakhtoiarov-8451 settings the credentials would solve the authentication issue, but then how do i set image and tag to deploy? this would normally be done using the deploy webapp task, but doing so switches the container settings back to docker hub and deletes the credentials.

**Comment by dadakleinedler** [comment]
> how this can work on Azure Pipeline

I might be too late to answer but I encountered the same issue just today when setting up my Azure Pipeline; and I was able to fix it. I set up the task as "Azure App Service Deploy" and it is important to choose the correct subscription where the Container Registry and the App Service both under with (just like one of the comments pointed out in this post). My task looks like this in my yml file:

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go _(SubscriptionId)'_ #Automatically populated if the task is selected via Tasks side panel
        appType: 'webAppContainer'
        WebAppName: 'myWebAppName'
        DockerNamespace: '$(containerRegistry)' #variable translates to <_my_container_registry_.azurecr.io>
        DockerRepository: '$(imageRepository)' #variable for the **Image** I set in the App Service
        DockerImageTag: '$(Build.BuildId)' 


I also added a task to restart the App Server (Task name: Azure App Service manage) right after the Deploy task above has been executed.

- task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'Pay-As-You-Go _(SubscriptionId)'_ #Automatically populated if the task is selected via Tasks side panel
        Action: 'Restart Azure App Service'
        WebAppName: 'myWebAppName'

After completing the run of my updated pipeline job, I don't have to do anything further in Azure App Service UI. I just checked the logs to see if the activity is done. Afterwards, I was able to call my updated service successfully. I hope this helps.

**Comment by 20shivangi** [comment]
Is the issue still occuring ?

**Comment by devsbryan** [comment]
This is still an issue I can't resolve.

The scenario for me is:

Azure Container Registry - only accessible to App Service in the same subscription AND with ACR admin key enabled.

Microsoft state that the admin key being enabled is not good security practice, so I'm trying to use a service principal instead.

In order to provide specific credentials for the docker registry in App Service (i.e. the service principal credentials), it necessitates setting App Service to look to a private registry instead.

The problem is the App Service deploy task doesn't provide that option, and trying to apply the private registry credentials manually in the portal doesn't seem to work - it keeps trying to revert to the Azure Container Registry tab settings and then failing to pull the image because I've disabled the admin key.

Perhaps the only way this works is if you set the App Service to use the private registry settings at the point of creation?

The whole experience is very poor, but to be fair the issue is with App Service and ACR rather than the build step!

Seems there is a feature request to sort this out but doesn't appear to be going anywhere fast: https://feedback.azure.com/forums/169385-web-apps/suggestions/36145444-web-app-for-containers-acr-access-requires-admin

I think @igor-bakhtoiarov-8451 comment is the only workaround.

**Comment by RobTF** [comment]
Still an issue.
