### ISSUE TITLE
NugetCommand: Basic authentication breakes when pushing to jfrog artifactory

### ISSUE THREAD

**Issue by acasella** [microsoft/azure-pipelines-tasks#7870]
## Environment
- VSTS
- Agent - Hosted and private

## Issue Description

Task: NuGetCommandV2.
When using basic authentication, the nuget push command adds an invalid parameter: 
 -ApiKey RequiredApiKey
This is causing the nuget push command to fail when calling jfrog artifactory. Removing this parameter fix the problem.
![image](https://user-images.githubusercontent.com/8753512/43402175-6b454d1c-9412-11e8-9cf6-5706f7b879a3.png)

### Error logs

The error log is a simple 403 from artifactory.

**Comment by jotaylo** [comment]
Unfortunately different NuGet services have different requirements in terms of how requests are handled when both X-NuGet-ApiKey and another form of authentication are provided, so the current implementation is a compromise. Since Artifactory supports authentication via API Key, I recommend switching to that instead (this may require separate endpoints for pushing & restoring).

**Comment by acasella** [comment]
I'm not sure to understand the answer. For me, the problem is a simple bug. A "break" sentence is missing. By only adding it the bugs dissapears. Take a look at this PR: https://github.com/Microsoft/azure-pipelines-tasks/pull/7871

**Comment by elbatk** [comment]
@zjrunner could you take a look at this + the corresponding PR to see if this is a small papercut that we could get in? The PR is from December 2018 (sorry @acasella ) and has some conflicts.

**Comment by elbatk** [comment]
hi @acasella , I've taken a look at the PR here and I think while it would fix your issue, it would break other scenarios (posting to other azure devops organizations, for instance). We are going to be making some big changes to our authentication tasks in the next quarter and we are going to implement a fix for this bug there. Since that work is being tracked and you've got a workaround here, I'm going to close this. Let me know if you have any questions!
