### ISSUE TITLE
Bash V3 task sources script instead of executing it

### ISSUE THREAD

**Issue by andreasf** [microsoft/azure-pipelines-tasks#7934]
## Troubleshooting
Troublesome code was found at https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/BashV3/bash.ts#L71

## Environment
- Server - VSTS
- Agent - Private

## Issue Description

When running a Bash V3 task with a target script type of "File Path", the task wraps the target script with something like the following:

```bash
. '/home/vsts/agent01/_work/6/s/ci/build.sh'
```

Sourcing (.) a script instead of executing it is problematic because the source built-in does not set the $0 variable to the target script path.

$0 can be used to make scripts work independently of the current working directory, e.g.:

```bash
main() {
    local project_dir="$(dirname "$0")/.."
    # move to project directory using relative path
    pushd "$project_dir"
        # now run something with a known path
        ./gradlew clean build
        ...
    popd
}

main $*
```

Here's an example of how the wrapper changes $0:
```bash
$ cat target-script.sh:
echo "arg 0: $0, arg 1: $1"

$ cat wrapper.sh
. target-script.sh some-arg

$ sh target-script.sh some-arg
arg 0: target-script.sh, arg 1: some-arg

$ sh wrapper.sh
arg 0: wrapper.sh, arg 1: some-arg
```

Steps to reproduce
1. Place target-script.sh from above in a repository
2. Set up a Bash V3 task, choose "File Path", point it to target-script.sh, and set the arguments to "some-argument"
3. Run the task

Expected outcome:
Log shows something like:
arg 0: /home/vsts/agent01/_work/6/s/**target-script.sh**, arg 1: some-arg

Actual outcome:
Log shows something more akin to:
arg 0: /home/vsts/agent01/_work/_temp/66109fbc-a421-4b3c-a049-3a1f062bd1f9.sh arg 1: some-arg

**Comment by ericsciple** [comment]
Thanks. That makes sense. A workaround is to switch to inline and then call your script.

I'm trying to remember why I chose to dot source. I think it solves an issue if the executable bit is not set.

**Comment by ArieHein** [comment]
what happens if you continue to use v2 ? 
I only used v3 so far if I had a quick inline bash script I wanted to run which I didnt want to place in the repo, which I couldn't do with v2

**Comment by andreasf** [comment]
V2 still works. We're currently using V3 with inline scripts as a workaround.

**Comment by ArieHein** [comment]
Did you try to use the "Working Directory" settings instead, so it doesn't take the default Agents' working folder ?

**Comment by grenzr** [comment]
I hit the same problem just now, unable to use `dirname` properly in my scripts because of the wrapper as @andreasf describes. Using Working Directory property makes no difference to the execution. Reverting to V2 works.

Also the shebang and any switches set on it (eg. -e) are ignored too, which is a bit annoying, but I supposed can be worked around by ensuring you use 'set' command directly in your script underneath the shebang.

re: @ericsciple comments, personally I think it should be the responsibility of the script writer to ensure the executable bit is set at whatever source it came from.

**Comment by bryanmacfarlane** [comment]
agreed

**Comment by ericsciple** [comment]
@vtbassmatt fyi

We'll want to make sure to have we have an actionable error. We could add telemetry before making the change.

**Comment by vtbassmatt** [comment]
I see two options. Option 1:
- Check a variable `AZP_BASHV3_OLD_SOURCE_BEHAVIOR`. If it's `true`, throw a warning and use the old (current) behavior.
- Otherwise, check the executable bit. If set, run the script.
- If not set, throw a warning and use the old behavior. This warning will include a pointer to docs which illustrate the back-compat variable.
- In a few months, we remove the back-compat stuff. Then, we'll run the script and if it's not executable, report that error.

Or, if we feel like we're making a breaking change, option 2 is to bump the major version and skip all the other stuff. @damccorm / @stephenmichaelf let's chat today.

**Comment by damccorm** [comment]
After offline discussion decided to go with option 1, with one slight difference of not warning if ```AZP_BASHV3_OLD_SOURCE_BEHAVIOR``` is ```true```.
