### ISSUE TITLE
NuGet task doesn't correctly error when "Path to NuGet.config" incorrect

### ISSUE THREAD

**Issue by zarenner** [microsoft/azure-pipelines-tasks#8080]
When "Path to NuGet.config" is incorrectly set to a folder path instead of the NuGet.config path, instead of erroring, sometimes the task will continue, creating a temporary nuget.config with just "<configuration />" in it. The build proceeds and then users are confused when their packages fail to restore because the sources/creds aren't there.

The expected behavior is that it would fail with a "you provided a directory, provide the exact path to nuget.config" type error. This does kinda happen in some cases ("illegal operation on a directory, read"), but not always. Also the current error message could obviously be improved.

I believe the difference in behavior (continuing with empty nuget.config, versus failing) seems to depend on if the folder provided is within the repository or not. Looking at the [code](https://github.com/Microsoft/vsts-tasks/blob/a6b3db8e61b623bbc38e8c45b1725450b045642d/Tasks/NuGetCommandV2/nugetrestore.ts#L111), it seems like tl.filePathSupplied or our use of it is likely the culprit.

**Comment by zarenner** [comment]
@satbai @keithrob

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!

Adding: closing this issue because this looks like an inconvenience error instead of a bug that's blocking users.
