### ISSUE TITLE
Add option to BashV3 to enable loading profile and rc

### ISSUE THREAD

**Issue by giggio** [Microsoft/azure-pipelines-tasks#8259]
Right now BashV3 never loads profile and RC, which I believe is a good default, as seen here:
https://github.com/Microsoft/vsts-tasks/blob/f1b8d42c24662857177d47faf8d744415dff85ab/Tasks/BashV3/bash.ts#L9-L13

But we should be able to load them optionally, there should be options that we could enable and then run BashV3 without `--noprofile` and/or `--norc`.

**Comment by giggio** [comment]
My use case is the use of `nvm` which is installed on the build agent, and we can't use it until it is sourced, which is the default if bashrc is loaded.

**Comment by giggio** [comment]
@damccorm Awesome! Any ideia of when this might be released?

**Comment by damccorm** [comment]
It should start rolling out with the rest of the product soon and be done by Friday 3/8 at the latest.

**Comment by SudoBrendan** [comment]
Writing this down in the hopes it will be helpful... I *think* the ticket can remain closed...

In the current BashV3, the default behavior is to launch `/bin/bash` directly, that is, you'll write a Task with either a file to execute, or some in-line script that's written to a temp file then executed. Here are all the paths for the new parameters, and what files get sourced:

DEFAULT: command to the agent will be `/bin/bash --noprofile --norc /path/to/file`. Since this is a non-interactive (and non-login shell), this will source NO files because there is no avenue to add `--rcfile` flags on your own.

BASHRC: If you un-flag the bashrc option, you will eventually execute `/bin/bash --noprofile /path/to/file`. Since this is a non-interactive (and not a login shell) this will source `/etc/bash.bashrc` and `~/.bashrc` if they exist. 

PROFILE: If you un-flag the noprofile option, the final command will be `/bin/bash --norc /path/to/file`, which, in effect, *does nothing differently than the DEFAULT behavior*. You will not source any files.

BASHRC + PROFILE: If you unflag both options, the final command will be `/bin/bash /path/to/file`, which *does nothing differently than the BASHRC behavior*. This will source `/etc/bash.bashrc` and `~/.bashrc` if they exist. 

The `--noprofile` flag is pretty meaningless without the `--login` flag (which sources files like `/etc/profile`, `~/.bash_profile`, `~/.bash_login` and `~/.profile`)... so this threw me way off because I assumed that the existence of a "disable profile loading" implies that `--login` is always added to all invocations (DEFAULT would be `/bin/bash --login --norc --noprofile /path/to/file`). In all honesty, **this option should probably be removed for clarity**. I agree with OP - not sourcing `--login` files by default is probably a good thing, but could potentially be an option alongside `--noprofile` (that is, flagging a (currently unavailable) "use login shell" will make "don't source bash profiles" available to select).

So, then... how do you source files like `/etc/profile` as an option (the original intent of this post?). It might not be a selectable "thing" in the UI, but it is possible!

Since the Task will always launch `/bin/bash <opts?> /path/to/file`, *the shell will always be launched non-interactively, and not be a login shell*. This means you can set the environment var BASH_ENV to point to the file you want to source before any BashV3 scripts are run. So, you have two options: 1.) Update the agent to have this var set for ALL tasks as a default with `export BASH_ENV=/etc/profile`, or 2.) you can set the BASH_ENV var as part of the BashV3 Task as a one-off for a given Task under the Environment Variables section. Dealer's choice. BASH_ENV will bypass both the NORC and NOPROFILE options, so you will definitely source that file if you set that variable.

**Comment by giggio** [comment]
@SudoBrendan suggestion makes sense. I am not sure if there should be a `Login` option, or if removing `--noprofile` should imply `--login`. What do you think?

**Comment by SudoBrendan** [comment]
@giggio Even though the paths I outline above describe how the currently supported Task options for launching `/bin/bash` don't necessarily make sense, I think that making assumptions in the Task code (`--noprofile` implies `--login`) obfuscates what the Task will ultimately do and also restricts what the users will be capable of controlling (aside from a reasonable default, which I think the Task achieves).

IMHO, if support of an option (`--login`, `-i`, `--rc-file`, etc) is desirable, it should be a new Task flag, just like it's a separate entity when launching `/bin/bash`; that new flag should do exactly one thing, and it should be obvious how the flag maps directly to an option when launching `/bin/bash`. I'd rather have 1-1 mappings on Task flags to `/bin/bash` options (then read-up from `man bash`) than have to go into the Task source code to figure out how the Task flags translate into bash options, then end up at `man bash` anyways.

**Comment by giggio** [comment]
This makes sense to me.

**Comment by giggio** [comment]
@damccorm should we open another issue for this, or do you think we should reopen this one?

**Comment by wngr** [comment]
I'm sorry to dig this up here, but it seems to me that this is currently not working as intended. At least on my server running `Ubuntu 20.04.2 LTS`.

Running a task like
```yaml
          - task: Bash@3
            inputs:
              targetType: 'inline'
              noRc: false
              script: |
                set -e
                make something
```

definitely does not source `~/.bashrc`.

Also, looking at `man bash` (excerpt):
>        When an interactive shell that is not a login shell is started,  bash  reads  and  executes  commands  from
       ~/.bashrc,  if  that file exists.  This may be inhibited by using the --norc option.  The --rcfile file op‐
       tion will force bash to read and execute commands from file instead of ~/.bashrc.

       When bash is started non-interactively, to run a shell script, for  example,  it  looks  for  the  variable
       BASH_ENV in the environment, expands its value if it appears there, and uses the expanded value as the name
       of a file to read and execute.  Bash behaves as if the following command were executed:
              if [ -n "$BASH_ENV" ]; then . "$BASH_ENV"; fi
       but the value of the PATH variable is not used to search for the filename.

So it does seem, that the `Bash@3` script task is being executed in a non-interactive shell, meaning that no matter the bit on `noRc`, the `.bashrc` file will never be sourced.

I feel that the two options `noRc` and `noProfile` make it unnecessarily hard for end users, and should be removed. Maybe a convenience alias like `sourceUserBashrc` could be added, which under the hood sets the `BASH_ENV` env var.

**Comment by Nightreaver** [comment]
I can confirm, even setting this noRc to false (true by default) doesnt make it work.
What the Idea behind this? is this going to get solved?
