### ISSUE TITLE
npm publish ignores NO_PROXY environment var (and AGENT_PROXYBYPASSLIST)

### ISSUE THREAD

**Issue by guylevy** [Microsoft/azure-pipelines-tasks#8289]
## Environment
- Server - TFS on-premises 2018.1
- Agent - Private: Win10
- Both agent and TFS server are on premises and behind a proxy
    
## Issue Description
Using the NPM task -> publish to internal feed (registry I select here and selecting an existing private TFS NPM feed) -> results in error "socket hang up".
Since both 
When checking the proxy logs, we see that the task hits it even that both NO_PROXY environment var and AGENT_PROXYBYPASSLIST are set correctly.
Looking at the [source code](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/NpmV1/npmtoolrunner.ts) it looks like the the proxy bypass list is not transferred in the _getProxyFromEnvironment method. 
Based on the source code, this info is probably ignored for all NPM command type

## Expected behaviour: 
since npm supports the NO_PROXY environment var, the proper information should be set by the task.

**Comment by jotaylo** [comment]
Yep, this is a bug. I've taken a quick look, unfortunately there doesn't appear to be a trivial fix, since AGENT_PROXYBYPASSLIST is a list of regexes, but npm's no-proxy setting is expecting a list of hostnames. 
For the publish task we can just run the regexes against the publish registry, but for install/custom I guess that we'll need to parse all the registries out of the npmrc, then run the regexes against them all to find matches (we have a handy list of all registries that require authentication, but no-proxy may need to include unauthenticated registries).

**Comment by alexmullans** [comment]
We've just added proxy support to the Npm@1 task. It will be available in the next feature update to Azure DevOps Server.
