### ISSUE TITLE
UsePythonVersion@0 does not configure correctly Python 3.4 and 3.5

### ISSUE THREAD

**Issue by gaborbernat** [microsoft/azure-pipelines-tasks#8330]
```bash
2018-09-17T20:14:15.5777113Z py -3.5 -c "import sys; print(sys.executable)"
2018-09-17T20:14:15.6419862Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\15c4da66-e82e-4a75-ab7d-6d7f0803f389.cmd""
2018-09-17T20:14:16.2417178Z Requested Python version (3.5) not installed
2018-09-17T20:14:16.4035016Z ##[error]Cmd.exe exited with code '103'.
```
See tests inside https://github.com/tox-dev/tox/pull/995.

**Comment by zooba** [comment]
That’ll be the lack of PEP 514 registry entries. Python 3.6 works because it’s finding a different install than the one installed by this task.

The expected use would be to run "python" rather than "py", but I suspect it wouldn’t be too hard to get the UsePythonVersion task to also update the registry? That might not play well on not-our-machines though. Still, probably better than the vague error message we're seeing right now.

**Comment by brcrista** [comment]
@zooba is right, the registry entries aren't set on the hosted Windows machines.  They should probably be set at image creation when installing Python rather than by the Use Python Version task.  That will be easier, it won't mess with self-hosted agents, and it will let people use `py` instead of Use Python Version if they're so inclined.

The fix will be straightforward but will need to roll out with the next hosted image update.  @gaborbernat , is this blocking you?

**Comment by gaborbernat** [comment]
Thanks 😎 I can work around it in the meantime, just noticed that this part does not work for the Python usage.

**Comment by brcrista** [comment]
(Going back through Python issues)

This issue is for setting up Python versions in the hosted tools cache to work with the Py launcher on Hosted VS2017.  The work required would be to use the Windows Python installer during image generation.
