### ISSUE TITLE
Azure PowerShell with Managed Identity Authentication fails due to proxy

### ISSUE THREAD

**Issue by gpendle** [Microsoft/azure-pipelines-tasks#8539]
## Environment
- Server - Azure Pipelines
    
- Agent - Private
    
    - Azure VM
    - Server 2016
    - Agent Version 2.140.0 

## Issue Description

Task Azure PowerShell Version 3.1.6

Using Azure PowerShell task with Managed Identity Authentication with the Agent configured to use a proxy.  

Step gets a 503 (after some 407s) when connecting to http://169.254.169.254/metadata/identity/oauth2/token?

This call should be ignoring the proxy settings as it has to route over Azure network and not via the proxy so the request comes from the VM.

The Get-Proxy function in the VstsAzureHelpers_ does not check the proxy bypass list so adding 169.254.169.254 to the .proxybypass does not work.

Suspect he Get-MsiAccessToken function should ignore proxy settings.

**Comment by asranja** [comment]
@gpendle As pointed out by you, it does seem that the Get-MsiAccessToken function should ignore proxy settings. 

While we work to make a fix, can you try removing the proxy parameters from the Invoke-WebRequest [here](https://github.com/Microsoft/azure-pipelines-tasks/blob/8c77eb80b647661318d64c1a62a3b92f29670a89/Tasks/Common/VstsAzureRestHelpers_/VstsAzureRestHelpers_.psm1#L438) in the Azure PowerShell task downloaded on your agent machine. You can run any Azure PowerShell cmdlet (Ex: Get-AzureRmSubscription) to verify if the fix is working for you.

**Comment by gpendle** [comment]
Thanks @asranja, the suggested change works.
