### ISSUE TITLE
making CI build entries meaningful like PR build entries

### ISSUE THREAD

**Issue by stas00** [microsoft/azure-pipelines-tasks#8586]
I don't know whether this is a feature request or whether there is some configuration that can be tweaked, but how can I get meaningful CI build entries, similar to PR entries as it can be seen from the snapshot:

![snap8](https://user-images.githubusercontent.com/10676103/46902088-cd8e0e00-ce73-11e8-863c-677e2027be32.png)

I know you have the commit message, since once I click on the build, it's there. Any reason why it's not being displayed in the index listing, same as PRs?

Thank you.

**Comment by bryanmacfarlane** [comment]
BTW, these issues are for the tasks in this repo.  Service / UI issues should be on developer community.  Moving to build to look.

**Comment by stas00** [comment]
Is it possible to create some kind of a map of the different areas of CI devops with brief explanations of when to submit issues/questions to which repo or dev community? Thank you.

**Comment by moswald** [comment]
@stas00 If it's a problem or feature request for a pipeline task _specifically_, open an issue here. If it's a problem with running the tasks (sort of subjective, I know), then open an issue in the [azure-pipelines-agent repo](https://github.com/microsoft/azure-pipelines-agent). If it's a general problem or suggestion with the service, then your query should be directed to the [Azure DevOps Developers Community site](https://developercommunity.visualstudio.com/spaces/21/index.html). We have made many improvements with our GitHub checks support since February, but if this is still an issue for you, please reopen it there.
