### ISSUE TITLE
IIS Web Deploy - Unable to find a way to have it backup site before deployment.

### ISSUE THREAD

**Issue by CoolDadTx** [Microsoft/azure-pipelines-tasks#8696]
## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

- Agent - Hosted or Private:  Hosted

## Issue Description

We were using the IIS Web Deploy task to deploy a site to IIS running on an internal server. Prior to CD we have always deployed our apps to a new virtual directory and then just changed the app pool to point to the new directory. That allows us to hotswap back to the original app if needed without bring the site down. But it also provided a backup of our previous version in case we need to restore it after deployment (e.g. the performance is bad and we need to revert back).

MSDeploy supports backing up a site using the -dest:archiveDir option. However I'm not able to find any way to get this to happen with the existing task or find any other task that would work. 

How can the task be adjusted to automatically back up the old site somewhere else first. We don't want to the backup to be deleted if the deployment was successful because it may be hours or even days before we realize we need to revert.

If it isn't possible with this task then how else can we do it because all the options I see around using PowerShell or whatnot don't seem to behave correctly. In one case I tried to use %SYSTEMDRIVE%\inetpub\wwwroot to get to the server's root (within the Run on Deployment Group set of tasks) and it seems to have mapped to the release agent machine instead because it couldn't find the path. But this is the correct path because that is what IIS Web Management is using.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by Ajay-MS** [comment]
@CoolDadTx 

Thanks for your feedback.  

In IIS web app deploy task, msdeploy argument -dest values are limited to iisApp, contentPath, and auto and it's being decided automatically by the task. Since the task doesn't provide an option to specify -dest argument,  you won't be able to use task for backup purpose. 

Yes, you are right in order to take backup either you need to use PowerShell task or Copy Files task. 

With PS task,  `%SYSTEMDRIVE%\inetpub\wwwroot` won't work because `%<ENV_VAR>%` is a cmd way to represent an env variable. 

In PS task, please try as follow:
`"$env:SystemDrive\inetpub\wwwroot"`

I hope this information would be useful for you.

**Comment by CoolDadTx** [comment]
I'll try that, thanks.

**Comment by CoolDadTx** [comment]
I ended up having to write a more complex script to backup things but it is working for me now. Thanks.
