### ISSUE TITLE
[Maven] "Authenticate built-in Maven feeds" not toggled by default

### ISSUE THREAD

**Issue by vbossica** [Microsoft/azure-pipelines-tasks#8711]
## Environment

- Azure Pipelines

## Issue Description

When adding a Maven task (any version), the "Authenticate build-in Maven feeds" checkbox is not selected by default:

![image](https://user-images.githubusercontent.com/1238627/47555732-d91a1400-d90c-11e8-951b-9ec4e67ac30a.png)

Yet its default value is "true" in the `task.json` definition: https://github.com/Microsoft/azure-pipelines-tasks/blob/fd642f5bc5f1f217474c718d16396df7aa8297ca/Tasks/MavenV2/task.json#L299

Not having the checkbox selected make deselecting it (to not have the effective pom generated, for example) a guess work.

**Comment by madhurig** [comment]
Hi, 

Thank you for the feedback. We changed the default in MavenV3 to not enable this option by default since it slows down builds that are not using Maven feeds in Azure DevOps which is still the more common case. We will consider your input along with others to see if we should switch the defaults again or make this option more visible when setting up the pipeline.

Thanks,
Madhuri
