### ISSUE TITLE
VSTest Task - Setting batch options to custom size produces undesired behavior in the test run

### ISSUE THREAD

**Issue by parrainc** [Microsoft/azure-pipelines-tasks#8718]
## Issue Description

After setting up my release definition for running on-demand tests through Test Hub, I noticed that my test results were not being updated as they were passing or failing. The release logs for the vstest task were always showing:

> Test run '510660' is in 'InProgress' state. Total Tests: 20, Passed Tests: 0

and only when all the tests were passed or failed, it showed the actual results:

> Test run '510660' is in 'Completed' state with 'Total Tests' : 20 and 'Passed Tests' : 20.

This is not the expected behavior I'd like to see on the test results, and because of that, I found out that playing around with the [batch options](https://blogs.msdn.microsoft.com/devops/2017/11/14/test-batching-options-with-vstest-task/) would allow me to get the result i was expecting to see.

I did the following setup in my **vstest task**:

![batching-issue-01](https://user-images.githubusercontent.com/10530861/47591468-8fd5be80-d924-11e8-9d82-7143b208eece.PNG)

After doing that, the Test Run summary screen was behaving as expected (showing my results as the test were passed/failed)

> Test run '510661' is in 'InProgress' state. Total Tests: 3, Passed Tests: 1

![batching-issue-02](https://user-images.githubusercontent.com/10530861/47591972-49815f00-d926-11e8-85a2-6c87efb9abf2.PNG)

Even though this is what i wanted to see in the test run, there are now one major issue (and that's the reason i opened up this one). The `Test Context` is being reset every time a new test method in the same test run is executed. This is causing my tests to create duplicates files in the test agent (i have a report that is generated by test run. That guys is being created depending of how many tests are in a test run).

### Task logs

Logs without the batch option set up:
[log-without-batching.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2521035/log-without-batching.zip)

Logs with the batch option set up:
[logs-batch-options.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2521020/logs-batch-options.zip)

### Environment
- TFS 2018 update 2 on-premises, version 16.131.27701.1
- Private Agents
  - OS: Windows 10
  - VSTS-Agent: 2.131.0
  - VSTest task Version 2.*

**Comment by kaadhina** [comment]
Can you please elaborate on the Test Context a bit more? Are you referring to the TestContext class of the mstest framework?
Since the batch size is 1, the test platform would then invoke each of these separately, each with its own test context. But what is the property that you are depending on that is different for each test. Can you please explain your scenario more?

**Comment by parrainc** [comment]
@kaadhina That's correct, the Test Context I'm referring to is the TestContext class from MSTest framework.
Is there a possibility that we could avoid that behavior `Since the batch size is 1, the test platform would then invoke each of these separately, each with its own test context.`?

I'm expecting to see real time results in test run screen, but i don't want to lose the ability of getting all my test within the same test run to share the TestContext value.

I have a test framework based on MSTestV1 (currently being moved to V2) and in one of the framework setup classes, if more than one test is executed, it will create a single test result folder for those test (s) that were executed. This works perfectly fine in TestHub (without touching the batch settings at all) but without the ability to see the results in Test Results screen, which is a nightmare if we have lot of ui tests and would like to see results at the same time they are passing or failing. However, when I changed the batch options, the results were updated as expected, but the folder creation is now being executed as many time as tests in my test run (which could be a problem if we have a test run, let say, with 50 tests or more).

So, i wanted to know if it's possible to update the behavior when setting up the batch size to 1 (or any other size) in a way that the context is not updated and we could still see the results in test results screen without needing to wait until all the tests in a test run finish, or maybe if it could be added an option in the task to prevent this behavior.

**Comment by kaadhina** [comment]
Yes, you are using the right options to be able to see incremental results updates.
This will results in tests running in multiple batches, each of which is executed as a run by the platform (which are then collated on the server into a single run). Each of these is self contained (which is why it is able to report results incrementally). So by design each of these will create its own results file.
I'm not sure I understood why this is an issue. If you use the default results folder, these will be automatically cleaned up after the run on the agents and the required attachments are uploaded to the server. Please correct me if your concerns are different from my understanding.

**Comment by parrainc** [comment]
Hi @kaadhina sorry for my late response.
You're right, i know that by setting the batch size to "x" number, the tests will run that way, but actually i just wanted to know if it could be taken as an enhancement (maybe?) if the user could have the ability to tell the platform not to reset the context and keep them together, but the results part will remain the same. Does that make sense?

let say, something like, after setting batch size to 1 (to see results incrementally in test hub), and an option to: `Reset TestContext: true | false`. Or maybe, with no need to update the batch size to 1, an option to `Show results incrementally`?

I'm pretty sure that lot of people that have moved from old test manager to test hub, would be pro this suggestion/enhancement.

**Comment by kaadhina** [comment]
@parrainc Thank you for the feedback! I'm marking this as enhancement, but please note that this is not on priority right now. Like I said above, the results files will get cleaned up on the agent machines and uploaded to the server. So the context changing should not cause any issues. Please let us know if your issue is different so we can suggest alternatives.

**Comment by parrainc** [comment]
Thanks! It's alright. For now, I'm fine knowing that this would be implemented :)
question... shouldn't it be opened instead of closed? Or you will track it even closed?

**Comment by tmilnthorp** [comment]
I think I'm seeing a similar issue with the TestContext being reset. I pass in a custom test run parameter ("Override test run parameters" in the VSTest task) to the test context that has a directory path for where to locate some binary files to open. However the path is the same for all agents, even if the VSTest task is passed $(System.ArtifactsDirectory) for the current agent.
