### ISSUE TITLE
FtpUpload cleanRemoteContents fails 

### ISSUE THREAD

**Issue by andreasblueher** [microsoft/azure-pipelines-tasks#8779]
## Environment
- Server
Azure DevOps
Acountname: GOB
Team project name: unitop Apps
Build number: 2454
Release id: 117

- Agent
Hosted VS2017

## Issue Description
We got an error in our release pipeline today saying: "The directory is not empty". I checked the folder in Azure WebApps and the folder was empty. When I tried to deploy for a 2nd time, everything ran smoothly.

### Task & Error logs
[ReleaseLogs_117.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2548666/ReleaseLogs_117.zip)
[Insert error from the logs here for a quick overview]

**Comment by yacaovsnc** [comment]
Just to confirm, no one manually cleaned the folder between the two attempts, but  the first time server returned "directory not empty" and second time it went through?  

If that's the case, it feels like some process is holding a reference to some file and it wasn't cleaned.  The task is only a thin wrapper and this sounds like a server side condition.  

Also since you are deploying to Azure WebApps, you can also consider using this [task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=vsts).  This is the [code](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4) instead of using this vanilla ftp task.

**Comment by andreasblueher** [comment]
Hello @yacaovsnc yes I can confirm no one manually cleaned the folder and the second time it went through.

I'll look into the other task, but for that I need not only permissions in Azure DevOps plus credentials for ftp in Azure Webapp, but I need also permissions for the Azure WebApp which I currently don't have with my personal account.

I agree to your analysis, but I still wanted to report it.

**Comment by yacaovsnc** [comment]
We appreciate you report the issue.

**Comment by yacaovsnc** [comment]
We have release a v2 of ftp upload task.  Please give that a try if you are still using ftp instead of azure deployment task.  This problem doesn't sound like a task issue, most likely some other process was holding a file handle.
