### ISSUE TITLE
Test results directory is cleaned up only for the first slice hence uploading similar multiple trx files to vsts

### ISSUE THREAD

**Issue by jagany** [Microsoft/azure-pipelines-tasks#8821]
Our build definition (https://microsoft.visualstudio.com/Universal%20Store/_build?definitionId=23050) is experiencing this issue since yesterday that duplicate test result files are being uploaded. This is blocking our release test evidence, since one service change can only have no more than 100 attachments. Usually our builds will have 80+ test files, now it's generating hundreds of files due to the issue. 
Sample build: https://microsoft.visualstudio.com/Universal%20Store/_build/results?buildId=12853153&view=logs
Test run for the build: https://microsoft.visualstudio.com/Universal%20Store/_TestManagement/Runs?runId=106683888&queryPath=Recent%20Run%2FRun%20106683888&_a=runCharts

**Comment by ShreyasRmsft** [comment]
@jagany this has been fixed in the latest version of the vstest task.

Another additional fix was made with regards to proc dump holding onto a file in the results directory - to get this please use the latest version of the test platform using the vstestplatform tool installer task.

Please reopen the issue if you are still facing this problem.
