### ISSUE TITLE
AzureBlob File Copy does not upload/timeout

### ISSUE THREAD

**Issue by SeriousM** [Microsoft/azure-pipelines-tasks#8824]
## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure DevOps

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    AccountName: scan2lead
    TeamName: Scan2Lead
    Release Definition: 2

- Agent - Hosted or Private: 
        - If using private agent, provide the OS of the machine running the agent and the agent version: 
    Private:
      Windows10 x64, 10.0.17134
      Agent Version: 2.141.1
      AzurePS: 5.7.0
      Agent is executed in the user context as console application (not service).

## Issue Description

We're uploading build artifacts to azure and for some time now it's not possible to finish the task anymore.
The task comes to the point where it starts the upload and then suddenly stops and a timeout happen after 20+ minutes.
The earlier release definition contained the file copy task v1 and I changed it to v2 with the same error result.

### Task logs

I've sent the logs to RM_Customer_Queries@microsoft.com as they contain sensitive informations.
One log is with normal output, the second is with debug on.

### Error logs

`Upload to container: '<name>' in storage account: '<name>' with blob prefix: '<name>' failed with error: 'AzCopy.exe exited with non-zero exit code while uploading files to blob storage.' For more info please refer to https://aka.ms/azurefilecopyreadme`

**Comment by asranja** [comment]
@SeriousM Since this is a timeout issue, lowering the number of concurrent threads used by AzCopy might help resolve it. The [/NC](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy#ncnumber-of-concurrent-operations) parameter is used to control the number of concurrent operations. Please try passing **/NC:2** in the Additional Arguments of the Azure File Copy task and redploy the release.

**Comment by SeriousM** [comment]
Well, ok, that worked **once**, the next attempt died again: https://scan2lead.visualstudio.com/Scan2Lead/_releaseProgress?_a=release-environment-logs&releaseId=507&view=mine&environmentId=1689

But how is that possible? it's just about 100mb on 4 files (3x big, 1x 1kb). This is just not good...

**Comment by asranja** [comment]
We are investigating this further with the AzCopy team. Meanwhile, can you try running the AzCopy.exe command (mentioned in the logs) directly from your agent machine to see if there is any timeout.

**Comment by SeriousM** [comment]
the upload problem has stabilized but it's still very slow

**Comment by asranja** [comment]
Client timeout typically happens when the network condition is not good enough for transfer, and can be commonly mitigated by using lower number of transfer concurrency(NC). 

I am suspecting the problem to be related to the network connectivity between agent and the Azure storage service and should get automatically resolved once the connectivity is good.

**Comment by vincentdass** [comment]
@SeriousM , Is the issue still persisting?

**Comment by SeriousM** [comment]
No, it's resolved now.
