### ISSUE TITLE
NuGetV2: Specifying an AppVeyor NuGet feed doesn't work

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/azure-pipelines-tasks#8875]
## Environment
- Server - Azure Pipelines
https://cloudbuild.visualstudio.com/CodexIngest/_build?definitionId=123

- Agent - Hosted or Private: 
Hosted VS2017

## Issue Description
Restoring via this NuGet.config file fails:
https://github.com/icsharpcode/ILSpy/blob/master/NuGet.config

### Task logs

```
2018-11-20T01:29:18.8455315Z ##[error]The nuget command failed with exit code(1) and error(NU1101: Unable to find package Mono.Cecil. No packages exist with this id in source(s): ILSpy
NU1101: Unable to find package DiffLib. No packages exist with this id in source(s): ILSpy
NU1101: Unable to find package Microsoft.CodeAnalysis.VisualBasic. No packages exist with this id in source(s): ILSpy
```

**Comment by KirillOsenkov** [comment]
See related: https://github.com/Microsoft/azure-pipelines-tasks/issues/8850

**Comment by KirillOsenkov** [comment]
@chrisrpatterson @bryanmacfarlane hey folks, there are quite a few issues with the NuGetV2 restore task and I haven't seen any activity for months. I would like to make sure this is prioritized if possible as it's blocking real world adoption of Azure Pipelines. See related: 

https://github.com/Microsoft/azure-pipelines-tasks/issues/7616

**Comment by KirillOsenkov** [comment]
Also I'm confused because there's `NuGet` and `NuGetRestore` and `NuGetCommand` and I only see NuGet in the marketplace, but the source code doesn't match. Who would be the best person I can contact internally to help me sort this out?

**Comment by phil-hodgson** [comment]
@KirillOsenkov The restore is failing because the source NuGet.Config file only contains a single source (https://ci.appveyor.com/nuget/ilspy-masterfeed). It does not contain nuget.org as a source, which is where the majority of the referenced packages exist.

Whilst nuget.org _may_ be set in a machine or user default NuGet.config file, or whilst earlier versions of nuget.exe will automatically add it, you shouldn't rely on it automatically being there.

Two options:

1. Have the repo owner add nuget.org's endpoint as a source in their NuGet.Config file
2. In your build, add a step before the restore which runs `nuget sources Add -Name nuget.org -Source https://api.nuget.org/v3/index.json -ConfigFile NuGet.config`
