### ISSUE TITLE
I need a fully-featured Azure Storage copy task for Linux

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/azure-pipelines-tasks#8879]
I feel as though not having a first-party option to interact with Azure Storage from a Linux based build host is something that needs to be addressed with some degree of priority.

![image](https://user-images.githubusercontent.com/115199/48778175-1e2a2f80-ec9a-11e8-936d-ad24393139e5.png)

I might also additionally suggest an audit of all official Microsoft plugins to ensure they work on Linux.

With full apologies for being so direct, I hope you can appreciate how frustrating this is.  These kinds of surprises are not documented anywhere and leave people to the last moment before they realize Azure Devops has an innate and blocking preference for Windows.
A follow-on concern I have as a result of this is over how long I will have to wait before Azure Devops is able to correct this.  What am I supposed to do in the interim?

( cc. from https://twitter.com/martinwoodward/status/1064604300930887681 - reassuring response from @martinwoodward, but no followup from the team members he pinged. )

_I've encountered this scenario enough on Azure Devops times that I think something proactive would make a lot of sense.  The plugin marketplace would be well served by only showing extensions that run on all platforms.  This would give Azure Devops a clear idea of the extent of the issue and start to make inroads on resolving something this recurrent._

**Comment by RoopeshNair** [comment]
@atrauzzi, we have converted most of the Azure tasks to be xPlat, Azure File Copy is on the pending list. To be honest, we haven't had many requests for the same. Since this is a feature ask, I would recommend you to report this on [AzureDevOp DeveloperCommunity](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) (Suggest a feature) This will help to prioritize appropriately.
