### ISSUE TITLE
Azure SQL Publish - SQL Script File - Not able to pass secret value as Variable

### ISSUE THREAD

**Issue by sugarjig** [Microsoft/azure-pipelines-tasks#8882]
## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description
Here are the steps I am taking:
1. Use the Azure Key Vault task to retrieve two secrets: `admin-password` and `user-password`.
2. Use the Azure SQL Publish task to run an SQL script. The script references a `$(UserPassword)` variable. Attempt to pass the value of `user-password` to the script by setting the "Additional Invoke-Sqlcmd Arguments" field to `-Variable "UserPassword=$(user-password)"`.
3. The Azure SQL Publish task fails.

### Error logs
```
Sql file: D:\a\r1\a\API Build\scripts\createDbUser.sql
Invoke-Sqlcmd -ServerInstance "hostname.database.windows.net" -Database "dbName" -Username "dbAdmin"  -Password ******  -Inputfile "D:\a\r1\a\API Build\scripts\createDbUser.sql" -Variable "UserPassword=***" -ConnectionTimeout 120
##[error]Incorrect syntax near '***'.
```

If I remove the `-Variable` flag, the error becomes
```
##[error]'UserPassword' scripting variable not definedCheck out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
```
which is expected.

**Comment by Ajay-MS** [comment]
@deepnetwork 

I apologise for a delay in the response. 

From error message, It seems syntax of the SQL query got incorrect after replacing the variable of the value probably because of some special character. 

I have tested with variables in following format and working. 
```
Invoke-Sqlcmd -ServerInstance "test.database.windows.net" -Database "Testdb" -Username "test"  -Password ******  -Inputfile "C:\test.sql" -variable "MYVAR1='$(variablevalue1)'", "MYVAR2='String2'" -ConnectionTimeout 120
``` 

Can you please try in following ways : 
1. SQL Variables without a special characters. 
2. SQL Variable in single quotes as I have given example. 

Depending on the output we will further look into this issue.

**Comment by sugarjig** [comment]
It looks like that worked. I think the difference was the single quotes surrounding the variable, within the double quotes around the key-value pair.
