### ISSUE TITLE
Maven parent pom in Azure Artifacts fails

### ISSUE THREAD

**Issue by ahaeber** [microsoft/azure-pipelines-tasks#8896]
## Environment
Azure Pipelines
    
- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Private agent based on microsoft/ubuntu-16.04-docker-17.12.0-ce-standard

## Issue Description
When building a project that has a parent-pom in Azure Artifacts it fails the build. This seems to be because the Maven v3 task will first do "mvn effective:pom" to generate the effective pom model, parse it and retrieve authentication tokens. Because the Maven task depends on executing "mvn effective:pom" before preparing authentication tokens this fails because it cannot access the parent pom.

As a workaround we added credentials for the parent-pom's feed to the agent docker image in /etc/maven/settings.xml. However that is something we would prefer to avoid doing to avoid disclosing tokens. Another option is to include the Maven settings in the project's git repository and refer to it in the pipeline yml (.vsts-ci.yml) using Maven -s option. However, that has the same flaw as the aforementioned workaround.

**Comment by lpghartz** [comment]
A comment on this, because we got caught by it, too -- the Maven task isn't parsing the POM to retrieve tokens, its parsing it to retrieve a list of all the repositories in the effective POM, and adding the authentication to settings.xml for the ones it finds.  

The fix, as far as we've been able to determine, is to run the process twice -- one on the actual POM, update the settings file, and then on the effective POM, to ensure the parent POM can be retrieved. 

Although, to be honest, I'm not sure there's a value in what its doing -- running the scan against the POM would work for scenarios where you have all the repositories coming from Azure Artifacts listed in the POM, and I'm not sure a scenario where you're inheriting a non-authenticated repository from a parent POM that isn't in an authenticated repo makes any sense. 

We were going to just rip the code out that runs the effective-pom and use the POM on disk, but as of yet we haven't figured out how to deploy a private version of a task into a hosted build environment.

**Comment by madhurig** [comment]
@lpghartz: To upload a private version of the task to your Azure DevOps organization, you can use this tool: https://github.com/Microsoft/tfs-cli. You can update the task version, compile locally and upload the private version. That version will be used on the hosted build environment.

**Comment by lpghartz** [comment]
And that'll work with updated versions of the existing Azure Pipelines tasks? Or do I need to change the GUID as well?  (If its possible to patch and update the existing tasks, that might be worth mentioning in the root readme of the repository...)

**Comment by madhurig** [comment]
Just update the patch version of the task and upload it, don't change the guid. It will update the existing task for your org, so it will impact all builds in the org. So, please be careful if there are other builds/releases in your organization. 

In case of any issues, you can delete the version you uploaded, that will fallback to the original version that we shipped. Delete will not delete the shipped version of the task, it will only remove the version you uploaded. 

Thanks,
Madhuri

**Comment by lpghartz** [comment]
Awesome, that worked like a charm! We added a checkbox to the MavenV3 advanced settings to disable the use of the effective POM and to use the native POM directly, which solves this problem. Thanks!

**Comment by madhurig** [comment]
If you would like to provide a contribution, you can submit a pull request to this repo.

Thanks,
Madhuri

**Comment by lpghartz** [comment]
I don't like working in github, so the change is in a devops git repo that was initialized from this one. I don't think there's a way to do a pull request without creating a branch here, and re-applying the changes, correct? If that's the case, I can do that, but I will need to find some cycles to mess around with the process here.

**Comment by elbatk** [comment]
I believe this was fixed in this PR: https://github.com/microsoft/azure-pipelines-tasks/pull/10637 so I'm closing this here, thank you everyone!
