### ISSUE TITLE
Downloading and Extracting Packages spyder-3.3.2       

### ISSUE THREAD

**Issue by abhishekguin95** [Microsoft/azure-pipelines-tasks#8980]
(base) C:\Users\HP>conda update spyder
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - spyder

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    spyder-3.3.2               |           py37_0         2.8 MB

The following packages will be UPDATED:

    certifi: 2018.8.24-py37_1 --> 2018.10.15-py37_0
    spyder:  3.3.1-py37_1     --> 3.3.2-py37_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
spyder-3.3.2         | 2.8 MB    | ###################################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::spyder-3.3.1-py37_1'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Access is denied')

**Comment by bryanmacfarlane** [comment]
Issues in this repo track issues with in the box tasks in /Tasks.  Can you reactivate and clarify which task you're having an issue with?

**Comment by SarahGrif** [comment]
I got the same error, Windows 10, installing update for Spyder 3.3.2 from Anaconda download.  I rebooted and then went to start menu again.  But instead of opening the Anaconda prompt normally, I right clicked and selected "open as administrator".  Then I did the two prompts:
conda update qt pyqt
conda update spyder

This worked and I verified that the new 3.3.2 version of Spyder was in my Anaconda navigator.
