### ISSUE TITLE
Publishing test results in JUnit format results in unusual Run Id and wrong test run name(s)

### ISSUE THREAD

**Issue by raketenolli** [Microsoft/azure-pipelines-tasks#8982]
## Environment
- Server - Azure Pipelines
- Agent - Hosted: Hosted VS 2017
    
## Issue Description

We have a nightly build definition that runs Node.js WebdriverIO tests using the Jasmine framework through SauceLabs. We have a custom reporter that outputs JUnit format XML files which get published in the _Publish Test Results_ step with the following settings
- Version: 2.*
- Display name: Publish Test Results
- Test result format: JUnit
- Test results files: **\results\\*.xml
- Search folder: ${System.DefaultWorkingDirectory}
- Merge test results not selected
- Test run title: \<empty\>
- Advanced
  - Build platform: \<empty\>
  - Build Configuration: \<empty\>
  - Upload test results files selected
- Control Options
  - Enabled selected
  - Continue on error not selected
  - Timeout: 0
  - Run this task: even if a previous task has failed, unless the build was canceled
- Output variables
  - Reference name: \<empty\>

Before 2018-12-03, JUnit format XML files in this format

    <?xml version="1.0" encoding="UTF-8"?>
    <testsuite name="test run name" timestamp="..." ...>
    <testcase name="test case name 1" classname="spec.js" time="1.234"/>
    <testcase name="test case name 2" classname="spec.js" time="1.234"/>
    <testcase name="test case name 3" classname="spec.js" time="1.234"/>
    </testsuite>

would produce an entry in the _/ Test Plans / Runs / Recent test runs_ list with “test run name” as the _Title_, a _Run Id_ of approx. 111000 and the actual _Build Number_, e.g. 20181130.1

![grafik](https://user-images.githubusercontent.com/14631918/49360615-057a3a80-f6da-11e8-94cc-c158bf3b1f52.png)

Right now (as of 2018-12-03, there were no builds on 2018-12-01 and -02 as this was the weekend) the _Run Id_ is approx. 1100000 (sorting by _Run Id_ is broken, by the way), the _Title_ is “JUnit_TestResults_[BuildNumber]_[TestRun]“ and the _Build Number_ is just a five-digit number.

![grafik](https://user-images.githubusercontent.com/14631918/49360706-3eb2aa80-f6da-11e8-9d84-3ccd8d4d96ab.png)

The wrong test run names also show in the _/ Pipelines / Build / \<Build name\> / #\<Build number\> / Tests_ tab. All internals like test case name, running times, numbers of passed/not executed/failed tests seem to be fine.

Is this change in behavior intentional, and if yes, how can I get my test run _Titles_ back?

**Comment by SadagopanRajaram** [comment]
There are two specific issues here
1) Build Number is showing up as a five digit number. This is a code defect in our service which we have fixed and will be deployed with the next service deployment
2) Test Run Name has changed - we made an explicit change to honor the name given in the task and default to a generated name (as you see) otherwise. If there are multiple suites in the JUnit file, we fall back to a generated test run name and if the name is given in the task, we will use that. To keep it consistent, we made a call to generate the name even for a JUnit result file with a single suite. We will make this the default behavior for non-Windows as well. To get a specific Run Title, please use the name in the task definition. 
Hope that helps.
