### ISSUE TITLE
Node Tool Installer fails on versions [0-3].x

### ISSUE THREAD

**Issue by damccorm** [Microsoft/azure-pipelines-tasks#8987]
## Environment
- Server - Azure Pipelines
- Agent - Hosted VS2017

## Issue Description

The node tool installer fails with a 404 response.

![image](https://user-images.githubusercontent.com/42773683/49381203-63f6e700-f6e1-11e8-9cf5-674d70321d0a.png)

Upon inspection, it looks like it is expecting there to be packages containing node for windows at https://nodejs.org/dist/v0.12.18 that aren't there. This isn't an issue for other newer versions (e.g. https://nodejs.org/dist/v6.13.1/node-v6.13.1-win-x64.7z exists).

### Task logs

More verbose logs:
![image](https://user-images.githubusercontent.com/42773683/49385612-d2d93d80-f6eb-11e8-83ff-7f4744c31e38.png)

zip: [log_21_12.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2640225/log_21_12.zip)

**Comment by damccorm** [comment]
Hm, the Windows 0.x error is definitely the same, the Linux errors look more like expected behavior when that version of node isn't available on nodejs.org (coming from [this line](https://github.com/Microsoft/azure-pipelines-tasks/blob/69a6b16dd2fcd32650a4beccb34982f5bff6d36e/Tasks/NodeToolV0/nodetool.ts#L66)). Judging from [here](https://nodejs.org/dist/index.json) and [here](https://nodejs.org/dist/) it looks like Node 1-3 isn't available for download (or at least isn't from nodejs.org). 

Doing a little more investigation, from [here](https://nodejs.org/en/download/releases/) and other places I've looked it looks like Node itself doesn't actually have versions 1-3, they ended up merging in io.js which did have versions 1-3. Not 100% sure if that's the case, but it definitely looks like they want you to use io.js for those versions. 

@mickeygousset what's your use case here? I'm not sure that the installer is behaving incorrectly given what I just found, and I think most teams just test 0.x and 4.x since Node tries to guarantee back-compat. At the same time, if there's a reason to explicitly test [1-3].x I'd be interested in it.

**Comment by bryanmacfarlane** [comment]
Yeah, there never was a node 1 - 3.  0.12 is marginally interesting to fix

**Comment by mickeygousset** [comment]
@damccorm @bryanmacfarlane  I'm trying to create Azure Pipeline builds for some different open source projects. The goal being I want to recreate their current builds as much as possible.   The particular example I've given above is from the [expressjs\express](https://github.com/expressjs/express) project.   In their Travis and their Appveyor builds, they are testing the following versions:

- 0.10
- 0.12
- 1.8
- 2.5
- 3.3
- 4.9
- 5.12
- 6.14
- 7.10
- 8.12

The Travis builds work for ALL of these versions (it seems to use NVM for the install, based off looking at the logs).  Therefor, I feel this tool should also support it, both so that I can completely recreate the functionality of their current build, as well as to have feature parity with Travis and Appveyor.

I understand that for a lot of teams, testing on the lower versions may not be that critical. However, Appveyor and Travis make it work.  For completeness, I feel the Node Tool should as well.

**Comment by damccorm** [comment]
Judging from the output [here](https://travis-ci.org/expressjs/express/jobs/467371622) what Travis/Appveyor are pulling down is indeed io.js, not technically Node. @bryanmacfarlane I think I'd lean towards doing the same (it should be a pretty small code change) - I tend to think if you're asking for Node 1-3 you probably know what you're actually getting. If we don't want to do that our recommendation should probably be to just install/use nvm.

**Comment by bryanmacfarlane** [comment]
Sure, I'll re-open and mark as an enhancement

**Comment by damccorm** [comment]
Added a PR to address the issue with versions 1-3 (a solution to the original 0.x issue has already been merged)

**Comment by damccorm** [comment]
After discussion in #9116, we're not going to support iojs at this time.
