### ISSUE TITLE
[Question] "File buffer is too short to detect encoding type" fix/solution?

### ISSUE THREAD

**Issue by danieland** [Microsoft/azure-pipelines-tasks#9035]
Hi guys, nice work on this repo:

I'm getting the error: "File buffer is too short to detect encoding type" from a .config file in my website - but I'm having a very hard time figuring out what I can do about this as this error seems to be quite custom and not really leading to anything when googling (only this repo)

Any tips or helpful links on where to go to try and fix this problem with my web deployment?

**Comment by kmkumaran** [comment]
@danieland - can you tell us what task you are using for the web deployment here.

**Comment by danieland** [comment]
Thanks for having a look @kmkumaran !

I'm using a very standard IIS Deployment with the:
- IIS Web App Manage
- IIS Web App Deploy

Pretty much out of the box, only slight changes

**Comment by SumiranAgg** [comment]
If you are still facing the issue please share above information and reopen the ticket.

**Comment by sunmorgus** [comment]
Saw this and thought I would mention here. Ran into this issue today, we have the "XML Variable Substitution" option selected on one of our release pipelines, and the task was failing because the project included a blank ApplicationInsights.config file. Worked around it simply by deleting that file.
