### ISSUE TITLE
Port cannot be defined with Azure File Copy -task

### ISSUE THREAD

**Issue by miksteri** [Microsoft/azure-pipelines-tasks#9049]
Cannot define port with Azure File Copy -task, would be necessary when load balancer is used in order to copy files to all VM's behind load balancer. If port could be defined then i could chain many tasks with Azure File Copy -task and use different port for each task. Then from load balancer NAT rules forward certain port to certain VM.

**Comment by rajatagrawal-dev** [comment]
@miksteri I'm not sure I completely understand your scenario. You can use the task to copy to all VM's behind the load balancer. Also, if you need to copy to a subset of VM's in the resource group, you can use the Filter Criteria option in the task. We support tag based and VM name based filtering.

**Comment by henrikmh** [comment]
I believe i'm hitting the same scenario/issue as @miksteri. My scenario is as follows:

I have a resource group with 2 VMs for HA. Both of these VMs are on a VNET and do not have a public IP address. However, in front of these two VMs is a load balancer that _do_ have a public IP assigned. 

I can make the Azure file copy task work fine for a single VM by creating an Inbound NAT Rule that opens port 5986 (WinRM) and point it to one of the VMs. As a desperate attempt, i tried creating an Inbound NAT Rule on Port 5987 for the other VM, but that did not work.

So question is, beyond assigning a public IP to each of these VMs, how would I copy the files to both VMs when they are behind a load balancer? What kind of Inbound NAT Rule should I create? 

I think OPs suggestion is that you could add a port parameter, and this would allow for creating idfferent inbound NAT rules, and you could then chain tasks in VSTS, creating one copy task per VM.

**Comment by rajatagrawal-dev** [comment]
@henrikmh You are right in creating inbound NAT rules on the load balancer. But you do not need to map 5986 port of load balancer. You can map any port of load balancer to port 5986 of the VM.

So if you have 2 VM's behind the load balancer, you can create these NAT rules:

1. Map port 9000 of load balancer to port 5986 of VM1
2. Map port 9001 of load balancer to port 5986 of VM2

The Azure File Copy task searches for all mappings targeting port 5986 of all VM's.

PS: We identified a bug in the Azure File Copy task due to which the task fails while fetching the status of the copy job. We are working on a fix and will let you know once it is released.

**Comment by henrikmh** [comment]
@rajatagrawal-dev Ah, i see, got it - thank you! That got me past the FQDN error, but I did get the error on fetching of status as you described. I disabled "copy in parallel" which seemed to resolve it though

**Comment by niadak** [comment]
@henrikmh,  Can you please use "Deployment Group" feature for your scenario. In this model we dont have WinRM or Remote Deployment dependency and deployment will be done in Pull based model. For more details refer to below documents.

https://devblogs.microsoft.com/devops/deployment-groups/
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=azure-devops
