### ISSUE TITLE
Please add Node Tool support for using nodejs nightly builds

### ISSUE THREAD

**Issue by mickeygousset** [Microsoft/azure-pipelines-tasks#9096]
## Environment

- Server - Azure Pipelines
- Agent - Hosted VS2017 

## Issue Description

Travis CI provides the ability to create builds using the nightly build from Nodejs.  In the screenshot below (from the ExpressJS repository), they are specifying multiple versions of NodeJS, and specifying that certain versions use the nightly build.

The Node Tool should provide this support as well.  It should be provided in such as way that, if I am using a matrix, then, for each node version in the matrix, I can specify whether or not that version should use the nightly build.

![image](https://user-images.githubusercontent.com/20031479/50060515-b8c34480-015a-11e9-9580-b494698c5bdd.png)

**Comment by damccorm** [comment]
I'm looking into this, a couple of clarifying questions/thoughts though:

1) What does it actually mean to get nightly builds for node v9 or v10? From [here](https://nodejs.org/download/nightly/), new nightly builds are only being released for v12 since its the only one being actively developed, so I'm not sure what that would even mean.
2) To get some clarification on (1), I tried to look at the travis builds of the express repo you're referencing. It doesn't actually look like they're using nightly builds, regardless of what is in their YAML. Look at the nvm install steps [here](https://travis-ci.org/expressjs/express/jobs/469351438) and [here](https://travis-ci.org/expressjs/express/jobs/469351439) - they're pulling from https://nodejs.org/dist, not https://nodejs.org/download/nightly. Maybe because the env variable they're using [is deprecated](https://stackoverflow.com/questions/36467239/nvm-nodejs-org-mirror-is-deprecated-please-use-nodejs-org-mirror)?
3) Why is this actually a useful feature? I don't really see a use case where you need this (though that's not to say there isn't one, I'm just struggling to think of one).

Overall, I'd be open to adding this, but I think we need a compelling reason beyond just maintaining exact feature parity with Travis, especially if they're not actually doing anything with this.

**Comment by mickeygousset** [comment]
I'm not sure I'll be much help answering these questions, unfortunately.  If, in examining the repos, it doesn't look like they are using the nightly builds, then it could be because they didn't update the build file to use the new variable.  But if no one is complaining, then it may be that it doesn't matter as much.  My biggest argument for this feature was for parity, and so I could create an Azure Pipeline build that matched what they have.  I can always make the argument that the currently nightly feature is no longer being used.  So I'm not sure I have the silver bullet argument that says this feature MUST be added. However, it would be something nice to have, and would give parity with Travis.

**Comment by damccorm** [comment]
Ok, I don't think that it makes sense to add this right now, then. Since we don't have a use case I think I'd rather avoid having 1 more thing to maintain/document. With that being said, I'd definitely be open to adding it in the future given a use case.

**Comment by bryanmacfarlane** [comment]
Is their a specific customer that's driving this need?  If so then that's a good use case ...

@mickeygousset ?

**Comment by mickeygousset** [comment]
Specific customer at this point, no.  The test will be when I finish creating the Azure DevOps pipeline for the ExpressJS repository and submit it to them.  If they reject it because that functionality isn't in the build, then it definitely becomes an issue.

What I will do is submit it without it, and see what happens. I'll also point out that their current build isn't really using it either.
