### ISSUE TITLE
[Github Release] Changelog doesn't work on non-master branch

### ISSUE THREAD

**Issue by mydiemho** [Microsoft/azure-pipelines-tasks#9138]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines 
   * https://dev.azure.com/msft-vott/VoTT/_releaseProgress?_a=release-pipeline-progress&releaseId=3

- Agent - Hosted 
    - Queue: Hosted

## Issue Description

ChangeLog feature doesn't work if I'm trying to release on a beta branch because it will try to find the changes between the commit on my working branch with the latest public release (which was based off master).  This will fail because there's no common ancestor.

It will be great if there's a setting for saying base ChangeLog off the branch and not whatever is latest release.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

[tasklog_7.log](https://github.com/Microsoft/azure-pipelines-tasks/files/2700700/tasklog_7.log)

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by raiyanalam** [comment]
Sorry for the inconvenience faced. The changelog in release notes generally contain the changes that have been done to the last release. For this, the task internally uses the APIs provided by GitHub to find the difference between 2 commits. The difference works even when the commits are from 2 different branches but they should have at least some common ancestry. In your case however, the beta branch seems to be completely different compared to the master branch, thus the GitHub API returns an error because the difference cannot be calculated. 
Is there a reason that beta branch is completely new compared to the older release? What do you think should be the ideal output of the task in such cases?

**Comment by mydiemho** [comment]
1. The beta branch is completely new because we needed to start over with V2.  
1. In such cases, I wasn't hoping for a different output but more of configuration that would allow me to choose an origin branch, ie. specify an origin branch other than master.

**Comment by raiyanalam** [comment]
I see. This seems to be a one off case. However, can you add this feature request in [Azure DevOps Community](https://developercommunity.visualstudio.com/spaces/21/index.html) so that other people can see it and upvote. This will help us prioritize it better. 
I am closing this issue for now.
