### ISSUE TITLE
Code Coverage tab not formatted correctly in Azure Devops

### ISSUE THREAD

**Issue by teejam2** [Microsoft/azure-pipelines-tasks#9215]
## Environment
- Server - Azure Pipelines
- Account name: bcagroup
- Team project name: LOL
- Build definition name: ci_lolrequestdetectionserver
- Build number: #20181231.2
- Agent - Private
- OS: Windows Server 2008
- Agent version: 2.142.1

## Issue Description

Similar to https://github.com/Microsoft/azure-pipelines-tasks/issues/3027#issue-187223113

When I run the build the code coverage task completes successfully. This is shown in the summary:
![image](https://user-images.githubusercontent.com/27975947/50594628-3abea780-0e95-11e9-939f-1cd5030ac615.png)

I can download the artifact and extract it, and then when I open index.html I can see the correct output:
![image](https://user-images.githubusercontent.com/27975947/50594826-fe3f7b80-0e95-11e9-8423-aa199e4f1ce7.png)

But when I click on the Code Coverage tab the output is rendered as text only:

![image](https://user-images.githubusercontent.com/27975947/50594857-28913900-0e96-11e9-9fe0-a4a525a46333.png)

### Task logs
[log_7_10013.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2720913/log_7_10013.zip)

### Error logs

n/a

**Comment by vagisha-nidhi** [comment]
Hi @teejam2 
This is a know issue as pointed out in #3027 
We have disabled styling due to some security constraints. You can download the coverage files and view it with rich HTML experience in offline.
As a workaround, you can take reference from #3027 [here](https://github.com/Microsoft/azure-pipelines-tasks/issues/3027#issuecomment-385740426).
Please suggest/vote for this at [https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services)
We appreciate your feedback and please do consider that we prioritize based on the feedback.

**Comment by teejam2** [comment]
Yes I used the inline CSS workaround, thanks, I wasn't sure if this should be a seperate issue as #3027 makes reference to VSTS and this is in Azure Devops
