### ISSUE TITLE
VsTestV2 Publishing test results fails

### ISSUE THREAD

**Issue by bergmeister** [microsoft/azure-pipelines-tasks#9226]
## Environment
- Server - Azure Pipelines or TFS on-premises?

Azure Pipelines:
https://rcss-02-willistowerswatson.visualstudio.com/Unify/_releaseProgress?_a=release-environment-logs&releaseId=12746&environmentId=13298

- Agent - Hosted or Private: 
    
    - private agent, Windows, agent version 2.141.1

## Issue Description

The VSTestV2 tasks fails to publish test results when setting the following setting (it was blank before and still works for other release definitions)
![image](https://user-images.githubusercontent.com/9250262/50631948-326e7700-0f3e-11e9-9945-3646501b381f.png)

### Task logs

See e.g. run [here](https://rcss-02-willistowerswatson.visualstudio.com/Unify/_releaseProgress?_a=release-environment-logs&releaseId=12746&environmentId=13298)
```
2019-01-02T16:56:02.1826054Z Results File: D:\_Builds\RCSSV-EM20-014T.01\r2\a\TestResults\sveAzRCSTST_RCSSV-EM20-014T_2019-01-02_16_28_36.trx
2019-01-02T16:56:02.1848960Z 
2019-01-02T16:56:02.1851666Z Total tests: 937. Passed: 937. Failed: 0. Skipped: 0.
2019-01-02T16:56:02.1852865Z Test Run Successful.
2019-01-02T16:56:02.1866617Z Test execution time: 27.5795 Minutes
2019-01-02T16:56:02.3949709Z ##[warning]Failed to publish test results: The filename, directory name or volume label syntax is incorrect : 'C:\_VSTS Agents\RCSSV-EM20-014T.01\bin\;publishRunAttachments=true;resultFiles=D:\_Builds\RCSSV-EM20-014T.01\r2\a\TestResults\sveAzRCSTST_RCSSV-EM20-014T_2019-01-02_16_28_36.trx;]'
```

**Comment by vagisha-nidhi** [comment]
![image](https://user-images.githubusercontent.com/13175100/50885347-79afa880-1413-11e9-98e3-37176ddb81d5.png)

Please provide the logs zip as requested in the issues template. For details on how to obtain logs please check the issues template again.

**Comment by bergmeister** [comment]
@vagisha-nidhi Please find the attached log file with `system.debug` set to `true of [this](https://rcss-02-willistowerswatson.visualstudio.com/Unify/_releaseProgress?releaseId=12854&environmentId=13416&_a=release-environment-logs) release below
[tasklog_8.log](https://github.com/Microsoft/azure-pipelines-tasks/files/2740861/tasklog_8.log)

**Comment by vagisha-nidhi** [comment]
Hi @bergmeister 
The issue as we can see in the log is the test run title, i.e, _$(RELEASE.RELEASENAME)_ you are providing.
```
2019-01-09T11:11:07.7478830Z ##[debug]1 final results
2019-01-09T11:11:07.9952454Z ##[debug]Reading test results from file ';publishRunAttachments=true;resultFiles=D:\_Builds\RCSSV-EM20-014T.01\r2\a\TestResults\sveAzRCSTST_RCSSV-EM20-014T_2019-01-09_10_46_20.trx;]'
2019-01-09T11:11:08.0484767Z ##[warning]Failed to publish test results: The filename, directory name or volume label syntax is incorrect : 'C:\_VSTS Agents\RCSSV-EM20-014T.01\bin\;publishRunAttachments=true;resultFiles=D:\_Builds\RCSSV-EM20-014T.01\r2\a\TestResults\sveAzRCSTST_RCSSV-EM20-014T_2019-01-09_10_46_20.trx;]'
2019-01-09T11:11:08.0494095Z ##[debug]Processed: ##vso[results.publish type=VSTest;mergeResults=false;runTitle=Unify (IT) - Branch [12854];publishRunAttachments=true;resultFiles=D:\_Builds\RCSSV-EM20-014T.01\r2\a\TestResults\sveAzRCSTST_RCSSV-EM20-014T_2019-01-09_10_46_20.trx;]
```
The test run title is _Unify (IT) - Branch [12854]_ which contains square brackets **[**12854**]** is causing parsing error in determining the result files. 
`2019-01-09T11:11:07.9952454Z ##[debug]Reading test results from file ';publishRunAttachments=true;resultFiles=D:\_Builds\RCSSV-EM20-014T.01\r2\a\TestResults\sveAzRCSTST_RCSSV-EM20-014T_2019-01-09_10_46_20.trx;]'`

We'll mark this as bug but since we haven't been hitting this a lot, I'll suggest a quick workaround to not to use square brackets in test run title. For example, _runTitle=Unify (IT) - Branch (12854)_ would work fine.

**Comment by bergmeister** [comment]
@vagisha-nidhi Thanks for the info.
We are using the ` $(RELEASE.RELEASENAME)` that is built into Azure DevOps to uniquely identify the the test run later (we call the rest APIs to analyse the test run if tests had to be rerun and then mark the release as orange since issue #8133 has not been implemented yet). Therefore I'd like to avoid using a non-standard name for that to avoid strong coupling. Also note that because this is a built in variable in a release, it is not us but Azure DevOps adding the release number in brackets to it.

**Comment by vagisha-nidhi** [comment]
Hi @bergmeister 
I tried the scenario you mentioned, that is publishing failing only when providing a test run title. I tried to repro this locally using the test run title given in the logs. I was able to see the same failing pattern only with the square brackets. 
For us to see if the issue is something else, can you please provide the _entire zip containing all logs_ as mentioned in the issue template?
Also, as you mentioned, you have other release definitions where this does not happen with the same naming pattern for test run title?

**Comment by bergmeister** [comment]
@vagisha-nidhi [Here](https://rcss-02-willistowerswatson.visualstudio.com/Unify/_releaseProgress?_a=release-pipeline-progress&releaseId=12846) is a result from a different release definition that is using VSTest in the same way where this does not happen. I have given you a [link](https://rcss-02-willistowerswatson.visualstudio.com/Unify/_releaseProgress?releaseId=12854&environmentId=13416&_a=release-environment-logs) to the release where it happens, I am afraid I cannot attach the log of the whole release due to this forum being public but I do not see the need for it since this is an issue of the task itself only

**Comment by vagisha-nidhi** [comment]
@bergmeister 
It makes sense to use a standard name for run title. There is one more thing you can try and let me know if this unblocks you for now.
Instead of using _$(RELEASE.RELEASENAME)_ for test run title, can you try _$(Release.DefinitionName)-($(Release.DefinitionId))_? This will make sure that you are using standard variables.
Please share logs of this task even this workaround doesn't work for you.

**Comment by prawalagarwal** [comment]
Please reopen if the issue is not resolved.
