### ISSUE TITLE
Azure Powershell task 2.1.7 and higher (3.* included) have problem with Get-AzureRmContext

### ISSUE THREAD

**Issue by RadekVoltr** [Microsoft/azure-pipelines-tasks#9315]
- Azure DevOps
- Private agent, latest version, latest version AzureRm

We have this code on beginning of our script : 

# sign in
Write-Host "Logging in...";
if ([string]::IsNullOrEmpty($(Get-AzureRmContext).Account)) {Login-AzureRmAccount}

If powershell is already logged (manually or from devops), it just pass and everything is ok. It worked for more than year but suddenly stopped today with version of task 2.1.7 and higher. Works again when I changed our pipelines to use 1.* as hotfix

Can you advise working version how to check if user is already logged in by Azure DevOps task or fix that issue ?

**Comment by vincentdass** [comment]
@RadekVoltr , we identified a security issue with Azure PowerShell issue and made a hotfix.
This is to ensure that no credentials or context is left back once the task is completed. 
To run Azure PS commandlets, You can login again using the PowerShell task.

**Comment by RadekVoltr** [comment]
ok, I removed Get-AzureRmContext and it works now. Thanks for feedback

**Comment by robdmoore** [comment]
Hi @vincentdass,

That's a fairly major breaking change - I have a few uses for `Get-AzureRmContext` in my scripts.

In particular:

* Checking that the subscription ID of the context is in fact the right one (avoids this issue in earlier versions of Azure PowerShell: https://github.com/Azure/azure-powershell/issues/4715) <- this one I can skip when running in Azure DevOps by checking for the TF_BUILD environment variable, but it was nice to be able to query what subscription the script is currently acting against...
* Getting the object id of the current user so I can provision a key vault that the deployment user has access to set and get secrets in for the purposes of randomly generating passwords idempotently. There is no workaround for this that I can find since `Get-AzureRmAdUser` requires you to search by something, but in Azure DevOps the user is via an automatically generated service principal I have no information about.

Do you have any suggestions for how to deal with the latter now that Get-AzureRmContext no longer works?

Totally understand the security issue, interestingly, the code I had to get the object ID of the user actually had to parse the JWT from the context and pull out the oid claim.

**Comment by robdmoore** [comment]
Side note: changing to 1.x doesn't seem to work for me as a workaround unless I'm missing something...

**Comment by robdmoore** [comment]
Ugh, ignore everything I wrote above, my problem wasn't this, but rather that I was setting up a new pipeline and selected "Hosted" agent rather than "Hosted VS 2017" and got a really old version of Azure PowerShell :/

Confusingly, I'm now running  v3 of this task and my code that uses Get-AzureRmContext actually works, so now I'm super confused about what the original poster was experiencing?
