### ISSUE TITLE
Nuget tool installer in offline environment

### ISSUE THREAD

**Issue by vlm---** [Microsoft/azure-pipelines-tasks#9398]
## Environment
- TFS on-premises, latest
- Agent - Private: Windows, latest
## Issue Description
Nuget tool installer task downloads file from internet or local tools cache hence in our offline environment we have to manually populate cache for every installed agent. I would suggest to add capability to download Nuget.CommandLine package from local nuget feed as third option.

**Comment by alexmullans** [comment]
The tool installers are generally intended for internet-connected environments. Unless it's changed (@vtbassmatt or @bryanmacfarlane to confirm), manually populating the cache is the right answer for offline agents. Closing this for now; Bryan/Matt, feel free to reopen if I've missed something.

**Comment by vtbassmatt** [comment]
I'm not sure it's fair to say they're "for internet-connected environments". The tools cache is the mainline way to support non-internet scenarios. Packaging tools are interesting in that most of them self-host, so I can `pip install -U pip` and `npm install -g npm` from a command line. I wouldn't stand in the way of making that available in the task, but I think it's an edge case.

**Comment by vtbassmatt** [comment]
[Tool cache docs](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/tools.md#tool-cache) are available.

**Comment by thomasdgx** [comment]
In some enterprises it is simply not allowed to provide internet access to the machines. The tool cache is not a sustainable workaround. One needs to touch the build machines every time when a new version should be used or when a new build agent is added. In larger enterprises this does not scale, therefore we need a better solution.

Currently the url is hard coded: (see here: [NuGetToolGetter.ts](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/packaging-common/nuget/NuGetToolGetter.ts))

````
137:    async function getLatestMatchVersionInfo(versionSpec: string): Promise<INuGetVersionInfo> {
138:        taskLib.debug('Querying versions list');
139:
140:        let versionsUrl = 'https://dist.nuget.org/tools.json';
````

I would prefer to be able to use internal package feeds (as provided with TFS package management). 

Would it be ok to send a pull request in order to make this url configurable?

**Comment by vtbassmatt** [comment]
@thomasdgx feel free to propose something. I have only ~medium confidence we would accept such a change. The tasks are complicated enough as it is, so taking additional options and inputs always has a high bar to clear.

I'm interested to hear more about using the tool cache and where it fails. In large enterprises, I imagine you have automation for bringing up and updating agent hosts (ARM templates, Packer files, or at least scripts). Your tool cache could even live on a network share so that you can drop new versions on it and have them automatically picked up on every agent.

**Comment by silvianoblea** [comment]
FYI, I am also interested in an offline nuget installer or somehow upgrade the AZDO or Build Server nuget package as a workaround?  I have on-premise instances that don't have connection to internet and we need to be able to upgrade the existing buget version.  I have discovered that the seems to be several instances of nuget in the tools cache as well as in an external directory??  How can we patch the source of nuget.exe on the build servers (aka where does the original source reside)?

Environment: Azure DevOps Server 2019 on premise.

**Comment by ColinM9991** [comment]
> [Tool cache docs](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/tools.md#tool-cache) are available.

Tried this recently but it didn't work, it still used NuGet 4.1.0.

The folder structure was

```
_work/tools
    NuGet
        5.6.0
            x64
                 nuget.exe
```

**Comment by vlm---** [comment]
> > [Tool cache docs](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/tools.md#tool-cache) are available.
> 
> Tried this recently but it didn't work, it still used NuGet 4.1.0.
> 
> The folder structure was
> 
> ```
> _work/tools
>     NuGet
>         5.6.0
>             x64
>                  nuget.exe
> ```

Recently I've tried to use one common tools directory for multiple agents on one machine and only after examining the source code for installer task I 've found the solution: There has to be an empty file named `x64.complete` beside the x64 folder for installer to find it there.
