### ISSUE TITLE
TFS Impact Tests are not working with NUnit

### ISSUE THREAD

**Issue by ADBrinkman** [Microsoft/azure-pipelines-tasks#9406]
## Issue description 
When configuring the VS Test task to "Run only impacted Tests", code changes are not picked up by any of the affected NUnit tests.
The tests are correctly discovered with the NUnit Adapter, but the TestSelector GetImpactedTests does not return any impacted tests.

New tests or failed tests are correctly picked up and run. But tests are not picked up and run for code changes that impact tests.

If I use MSTest tests instead, these work as expected.

### Task logs
Full build debug logs are here:
[Build logs - Impact tests not working.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2793467/Build.logs.-.Impact.tests.not.working.zip)

## Environment
- TFS is on-premise
- TFS Version 15.117.27414.0
- Visual Studio Enterprise 2017, version 15.9.5    
- NUnit version 3.11.0
- NUnit Adapter version 3.12.0.0

**Comment by mayankbansal018** [comment]
@ADBrinkman test impact doesn't work with nUnit adapter, as they send events like "TestCaseStart", "TestCaseEnd" etc. asynchronously. TestImpact relies on these events to be in synchronous manner.
@acesiddhu  to confirm.

**Comment by ADBrinkman** [comment]
Hi @mayankbansal018 , @acesiddhu 

We ran the VS Test task with a runsettings file specifying the CollectDataForEachTestSeparately which according to this post https://github.com/nunit/nunit3-vs-adapter/issues/560 I think should mean that the events are fired synchronously, but this still had the same problem:

`<RunConfiguration>`
`        <CollectDataForEachTestSeparately>true</CollectDataForEachTestSeparately>`
`</RunConfiguration>`

Thanks,
Adam

**Comment by acesiddhu** [comment]
@ADBrinkman from this PR https://github.com/nunit/nunit3-vs-adapter/pull/510/files it looks like this will work only for InProcDataCollector. Here is the comment in code "TestPlatform can opt-in to run tests one at a time so that the InProcDataCollectors can collect the data for each one of them separately. "

TestImpact is a outofprocdatacollector. May be you should create a issue on NUnit side and see if ourofproc data collectors can also benefit from the above flag?
