### ISSUE TITLE
SqlDacpacDeploymentOnMachineGroup : error on queuing new build

### ISSUE THREAD

**Issue by RubenDelange** [Microsoft/azure-pipelines-tasks#9428]
## Environment
- Server - Azure Pipelines
- Agent - Hosted 

## Issue Description

- Task name : SqlDacpacDeploymentOnMachineGroup
- Configuration
![image](https://user-images.githubusercontent.com/17595270/51833590-28028b80-22f8-11e9-918a-c45d554be0fa.png)
- Error on queuing a new build
![image](https://user-images.githubusercontent.com/17595270/51833651-5718fd00-22f8-11e9-93a4-935623a0ad90.png)

**Comment by kmkumaran** [comment]
@RubenDelange - The Machinegroup suffixed task are applicable only with Deployment group phase in "Release Management".
![image](https://user-images.githubusercontent.com/11780076/51845216-1e4f4700-233d-11e9-98fb-c50ff78e23bd.png)

This task does now show in the task catalogue if you are adding tasks for agent phase. So, I am surprised that you were able to create a workflow with deployment group based task in agent phase. Can you tell us the sequence of steps you followed to get here?

**Comment by RubenDelange** [comment]
@kmkumaran : we would like to use a custom task group that contains the "SQL Server Database Deploy" task in order to publish a dacpac file to a SQL local db on Azure DevOps.

For now, we do the publishing via a cmd line task pointing to "%ProgramFiles%\Microsoft SQL Server\140\DAC\bin\sqlpackage.exe". However, we noticed today that this step started to break because the "140" path no longer exists on the hosted build agent. Switching to a "150" path solves the issue, but we would like to avoid this manual fix in the future.

If we disable the cmd line task, introduce a "SQL Server Database Deploy" task, save the task group and manually trigger a new build, we see the exception as shown in my original post.

**Comment by arjgupta** [comment]
Hi @RubenDelange , you are using the "Sql Server on Dacpac Deployment" task for Deployment Group. This task is meant to be used only in a Deployment Group Phase. That is why you are getting the error because you try to use this task in an Agent Phase. I think what you need is the "IIS Web App Deployment using WinRM" extension. This extension has a task called "Sql Server Dacapac Deployment using WinRM". You can install this extension from marketplace [here](https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.iiswebapp)

**Comment by RubenDelange** [comment]
@arjgupta : Thanks, we'll give it a try!
