### ISSUE TITLE
SqlPackage.exe /p:BackupDatabaseBeforeChanges=true fails on Azure

### ISSUE THREAD

**Issue by RobinHSanner** [Microsoft/azure-pipelines-tasks#9515]
Adding the SqlPackage.exe parameter /p:BackupDatabaseBeforeChanges=true fails on a deployment to Azure SQL with the error: 

2019-02-06T17:41:15.4560995Z ##[error]*** Could not deploy package.
2019-02-06T17:41:15.4593389Z ##[error]Error SQL72014: .Net SqlClient Data Provider: Msg 40515, Level 15, State 1, Line 16 Reference to database and/or server name in 'master.dbo.xp_instance_regread' is not supported in this version of SQL Server.

The database version info is:
ProductVersion	ProductLevel	Edition	EngineEdition	Edition	MayorVersion	version
12.0.2000.8	RTM	SQL Azure	5	SQL Azure	12	Microsoft SQL Azure (RTM) - 12.0.2000.8   Dec 19 2018 08:43:17   Copyright (C) 2018 Microsoft Corporation

**Comment by Ajay-MS** [comment]
@RobinHSanner 
As this issue is related to SQLPackage.exe tool. I have reported issue with SQL team and will update the thread once get a response on this.

**Comment by Ajay-MS** [comment]
`/p:BackupDatabaseBeforeChanges=true` options is for on-premise databases. That option doesn’t apply to Azure since the backup system is completely different. 

You should use [Azure backup mechanisms](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-automated-backups), which are mostly automatic.

**Comment by successhawk** [comment]
Why wouldn't you update the documentation/help to specify this?
