### ISSUE TITLE
appcmd.exe' exited with code '1062

### ISSUE THREAD

**Issue by fthkucuk** [microsoft/azure-pipelines-tasks#9596]
## Environment

- Server - Azure Pipelines and TFS on-premises

- Agent - Hosted and Private:
   
## Issue Description

Could you add a checkbox to action for arguments (for example; "| exit 0") or work with an argument.

If you add a checkbox, I don't get an error for this reason.

![image](https://user-images.githubusercontent.com/46280608/52850625-f88bb580-3124-11e9-99f5-84cae385b512.png)

![image](https://user-images.githubusercontent.com/46280608/52850643-02adb400-3125-11e9-8a40-ba6d61a1ea88.png)

**Comment by niadak** [comment]
@fthkucuk, Are you still facing the issue? Can you please share the debug log of the task with us?

**Comment by fthkucuk** [comment]
> @fthkucuk, Are you still facing the issue? Can you please share the debug log of the task with us?
@niadak I attached log of the task.

[tasklog_5.log](https://github.com/Microsoft/azure-pipelines-tasks/files/2991776/tasklog_5.log)

**Comment by JasonHenson** [comment]
I am also having the same issue this morning.

**Comment by chperich** [comment]
@fthkucuk: The main issue here is stop operation is not being treated as idempotant. The task should ideally check for this exit code and ignore this error. We will add this to our back log. But it might take a little longer for us to get to it.

Until then, to avoid your pipeline run from failing due to this error, you can choose "Continue on error". This will let the run continue even on task failure. Incase you want to contribute, please feel free to raise a PR against this repo.

![image](https://user-images.githubusercontent.com/29059599/56033389-1f8bef80-5d42-11e9-9082-7d4f624b69f7.png)

**Comment by fthkucuk** [comment]
Hi @chperich, I already know that (Continue on error) but it might be nice to solve that in future.

**Comment by MartinEnser** [comment]
Hello Guys,
i actually got the same problem. My Pipeline is throwing the error that is mentioned above because my AppPool is already stopped. I could use "Continue on Error" aswell, but i want to have a sucessfull release and not a "partial sucessfull" one.
If there is a solution available it would be great to hear it. ;)
Greetings Martin

**Comment by freemstr** [comment]
Maybe this is worth revisiting?
https://github.com/microsoft/azure-pipelines-tasks/issues/13232#issuecomment-818428529

**Comment by kmkumaran** [comment]
+ @vijayma

**Comment by vzalamea** [comment]
got same error today.  This should be reopened.
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/20912588/dd862db5-3da0-4c5d-a6a2-f1761286f7c8)

**Comment by oulaoba** [comment]
The error that appears to be caused by file occupation leading to a failed file replacement is usually the ` [appname]. dll` file.

**Comment by Vikitorony** [comment]
In my opinion, this is not an Azure Pipelines issue, but an IIS behaviour.

When you try to stop a stopped AppPool, `appcmd` will return with error code `1062`.
<img width="661" height="193" alt="Image" src="https://github.com/user-attachments/assets/f77d9eba-76e5-43a7-a0d7-35e7693ed8f8" />

When you try to start a started AppPool, `appcmd` returns `0`.
<img width="669" height="177" alt="Image" src="https://github.com/user-attachments/assets/ef081bcd-2fb7-4e8e-9ca1-bad905a14ac7" />
