### ISSUE TITLE
[Question] How to get task updates for Azure DevOps Server 2019

### ISSUE THREAD

**Issue by MattDavisRM** [Microsoft/azure-pipelines-tasks#9660]
I see in a few other questions that it is mentioned that task updates / new versions might be provided for consumption in quarterly updates.  Is that still the way to get updates?  We are testing an upgrade to Azure DevOps Server and I noticed that in Azure DevOps Services there are some newer versions of tasks (PowerShell on Target Machine for example) that are not currently available on Server.

Is there anywhere I can track the roadmap/timeline for version availability of tasks?  Is there any reason the latest versions of these tasks have not already packaged into the RC for Azure DevOps Server?

**Comment by stephenmichaelf** [comment]
@MattDavisRM We have regular releases and we have our release notes [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/). In each of the release to Azure Dev Ops Server there are updates to our tasks but due to branching and timing they may not always be the latest. Outside of getting task updates through updating Azure DevOps Server there are no supported methods for getting the latest of all tasks.

Which version of Azure DevOps Server are you looking at upgrading to and which version of PowerShell on Target Machine is missing? The latest code has V1/V2/V3.

If possible the best way to get the most recent tasks and their most recent versions is to use the service. We currently release every 3 weeks and the latest tasks are always there.

Unfortunately we do not track our on premise roadmap at the task version granularity.
