### ISSUE TITLE
[Feature Request] GitHub Release Task should allow force-updating a user-specified tag

### ISSUE THREAD

**Issue by TheGoddessInari** [Microsoft/azure-pipelines-tasks#9735]
To support 'nightly' or 'latest' style releases on GitHub, the create subtask should support force-updating a user-specified tag (such as `nightly` or `latest`) to whatever source commit the release has a hold of, as part of the release process.

This would enable the specific use-case of `nightly` style releases. Currently, DevOps provides no way to update the tag underlying a GitHub release once created, even if you delete and recreate the release itself.

**Comment by raiyanalam** [comment]
Thanks for your suggestion. Can you also point me to your repo or a public one, which has similar release process. This will help us understand it at a better depth.

**Comment by TheGoddessInari** [comment]
I hope this is what you mean.

https://github.com/TheGoddessInari/rambox
https://dev.azure.com/TheGoddessInari/rambox/_release?definitionId=1

I'd noticed it before, but GitHub doesn't itself handle this very well.

I'd been previously using AppVeyor for holding build artifacts, but they have been evasive about ever supporting MacOS.

I'd just host builds directly on Azure DevOps, but there doesn't seem to be a way to have an URL that's "this is the latest successful build artifacts, and here's a direct download URL for a particular binary". That being so if you put the links in a README or similar, people can just click on it to get the latest without there being any hiccups if a build is uploading new binaries.

Access to nightlies I learned is an important convenience function as no matter how (relatively) painless you make building, most people who are even tracking your repo and submitting issues won't bother building themselves.

**Comment by raiyanalam** [comment]
Hi,
   Instead of renaming the older release, is it possible for you to have a new nightly release with a accurate versioning- something similar to this: [https://github.com/atom/atom-nightly-releases/releases](https://github.com/atom/atom-nightly-releases/releases).
This way all your old nightly releases are still available for users. In order to get the latest one using a static url one needs to append 'latest' in the end of url. [This github doc](https://help.github.com/en/articles/linking-to-releases) elaborates the scenario. However the catch seems to be that this release should be marked as 'latest'.

Let me know if this works in your case.

**Comment by TheGoddessInari** [comment]
The 'latest' release only works with non-prerelease builds from what I can tell of GitHub's API, so it's not really sufficient

A separate repo could be used, but part of the reason I forked in the first place was to get away from needing separate release/nightly/staging repos for a single project.

That comes with its own maintenance burdens and confusion.

Ideally the GitHub API itself would allow replacing the artifacts and change the release time, or allow some way to 'pin' a release to the top. Either way, force-updating the underlying tag would still be needed.

**Comment by raiyanalam** [comment]
I see your scenario. For my previous suggested solution, i assumed that  marking the release as 'pre-release' would not be important for you since the tag itself says 'nightly-v0.0.12'. Also AFAIK, this is a concept specific to github only.  Is there a specific reason for having 'pre-release' badge on your releases?

Keeping the above aside, can you try the following work around:
1. First time a new binary has to be released, create 2 github releases. One with "nightly-latest" tag and another with actual nightly version eg 'nightly-v0.0.12'. You can use github release task for this. 
2. From next time onwards, whenever a new binary needs to be uploaded. do the following:
- delete release with 'nightly latest'. You can use github release task for this.
- delete tag 'nightly latest' from repo. You may have to write a small script for this. Here is the [github api](https://developer.github.com/v3/git/refs/#delete-a-reference)
- create 2 new github releases. One with "nightly-latest" tag and another with next nightly version eg 'nightly-v0.0.13'. Again you can use the github release task for this.

Hope this works out for your scenario. Let me know if it doesn't.

**Comment by TheGoddessInari** [comment]
I'm aware of the github API, but the whole point is that I'd like to be able to (and should be able to) force-update the tag through the Azure DevOps configuration instead of having to put tokens and make a special script for what's a fairly straightforward need. That's why it's a feature request. :)

Currently I'm doing it manually, but then there's a mismatch between the time of tagging (during the push to the upstream repo), and when it actually gets built, then deployed.

I might be a bit spoiled by the notion of evergreen artifact URLs and atomic updates, so someone doesn't unexpectedly have their file get a 404 or corrupted if they happen to be downloading or trying to download when a deployment is in progress. It's a boon for small projects like mine where I can't really get special external hosting for nightly builds or similar, but still need to support MacOS builds, which normally come with a high cost or complete infeasibility from pretty much everything except Azure DevOps.

**Comment by raiyanalam** [comment]
Apologies, I missed responding to this.
I see your scenario, apart from the work around suggested earlier, we would like you to submit a feature request as well in our [Azure Devops forum](https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea). This will let others who are facing similar issue vote on this and we can prioritize your request better. I am closing this for now.
