### ISSUE TITLE
[Feature Request] GitHub release edit task should have an option for recreating a release

### ISSUE THREAD

**Issue by TheGoddessInari** [microsoft/azure-pipelines-tasks#9736]
The edit task should have an option to 'recreate' a github release atomically to update the timestamp seen on the GitHub releases page.

Along with #9735, this would enable easy updates of `nightly` style releases.

**Comment by raiyanalam** [comment]
Hi, 
  Apologies for delayed response. Are you asking to delete a older release and republishing a exact copy of the older one so that the timestamp is updated? What scenario does updating the timestamp fulfill?. BTW, GitHub already has a concept of `latest` tag that helps users to identify the latest release.

**Comment by TheGoddessInari** [comment]
Updating the timestamp leaves a particular release at the top, since github doesn't allow the notion of pinning a release to the top otherwise.
Prerelease doesn't update the 'latest' tag, and for good reason, as it's not a full release.
If you simply edit a release and change the artifacts, it will drop below other full releases, and generally not get found again by someone browsing releases fairly quickly.

**Comment by raiyanalam** [comment]
Closing this feature ask for now as we haven't had similar requests. However, we have taken a note of this requirement and will keep an eye if others need this too in future.
