### ISSUE TITLE
Download Build Artifact fails when using http (not https) connection

### ISSUE THREAD

**Issue by fran-hermida** [microsoft/azure-pipelines-tasks#9781]
## Environment
- Server - TFS2018.3 on-premises 
- Agent - Private: 
    
    - Windows 7 Enterprise SP1

    - Current agent version: '2.136.1'

## Issue Description

Maybe it is an expected behaviour.

Our TFS server has 2 urls: one http: (the one normally used) and one https: (normally not used because our certificates don't play well with modern browsers)

When using Download Build Artifact task, it starts downloading the artifact:

> 2019-03-08T12:48:13.8578716Z Downloading artifacts from: http://tfs.rp:8080/tfs/IDP//_apis/resources/Containers/1045?itemPath=drop&isShallow=true&api-version=4.1-preview.4

But then says:

> 2019-03-08T12:48:13.9978716Z Error getting drop:Error: Protocol "https:" not supported. Expected "http:"
2019-03-08T12:48:13.9998716Z Retrying download of drop, retry count: 1
2019-03-08T12:48:14.8638716Z Error getting drop/APF:Error: Protocol "https:" not supported. Expected "http:"
2019-03-08T12:48:14.8638716Z Retrying download of drop/APF, retry count: 1

I have checked the first url in a browser and it gets a json file, but with https urls in it:

> {"count":3,
"value":[{"containerId":1044
         ,"scopeIdentifier":"83014a28-a494-4d95-b636-7070380e3eda"
		 ,"path":"drop"
		 ,"itemType":"folder"
		 ,"status":"created"
		 ,"dateCreated":"2019-03-08T12:01:08.29Z"
		 ,"dateLastModified":"2019-03-08T12:01:08.29Z"
		 ,"createdBy":"6a2c6a76-1e3a-420e-97fb-ee7d0094b842"
		 ,"lastModifiedBy":"6a2c6a76-1e3a-420e-97fb-ee7d0094b842"
		 ,"itemLocation":"https://vmidp-tfs2018/tfs/IDP/_apis/resources/Containers/1044?itemPath=drop&metadata=True"
		 ,"contentLocation":"https://vmidp-tfs2018/tfs/IDP/_apis/resources/Containers/1044?itemPath=drop"
		 ,"contentId":""}

The agent is registered against the http url.
I tried registering the agent against the https url and it works

I looks like webclient runned by the tasks expects only http connections when agent is registered against http url ( System.TeamFoundationCollectionUri shows the http url)

### Task logs

[DownloadBuildArtifactTaskLog.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2951965/DownloadBuildArtifactTaskLog.txt)

**Comment by omeshp** [comment]
Currently "Download Build Artifacts" task expects the root url (http://tfs.rp:8080/tfs/IDP//_apis/resources/Containers/1045?itemPath=drop&isShallow=true&api-version=4.1-preview.4) scheme and item url (https://vmidp-tfs2018/tfs/IDP/_apis/resources/Containers/1044?itemPath=drop&metadata=True) scheme to match. In guess the real question here is why the itemLocation in json response has https scheme while the url that was called was http?

**Comment by fran-hermida** [comment]
Yes, that's a good question. I suppose it is related to the TFS server configuration.
However, in the releases pipelines, the artifact is download in the first step from the same url and it works.
What is the difference between the Download Build Artifact task in a build pipeline and the artifact download in a release pipeline?

**Comment by omeshp** [comment]
@fran-hermida Both the code flows are different, artifact download in release is handled by agent. My guess is that it is has handling both http and https urls.

**Comment by omeshp** [comment]
@fran-hermida Were you able to figure out if the difference in schemes was due to server configuration? Other thing you can try to unblock yourself is to configure the agent using https url.

We will look at supporting different schemes at root and item level, but since yours is onprem setup it won't reach you soon.

**Comment by fran-hermida** [comment]
Thank you @omeshp, I wasn't able to test different TFS server configurations, since we don't have a test environment, only production environment.

I have already setup an https agent. Luckily, only one of our agents needs to use the Download Build Artifacts Task. The rest will remain http only and I will try to avoid using this task, as a workaround.

**Comment by Lovakumar** [comment]
Since the customer is unblocked - not investing in fixing this scenario.

**Comment by mdschweda** [comment]
> Were you able to figure out if the difference in schemes was due to server configuration? Other thing you can try to unblock yourself is to configure the agent using https url.

Can confirm that protocols of the [URL you pass during agent configuration](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops-2020#required-options) (`config.sh --url <url>`) and of the [public URL in the administration console](https://docs.microsoft.com/en-us/azure/devops/server/admin/open-admin-console?view=azure-devops-2020#view-or-change-the-public-url) *MUST* match. Otherwise http(s)://{instance}/{collection}/_apis/resources/Containers/{id} will return a JSON object with URLs of deviating protocols which will lead to the error `##[debug]Error getting {artifactName}:Error: Protocol "http:" not supported. Expected "https:"` (or vice versa) within the `DownloadBuildArtifacts@0` task (set `System.Debug` to `true` in your pipeline to investigate).

Since the Azure team is "not investing in fixing this scenario" reconfigure your build agent or change the public URL of your application tier accordingly.
