### ISSUE TITLE
DotNetCoreCLI@2 Push running two push commands

### ISSUE THREAD

**Issue by Lutando** [Microsoft/azure-pipelines-tasks#9784]
Here is an example of my [yaml ](https://github.com/Lutando/Akkatecture/blob/master/build/azure-pipelines-development-ci-cd.yaml#L7)

This task results in two dotnet nuget push commands being executed

Here is the build result of that task : https://dev.azure.com/lutando/Akkatecture/_build/results?buildId=385

Is this a bug or something?

**Comment by sachinma** [comment]
@alexmullans this seems to be an issue with push command in dotnet task. Can you help out here.

**Comment by alexmullans** [comment]
This is by design. Your yaml file has a file selector in it: `'src/Akkatecture/bin/{0}/*.nupkg'` that is matching two packages in your Release folder: `Akkatecture.0.4.3-alpha-0705.nupkg` and `Akkatecture.1.0.0.nupkg`. The second push is failing because `'Akkatecture 1.0.0' cannot be published to the feed because it exists in at least one of the feed's upstream sources. Publishing this copy would prevent you from using 'Akkatecture 1.0.0' from 'nuget.org'.` 

If you edit your yaml to change the file selector to exclude the second package, your build should succeed.
