### ISSUE TITLE
Release build stucked at "All eligible agents are busy"

### ISSUE THREAD

**Issue by mariankral** [Microsoft/azure-pipelines-tasks#9821]
Release build is stucked at screenshot below. I have a private pool with one build agent enabled and online.  Agent run in interactively / visible mode with auto-logon.
![EligibleAgents](https://user-images.githubusercontent.com/3882110/54281241-972afb00-4599-11e9-9b74-5f001c88c3ec.png)

If I use a next agent pool with different agent server but with the same settings (capabilities), it works.

Thank in advance for help.

**Comment by bansalaseem** [comment]
@mariankral, do you mean to say that the agent is actually not busy but still the UI is saying that its busy and agent is not picking up the job?  If yes, can you please share the link to the release & its environment so that we can check logs for your account/project/release id/release environment id?

**Comment by mariankral** [comment]
Yes, agent is not busy and UI is saying that its busy.
I can not share the link.

**Comment by bansalaseem** [comment]
Can you please send the link at RM Customer Queries <RM_Customer_Queries@microsoft.com>?

**Comment by bansalaseem** [comment]
This is not a task issue and hence should not be discussed here. You should report the problem here. https://developercommunity.visualstudio.com/spaces/21/index.html
