### ISSUE TITLE
Error while running Pip Authentication task

### ISSUE THREAD

**Issue by lagnam** [Microsoft/azure-pipelines-tasks#9933]
The task name is `PipAuthenticate@0`

## Issue Description

When i try to run the `PipAuthenticate@0` task it gives me an error that says `Authentication for internal feeds is not supported in this version of Azure DevOps Server`. But my pipeline doesn't include any internal feeds for authentication. 

I have attached the screenshots of task's configuration below for reference. 

![image](https://user-images.githubusercontent.com/16524280/54990333-76729480-4fe0-11e9-98a5-0404d5777f31.png)

### Error logs

I have attached the error log file and screenshot below

[tasklog_3.log](https://github.com/Microsoft/azure-pipelines-tasks/files/3007695/tasklog_3.log)

![image](https://user-images.githubusercontent.com/16524280/54990495-e54fed80-4fe0-11e9-8df6-a2655ae3b186.png)

**Comment by salvmd** [comment]
Apologies for the inconvenience. The PipAuthenticate task only supports authentication to Azure DevOps hosted feeds (called here "internal feeds"). Since Python packages are not supported at this time in Azure DevOps Server feeds, the task won't work in Azure DevOps Server, which is why it is throwing an error immediately after starting. Both the task description and the error message are not making this very clear. I am logging a bug on our team to get those changed.
